### ISSUE TITLE
ClassNotFoundException Caffeine SSLMS

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1003]
More issues testing Quarkus/Graal masters with JDK11 in `quarkus-universe-integration-tests-camel-consul` module:

```
Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.SSLMS
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:229)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:95)
	... 27 more
```

[Longer output](https://gist.github.com/galderz/d0d91466157039f3ad5c47eb3d57df20).

**Comment by lburgazzoli** [comment]
That seems strange as we do use the caffeine extension from quarkus and - IMHO -  it should fail also on Jdk 8

**Comment by galderz** [comment]
@lburgazzoli Note that I'm testing Quarkus/Graal masters, maybe something else is triggering this.

**Comment by lburgazzoli** [comment]
@galderz I think we can close this one right ?

**Comment by galderz** [comment]
Yup
