### ISSUE TITLE
camle-tagsoup extension tests  fails in native mode on Jdk 11

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#1010]
I'm working on fixes for:

- #1000 
- #1005 
- #999 

And I've almost everithiung fixced but camle-tagsoup tests are failing in native mode:

```
caused by: org.apache.camel.CamelException: Failed to convert the HTML to tidy Markup
	at org.apache.camel.dataformat.tagsoup.TidyMarkupDataFormat.asNodeTidyMarkup(TidyMarkupDataFormat.java:191)
	at org.apache.camel.dataformat.tagsoup.TidyMarkupDataFormat.unmarshal(TidyMarkupDataFormat.java:133)
	at org.apache.camel.support.processor.UnmarshalProcessor.process(UnmarshalProcessor.java:64)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:396)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:153)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:286)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:66)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:212)
	at org.apache.camel.processor.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:110)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:84)
	at org.apache.camel.processor.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:107)
	at org.apache.camel.impl.engine.DefaultProducerCache.send(DefaultProducerCache.java:185)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:390)
	... 33 more
Caused by: com.sun.org.apache.xml.internal.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at com.sun.org.apache.xml.internal.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:343)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.setDefaults(TransformerImpl.java:1178)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.createOutputProperties(TransformerImpl.java:1138)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:267)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.<init>(TransformerImpl.java:258)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:791)
	at org.apache.camel.dataformat.tagsoup.TidyMarkupDataFormat.asNodeTidyMarkup(TidyMarkupDataFormat.java:186)
```

I think the issues is related to the TransformerFactory the dataformat relies upon

**Comment by ppalaga** [comment]
I can have a look. What are the steps to reproduce?

**Comment by lburgazzoli** [comment]
let me first commit my work that fixes something to get the test running

**Comment by lburgazzoli** [comment]
Requires https://github.com/apache/camel-quarkus/pull/1011 (to see the test failing you need to re-enable tagsoup tests thata re disabled in native mode in integration-tests/xml)

**Comment by zhfeng** [comment]
TidyMarkupDataFormat.java:186
```
TransformerFactory transformerFactory = TransformerFactory.newInstance();
transformerFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, Boolean.TRUE);
Transformer transformer = transformerFactory.newTransformer();
```
It looks like it uses the Transformer in the JDK internal implementation. But it is wired that the ```output_xml.properties``` does not include in the native resource. Is it possible to add ```com/sun/org/apache/xml/internal/serializer/output_xml.properties``` explicitly ?

**Comment by lburgazzoli** [comment]
I think it is possible however as example in the xslt component we don't use the internal implementation as it is broken, guess TidyMarkupDataFormatshoudl allow to do the same or we should configure the system to always ignore the internal impl

**Comment by lburgazzoli** [comment]
So I've experimented by creating a substitution like:

```java
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.TransformerFactoryConfigurationError;

import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;
import org.apache.xalan.xsltc.trax.TransformerFactoryImpl;

@TargetClass(className = "javax.xml.transform.TransformerFactory")
final class TransformerFactorySubstitution {
    @Substitute
    public static TransformerFactory newDefaultInstance() {
        return new TransformerFactoryImpl();
    }

    @Substitute
    public static TransformerFactory newInstance() throws TransformerFactoryConfigurationError {
        return newDefaultInstance();
    }
}
```

Which basically force to use `TransformerFactoryImpl` from `xalan` artifact and this appears to fix the issue but I don't know if it can be an acceptable solution.

@ppalaga @jamesnetherton WDYT ?

**Comment by ppalaga** [comment]
That's OK as a quick temporary solution. In any case, we need to figure out why the GraalVM@java11 is regressing.

**Comment by jamesnetherton** [comment]
Agreed. Let's go with it and improve later if we need to.

**Comment by lburgazzoli** [comment]
ok will push to the other pr about java 11
