### ISSUE TITLE
ActiveMQ test failing with Quarkus master

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1115]
```
[INFO] Running org.apache.camel.quarkus.component.activemq.it.ActiveMQTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.058 s <<< FAILURE! - in org.apache.camel.quarkus.component.activemq.it.ActiveMQTest
[ERROR] testActiveMQComponent  Time elapsed: 0.024 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Neither the application artifact nor the project root path has been provided
	at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:247)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:197)
```

[Longer output](https://gist.github.com/galderz/b741e0979cfc777a0697acce9263ab3b).

**Comment by galderz** [comment]
Fixed.
