### ISSUE TITLE
MethodAccessorGenerator reachable error in camel-activemq tests with jdk11u-dev

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1145]
Env: jdk11u-dev base, graal and quarkus masters.

`camel-activemq` test failing with:
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at java.base@11.0.8-internal/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base@11.0.8-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at app//com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
	at platform/jdk.crypto.cryptoki@11.0.8-internal/sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at platform/jdk.crypto.cryptoki@11.0.8-internal/sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.base@11.0.8-internal/java.lang.Thread.run(Thread.java:834)
	at app//com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at app//com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

We've seen similar issues before (see optaplanner issue https://github.com/quarkusio/quarkus/issues/7422). The problem is not clear at first sight and requires some digging to find out the root cause. I'll look into this.

[Longer output](https://gist.github.com/galderz/beea969ec6b0451c117e3f9cf6b39d8f)

**Comment by galderz** [comment]
I realised I had a bug in my calls to test things, it might have been testing old code. I'll try again next week.

**Comment by galderz** [comment]
Not present with latest snapshots.
