### ISSUE TITLE
ActiveMQ XalanXPathEvaluator CNFE warning

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1160]
Running native tests with OpenJDK 11 based GraalVM shows these log messages (doesn't cause build to fail):

```
[quarkus-universe-integration-tests-camel-activemq-999-SNAPSHOT-runner:28461]        setup:   4,963.04 ms,  0.93 GB
14:11:09,701 WARN  [org.apa.act.fil.XPathExpression] Invalid org.apache.activemq.filter.XPathExpression$XPathEvaluator implementation: org.apache.activemq.filter.XalanXPathEvaluator, reason: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.activemq.filter.XPathExpression.getXPathEvaluatorConstructor(XPathExpression.java:98)
	at org.apache.activemq.filter.XPathExpression.<clinit>(XPathExpression.java:55)
...
14:11:09,727 ERROR [org.apa.act.fil.XPathExpression] Default XPath evaluator could not be loaded: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.activemq.filter.XPathExpression.getXPathEvaluatorConstructor(XPathExpression.java:98)
	at org.apache.activemq.filter.XPathExpression.<clinit>(XPathExpression.java:55)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:169)
```

The issue could be due to the JVMCI layer on OpenJDK that uses reflection, instead of querying the JVM itself, and has in the past shown similar CNFEs. E.g. https://github.com/quarkusio/quarkus/issues/8081

[Longer output](https://gist.github.com/galderz/fe7949632665127193af2c8bca516be2)

**Comment by lburgazzoli** [comment]
The reason is that the activemq client uses reflection to discovery some classes (see https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/filter/XPathExpression.java#L51-L85) but the mentioned class is part of `activemq-broker` which brings ton of unused classes so it has been [excluded](https://github.com/apache/camel-quarkus/blob/master/extensions/activemq/runtime/pom.xml#L64-L75)

**Comment by galderz** [comment]
I see. Does not seem to cause failures, so closing this.
