### ISSUE TITLE
ASM Unsupported api 524288 after the upgrade to Gizmo 1.0.3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1182]
After upgrading to a Quarkus version using Gizmo 1.0.3, `camel-quarkus-integration-test-mail` is throwing the following exception during the augmentation:

```
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.apache.camel.quarkus.core.deployment.BuildProcessor$Core#createXMLRoutesLoader threw an exception: java.lang.IllegalArgumentException: Unsupported api 524288
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
        at io.quarkus.gizmo.GizmoClassVisitor.<init>(GizmoClassVisitor.java:22)
        at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:150)
        at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:203)
        at io.quarkus.deployment.proxy.ProxyFactory.doDefineClass(ProxyFactory.java:189)
        at io.quarkus.deployment.proxy.ProxyFactory.defineClass(ProxyFactory.java:120)
        at io.quarkus.deployment.proxy.ProxyFactory.newInstance(ProxyFactory.java:204)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.getRecordingProxy(BytecodeRecorderImpl.java:286)
        at io.quarkus.deployment.ExtensionLoader.lambda$loadStepsFrom$85(ExtensionLoader.java:759)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:928)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

The api version `524288` is the value of ASM's `org.objectweb.asm.Opcodes.ASM8`. It turns out that an unshaded `org.objectweb.asm.ClassVisitor` class is present in `org.graalvm.nativeimage:svm:19.3.1`. It pops up because the mail test project depends on it directly. The issue can be fixed through removing the dependency.
`

**Comment by gunnarmorling** [comment]
Ha, just ran into this very same issue myself. Thanks for the good explanation of the cause in this report, helped me to understand what I'd have to do :)
