### ISSUE TITLE
Azure native test failure

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1269]
* OpenJDK 11u-dev
* Graal 20.1
* Quarkus `master` branch
* Apache Quarkus `quarkus-master` branch

```
Caused by: java.security.InvalidKeyException: No installed provider supports this key: javax.crypto.spec.SecretKeySpec
	at javax.crypto.Mac.chooseProvider(Mac.java:392)
	at javax.crypto.Mac.init(Mac.java:435)
	at com.microsoft.azure.storage.StorageCredentialsAccountAndKey.getHmac256(StorageCredentialsAccountAndKey.java:190)
	at com.microsoft.azure.storage.core.StorageCredentialsHelper.computeHmac256(StorageCredentialsHelper.java:76)
	at com.microsoft.azure.storage.core.StorageCredentialsHelper.signBlobQueueAndFileRequest(StorageCredentialsHelper.java:133)
	at com.microsoft.azure.storage.core.StorageRequest.signBlobQueueAndFileRequest(StorageRequest.java:310)
	at com.microsoft.azure.storage.queue.CloudQueue$7.signRequest(CloudQueue.java:907)
	at com.microsoft.azure.storage.queue.CloudQueue$7.signRequest(CloudQueue.java:889)
	at com.microsoft.azure.storage.core.ExecutionEngine.setupStorageRequest(ExecutionEngine.java:341)
	... 50 more
Caused by: java.security.NoSuchAlgorithmException: class configured for Mac (provider: SunJCE) cannot be found.
	at java.security.Provider$Service.getImplClass(Provider.java:1857)
	at java.security.Provider$Service.newInstance(Provider.java:1818)
	at javax.crypto.Mac.chooseProvider(Mac.java:365)
	... 58 more
Caused by: java.lang.ClassNotFoundException: com.sun.crypto.provider.HmacCore$HmacSHA256
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.Class.forName(DynamicHub.java:1194)
	at java.security.Provider$Service.getImplClass(Provider.java:1842)
```

[Longer output](https://gist.github.com/galderz/5cce7afe616ca38255c5ea16d08d383e).¯

**Comment by galderz** [comment]
Can someone assign this to me?

**Comment by galderz** [comment]
Thx @jamesnetherton.

I've tried to add the following to `camel-quarkus/integration-tests/azure/src/main/resources/application.properties`, but didn't work:

```
quarkus.security.security-providers=SunJCE
```

However, if I run the test with `-Dquarkus.native.additional-build-args=--enable-all-security-services` it works.

**Comment by galderz** [comment]
I've seen this test pass about 1/2 months ago, so something recent change must have caused this. Looking.

**Comment by jamesnetherton** [comment]
BTW the integration test used to be suppressed because it required access to Azure. I recently tweaked things to use Azurite for testing, so maybe that's why you did not see such issues in the past.

**Comment by galderz** [comment]
Ah I see, that would explain. I think Quarkus security config is missing but not only is the [docu](https://quarkus.io/guides/security) inconsistent, none of the properties work. Both `quarkus.security.users.security-providers` and `quarkus.security.security-providers` throw warnings:

```
16:53:01,100 WARN  [io.qua.config] Unrecognized configuration key "quarkus.security.users.security-providers" was provided; it will be ignored
```

```
15:37:55,313 WARN  [io.qua.config] Unrecognized configuration key "quarkus.security.security-providers" was provided; it will be ignored
```

**Comment by galderz** [comment]
Created https://github.com/quarkusio/quarkus/issues/9664 to track the issue on Quarkus' side with security configuration.

**Comment by galderz** [comment]
Fixed the test, needed extra config and adding security extension. I'll send a PR tomorrow.

**Comment by galderz** [comment]
[PR](https://github.com/apache/camel-quarkus/pull/1272) with fix.

**Comment by galderz** [comment]
[PR https://github.com/apache/camel-quarkus/issues/1269] with better fix.

**Comment by ppalaga** [comment]
Fixed via https://github.com/apache/camel-quarkus/pull/1294 8c4d478bd5d7618f415dca63326850bdb0ea57c1
