### ISSUE TITLE
Unsupported type MethodAccessorGenerator on Consul

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1273]
* OpenJDK 11u (latest)
* Graal 20.1
* Quarkus master and Camel Quarkus quarkus-master

Consul testsuite failing with:

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at java.base@11.0.9-internal/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.base@11.0.9-internal/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at app//com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
	at platform/jdk.crypto.cryptoki@11.0.9-internal/sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at platform/jdk.crypto.cryptoki@11.0.9-internal/sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.base@11.0.9-internal/java.lang.Thread.run(Thread.java:834)
	at app//com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at app//com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

This is another case of https://github.com/quarkusio/quarkus/issues/9633 and similar ones. I have a PR for this issue which cuts off path only for Kafka. I'm going to experiment with a cut off that's shared by everyone which should stop all these issues.

**Comment by galderz** [comment]
Please assign to moi.

**Comment by ppalaga** [comment]
@galderz so there is nothing to do on Camel Quarkus side, we just need wait for the next Quarkus release, right?

**Comment by galderz** [comment]
Yep, this issue should be gone now for all Quarkus dependant projects/tests.
