### ISSUE TITLE
Nitrite native support

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#1298]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
Native support for nitrite is blocked by an issue in Quarkus https://github.com/oracle/graal/issues/460.
This error causes:
> Caused by: java.lang.IllegalArgumentException: Could not serialize IndexMetaService.IndexMeta(index=Index(indexType=NonUnique, field=address, collectionName=org.apache.camel.quarkus.component.nitrite.it.Employee), indexMap=$nitrite_index|org.apache.camel.quarkus.component.nitrite.it.Employee|address|NonUnique, isDirty=false) [1.4.200/0]
> ...
> ...
> ...
> Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:68)
	at org.h2.mvstore.type.ObjectDataType.serialize(ObjectDataType.java:356)

WIP for the nitrite support is prepared in this commit https://github.com/JiriOndrusek/camel-quarkus/commit/1eb6cb886edde1522354a4b6ae2d4d61b22ced73
(it contains working integration tests, which are successfull in JVM but fail in native because of unsupportedFeatureError)

**Comment by ppalaga** [comment]
I have sent a PR https://github.com/apache/camel-quarkus/pull/2035 with the tests adapted from your branch, @JiriOndrusek 

The Java Serialization support in GraalVM looks to be on a good way https://github.com/oracle/graal/pull/2730

So the native support is actually blocked by https://github.com/oracle/graal/pull/2730

**Comment by JiriOndrusek** [comment]
Because https://github.com/oracle/graal/pull/2730 is fixed in  GraalVM 21.0 , it should be possible to finish this issue.
I've updated work in progress into a new commit:  https://github.com/JiriOndrusek/camel-quarkus/commit/48a709caa5daf893ea943271f5d19e10ccd88b70

Unfortunately I see a different exception:

> 	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
	... 2 more
Caused by: java.lang.IllegalArgumentException: Could not serialize [19403199913046]NO₂ [1.4.200/0]
	at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:924)
	at org.h2.mvstore.type.ObjectDataType.serialize(ObjectDataType.java:359)
	at org.h2.mvstore.type.ObjectDataType$SerializedObjectType.write(ObjectDataType.java:1527)
	at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:127)
	at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:121)
	at org.h2.mvstore.Page.write(Page.java:669)
	at org.h2.mvstore.Page$Leaf.writeUnsavedRecursive(Page.java:1525)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1427)
	at org.h2.mvstore.MVStore.store(MVStore.java:1334)
	... 6 more
Caused by: java.lang.UnsupportedOperationException: Serialization of class definitions not supported
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:14)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1135)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.h2.mvstore.type.ObjectDataType.serialize(ObjectDataType.java:356)
	... 13 more

I found opened issue on GraalVM  (https://github.com/oracle/graal/issues/2685), which shows very similar exception with a statement, that it is happening on  GraalVM 21.0 
It looks like this extension is still blocked...

**Comment by JiriOndrusek** [comment]
But I try to dig into ot in case, the reason of the issue is not caused by serialization

**Comment by jamesnetherton** [comment]
Although serialization support is present in GraalVM 21.x, AFAIK there is no user friendly support for it in Quarkus yet.

So you'd have to manually add build args like: 

```
quarkus.native.additional-build-args=-H:SerializationConfigurationResources=my-serialization-configs.json
```

**Comment by JiriOndrusek** [comment]
Thanks I'll try to configure it.
