### ISSUE TITLE
Debezium unit tests failing with Quarkus master

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1312]
NPE:

```
[ERROR] org.apache.camel.quarkus.component.debezium.common.it.postgres.DebeziumPostgresTest  Time elapsed: 58.197 s  <<< ERROR!
java.lang.NullPointerException
        at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:498)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:365)
```

[Longer output](https://gist.github.com/galderz/597aa35b9b8c1d96d01875c37db05171).

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by ppalaga** [comment]
Closed via https://github.com/apache/camel-quarkus/pull/1325
