### ISSUE TITLE
[Quarkus 1.6] Unresolved method AutoscalingAPIGroupDSL.v1() error in Kubernetes native image generation

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1313]
* Quarkus master.
* Camel Quarkus master.
* Graal 20.1.x.
* OpenJDK 11 (not labs).

```
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.dsl.AutoscalingAPIGroupDSL.v1(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
        at parsing org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run(KubernetesHPAConsumer.java:94)
Call path from entry point to org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run():
        at org.apache.camel.component.kubernetes.hpa.KubernetesHPAConsumer$HpaConsumerTask.run(KubernetesHPAConsumer.java:93)
        at app//com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at app//com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at app//com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
        at app//com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
```

**Comment by galderz** [comment]
[Longer output](https://gist.github.com/galderz/ca60f39f333eb59f1c298ce52c465b6c).

**Comment by galderz** [comment]
Can you assign this to me?

**Comment by ppalaga** [comment]
Are you working on this one, @galderz ? I could have look now.

**Comment by galderz** [comment]
@ppalaga Sure go ahead! Let me know if you need a hand :)

**Comment by ppalaga** [comment]
https://github.com/quarkusio/quarkus/pull/9878 is one part. The second part is that, we will probably need to upgrade to kubenetes client 4.10.2 as well. This should happen in Camel Quarkus quarkus-master branch (cc @jamesnetherton ) once https://github.com/quarkusio/quarkus/pull/9878 is merged.

**Comment by galderz** [comment]
Thx again for helping with this @ppalaga :))
