### ISSUE TITLE
Make Kudu native test runnable on Quarkus Platform on Java 8 and 11

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1314]
* Quarkus master.
* Camel Quarkus master.
* Graal 20.1.x.
* OpenJDK 11 (not labs).

The normal unit test works, but the native test fails with:

```
Caused by: org.apache.kudu.client.NonRecoverableException: Couldn't find any valid locations, exceptions: [java.net.UnknownHostException: Failed to resolve the IP of `kudu-tserver']
        at org.apache.kudu.client.KuduClient.joinAndHandleException(KuduClient.java:413)
        at org.apache.kudu.client.KuduScanner.nextRows(KuduScanner.java:72)
        at org.apache.kudu.client.KuduScannerIterator.hasNext(KuduScannerIterator.java:69)
```

[Longer output](https://gist.github.com/galderz/c65e8a85802d8ffcd0c0600c05689b0b)

**Comment by ppalaga** [comment]
It is the same on quarkus-platform master. It is probably caused by the fact that these custom profiles https://github.com/apache/camel-quarkus/blob/master/integration-tests/kudu/pom.xml#L127-L144 were not ported to the platform.

**Comment by galderz** [comment]
Thx @ppalaga for picking this up! :)
