### ISSUE TITLE
NoClassDefFoundError for HttpServletRequest in native tests for olingo4

### ISSUE THREAD

**Issue by galderz** [apache/camel-quarkus#1319]
* Quarkus master.
* Camel Quarkus master.
* Graal 20.1.x.
* OpenJDK 11 (not labs).

This one is likely to be specific to the use of OpenJDK 11 (not present when using Oracle Labs). Similar issues in the past are https://github.com/quarkusio/quarkus/issues/8081 and https://github.com/apache/camel-quarkus/issues/1161.

```
[quarkus-universe-integration-tests-camel-olingo4-999-SNAPSHOT-runner:25482]     analysis:  99,017.27 ms,  5.57 GB
Fatal error:java.lang.NoClassDefFoundError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
        at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:463)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:518)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:117)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:546)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/ 
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotResolvedObjectTypeImpl.getDeclaredMethods(HotSpotResolvedObjectTypeImpl.java:932)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:385)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.hasDefaultMethods(ClassInitializationFeature.java:373)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.buildClassInitializationInfo(ClassInitializationFeature.java:358)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:193)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:720)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:538)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 19 more
```

**Comment by galderz** [comment]
@ppalaga Can you assign this one to me?

**Comment by jamesnetherton** [comment]
Olingo does loosely depend on serlvet-api, but none of that functionality is required by Camel, so there's a [substitution](https://github.com/apache/camel-quarkus/blob/quarkus-master/extensions/olingo4/runtime/src/main/java/org/apache/camel/quarkus/component/olingo4/graal/ODataImplSubstitutions.java) in place to avoid having all of the javax.servlet stuff on the classpath.

Maybe more needs to be done to handle it on Graal 20.1.x. I can take a look if the fix is not easy / obvious.

**Comment by galderz** [comment]
@jamesnetherton Not sure that substitution is enough, that happens at a later stage. The issue, which is specific to the JVMCI layer differences in OpenJDK 11 vs Oracle Labs (see linked issues) happens during the pointsto analysis phase, when trying to figure out all the methods available. And in OpenJDK 11 it uses reflection for that, so anything vaguely referenced needs to be in the classpath of the pointsto analysis phase. This classpath does not end up in the final native image, which is what the substitution is about. Please read linked issues for details.

**Comment by galderz** [comment]
The easy fix should be to add servlet dependency to the classpath, but I've also realised that there's a fix to improve the error reporting here that hasn't been backported, so wanted to test that out too (see https://github.com/oracle/graal/pull/2294).

**Comment by galderz** [comment]
The problematic class can be seen once you apply the class initialization feature patch (and you workaround the flipped condition, see https://github.com/oracle/graal/issues/2556):

```
[quarkus-universe-integration-tests-camel-olingo4-999-SNAPSHOT-runner:2096]     analysis:  57,083.16 ms,  5.41 GB
Fatal error:org.graalvm.compiler.debug.GraalError: Missing classes when looking up default methods in org.apache.olingo.server.api.ODataHttpHandler. Consider adding them to the classpath.
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.declaresDefaultMethods(ClassInitializationFeature.java:401)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.hasDefaultMethods(ClassInitializationFeature.java:375)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.buildClassInitializationInfo(ClassInitializationFeature.java:360)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:195)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:720)
```
