### ISSUE TITLE
Cron component not initialized when used with Endpoint DSL (since Quarkus 1.7.0.Final)

### ISSUE THREAD

**Issue by vladimirfx** [apache/camel-quarkus#1553]
This crashes:

    from(cron("httpsLogsToDb").schedule(cron))

Stack:

    2020-08-20 19:05:02,668 ERROR [io.qua.application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.RuntimeException: org.apache.camel.FailedToCreateRouteException: Failed to create route route9: Route(route9)[From[cron://httpsLogsToDb?schedule=0+0%2F1+*+*... because of Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:591)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:92)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:145)
        at java.base/java.lang.Thread.run(Thread.java:834)

    Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route9: Route(route9)[From[cron://httpsLogsToDb?schedule=0+0%2F1+*+*... because of Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:123)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:688)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:480)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2612)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:366)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2435)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2452)
        at org.apache.camel.quarkus.core.CamelContextRuntime.start(CamelContextRuntime.java:57)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        ... 15 more
    Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:975)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:897)
        at org.apache.camel.builder.endpoint.AbstractEndpointBuilder.resolve(AbstractEndpointBuilder.java:58)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:257)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:117)
        ... 25 more
    Caused by: java.lang.NullPointerException
        at org.apache.camel.component.cron.CronComponent.createEndpoint(CronComponent.java:51)
        at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:152)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:956)
        ... 29 more

    2020-08-20 19:05:02,671 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (Timer-0) Failed to start quarkus:        java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:156)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:176)
        at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:183)
        at org.apache.camel.quarkus.core.devmode.CamelHotReplacementSetup$1.run(CamelHotReplacementSetup.java:36)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

    Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:664)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:92)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:145)
        at java.base/java.lang.Thread.run(Thread.java:834)

    Caused by: java.lang.RuntimeException: org.apache.camel.FailedToCreateRouteException: Failed to create route route9: Route(route9)[From[cron://httpsLogsToDb?schedule=0+0%2F1+*+*... because of Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:591)
        ... 12 more

    Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route9: Route(route9)[From[cron://httpsLogsToDb?schedule=0+0%2F1+*+*... because of Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:123)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:688)
        at org.apache.camel.quarkus.core.FastCamelContext.startRouteDefinitions(FastCamelContext.java:480)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2612)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:366)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2435)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2452)
        at org.apache.camel.quarkus.core.CamelContextRuntime.start(CamelContextRuntime.java:57)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        ... 15 more

    Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: cron://httpsLogsToDb?schedule=0+0%2F1+*+*+*+%3F+* due to: null
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:975)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:897)
        at org.apache.camel.builder.endpoint.AbstractEndpointBuilder.resolve(AbstractEndpointBuilder.java:58)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:257)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:117)
        ... 25 more

    Caused by: java.lang.NullPointerException
        at org.apache.camel.component.cron.CronComponent.createEndpoint(CronComponent.java:51)
        at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:152)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:956)
        ... 29 more

This works:

    from("cron:httpsLogsToDb?schedule=$cron")

Quarkus 1.4.2 works too

**Comment by ppalaga** [comment]
https://issues.apache.org/jira/browse/CAMEL-15445 was fixed in Camel 3.5.0 so the issue should be fixed since Camel Quarkus 1.1.0. @vladimirfx could you please confirm that it works for you with any recent Camel Quarkus version?

**Comment by vladimirfx** [comment]
> https://issues.apache.org/jira/browse/CAMEL-15445 was fixed in Camel 3.5.0 so the issue should be fixed since Camel Quarkus 1.1.0. @vladimirfx could you please confirm that it works for you with any recent Camel Quarkus version?

Yes, it works in 1.9.2.Final. Thank you!
