### ISSUE TITLE
Deep Java Library native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1598]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
DJL native support can not be finished without changes in DJL library. Djl library heavily depends on JNA (mostly models). Full support for JNA is not available or planned (see https://github.com/oracle/graal/issues/673 or https://github.com/oracle/graal/issues/1701)

Here is a stack trace with error caused by JNA from model.

>java.lang.UnsatisfiedLinkError: com.sun.jna.Native.malloc(J)J [symbol: Java_com_sun_jna_Native_malloc or Java_com_sun_jna_Native_malloc__J]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at com.sun.jna.Native.malloc(Native.java)
	at com.sun.jna.Memory.malloc(Memory.java:722)
	at com.sun.jna.Memory.<init>(Memory.java:114)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:42)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:40)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:36)
	at ai.djl.mxnet.jna.JnaUtils.createSymbolFromFile(JnaUtils.java:1062)

My WIP is available in branch https://github.com/JiriOndrusek/camel-quarkus/commits/1598-djl-native
