### ISSUE TITLE
Flink native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1641]

**Comment by sohailalam2** [comment]
Hi Team,

Is there any plan to implement native support for Apache Flink? 
Any ETA?

Thanks

**Comment by ppalaga** [comment]
No ETA, but contributions are welcome! If you or anybody else would like to give it a try, here is the guide: https://camel.apache.org/camel-quarkus/latest/contributor-guide/promote-jvm-to-native.html

**Comment by apupier** [comment]
Started the basic steps to have a starting point on this branch: https://github.com/apupier/camel-quarkus/tree/1641-FlinkNative


native build ` mvn clean verify -Pnative -Dquarkus.native.additional-build-args="--trace-object-instantiation=java.util.Random"` is currently failing with:

```
[ERROR] Caused by: io.smallrye.common.process.AbnormalExitException: Process exited abnormally (pid 147997) with exit code 1 with error output:
[ERROR]  > Error: Unsupported features in 2 methods
[ERROR]  > Detailed message:
[ERROR]  > Error: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected. Try avoiding to initialize the class that caused initialization of the object.
[ERROR]  > The culprit object has been instantiated by the 'com.esotericsoftware.kryo.util.ObjectMap' class initializer with the following trace:
[ERROR]  >      at java.util.Random.<init>(Random.java:318)
[ERROR]  > … (skipped 176 line(s)) …
[ERROR]  > 
[ERROR]  > 
[ERROR]  >      at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
[ERROR]  >      at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:809)
```

**Comment by jamesnetherton** [comment]
There's a combination of problematic things that will make this hard to implement.

* Shaded dependencies. Jackson, Netty & Zookeeper (which has no native support aside from the [client](https://github.com/quarkiverse/quarkus-zookeeper-client))
 
* Flink has a lot of optional dependencies, which can be problematic for native mode, since we don't allow building with `allow-incomplete-classpath`

* From what I remember, Flink does some dynamic things with class loaders / class loading, which probably do not work OOTB in native mode
