### ISSUE TITLE
KuduIT fails with Camel 3.5.0

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1664]
Kudu was bumped from 1.10.0 to 1.12.0 and we now see:

```
2020-09-01T02:26:49.4092788Z Error: Class initialization of org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine failed. Use the option --initialize-at-run-time=org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine to explicitly request delayed initialization of this class.
2020-09-01T02:26:49.4093027Z Original exception that caused the problem: java.lang.NoClassDefFoundError: org/conscrypt/BufferAllocator
2020-09-01T02:26:49.4093237Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2020-09-01T02:26:49.4093390Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
2020-09-01T02:26:49.4093539Z 	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
2020-09-01T02:26:49.4093937Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:169)
2020-09-01T02:26:49.4094129Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:586)
2020-09-01T02:26:49.4094307Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:132)
2020-09-01T02:26:49.4094483Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:160)
2020-09-01T02:26:49.4094871Z 	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:223)
2020-09-01T02:26:49.4095040Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:264)
2020-09-01T02:26:49.4095198Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
2020-09-01T02:26:49.4095360Z 	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
2020-09-01T02:26:49.4095661Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4274)
2020-09-01T02:26:49.4096019Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInstanceOf(BytecodeParser.java:4475)
2020-09-01T02:26:49.4096183Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5349)
2020-09-01T02:26:49.4096356Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
2020-09-01T02:26:49.4100631Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
2020-09-01T02:26:49.4100811Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
2020-09-01T02:26:49.4100977Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
2020-09-01T02:26:49.4101119Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-09-01T02:26:49.4101272Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-09-01T02:26:49.4101427Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-09-01T02:26:49.4101583Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-09-01T02:26:49.4101739Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-09-01T02:26:49.4101905Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
2020-09-01T02:26:49.4102061Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
2020-09-01T02:26:49.4102210Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
2020-09-01T02:26:49.4102362Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
2020-09-01T02:26:49.4102515Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
2020-09-01T02:26:49.4102663Z 	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:437)
2020-09-01T02:26:49.4102791Z 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
2020-09-01T02:26:49.4103514Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-09-01T02:26:49.4103702Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2020-09-01T02:26:49.4103866Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-09-01T02:26:49.4104020Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-09-01T02:26:49.4104144Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-09-01T02:26:49.4104296Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-09-01T02:26:49.4104447Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2020-09-01T02:26:49.4104595Z Caused by: java.lang.ClassNotFoundException: org.conscrypt.BufferAllocator
2020-09-01T02:26:49.4104742Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
2020-09-01T02:26:49.4104885Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2020-09-01T02:26:49.4105027Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2020-09-01T02:26:49.4105165Z 	... 37 more
2020-09-01T02:26:49.4105918Z Error: Class initialization of org.apache.kudu.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine failed. Use the option --initialize-at-run-time=org.apache.kudu.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine to explicitly request delayed initialization of this class.
2020-09-01T02:26:49.4106140Z Original exception that caused the problem: java.lang.NoClassDefFoundError: org/apache/kudu/shaded/io/netty/internal/tcnative/SSL
2020-09-01T02:26:49.4106323Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<clinit>(ReferenceCountedOpenSslEngine.java:110)
2020-09-01T02:26:49.4106491Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2020-09-01T02:26:49.4106646Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
2020-09-01T02:26:49.4106773Z 	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
2020-09-01T02:26:49.4107192Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:169)
2020-09-01T02:26:49.4107385Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:586)
2020-09-01T02:26:49.4107561Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:132)
2020-09-01T02:26:49.4107735Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:160)
2020-09-01T02:26:49.4107896Z 	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:223)
2020-09-01T02:26:49.4108047Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:264)
2020-09-01T02:26:49.4108206Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:205)
2020-09-01T02:26:49.4108379Z 	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:155)
2020-09-01T02:26:49.4108538Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4274)
2020-09-01T02:26:49.4108707Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInstanceOf(BytecodeParser.java:4475)
2020-09-01T02:26:49.4108874Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5349)
2020-09-01T02:26:49.4109046Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
2020-09-01T02:26:49.4109209Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3230)
2020-09-01T02:26:49.4109349Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1088)
2020-09-01T02:26:49.4109521Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:982)
2020-09-01T02:26:49.4109684Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-09-01T02:26:49.4109840Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-09-01T02:26:49.4109992Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-09-01T02:26:49.4110265Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-09-01T02:26:49.4110419Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-09-01T02:26:49.4110574Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:225)
2020-09-01T02:26:49.4110729Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:352)
2020-09-01T02:26:49.4110881Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:322)
2020-09-01T02:26:49.4111041Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:311)
2020-09-01T02:26:49.4111173Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:112)
2020-09-01T02:26:49.4111321Z 	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:437)
2020-09-01T02:26:49.4111467Z 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:530)
2020-09-01T02:26:49.4111618Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-09-01T02:26:49.4111772Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2020-09-01T02:26:49.4111929Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-09-01T02:26:49.4112082Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-09-01T02:26:49.4112230Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-09-01T02:26:49.4112536Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-09-01T02:26:49.4112696Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2020-09-01T02:26:49.4112835Z Caused by: java.lang.ClassNotFoundException: org.apache.kudu.shaded.io.netty.internal.tcnative.SSL
2020-09-01T02:26:49.4112988Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
2020-09-01T02:26:49.4113138Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2020-09-01T02:26:49.4113282Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2020-09-01T02:26:49.4113413Z 	... 38 more
2020-09-01T02:26:49.4114184Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine.calculateOutNetBufSize(int, int). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
2020-09-01T02:26:49.4114396Z Trace: 
2020-09-01T02:26:49.4114545Z 	at parsing org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.allocateWrapBuffer(SslHandler.java:261)
2020-09-01T02:26:49.4114732Z Call path from entry point to org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.allocateWrapBuffer(SslHandler, ByteBufAllocator, int, int): 
2020-09-01T02:26:49.4114919Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.allocateWrapBuffer(SslHandler.java:260)
2020-09-01T02:26:49.4115086Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:2145)
2020-09-01T02:26:49.4115241Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:821)
2020-09-01T02:26:49.4115400Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.access$1600(SslHandler.java:166)
2020-09-01T02:26:49.4115575Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.resumeOnEventExecutor(SslHandler.java:1617)
2020-09-01T02:26:49.4115744Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.access$2000(SslHandler.java:1530)
2020-09-01T02:26:49.4115887Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner$1.run(SslHandler.java:1690)
2020-09-01T02:26:49.4116043Z 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
2020-09-01T02:26:49.4116194Z 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
2020-09-01T02:26:49.4116342Z 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
2020-09-01T02:26:49.4116487Z 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
2020-09-01T02:26:49.4116643Z 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
2020-09-01T02:26:49.4117393Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine.unwrap(java.nio.ByteBuffer[], java.nio.ByteBuffer[]). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
2020-09-01T02:26:49.4117599Z Trace: 
2020-09-01T02:26:49.4117743Z 	at parsing org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:243)
2020-09-01T02:26:49.4117929Z Call path from entry point to org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler, ByteBuf, int, int, ByteBuf): 
2020-09-01T02:26:49.4118104Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:234)
2020-09-01T02:26:49.4118266Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1324)
2020-09-01T02:26:49.4118606Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.unwrapNonAppData(SslHandler.java:1307)
2020-09-01T02:26:49.4118770Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler.access$1700(SslHandler.java:166)
2020-09-01T02:26:49.4118933Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.resumeOnEventExecutor(SslHandler.java:1638)
2020-09-01T02:26:49.4119103Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.access$2000(SslHandler.java:1530)
2020-09-01T02:26:49.4119246Z 	at org.apache.kudu.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner$1.run(SslHandler.java:1690)
2020-09-01T02:26:49.4119401Z 	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
2020-09-01T02:26:49.4119553Z 	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
2020-09-01T02:26:49.4119702Z 	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:141)
2020-09-01T02:26:49.4119850Z 	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:184)
2020-09-01T02:26:49.4120018Z 	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
2020-09-01T02:26:49.4120717Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.kudu.shaded.io.netty.internal.tcnative.SSL. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
2020-09-01T02:26:49.4120912Z Trace: 
2020-09-01T02:26:49.4121065Z 	at parsing org.apache.kudu.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<clinit>(ReferenceCountedOpenSslEngine.java:110)
2020-09-01T02:26:49.4121244Z Call path from entry point to org.apache.kudu.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<clinit>(): 
2020-09-01T02:26:49.4121397Z 	no path found from entry point to target method
2020-09-01T02:26:49.4121465Z 
2020-09-01T02:26:49.4121546Z 
2020-09-01T02:26:49.4121683Z com.oracle.svm.core.util.UserError$UserException: Unsupported features in 5 methods
2020-09-01T02:26:49.4121802Z Detailed message:
2020-09-01T02:26:49.4122375Z Error: Class initialization of org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine failed. Use the option --initialize-at-run-time=org.apache.kudu.shaded.io.netty.handler.ssl.ConscryptAlpnSslEngine to explicitly request delayed initialization of this class.
```

**Comment by ppalaga** [comment]
I am on it. It is caused by the fact that Kudu shades netty.

**Comment by ppalaga** [comment]
I do not see a better solution then to take mutatis mutandis what's needed from io.quarkus.netty.deployment.NettyProcessor
