### ISSUE TITLE
JT400 native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1739]

**Comment by eamazaj** [comment]
I am trying to call a PGM program with apache camel 3.5.0, but from Jt400Type it doesn't support PGM type:

Example:

from(jt400://DEMO678:xxxxx@host/QSYS.LIB/DEMO6781.LIB/HELLO.PGM)
    .to(direct:demo)

StackTrace:

2020-09-22 19:59:05,714 ERROR [io.qua.application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.RuntimeException: org.apache.camel.FailedToStart
RouteException: Failed to start route route1 because of null
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)

Caused by: org.apache.camel.FailedToStartRouteException: Failed to start route route1 because of null
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:124)

Caused by: javax.naming.OperationNotSupportedException
        at org.apache.camel.component.jt400.Jt400Endpoint.createConsumer(Jt400Endpoint.java:101)


**Will this improvement be added in future versions?**

**Comment by davsclaus** [comment]
The PGM cannot be in from, but you can use it in to, so do

from timer foo
  to jt400 pgm

**Comment by eamazaj** [comment]
> The PGM cannot be in from, but you can use it in to, so do
> 
> from timer foo
> to jt400 pgm

It does not work because it does not load the parameters of the uri outputFieldsIdxArray outputFieldsLengthArray in the Jt400Configuration class, according to the documentation that would be enough. But it does not work.

**Comment by davsclaus** [comment]
This is not the place to ask for JT400 help with Camel, see here
https://camel.apache.org/community/support/

**Comment by jamesnetherton** [comment]
Implemented in https://github.com/apache/camel-quarkus/issues/5742.
