### ISSUE TITLE
Barcode data format native support

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1752]

**Comment by JiriOndrusek** [comment]
Please, assign to me.

**Comment by JiriOndrusek** [comment]
Problem is blocked by an issue with awt:
>2020-10-27 10:25:19,819 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Can't load standard profile: GRAY.pf
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:942)
	at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:936)
...

Problem is reported as https://github.com/quarkusio/quarkus/issues/12972
My current work (including working jvm tests)  is located here: https://github.com/JiriOndrusek/camel-quarkus/tree/1752_barcode-dataformat-WIP
