### ISSUE TITLE
1.1.0 Main fails to start in IntelliJ

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#1800]
camel-quarkus-examples-timer-log-main fails to start in Intelij:

```
Caused by: java.lang.IllegalArgumentException: The supplied 'main-class' value of 'org.apache.camel.quarkus.main.CamelMainApplication' does not correspond to either a fully qualified class name or a matching 'name' field of one of the '@QuarkusMain' annotations
```

Stacktrace:

```
at io.quarkus.builder.Execution.run(Execution.java:116)
at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:149)
at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:250)
... 18 more
Caused by: java.lang.IllegalArgumentException: The supplied
'main-class' value of
'org.apache.camel.quarkus.main.CamelMainApplication' does not
correspond to either a fully qualified class name or a matching 'name'
field of one of the '@QuarkusMain' annotations
at io.quarkus.deployment.steps.MainClassBuildStep.mainClassBuildStep(MainClassBuildStep.java:400)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:936)
at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
at java.base/java.lang.Thread.run(Thread.java:832)
at org.jboss.threads.JBossThread.run(JBossThread.java:479)

2020-09-16 16:35:45,823 INFO  [io.qua.dep.dev.IsolatedDevModeMain]
(main) Attempting to start hot replacement endpoint to recover from
previous Quarkus startup failure
```

**Comment by jamesnetherton** [comment]
I think the problem is [here](https://github.com/quarkusio/quarkus/blob/cd98a9ed54bd986129a7118f87e6c95ff14c0bd6/core/deployment/src/main/java/io/quarkus/deployment/steps/MainClassBuildStep.java#L376-L377).

No implementors of `QuarkusApplication` are found, so Quarkus does not know which main class to run. I think we can fix it by adding a new `BuildStep` to the main extension, so that `CamelMainApplication` is indexed. E.g:

``` 
AdditionalIndexedClassesBuildItem(CamelMainApplication.class.getName())
```

Until then, the workaround is to manually index `camel-quarkus-main` by setting properties in `application.properties`:

```
quarkus.index-dependency.camel-quarkus-main.group-id=org.apache.camel.quarkus
quarkus.index-dependency.camel-quarkus-main.artifact-id=camel-quarkus-main
```

Or you can tweak the `QuarkusMain` annotation to:

```
@QuarkusMain(name = "org.apache.camel.quarkus.main.CamelMainApplication")
```
