### ISSUE TITLE
[Serialization] transferException URI option does not work in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1868]
`transferException` uses object serialization / deserialization which is currently not supported by GraalVM.

We should add some documentation to the affected extensions:

* activemq
* ahc
* ahc-ws
* ahc-wss
* amqp
* http
* https
* jms
* netty-http
* rabbitmq
* servlet
* vertx-http

**Comment by ppalaga** [comment]
Could you please explain where that serialization happens? If it in Camel, we could perhaps implement a workaround?

**Comment by jamesnetherton** [comment]
Yes, it's in the various Camel components. E.g like here:

https://github.com/apache/camel/blob/master/components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java#L205-L210

And here:

https://github.com/apache/camel/blob/master/components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java#L383

I forget there's also the `allowJavaSerializedObject` which has the same issue. But it's not enabled by default since it can be a security risk.

**Comment by jamesnetherton** [comment]
I spent some time trying to enable serialization support for `transferException`. There might be a GraalVM bug that is stopping deserialization of exceptions from working. 

I've configured the relevant classes for serialization but deserializing an exception always results in: 

```
Exception in thread "main" java.lang.ClassNotFoundException: [Ljava.lang.StackTraceElement;
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:71)
	at java.lang.Class.forName(DynamicHub.java:1319)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:756)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1995)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2057)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:629)
	at java.lang.Throwable.readObject(Throwable.java:896)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
```

I tried with a basic test app without Camel or Quarkus and got the same result.

**Comment by ppalaga** [comment]
`[Ljava.lang.StackTraceElement` is array of `java.lang.StackTraceElement` - maybe array types need some special registration or they are not supported yet?

**Comment by jamesnetherton** [comment]
I got a bit further by registering some additional classes for reflection. But now stuck at:

```
java.io.InvalidClassException: java.util.Collections$EmptyList; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:159)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:875)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2170)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:629)
	at java.lang.Throwable.readObject(Throwable.java:896)
```

I'll dig into it some more...
