### ISSUE TITLE
Remove Camel AS2 configuration class reflection registration

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1874]
See here:

https://github.com/apache/camel-quarkus/blob/master/extensions/as2/deployment/src/main/java/org/apache/camel/quarkus/component/as2/deployment/As2Processor.java#L52-L53

`AS2ServerManagerEndpointConfiguration` and `AS2ClientManagerEndpointConfiguration` have corresponding configurer classes. So reflective access should not be required.

**Comment by jamesnetherton** [comment]
When I remove the as2 configuration classes from the `ReflectiveClassBuildItem` config, native compilation fails. So it seems it is doing fallback on reflection:

```
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: as2://server/listen?clientFqdn=example.com&requestUriPattern=%2F&serverPortNumber=45425 due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{requestUriPattern=/}]
	at org.apache.camel.support.DefaultComponent.validateParameters(DefaultComponent.java:288)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:177)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:862)
```

@davsclaus any idea what's wrong here?

**Comment by davsclaus** [comment]
Yeah it looks like it does, after I debugged a bit. Can you create a JIRA ticket then I can look at this for 3.7

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-15737

**Comment by ppalaga** [comment]
The fix is available in the camel-master branch
