### ISSUE TITLE
IllegalArgumentException thrown on itest application startup 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1891]
Something I observed since the Quarkus 1.9.0 upgrade is that itests requiring property based configuration (ActiveMQ, Debezium, Jira, Slack & others) throw an `IllegalArgumentException` on startup.

Everything proceeds to run and pass ok, so not sure if it's something to be concerned about.

```
2020-10-08T08:32:22.8336944Z [INFO] -------------------------------------------------------
2020-10-08T08:32:22.8340853Z [INFO]  T E S T S
2020-10-08T08:32:22.8349314Z [INFO] -------------------------------------------------------
2020-10-08T08:32:24.0772764Z [INFO] Running org.apache.camel.quarkus.component.jira.it.JiraTest
2020-10-08T08:32:32.1661649Z 2020-10-08 08:32:32,163 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2020-10-08T08:32:32.2078747Z 2020-10-08 08:32:32,207 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary:
2020-10-08T08:32:32.2091764Z LogManager error of type FORMAT_FAILURE: Formatting error
2020-10-08T08:32:32.2099488Z java.lang.IllegalArgumentException: can't parse argument number: {env:JIRA_PASSWORD:s3cr3t}
2020-10-08T08:32:32.2106490Z 	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1451)
2020-10-08T08:32:32.2135815Z 	at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:491)
2020-10-08T08:32:32.2137278Z 	at java.base/java.text.MessageFormat.<init>(MessageFormat.java:370)
2020-10-08T08:32:32.2138476Z 	at java.base/java.text.MessageFormat.format(MessageFormat.java:859)
2020-10-08T08:32:32.2140257Z 	at org.jboss.logmanager.ExtFormatter.formatMessageLegacy(ExtFormatter.java:107)
2020-10-08T08:32:32.2142371Z 	at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:70)
2020-10-08T08:32:32.2146855Z 	at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:781)
2020-10-08T08:32:32.2148459Z 	at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:221)
2020-10-08T08:32:32.2150571Z 	at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:86)
2020-10-08T08:32:32.2156574Z 	at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
2020-10-08T08:32:32.2160057Z 	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
2020-10-08T08:32:32.2161768Z 	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
2020-10-08T08:32:32.2163405Z 	at org.jboss.logmanager.handlers.DelayedHandler.publishToChildren(DelayedHandler.java:208)
2020-10-08T08:32:32.2166475Z 	at org.jboss.logmanager.handlers.DelayedHandler.doPublish(DelayedHandler.java:49)
2020-10-08T08:32:32.2174299Z 	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
2020-10-08T08:32:32.2179223Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:316)
2020-10-08T08:32:32.2182231Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
2020-10-08T08:32:32.2193551Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
2020-10-08T08:32:32.2194754Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
2020-10-08T08:32:32.2196247Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
2020-10-08T08:32:32.2197233Z 	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:324)
2020-10-08T08:32:32.2206325Z 	at org.jboss.logmanager.Logger.logRaw(Logger.java:748)
2020-10-08T08:32:32.2207408Z 	at org.jboss.logmanager.Logger.log(Logger.java:706)
2020-10-08T08:32:32.2208843Z 	at org.jboss.logging.JBossLogManagerLogger.doLog(JBossLogManagerLogger.java:44)
2020-10-08T08:32:32.2210067Z 	at org.jboss.logging.Logger.log(Logger.java:2103)
2020-10-08T08:32:32.2214554Z 	at org.jboss.slf4j.JBossLoggerAdapter.log(JBossLoggerAdapter.java:302)
2020-10-08T08:32:32.2215854Z 	at org.jboss.slf4j.JBossLoggerAdapter.info(JBossLoggerAdapter.java:188)
2020-10-08T08:32:32.2217217Z 	at org.apache.camel.main.BaseMainSupport.lambda$autoconfigure$0(BaseMainSupport.java:603)
2020-10-08T08:32:32.2218297Z 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
2020-10-08T08:32:32.2223505Z 	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:598)
2020-10-08T08:32:32.2225339Z 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:654)
2020-10-08T08:32:32.2227380Z 	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:97)
2020-10-08T08:32:32.2228841Z 	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:67)
2020-10-08T08:32:32.2230129Z 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
2020-10-08T08:32:32.2231442Z 	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:118)
2020-10-08T08:32:32.2238640Z 	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
2020-10-08T08:32:32.2240885Z 	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
2020-10-08T08:32:32.2243259Z 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
2020-10-08T08:32:32.2246099Z 	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
2020-10-08T08:32:32.2261074Z 	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:653)
2020-10-08T08:32:32.2266414Z 	at io.quarkus.runtime.Application.start(Application.java:90)
2020-10-08T08:32:32.2267777Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-10-08T08:32:32.2273790Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-10-08T08:32:32.2276364Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-10-08T08:32:32.2280970Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-10-08T08:32:32.2287646Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:212)
2020-10-08T08:32:32.2290004Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:231)
2020-10-08T08:32:32.2292819Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:519)
2020-10-08T08:32:32.2294568Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:552)
2020-10-08T08:32:32.2314609Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
2020-10-08T08:32:32.2331833Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-10-08T08:32:32.2359802Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
2020-10-08T08:32:32.2362940Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
2020-10-08T08:32:32.2365263Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
2020-10-08T08:32:32.2367491Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
2020-10-08T08:32:32.2374642Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-10-08T08:32:32.2377465Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-10-08T08:32:32.2383549Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-10-08T08:32:32.2386810Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-10-08T08:32:32.2389417Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-10-08T08:32:32.2413345Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-10-08T08:32:32.2415906Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-10-08T08:32:32.2417260Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2020-10-08T08:32:32.2420132Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-10-08T08:32:32.2456027Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-10-08T08:32:32.2458763Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-10-08T08:32:32.2477003Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-10-08T08:32:32.2492616Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-10-08T08:32:32.2494528Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-10-08T08:32:32.2496959Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-10-08T08:32:32.2516880Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-10-08T08:32:32.2526620Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-10-08T08:32:32.2529757Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-10-08T08:32:32.2533504Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-10-08T08:32:32.2536491Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-10-08T08:32:32.2545218Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2020-10-08T08:32:32.2547237Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2020-10-08T08:32:32.2549348Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2020-10-08T08:32:32.2551671Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2020-10-08T08:32:32.2559017Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2020-10-08T08:32:32.2561793Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2020-10-08T08:32:32.2564317Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
2020-10-08T08:32:32.2571148Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-10-08T08:32:32.2574123Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-10-08T08:32:32.2575994Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-10-08T08:32:32.2577448Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2020-10-08T08:32:32.2578645Z Caused by: java.lang.NumberFormatException: For input string: "{env:JIRA_PASSWORD:s3cr3t}"
2020-10-08T08:32:32.2643699Z 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2020-10-08T08:32:32.2645569Z 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
2020-10-08T08:32:32.2646273Z 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
2020-10-08T08:32:32.2651279Z 	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1449)
2020-10-08T08:32:32.2651918Z 	... 85 more
```

**Comment by jamesnetherton** [comment]
This could be due to the upgrade of `slf4j-jboss-logging` to 1.2.1.Final. If I force the dependency back to 1.2.0.Final, the error no longer shows.

Possibly due to this change:

https://github.com/jboss-logging/slf4j-jboss-logging/commit/1204d4301b82aeddfb0b0b3c0905f48df9c266d7

It's the only thing that stands out in the diff between the two tags:

https://github.com/jboss-logging/slf4j-jboss-logging/compare/1.2.0.Final...1.2.1.Final

**Comment by lburgazzoli** [comment]
I think we should report this to quarkus, last time I saw a similar error was about MP Config not able to resolve some env vars and we implemented a workaround on our side but looks like it is something outside of our control now

**Comment by jamesnetherton** [comment]
Quarkus has downgraded `slf4j-jboss-logging` which fixes the issue. I'll close this (for now).
