### ISSUE TITLE
ActiveMQ Default XPath evaluator could not be loaded

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1933]
There are some warnings during native compilation with the ActiveMQ extension. Seems to be thrown from the static initialiser in 
[XPathExpression](https://github.com/apache/activemq/blob/112c4e602f79d8a4df411657d2de2dc4d6e01b5e/activemq-client/src/main/java/org/apache/activemq/filter/XPathExpression.java).

The fallback evaluator `XalanXPathEvaluator` wont be on the classpath because `activemq-broker` is excluded from the dependency tree.

I think this stuff is to support XPath based JMS selectors. Not sure whether anyone is likely to use this with Camel, I guess it could be possible via the JMS endpoint `selector` option.

https://activemq.apache.org/selectors.html

```
2020-10-20T07:16:04.2737046Z 07:16:04,258 WARN  [org.apa.act.fil.XPathExpression] Invalid org.apache.activemq.filter.XPathExpression$XPathEvaluator implementation: org.apache.activemq.filter.XalanXPathEvaluator, reason: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator
2020-10-20T07:16:04.2741436Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
2020-10-20T07:16:04.2742660Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2020-10-20T07:16:04.2743889Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2020-10-20T07:16:04.2746127Z 	at org.apache.activemq.filter.XPathExpression.getXPathEvaluatorConstructor(XPathExpression.java:100)
2020-10-20T07:16:04.2748631Z 	at org.apache.activemq.filter.XPathExpression.<clinit>(XPathExpression.java:56)
2020-10-20T07:16:04.2750329Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2020-10-20T07:16:04.2752057Z 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
2020-10-20T07:16:04.2753616Z 	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
2020-10-20T07:16:04.2757612Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:177)
2020-10-20T07:16:04.2764539Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:594)
2020-10-20T07:16:04.2772343Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:130)
2020-10-20T07:16:04.2917987Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:168)
2020-10-20T07:16:04.2921689Z 	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:236)
2020-10-20T07:16:04.2923601Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:271)
2020-10-20T07:16:04.2926908Z 	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:209)
2020-10-20T07:16:04.2930190Z 	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:164)
2020-10-20T07:16:04.2933087Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4264)
2020-10-20T07:16:04.2935573Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4545)
2020-10-20T07:16:04.2938217Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5343)
2020-10-20T07:16:04.2941151Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
2020-10-20T07:16:04.2944021Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
2020-10-20T07:16:04.2946335Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
2020-10-20T07:16:04.2948742Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
2020-10-20T07:16:04.2951180Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-10-20T07:16:04.2953535Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
2020-10-20T07:16:04.3076493Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-10-20T07:16:04.3078240Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-10-20T07:16:04.3079982Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-10-20T07:16:04.3081582Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-10-20T07:16:04.3083729Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
2020-10-20T07:16:04.3086340Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
2020-10-20T07:16:04.3088724Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
2020-10-20T07:16:04.3090981Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
2020-10-20T07:16:04.3093301Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
2020-10-20T07:16:04.3095630Z 	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:434)
2020-10-20T07:16:04.3097350Z 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
2020-10-20T07:16:04.3099077Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-10-20T07:16:04.3101147Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2020-10-20T07:16:04.3102764Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-10-20T07:16:04.3104293Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-10-20T07:16:04.3105769Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-10-20T07:16:04.3107258Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-10-20T07:16:04.3109073Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-10-20T07:16:04.3110124Z 
2020-10-20T07:16:04.3111878Z 07:16:04,272 ERROR [org.apa.act.fil.XPathExpression] Default XPath evaluator could not be loaded: java.lang.ClassNotFoundException: org.apache.activemq.filter.XalanXPathEvaluator
2020-10-20T07:16:04.3114129Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
2020-10-20T07:16:04.3115335Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2020-10-20T07:16:04.3116796Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2020-10-20T07:16:04.3119131Z 	at org.apache.activemq.filter.XPathExpression.getXPathEvaluatorConstructor(XPathExpression.java:100)
2020-10-20T07:16:04.3121659Z 	at org.apache.activemq.filter.XPathExpression.<clinit>(XPathExpression.java:56)
```

**Comment by davsclaus** [comment]
I would turn the xpath off and add it in the docs as a limitation. I have not seen anyone uset that
