### ISSUE TITLE
PDF integration tests failing with Camel 3.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#1979]
The initial PDF creation step fails with:

```
2020-11-01T01:49:00.5763116Z 2020-11-01 01:49:00,570 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /pdf/createFromText failed, error id: da60e408-6679-45cb-b42d-51c2545cee4a-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: pdf://create?font=Courier&fontSize=6&pageSize=PAGE_SIZE_A5 due to: Error binding property (fontSize=6) with name: fontSize on bean: pdf://create?font=Courier&fontSize=6&pageSize=PAGE_SIZE_A5 with value: 6
2020-11-01T01:49:00.5768188Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
2020-11-01T01:49:00.5770944Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
2020-11-01T01:49:00.5773593Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
2020-11-01T01:49:00.5776100Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
2020-11-01T01:49:00.5778406Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2020-11-01T01:49:00.5780758Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2020-11-01T01:49:00.5786426Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-01T01:49:00.5789787Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2020-11-01T01:49:00.5791990Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2020-11-01T01:49:00.5794368Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2020-11-01T01:49:00.5797170Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:131)
2020-11-01T01:49:00.5800355Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
2020-11-01T01:49:00.5802969Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
2020-11-01T01:49:00.5805490Z 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2020-11-01T01:49:00.5807766Z 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
2020-11-01T01:49:00.5809634Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
2020-11-01T01:49:00.5811405Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
2020-11-01T01:49:00.5813130Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2020-11-01T01:49:00.5815001Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2020-11-01T01:49:00.5816459Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-01T01:49:00.5817299Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
2020-11-01T01:49:00.5819293Z Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: pdf://create?font=Courier&fontSize=6&pageSize=PAGE_SIZE_A5 due to: Error binding property (fontSize=6) with name: fontSize on bean: pdf://create?font=Courier&fontSize=6&pageSize=PAGE_SIZE_A5 with value: 6
2020-11-01T01:49:00.5822097Z 	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:902)
2020-11-01T01:49:00.5824731Z 	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:783)
2020-11-01T01:49:00.5827882Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:573)
2020-11-01T01:49:00.5830763Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:411)
2020-11-01T01:49:00.5893185Z 	at org.apache.camel.quarkus.component.pdf.it.PdfResource.createFromText(PdfResource.java:53)
2020-11-01T01:49:00.5895986Z 	at org.apache.camel.quarkus.component.pdf.it.PdfResource_ClientProxy.createFromText(PdfResource_ClientProxy.zig:234)
2020-11-01T01:49:00.5898307Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-01T01:49:00.5900604Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-01T01:49:00.5903309Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-01T01:49:00.5905476Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-01T01:49:00.5906999Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2020-11-01T01:49:00.5909022Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2020-11-01T01:49:00.5911763Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
2020-11-01T01:49:00.5915242Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
2020-11-01T01:49:00.5918456Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
2020-11-01T01:49:00.5994401Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2020-11-01T01:49:00.5997886Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
2020-11-01T01:49:00.6000431Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
2020-11-01T01:49:00.6002571Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
2020-11-01T01:49:00.6004696Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
2020-11-01T01:49:00.6006803Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2020-11-01T01:49:00.6007969Z 	... 17 more
2020-11-01T01:49:00.6009111Z Caused by: org.apache.camel.PropertyBindingException: Error binding property (fontSize=6) with name: fontSize on bean: pdf://create?font=Courier&fontSize=6&pageSize=PAGE_SIZE_A5 with value: 6
2020-11-01T01:49:00.6011909Z 	at org.apache.camel.support.PropertyBindingSupport.setSimplePropertyViaConfigurer(PropertyBindingSupport.java:849)
2020-11-01T01:49:00.6014881Z 	at org.apache.camel.support.PropertyBindingSupport.doSetPropertyValue(PropertyBindingSupport.java:609)
2020-11-01T01:49:00.6017638Z 	at org.apache.camel.support.PropertyBindingSupport.doBuildPropertyOgnlPath(PropertyBindingSupport.java:481)
2020-11-01T01:49:00.6020492Z 	at org.apache.camel.support.PropertyBindingSupport.doBindProperties(PropertyBindingSupport.java:376)
2020-11-01T01:49:00.6023155Z 	at org.apache.camel.support.PropertyBindingSupport.access$100(PropertyBindingSupport.java:87)
2020-11-01T01:49:00.6025296Z 	at org.apache.camel.support.PropertyBindingSupport$Builder.bind(PropertyBindingSupport.java:1877)
2020-11-01T01:49:00.6027346Z 	at org.apache.camel.support.DefaultEndpoint.setProperties(DefaultEndpoint.java:435)
2020-11-01T01:49:00.6029549Z 	at org.apache.camel.support.DefaultEndpoint.configureProperties(DefaultEndpoint.java:403)
2020-11-01T01:49:00.6031795Z 	at org.apache.camel.support.DefaultComponent.setProperties(DefaultComponent.java:387)
2020-11-01T01:49:00.6034193Z 	at org.apache.camel.component.pdf.PdfComponent.createEndpoint(PdfComponent.java:38)
2020-11-01T01:49:00.6036523Z 	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:156)
2020-11-01T01:49:00.6060870Z 	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:868)
2020-11-01T01:49:00.6062510Z 	... 37 more
2020-11-01T01:49:00.6064355Z Caused by: java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Float (java.lang.Double and java.lang.Float are in module java.base of loader 'bootstrap')
2020-11-01T01:49:00.6066596Z 	at org.apache.camel.component.pdf.PdfEndpointConfigurer.configure(PdfEndpointConfigurer.java:46)
2020-11-01T01:49:00.6069835Z 	at org.apache.camel.support.PropertyBindingSupport.setSimplePropertyViaConfigurer(PropertyBindingSupport.java:847)
2020-11-01T01:49:00.6071918Z 	... 48 more
```

**Comment by aldettinger** [comment]
Should be fixed [in camel-upstream](https://github.com/apache/camel/commit/d841a2bac27646cd16687bdb5b907dddcb355de6#diff-d31a06295d347a70d614c356860c2e03f854d84bc74cb8dcbcf5f3d77f7c0dea). Let's check in the next camel-master build.

**Comment by aldettinger** [comment]
Ok, I was able to run pdf itests against the last camel SNAPSHOT.
