### ISSUE TITLE
camel-nats intermittently failing on quarkus-platform

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#2061]
On quarkus-platform, the quarkus-universe-integration-tests-camel-nats has failed at least two times with the stack trace below:
```
2020-12-08T15:21:30.9252738Z [INFO] [INFO] Running org.apache.camel.quarkus.component.nats.it.NatsTest
2020-12-08T15:21:42.3156580Z [INFO] [ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 11.382 s <<< FAILURE! - in org.apache.camel.quarkus.component.nats.it.NatsTest
2020-12-08T15:21:42.3189043Z [INFO] [ERROR] consumeMaxMessagesShouldRetainFirstTwoMessages  Time elapsed: 0.012 s  <<< ERROR!
2020-12-08T15:21:42.3202141Z [INFO] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2020-12-08T15:21:42.3216236Z [INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:563)
2020-12-08T15:21:42.3240628Z [INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:630)
2020-12-08T15:21:42.3267155Z [INFO] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-12-08T15:21:42.3299362Z [INFO] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-12-08T15:21:42.3350970Z [INFO] 	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
2020-12-08T15:21:42.3351802Z [INFO] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-12-08T15:21:42.3369054Z [INFO] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-12-08T15:21:42.3369856Z [INFO] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-12-08T15:21:42.3385131Z [INFO] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-12-08T15:21:42.3385918Z [INFO] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-12-08T15:21:42.3386715Z [INFO] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-12-08T15:21:42.3434764Z [INFO] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
2020-12-08T15:21:42.3435462Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
2020-12-08T15:21:42.3451706Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
2020-12-08T15:21:42.3452528Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
2020-12-08T15:21:42.3453508Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
2020-12-08T15:21:42.3466983Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
2020-12-08T15:21:42.3467683Z [INFO] 	at java.util.Optional.orElseGet(Optional.java:267)
2020-12-08T15:21:42.3484034Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
2020-12-08T15:21:42.3485379Z [INFO] 	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
2020-12-08T15:21:42.3486536Z [INFO] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
2020-12-08T15:21:42.3501079Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3521618Z [INFO] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
2020-12-08T15:21:42.3522984Z [INFO] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
2020-12-08T15:21:42.3558853Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
2020-12-08T15:21:42.3627672Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3629068Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
2020-12-08T15:21:42.3643782Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
2020-12-08T15:21:42.3644873Z [INFO] 	at java.util.ArrayList.forEach(ArrayList.java:1259)
2020-12-08T15:21:42.3646235Z [INFO] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-12-08T15:21:42.3665516Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-12-08T15:21:42.3666750Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3684464Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-12-08T15:21:42.3685589Z [INFO] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-12-08T15:21:42.3686636Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-12-08T15:21:42.3731059Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3732398Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-12-08T15:21:42.3733687Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-12-08T15:21:42.3751068Z [INFO] 	at java.util.ArrayList.forEach(ArrayList.java:1259)
2020-12-08T15:21:42.3752302Z [INFO] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-12-08T15:21:42.3770509Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-12-08T15:21:42.3772067Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3773125Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-12-08T15:21:42.3793373Z [INFO] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-12-08T15:21:42.3794535Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-12-08T15:21:42.3795651Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.3830241Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-12-08T15:21:42.3831443Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-12-08T15:21:42.3892794Z [INFO] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-12-08T15:21:42.3894232Z [INFO] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-12-08T15:21:42.3902707Z [INFO] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-12-08T15:21:42.3914552Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
2020-12-08T15:21:42.3915659Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
2020-12-08T15:21:42.3916600Z [INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
2020-12-08T15:21:42.3935292Z [INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
2020-12-08T15:21:42.3936123Z [INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
2020-12-08T15:21:42.3963019Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
2020-12-08T15:21:42.3963843Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
2020-12-08T15:21:42.3964437Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
2020-12-08T15:21:42.3966931Z [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
2020-12-08T15:21:42.3975876Z [INFO] Caused by: java.lang.reflect.InvocationTargetException
2020-12-08T15:21:42.3976421Z [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-08T15:21:42.3977016Z [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-08T15:21:42.3996909Z [INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-08T15:21:42.3997521Z [INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-12-08T15:21:42.3998071Z [INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:249)
2020-12-08T15:21:42.4021592Z [INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:541)
2020-12-08T15:21:42.4036330Z [INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:574)
2020-12-08T15:21:42.4037266Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
2020-12-08T15:21:42.4054195Z [INFO] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-08T15:21:42.4054949Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
2020-12-08T15:21:42.4064273Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
2020-12-08T15:21:42.4072286Z [INFO] 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
2020-12-08T15:21:42.4073168Z [INFO] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
2020-12-08T15:21:42.4073748Z [INFO] 	... 29 more
2020-12-08T15:21:42.4104902Z [INFO] Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.apache.camel.quarkus.component.nats.it.NatsTestResource@486ec456
2020-12-08T15:21:42.4105904Z [INFO] 	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:57)
2020-12-08T15:21:42.4106582Z [INFO] 	... 42 more
2020-12-08T15:21:42.4109225Z [INFO] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2020-12-08T15:21:42.4112592Z [INFO] 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
2020-12-08T15:21:42.4129487Z [INFO] 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
2020-12-08T15:21:42.4130754Z [INFO] 	at org.apache.camel.quarkus.component.nats.it.NatsTestResource.start(NatsTestResource.java:84)
2020-12-08T15:21:42.4131849Z [INFO] 	at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:52)
2020-12-08T15:21:42.4132719Z [INFO] 	... 42 more
2020-12-08T15:21:42.4136277Z [INFO] Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2020-12-08T15:21:42.4137446Z [INFO] 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
2020-12-08T15:21:42.4138459Z [INFO] 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
2020-12-08T15:21:42.4139324Z [INFO] 	... 45 more
2020-12-08T15:21:42.4143447Z [INFO] Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2020-12-08T15:21:42.4144568Z [INFO] 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
2020-12-08T15:21:42.4145452Z [INFO] 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
2020-12-08T15:21:42.4158281Z [INFO] 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2020-12-08T15:21:42.4158862Z [INFO] 	... 46 more
2020-12-08T15:21:42.4161615Z [INFO] Caused by: java.lang.IllegalStateException: Container did not start correctly.
2020-12-08T15:21:42.4165031Z [INFO] 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:436)
2020-12-08T15:21:42.4167723Z [INFO] 	... 48 more
2020-12-08T15:21:42.4168294Z [INFO] 
```

The `NatsTestResource.tlsAuthContainer` is not able to start for an unknown reason.

**Comment by ppalaga** [comment]
This does not seem to be happening anymore. Let close and reopen once we see it again.
