### ISSUE TITLE
Debezium-mysql: Native test fails.

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#2069]
Integration tests for debezium-mysql are not executed automatically (mysql driver it is GPL2 licensed).
I've run test locally and it fails for camel-quarkus  `1.5.0-SNAPSHOT` and ` 1.4.0`, works on `1.3.0`.

Here is error log:

> [camel-quarkus-integration-test-debezium-1.5.0-SNAPSHOT-runner:145033]   (typeflow):  30,523.43 ms,  4.50 GB
[camel-quarkus-integration-test-debezium-1.5.0-SNAPSHOT-runner:145033]    (objects):  37,360.32 ms,  4.50 GB
[camel-quarkus-integration-test-debezium-1.5.0-SNAPSHOT-runner:145033]   (features):   1,601.39 ms,  4.50 GB
[camel-quarkus-integration-test-debezium-1.5.0-SNAPSHOT-runner:145033]     analysis:  74,068.17 ms,  4.50 GB
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by 
	reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef
>
>com.oracle.svm.core.util.UserError$UserException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by 
	reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef
>
>	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: Object was reached by 
	reading field com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.threadRef
>
>	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
	... 8 more
Error: Image build request failed with exit status 1

**Comment by JiriOndrusek** [comment]
Please, assign to me.
