### ISSUE TITLE
CSimple NPE even if CSimple language is not used

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#2098]
The route below runs into NPE while packaging a project:
```java
@ApplicationScoped
public class MyRoute extends EndpointRouteBuilder {
    @Inject
    MyProcessor myProcessor;

    @Override
    public void configure() {
        from("direct:start").process(myProcessor::process);  }

    @ApplicationScoped
    public static class MyProcessor {
        public String process(Exchange el) {    return "";   }
    }
}
```
As confirmed by @davsclaus the route does not use csimple at all, so that quarkus builder
shouldn't cause that NPE bug. 

Using lambda works however .process(e -> myProcessor.process(e))

```sh
[WARN] [org.apache.camel.quarkus.core.deployment.CSimpleRouteDefinitionProcessor]
Could not extract CSimple language expressions from the route
definition Routes: [Route[From[direct:start] -> []]] in class class
com.simple.temp.MyRoute.
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at com.simple.temp.MyRoute.configure(MyRoute.java:17)
        at org.apache.camel.quarkus.core.deployment.CSimpleRouteDefinitionProcessor.collectCSimpleExpresions(CSimpleRouteDefinitionProcessor.java:115)
        at jdk.internal.reflect.GeneratedMethodAccessor305.invoke(Unknown
Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by ppalaga** [comment]
Thanks for the report, @ennishol. This is a valid issue and we need to figure out, how to address it.

**Comment by ppalaga** [comment]
BTW, if you really do not use CSimple language, you can ignore the warning, or even suppress it by adding 

```
quarkus.camel.native.csimple.on-build-time-analysis-failure = ignore
```

to your `application.properties`

**Comment by ennishol** [comment]
thanks, I'll disable the warning then

**Comment by ppalaga** [comment]
https://github.com/apache/camel-quarkus/pull/2108 puts the csimple build time analysis to a new separate `camel-quarkus-csimple` extension. In that way, users not having `csimple` language in their routes won't see any warnings if their routes are not analyzable at build time.
