### ISSUE TITLE
Netty UDP does not work in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2187]
Seems there's only test coverage for TCP so any issues have gone undetected.

```
2021-02-02 11:25:06,791 ERROR [org.apa.cam.imp.eng.AbstractCamelContext] (main) Error starting CamelContext (camel-1) due to exception thrown: Class NioDatagramChannel does not have a public non-arg constructor: java.lang.IllegalArgumentException: Class NioDatagramChannel does not have a public non-arg constructor
	at io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:36)
	at io.netty.bootstrap.AbstractBootstrap.channel(AbstractBootstrap.java:110)
	at org.apache.camel.component.netty.SingleUDPNettyServerBootstrapFactory.startServerBootstrap(SingleUDPNettyServerBootstrapFactory.java:136)
	at org.apache.camel.component.netty.SingleUDPNettyServerBootstrapFactory.doStart(SingleUDPNettyServerBootstrapFactory.java:111)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:84)
	at org.apache.camel.component.netty.NettyConsumer.doStart(NettyConsumer.java:75)
```

**Comment by davsclaus** [comment]
Oh so wonder if we need some custom channel factory plugin (if possible) where we can create that NioDatagramChannel in Java code and not reflective or @jamesnetherton do you have some thoughts on this?

**Comment by jamesnetherton** [comment]
> wonder if we need some custom channel factory plugin

Perhaps... but it's the Netty channel factories that do the instantiation by reflection, so it's not something we can fix here directly.

This problem is actually already fixed when I added syslog native support. All that remains is to add more test coverage so we can be sure the main use cases are working ok.
