### ISSUE TITLE
camel-quarkus-git: integration test fail if gpg signing is enabled

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2210]
In my set-up I have GPG signing enabled on git, with the following config in .gitconfig

```
[commit]
    gpgsign = true
[gpg]
    program = gpg2
```

The git integration test fails with the following exception:

```
Caused by: org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:247)
	at org.apache.camel.component.git.producer.GitProducer.doCommit(GitProducer.java:336)
	at org.apache.camel.component.git.producer.GitProducer.process(GitProducer.java:121)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:218)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:112)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:109)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:189)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:158)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:229)
```

**Comment by lburgazzoli** [comment]
Maybe this helps: https://stackoverflow.com/questions/33804097/prevent-jgit-from-reading-the-native-git-config
