### ISSUE TITLE
FileTest fails on the platform

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2278]
https://github.com/quarkusio/quarkus-platform/pull/191/checks?check_run_id=1954131759#step:6:20071

```
[INFO] [INFO] Running org.apache.camel.quarkus.component.file.it.FileTest
[INFO] 2021-02-22 17:37:37,274 WARN  [io.qua.dep.QuarkusAugmentor] (main) Using Java versions older than 11 to build Quarkus applications is deprecated and will be disallowed in a future release!
[INFO] 2021-02-22 17:37:40,189 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.core.CamelContextRuntime
[INFO] 2021-02-22 17:37:40,284 INFO  [org.apa.cam.com.qua.QuartzComponent] (main) Create and initializing scheduler.
[INFO] 2021-02-22 17:37:40,288 INFO  [org.apa.cam.com.qua.QuartzComponent] (main) Setting org.quartz.scheduler.jmx.export=true to ensure QuartzScheduler(s) will be enlisted in JMX.
[INFO] 2021-02-22 17:37:40,421 INFO  [org.apa.cam.pol.qua.QuartzScheduledPollConsumerScheduler] (main) Job QuartzScheduledPollConsumerScheduler.trigger-1BFAB7128B42FD2-0000000000000000 (triggerType=CronTriggerImpl, jobClass=QuartzScheduledPollConsumerJob) is scheduled. Next fire date is Mon Feb 22 17:37:40 UTC 2021
[INFO] 2021-02-22 17:37:40,424 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:2 started:2)
[INFO] 2021-02-22 17:37:40,424 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) 	Started route1 (file://target/read-lock-in)
[INFO] 2021-02-22 17:37:40,425 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) 	Started route2 (file://target/quartz)
[INFO] 2021-02-22 17:37:40,426 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.8.0 (camel-1) started in 236ms (build:0ms init:81ms start:155ms)
[INFO] 2021-02-22 17:37:40,429 INFO  [org.apa.cam.com.qua.QuartzComponent] (main) Starting scheduler.
[INFO] 2021-02-22 17:37:40,443 INFO  [io.qua.qua.run.QuartzScheduler] (main) No scheduled business methods found - Quartz scheduler will not be started
[INFO] 2021-02-22 17:37:40,539 INFO  [io.quarkus] (main) Quarkus 1.12.0.Final on JVM started in 3.383s. Listening on: http://localhost:41755
[INFO] 2021-02-22 17:37:40,539 INFO  [io.quarkus] (main) Profile test activated. 
[INFO] 2021-02-22 17:37:40,539 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-file-watch, camel-quartz, camel-support-common, cdi, quartz, resteasy, resteasy-jackson, scheduler]
[INFO] 2021-02-22 17:37:42,834 WARN  [org.apa.cam.com.fil.wat.FileWatchConsumer] (Camel (camel-1) thread #1 - CamelFileWatchService) Caused by: [java.nio.file.InvalidPathException - Malformed input or input contains unmappable characters: /home/runner/work/quarkus-platform/quarkus-platform/integration-tests/camel/invoked/root/camel-file/target/FileTest371221233334910200/file.txt/?]: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/runner/work/quarkus-platform/quarkus-platform/integration-tests/camel/invoked/root/camel-file/target/FileTest371221233334910200/file.txt/?
[INFO] 	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
[INFO] 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
[INFO] 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
[INFO] 	at java.nio.file.Paths.get(Paths.java:84)
[INFO] 	at io.methvin.watcher.PathUtils.subMap(PathUtils.java:42)
[INFO] 	at io.methvin.watcher.DirectoryWatcher.watch(DirectoryWatcher.java:310)
[INFO] 	at io.methvin.watcher.DirectoryWatcher.lambda$watchAsync$0(DirectoryWatcher.java:212)
[INFO] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
Error: [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.963 s <<< FAILURE! - in org.apache.camel.quarkus.component.file.it.FileTest
Error: [ERROR] fileWatchCreateUpdate  Time elapsed: 12.307 s  <<< ERROR!
[INFO] org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.camel.quarkus.component.file.it.FileTest that uses java.nio.file.Path, java.nio.file.Pathjava.nio.file.Path, java.nio.file.Pathjava.lang.String was not fulfilled within 10 seconds.
[INFO] 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
[INFO] 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
[INFO] 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
[INFO] 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
[INFO] 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
[INFO] 	at org.apache.camel.quarkus.component.file.it.FileTest.awaitEvent(FileTest.java:136)
[INFO] 	at org.apache.camel.quarkus.component.file.it.FileTest.fileWatchCreateUpdate(FileTest.java:82)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:925)
[INFO] 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:831)
[INFO] 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
[INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
[INFO] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
[INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
[INFO] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
[INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
[INFO] 
[INFO] 2021-02-22 17:38:03,319 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.8.0 (camel-1) shutting down
[INFO] 2021-02-22 17:38:03,321 INFO  [org.apa.cam.pol.qua.QuartzScheduledPollConsumerScheduler] (main) Deleting job QuartzScheduledPollConsumerScheduler.trigger-1BFAB7128B42FD2-0000000000000000
[INFO] 2021-02-22 17:38:03,338 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes shutdown summary (total:2 stopped:2)
[INFO] 2021-02-22 17:38:03,338 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) 	Stopped route1 (file://target/read-lock-in)
[INFO] 2021-02-22 17:38:03,339 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) 	Stopped route2 (file://target/quartz)
[INFO] 2021-02-22 17:38:03,354 INFO  [org.apa.cam.com.qua.QuartzComponent] (main) Shutting down scheduler. (will wait for all jobs to complete first.)
[INFO] 2021-02-22 17:38:03,508 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.8.0 (camel-1) shutdown in 189ms (uptime:23s237ms)
[INFO] 2021-02-22 17:38:03,558 INFO  [io.quarkus] (main) Quarkus stopped in 0.288s
[INFO] [INFO] 
[INFO] [INFO] Results:
[INFO] [INFO] 
Error: [ERROR] Errors: 
Error: [ERROR]   FileTest.fileWatchCreateUpdate:82->awaitEvent:136 ? ConditionTimeout Condition...
[INFO] [INFO] 
Error: [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
```

I cannot reproduce this locally. Disabling the test for now.

**Comment by jamesnetherton** [comment]
I think this is caused by the OS locale not being set properly. Which is why we have [this](https://github.com/apache/camel-quarkus/blob/master/.github/workflows/ci-build.yaml#L47) in our CI workflow config.

**Comment by ppalaga** [comment]
Thanks, sent https://github.com/quarkusio/quarkus-platform/pull/214/

**Comment by ppalaga** [comment]
Fixed via https://github.com/quarkusio/quarkus-platform/pull/214
