### ISSUE TITLE
Test FTPS

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2317]
While we have a test for FTP, SFTP, there is no test for FTPS in `integration-tests/ftp`

**Comment by jamesnetherton** [comment]
I think I need to revisit this. It seems to be a bit flaky on GitHub CI.

```
Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:696)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:221)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:213)
	at org.apache.camel.quarkus.component.ftps.it.FtpsResource.createFile(FtpsResource.java:60)
	at org.apache.camel.quarkus.component.ftps.it.FtpsResource_ClientProxy.createFile(FtpsResource_ClientProxy.zig:193)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
Caused by: org.apache.camel.component.file.GenericFileOperationFailedException: File operation failed:  Connection or outbound has closed. Code: 550
	at org.apache.camel.component.file.remote.FtpOperations.doChangeDirectory(FtpOperations.java:903)
	at org.apache.camel.component.file.remote.FtpOperations.changeCurrentDirectory(FtpOperations.java:869)
	at org.apache.camel.component.file.remote.FtpOperations.buildDirectory(FtpOperations.java:394)
	at org.apache.camel.component.file.GenericFileProducer.writeFile(GenericFileProducer.java:279)
	at org.apache.camel.component.file.GenericFileProducer.processExchange(GenericFileProducer.java:173)
	at org.apache.camel.component.file.remote.RemoteFileProducer.process(RemoteFileProducer.java:60)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:190)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:153)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:219)
	... 32 more
Caused by: java.net.SocketException: Connection or outbound has closed
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1196)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at org.apache.commons.net.ftp.FTP.send(FTP.java:535)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:510)
	at org.apache.commons.net.ftp.FTPSClient.sendCommand(FTPSClient.java:561)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:635)
	at org.apache.commons.net.ftp.FTP.cwd(FTP.java:867)
	at org.apache.commons.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1317)
	at org.apache.camel.component.file.remote.FtpOperations.doChangeDirectory(FtpOperations.java:900)
	... 47 more
```

**Comment by ppalaga** [comment]
A similar one in https://github.com/apache/camel-quarkus/pull/2387/checks?check_run_id=2200441934 . I'll disable the test for now

```
[INFO] Running org.apache.camel.quarkus.component.ftps.it.FtpsIT
Mar 26, 2021 9:27:39 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
2021-03-26 09:27:38,588 INFO  [org.apa.ssh.com.io.DefaultIoServiceFactoryFactory] (main) No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
2021-03-26 09:27:40,122 INFO  [org.apa.ssh.com.io.DefaultIoServiceFactoryFactory] (build-46) No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:153)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:219)
	... 32 more
Caused by: java.net.SocketException: Connection or outbound has closed
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1196)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at org.apache.commons.net.ftp.FTP.send(FTP.java:535)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:510)
	at org.apache.commons.net.ftp.FTPSClient.sendCommand(FTPSClient.java:561)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:635)
	at org.apache.commons.net.ftp.FTP.cwd(FTP.java:867)
	at org.apache.commons.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1317)
	at org.apache.camel.component.file.remote.FtpOperations.doChangeDirectory(FtpOperations.java:900)
	... 47 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    FtpsIT>FtpsTest.testFtpsComponent:38 » SocketTimeout Read timed out
[INFO] 
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by ppalaga** [comment]
Created a new issue for the flaky FtpsIT #2810
