### ISSUE TITLE
quarkus 1.7.0 DocumentBuilderFactoryImpl not found

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#2323]
After migrating to  camel quarkus 1.7.0, the following exception occurs when running jar `java -jar target/quarkus-app/quarkus-run.jar`
 but not with `mvn quarkus:dev`

`
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
	at org.apache.camel.converter.jaxp.XmlConverter.createDocumentBuilderFactory(XmlConverter.java:951)
	at org.apache.camel.converter.jaxp.XmlConverter.getDocumentBuilderFactory(XmlConverter.java:880)
	at org.apache.camel.converter.jaxp.XmlConverter.getDocumentBuilderFactory(XmlConverter.java:938)
	at org.apache.camel.converter.jaxp.XmlConverter.toDOMDocument(XmlConverter.java:674)
	at org.apache.camel.converter.jaxp.CamelXmlJaxpBulkConverterLoader.doConvertTo(CamelXmlJaxpBulkConverterLoader.java:304)
	at org.apache.camel.converter.jaxp.CamelXmlJaxpBulkConverterLoader.convertTo(CamelXmlJaxpBulkConverterLoader.java:35)
	at org.apache.camel.impl.converter.CoreTypeConverterRegistry.doConvertTo(CoreTypeConverterRegistry.java:461)
	at org.apache.camel.impl.converter.CoreTypeConverterRegistry.doConvertTo(CoreTypeConverterRegistry.java:356)
	at org.apache.camel.impl.converter.CoreTypeConverterRegistry.convertTo(CoreTypeConverterRegistry.java:203)
	at org.apache.camel.language.xpath.XPathBuilder.doGetDocument(XPathBuilder.java:1290)
	at org.apache.camel.language.xpath.XPathBuilder.getDocument(XPathBuilder.java:1269)
	at org.apache.camel.language.xpath.XPathBuilder.doInEvaluateAs(XPathBuilder.java:1033)
	at org.apache.camel.language.xpath.XPathBuilder.evaluateAs(XPathBuilder.java:916)
	at org.apache.camel.language.xpath.XPathBuilder.evaluate(XPathBuilder.java:883)
	at org.apache.camel.language.xpath.XPathBuilder.evaluate(XPathBuilder.java:206)
	at org.apache.camel.processor.SetPropertyProcessor.process(SetPropertyProcessor.java:47)
	... 18 more`

**Comment by jamesnetherton** [comment]
Please can you provide a bit more context. What do your routes look like, what dependencies do you have etc?

**Comment by ennishol** [comment]
@jamesnetherton  Yes sorry, failed to add in the description.
Basically, adding org.apache.xmlgraphics will demonstrate the problem
```
<dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-xpath</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>fop</artifactId>
      <version>2.6</version>
    </dependency>
```
a little route to reproduce
```
@ApplicationScoped
public class MyRoute extends EndpointRouteBuilder {

    @Override
    public void configure() {
        String xml = "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?><Item Number=\"42\"></Item>";
        from("timer://foo?fixedRate=true&period=15000")
                    .log("started")
                    .setBody(constant(xml))
                    .setProperty("TestNumber", xpath("/Item/@Number", Long.class))
                    .log("Number ${exchangeProperty.TestNumber}");
    }

}
```

**Comment by jamesnetherton** [comment]
You probably need to add an exclusion to the `fop` dependency like:

```xml
<exclusions>
    <exclusion>
        <groupId>xml-apis</groupId>
        <artifactId>xml-apis</artifactId>
    </exclusion>
</exclusions>
```

If you want fop support with camel, then you can use `camel-quarkus-fop` it does this exclusion internally and adds the necessary native support.

**Comment by ennishol** [comment]
@jamesnetherton  Thank you very much! Looks like it will resolve the issue
