### ISSUE TITLE
Intermittent failure in camel-quarkus-master-integration-test

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2384]
We should investigate if it happens more often

```
2021-03-25 23:42:15,203 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-03-25 23:42:15,213 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:1 started:1)
2021-03-25 23:42:15,213 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (master:ns:timer:test)
2021-03-25 23:42:15,213 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 2ms (build:0ms init:1ms start:1ms)
2021-03-25 23:42:15,218 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 1.8.0-SNAPSHOT native (powered by Quarkus 1.13.0.Final) started in 0.025s. Listening on: http://0.0.0.0:45853
2021-03-25 23:42:15,218 INFO  [io.quarkus] (main) Profile prod activated. 
2021-03-25 23:42:15,218 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-support-common, camel-timer, cdi, resteasy, smallrye-health]
2021-03-25 23:42:16,213 INFO  [org.apa.cam.com.fil.clu.FileLockClusterView] (Camel (camel-1) thread #0 - FileLockClusterService-null) Lock on file target/cluster/ns acquired (lock=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid])
2021-03-25 23:42:16,213 INFO  [org.apa.cam.com.mas.MasterConsumer] (Camel (camel-1) thread #0 - FileLockClusterService-null) Leadership taken. Consumer started: timer://test?period=100
Mar 25, 2021 11:42:16 PM org.apache.camel.quarkus.test.support.process.QuarkusProcessExecutor <init>
INFO: Executing process: /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/master/target/camel-quarkus-integration-test-master-1.8.0-SNAPSHOT-runner -Dapplication.id=follower -Dquarkus.http.port=38653 -Dquarkus.http.ssl-port=34893
2021-03-25 23:42:16,430 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-03-25 23:42:16,475 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:1 started:1)
2021-03-25 23:42:16,475 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (master:ns:timer:test)
2021-03-25 23:42:16,475 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 2ms (build:0ms init:1ms start:1ms)
2021-03-25 23:42:16,478 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 1.8.0-SNAPSHOT native (powered by Quarkus 1.13.0.Final) started in 0.074s. Listening on: http://0.0.0.0:38653
2021-03-25 23:42:16,478 INFO  [io.quarkus] (main) Profile prod activated. 
2021-03-25 23:42:16,478 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-support-common, camel-timer, cdi, resteasy, smallrye-health]
2021-03-25 23:42:18,485 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Apache Camel 3.9.0 (camel-1) shutting down
2021-03-25 23:42:18,486 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Routes shutdown summary (total:1 stopped:1)
2021-03-25 23:42:18,486 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1)     Stopped route1 (master:ns:timer:test)
2021-03-25 23:42:18,486 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Apache Camel 3.9.0 (camel-1) shutdown in 1ms (uptime:3s274ms)
2021-03-25 23:42:18,491 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master stopped in 0.005s
Mar 25, 2021 11:42:18 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:45853: The target server failed to respond
Mar 25, 2021 11:42:18 PM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request to {}->http://localhost:45853
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.24 s <<< FAILURE! - in org.apache.camel.quarkus.component.master.it.MasterIT
Error:  testFailover  Time elapsed: 2.779 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by ppalaga** [comment]
Another failure

```
[INFO] Running org.apache.camel.quarkus.component.master.it.MasterIT
Mar 26, 2021 8:52:44 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
Mar 26, 2021 8:52:45 AM io.quarkus.arc.processor.BeanProcessor$PrivateMembersCollector log
INFO: Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field org.apache.camel.quarkus.component.master.it.MasterResource#camelContext
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/master/target/camel-quarkus-integration-test-master-1.8.0-SNAPSHOT-runner
======================================================================================
Executing [/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/master/target/camel-quarkus-integration-test-master-1.8.0-SNAPSHOT-runner, -Dquarkus.http.port=45081, -Dquarkus.http.ssl-port=43837, -Dtest.url=http://localhost:45081, -Dquarkus.log.file.path=/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/master/target/quarkus.log, -Dquarkus.log.file.enable=true]
2021-03-26 08:52:45,898 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-03-26 08:52:45,946 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:1 started:1)
2021-03-26 08:52:45,946 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (master:ns:timer:test)
2021-03-26 08:52:45,946 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 2ms (build:0ms init:1ms start:1ms)
2021-03-26 08:52:45,952 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 1.8.0-SNAPSHOT native (powered by Quarkus 1.13.0.Final) started in 0.064s. Listening on: http://0.0.0.0:45081
2021-03-26 08:52:45,952 INFO  [io.quarkus] (main) Profile prod activated. 
2021-03-26 08:52:45,952 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-support-common, camel-timer, cdi, resteasy, smallrye-health]
2021-03-26 08:52:46,945 INFO  [org.apa.cam.com.fil.clu.FileLockClusterView] (Camel (camel-1) thread #0 - FileLockClusterService-null) Lock on file target/cluster/ns acquired (lock=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid])
2021-03-26 08:52:46,946 INFO  [org.apa.cam.com.mas.MasterConsumer] (Camel (camel-1) thread #0 - FileLockClusterService-null) Leadership taken. Consumer started: timer://test?period=100
Mar 26, 2021 8:52:47 AM org.apache.camel.quarkus.test.support.process.QuarkusProcessExecutor <init>
INFO: Executing process: /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/master/target/camel-quarkus-integration-test-master-1.8.0-SNAPSHOT-runner -Dapplication.id=follower -Dquarkus.http.port=43871 -Dquarkus.http.ssl-port=37911
2021-03-26 08:52:47,068 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-03-26 08:52:47,075 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:1 started:1)
2021-03-26 08:52:47,075 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (master:ns:timer:test)
2021-03-26 08:52:47,076 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 2ms (build:0ms init:0ms start:2ms)
2021-03-26 08:52:47,084 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 1.8.0-SNAPSHOT native (powered by Quarkus 1.13.0.Final) started in 0.041s. Listening on: http://0.0.0.0:43871
2021-03-26 08:52:47,084 INFO  [io.quarkus] (main) Profile prod activated. 
2021-03-26 08:52:47,084 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-support-common, camel-timer, cdi, resteasy, smallrye-health]
2021-03-26 08:52:49,090 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Apache Camel 3.9.0 (camel-1) shutting down
2021-03-26 08:52:49,090 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Routes shutdown summary (total:1 stopped:1)
2021-03-26 08:52:49,090 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1)     Stopped route1 (master:ns:timer:test)
2021-03-26 08:52:49,091 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (executor-thread-1) Apache Camel 3.9.0 (camel-1) shutdown in 1ms (uptime:3s146ms)
Mar 26, 2021 8:52:49 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:45081: The target server failed to respond
Mar 26, 2021 8:52:49 AM org.apache.http.impl.client.DefaultRequestDirector tryExecute
INFO: Retrying request to {}->http://localhost:45081
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.25 s <<< FAILURE! - in org.apache.camel.quarkus.component.master.it.MasterIT
Error:  testFailover  Time elapsed: 2.694 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:668)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:481)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    MasterIT>MasterTest.testFailover:53 » Connect Connection refused (Connection r...
[INFO] 
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
