### ISSUE TITLE
FixedLengthWithLocaleTest.marshalFixedLengthWithLocaleShouldSucceed fails on Java 8

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2445]
We do not test on Java 8 anymore, but this happens on Quarkus platform where Java 8 still used:

```
[INFO] [INFO] Running org.apache.camel.quarkus.component.bindy.it.FixedLengthWithLocaleTest
[INFO] 2021-04-06 20:02:45,362 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /bindy/marshalFixedLengthWithLocaleShouldSucceed failed, error id: e7e9aafa-bcde-40b4-9066-1e11d5ac7ac7-1: org.jboss.resteasy.spi.UnhandledException: org.opentest4j.AssertionFailedError: expected: <٣٫٢٠٠
[INFO] > but was: <3.200
[INFO] >
[INFO] 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
[INFO] 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
[INFO] 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[INFO] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[INFO] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[INFO] Caused by: org.opentest4j.AssertionFailedError: expected: <٣٫٢٠٠
[INFO] > but was: <3.200
[INFO] >
[INFO] 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
[INFO] 	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
[INFO] 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
[INFO] 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
[INFO] 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
[INFO] 	at org.apache.camel.quarkus.component.bindy.it.BindyResource.marshalFixedLengthWithLocaleShouldSucceed(BindyResource.java:124)
[INFO] 	at org.apache.camel.quarkus.component.bindy.it.BindyResource_ClientProxy.marshalFixedLengthWithLocaleShouldSucceed(BindyResource_ClientProxy.zig:203)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
[INFO] 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
[INFO] 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
[INFO] 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] 	... 15 more
[INFO] 
Error: [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.082 s <<< FAILURE! - in org.apache.camel.quarkus.component.bindy.it.FixedLengthWithLocaleTest
Error: [ERROR] marshalFixedLengthWithLocaleShouldSucceed  Time elapsed: 0.082 s  <<< FAILURE!
```

**Comment by ppalaga** [comment]
I am going to disable the test in the platform for now.
