### ISSUE TITLE
Salesforce fails to start because loginUrl configuration is ignored

### ISSUE THREAD

**Issue by mmuzikar** [apache/camel-quarkus#2499]
While running the `1.8.1` integration-tests the salesforce tests failed with:
```
2021-04-20 09:57:58,684 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-04-20 09:57:58,754 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2021-04-20 09:57:58,756 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.salesforce.loginUrl=https://login.salesforce.com
2021-04-20 09:57:58,757 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.salesforce.password=xxxxxx
2021-04-20 09:57:58,757 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.salesforce.userName=xxxxxx
2021-04-20 09:57:58,757 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.salesforce.clientSecret=xxxxxx
2021-04-20 09:57:58,757 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.salesforce.clientId={{env:SALESFORCE_CLIENTID}}
2021-04-20 09:57:59,032 WARN  [org.apa.cam.com.sal.SalesforceConsumer] (main) Property sObjectName or sObjectClass NOT set, messages will be of type java.lang.Map
2021-04-20 09:57:59,048 INFO  [org.ecl.jet.uti.log] (main) Logging initialized @4854ms to org.eclipse.jetty.util.log.Slf4jLog
2021-04-20 09:57:59,084 INFO  [org.apa.cam.sup.jss.SSLContextParameters] (main) Available providers: SUN version 11.
2021-04-20 09:57:59,278 ERROR [org.apa.cam.imp.eng.AbstractCamelContext] (main) Error starting CamelContext (camel-1) due to exception thrown: Failed to start component salesforce because of loginUrl must be specified: org.apache.camel.FailedToStartComponentException: Failed to start component salesforce because of loginUrl must be specified
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3089)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2861)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2812)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2507)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:139)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:631)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:212)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:331)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:638)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:684)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at ...
Caused by: java.lang.IllegalArgumentException: loginUrl must be specified
	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:152)
	at org.apache.camel.component.salesforce.SalesforceLoginConfig.validate(SalesforceLoginConfig.java:218)
	at org.apache.camel.component.salesforce.internal.SalesforceSession.<init>(SalesforceSession.java:94)
	at org.apache.camel.component.salesforce.SalesforceComponent.doStart(SalesforceComponent.java:398)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3474)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3087)
	... 58 more

```
Which is interesting because the loginUrl is hardcoded in the test and is printed at the start, so there must be something wrong with the SalesforceLoginConfig validation I'd suspect.

**Comment by mmuzikar** [comment]
Tests are passing now after switch to 3.10.0
