### ISSUE TITLE
several integration-test failure in native mode

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2550]
I encountered test failures in integration-test for 
file
hazelcast
minio 
hbase
when running tests with -Pnative

For the hbase, since it's in extensions-jvm folder, IIUC, this means it supports jvm mode only, so I assume it shouldn't have native profile.

For the hazelcast, I got exceptions " java.lang.IllegalStateException: ICMP not supported in this platform: mac os x" on my mac. So I think disable it on mac should be sufficient
```
com.oracle.svm.core.util.UserError$UserException: Class initialization failed for com.hazelcast.internal.util.ICMPHelper. The class is requested for re-running (reason: Quarkus)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:385)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:1155)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:701)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:701)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unsafe.java:698)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:383)
	... 12 more
Caused by: java.lang.IllegalStateException: ICMP not supported in this platform: mac os x
	at com.hazelcast.internal.util.ICMPHelper.getBundledLibraryPath(ICMPHelper.java:66)
	at com.hazelcast.internal.util.ICMPHelper.extractBundledLib(ICMPHelper.java:51)
	at com.hazelcast.internal.util.ICMPHelper.<clinit>(ICMPHelper.java:36)
	... 16 more

```

For the file,  I constantly get the error like
```
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.camel.quarkus.component.file.it.FileTest that uses java.nio.file.Path, java.nio.file.Pathjava.nio.file.Path, java.nio.file.Pathjava.lang.String was not fulfilled within 10 seconds.
```
For FileIT>FileTest.fileWatchCreateUpdate:74->FileTest.awaitEvent:136 » ConditionTimeout.  But this seems to be a timing issue on my machine, change waiting time from 10 secs to 20 secs can fix it.

For the minio, I get error like
```
2021-05-04 09:58:00,872 WARN  [org.apa.cam.com.min.MinioConsumer] (Camel (camel-1) thread #0 - minio://mycamel) Consumer MinioConsumer[minio://mycamel?accessKey=testAccessKey&autoCreateBucket=true&destinationBucketName=camel-kafka-connector&minioClient=%23minioClient&moveAfterRead=true&secretKey=xxxxxx] failed polling endpoint: minio://mycamel?accessKey=testAccessKey&autoCreateBucket=true&destinationBucketName=camel-kafka-connector&minioClient=%23minioClient&moveAfterRead=true&secretKey=xxxxxx. Will try again at next poll. Caused by: [java.time.format.DateTimeParseException - Text 'Tue, 04 May 2021 13:57:51 GMT' could not be parsed at index 0]: java.time.format.DateTimeParseException: Text 'Tue, 04 May 2021 13:57:51 GMT' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:598)
	at io.minio.StatObjectResponse.<init>(StatObjectResponse.java:50)
	at io.minio.MinioClient.statObject(MinioClient.java:968)
	at org.apache.camel.quarkus.component.minio.it.MinioClientProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.statObject(MinioClientProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.zig:2799)
	at org.apache.camel.component.minio.MinioEndpoint.getObjectStat(MinioEndpoint.java:212)
```
I'm not sure this is only on my machine or not. I believe the time format "Tue, 04 May 2021 13:57:51 GMT" meets the required pattern "EEE',' dd MMM yyyy HH':'mm':'ss 'GMT'"

**Comment by ffang** [comment]
For the minio integration test, the exception throws from io.minio.Time class when using
```
public static final DateTimeFormatter HTTP_HEADER_DATE_FORMAT =
      DateTimeFormatter.ofPattern("EEE',' dd MMM yyyy HH':'mm':'ss 'GMT'", Locale.US).withZone(UTC);
```

I strongly suspest in the quarkus native mode, somehow on my machine can't find Locale.US, instead it will use Locale.CA. So the expected time stamp should be "Mon., 03 May 2021 18:10:53 GMT" instead of "Mon, 03 May 2021 18:10:53 GMT", I found a related jdk issue here https://bugs.openjdk.java.net/browse/JDK-8211321
