### ISSUE TITLE
[camel 3.10] NATS native image build failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2589]
```
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by 
	reading field java.security.SecureRandom.secureRandomSpi of
		constant java.security.SecureRandom@6b0032ba reached by 
	scanning method io.nats.client.support.SSLUtils.createOpenTLSContext(SSLUtils.java:43)
Call path from entry point to io.nats.client.support.SSLUtils.createOpenTLSContext(): 
	at io.nats.client.support.SSLUtils.createOpenTLSContext(SSLUtils.java:39)
	at io.nats.client.Options$Builder.build(Options.java:1352)
	at org.apache.camel.component.nats.NatsEndpoint.getConnection(NatsEndpoint.java:85)
	at com.oracle.svm.reflect.NatsEndpoint_getConnection_ae93cd8bd1f246593dcfa360791d8ee42ca51ac9_394.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:211)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:164)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:293)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

**Comment by jamesnetherton** [comment]
/CC @aldettinger - please can you take a look into this.

For now, I have disabled the NATS itest native build on CI in `test-categories.yaml`.

**Comment by aldettinger** [comment]
Ok, I see it disabled on camel-main, let's have a look.

**Comment by ppalaga** [comment]
Fixed via https://github.com/apache/camel-quarkus/pull/2643/commits/01110b56147af3ba94263b11a31f2275cd4e2cd2
