### ISSUE TITLE
integration-tests/servlet doesn't work in development mode

### ISSUE THREAD

**Issue by coolbeevip** [apache/camel-quarkus#263]
I'm run `mvn clean compile quarkus:dev -DnoDeps` getting the following error:

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< org.my-org:my-app >--------------------------
[INFO] Building my-app 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ my-app ---
[INFO] Deleting /Users/zhanglei/github/servlet/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ my-app ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ my-app ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ my-app ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ my-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ my-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/zhanglei/github/servlet/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:0.22.0:dev (default-cli) @ my-app ---
Listening for transport dt_socket at address: 5005
00:45:44,670 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
00:45:44,989 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
00:45:45,466 INFO  [io.qua.dep.QuarkusAugmentor] Quarkus augmentation completed in 796ms
00:45:45,490 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:126)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:325)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.camel.quarkus.component.servlet.CamelRoute
	at org.apache.camel.quarkus.core.runtime.CamelRecorder.addBuilder(CamelRecorder.java:75)
	at io.quarkus.deployment.steps.BuildProcessor$create7.deploy_0(BuildProcessor$create7.zig:106)
	at io.quarkus.deployment.steps.BuildProcessor$create7.deploy(BuildProcessor$create7.zig:36)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:263)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.quarkus.component.servlet.CamelRoute
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.camel.quarkus.core.runtime.CamelRecorder.addBuilder(CamelRecorder.java:73)
	... 12 more

00:45:45,491 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover
00:45:45,507 INFO  [org.xnio] XNIO version 3.7.2.Final
00:45:45,528 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final

```

**Comment by coolbeevip** [comment]
there have similar questions on quarkus. https://github.com/quarkusio/quarkus/issues/2809

**Comment by coolbeevip** [comment]
Upgrade camel-qurakus to 0.2.1-SNAPSHOT solve the issue
