### ISSUE TITLE
Intermittent failures in MllpIT 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2671]
Seen here https://github.com/apache/camel-quarkus/pull/2665/checks?check_run_id=2665270714#step:9:6969
```
[INFO] Running org.apache.camel.quarkus.component.mllp.it.MllpIT
May 25, 2021 1:57:08 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/mllp/target/camel-quarkus-integration-test-mllp-2.0.0-M1-SNAPSHOT-runner
======================================================================================
Executing [/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/mllp/target/camel-quarkus-integration-test-mllp-2.0.0-M1-SNAPSHOT-runner, -Dquarkus.http.port=43777, -Dquarkus.http.ssl-port=46297, -Dtest.url=http://localhost:43777, -Dquarkus.log.file.path=/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/mllp/target/quarkus.log, -Dquarkus.log.file.enable=true]
2021-05-25 13:57:10,589 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-05-25 13:57:10,598 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:3 started:3)
2021-05-25 13:57:10,598 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (mllp://localhost:43777)
2021-05-25 13:57:10,598 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route2 (direct://validMessage)
2021-05-25 13:57:10,599 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route3 (direct://invalidMessage)
2021-05-25 13:57:10,599 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.10.0 (camel-1) started in 5ms (build:0ms init:2ms start:3ms)
2021-05-25 13:57:10,602 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.10.0 (camel-1) shutting down
2021-05-25 13:57:10,603 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes shutdown summary (total:3 stopped:3)
2021-05-25 13:57:10,603 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route1 (mllp://localhost:43777)
2021-05-25 13:57:10,603 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route2 (direct://validMessage)
2021-05-25 13:57:10,603 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Stopped route3 (direct://invalidMessage)
2021-05-25 13:57:10,603 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.10.0 (camel-1) shutdown in 1ms (uptime:7ms)
2021-05-25 13:57:10,604 INFO  [org.apa.cam.com.mll.int.TcpServerAcceptThread] (TcpServerAcceptThread[mllp://localhost:43777] - localhost/127.0.0.1:43777) Starting ServerSocket accept thread for ServerSocket[addr=localhost/127.0.0.1,localport=43777]
2021-05-25 13:57:10,604 INFO  [org.apa.cam.com.mll.int.TcpServerAcceptThread] (TcpServerAcceptThread[mllp://localhost:43777] - localhost/127.0.0.1:43777) ServerSocket.accept loop finished - closing listener
2021-05-25 13:57:10,608 ERROR [io.ver.cor.imp.DeploymentManager] (main) Undeploy failed: java.lang.IllegalStateException: Already undeployed
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.doUndeploy(DeploymentManager.java:328)
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.undeploy(DeploymentManager.java:306)
	at io.vertx.core.impl.DeploymentManager.undeployVerticle(DeploymentManager.java:82)
	at io.vertx.core.impl.DeploymentManager.undeployAll(DeploymentManager.java:109)
	at io.vertx.core.impl.VertxImpl.lambda$close$14(VertxImpl.java:579)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
	at io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    MllpIT.validMessage » IllegalState Unable to determine the status of the runni...
[INFO] 
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 3
[INFO] 
```

**Comment by jamesnetherton** [comment]
Looking at the test logs, seems that `AvailablePortFinder` must have found the same port twice, because both `quarkus.http.port` and the MLLP consumer port have been set to 43777.

**Comment by ppalaga** [comment]
What a "luck"! Thanks for investigating!

**Comment by jamesnetherton** [comment]
Should be fixed by https://github.com/apache/camel-quarkus/commit/7b9a771ce40eff83bcf23e8b89ccfc3a0ea4c5dd.
