### ISSUE TITLE
GraalVM 21.1, KafkaSaslSslIT: ClassNotFoundException: org.apache.kafka.common.security.scram.internals.ScramSaslClient$ScramSaslClientFactory

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2674]
```
[INFO] Running org.apache.camel.quarkus.kafka.sasl.KafkaSaslSslIT
May 25, 2021 5:33:41 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/kafka-sasl-ssl/target/camel-quarkus-integration-test-kafka-sasl-ssl-2.0.0-M1-SNAPSHOT-runner
======================================================================================
Executing [/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/kafka-sasl-ssl/target/camel-quarkus-integration-test-kafka-sasl-ssl-2.0.0-M1-SNAPSHOT-runner, -Dquarkus.http.port=41361, -Dquarkus.http.ssl-port=39197, -Dtest.url=http://localhost:41361, -Dquarkus.log.file.path=/home/runner/work/camel-quarkus/camel-quarkus/integration-tests/kafka-sasl-ssl/target/quarkus.log, -Dquarkus.log.file.enable=true, -Dcamel.component.kafka.ssl-keystore-location=/tmp/kafka/kafka-keystore.p12, -Dcamel.component.kafka.ssl-keystore-type=PKCS12, -Dcamel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required username="alice" ***;, -Dcamel.component.kafka.ssl-truststore-type=PKCS12, -Dcamel.component.kafka.ssl-key-*** -Dcamel.component.kafka.security-protocol=SASL_SSL, -Dcamel.component.kafka.ssl-truststore-*** -Dcamel.component.kafka.ssl-truststore-location=/tmp/kafka/kafka-truststore.p12, -Dcamel.component.kafka.ssl-keystore-*** -Dcamel.component.kafka.sasl-mechanism=SCRAM-SHA-512, -Dcamel.component.kafka.brokers=SASL_SSL://localhost:49182]
2021-05-25 17:33:57,778 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-05-25 17:33:57,783 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2021-05-25 17:33:57,783 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.kafka.sslKeystoreType=PKCS12
2021-05-25 17:33:57,783 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.kafka.sslKeystoreLocation=/tmp/kafka/kafka-keystore.p12
2021-05-25 17:33:57,783 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.kafka.saslJaasConfig=xxxxxx
2021-05-25 17:33:57,783 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     camel.component.kafka.sslTruststoreType=PKCS12
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:290)
	at java.security.Provider$Service.getImplClass(Provider.java:1920)
	... 25 more
```

**Comment by ppalaga** [comment]
Fixed via c213c9b
