### ISSUE TITLE
Error when using camel-quarkus-jackson in native mode: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2677]
If we set com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule as ModuleClassNames for JacksonDataFormat, in native mode we see errors like
```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule
	at org.apache.camel.quarkus.core.CamelQuarkusClassResolver.resolveMandatoryClass(CamelQuarkusClassResolver.java:68)
	at org.apache.camel.component.jackson.AbstractJacksonDataFormat.doStart(AbstractJacksonDataFormat.java:628)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	... 47 more

2021-05-26 10:14:07,412 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.ClassNotFoundException: com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule
	at org.apache.camel.quarkus.core.CamelQuarkusClassResolver.resolveMandatoryClass(CamelQuarkusClassResolver.java:68)
	at org.apache.camel.component.jackson.AbstractJacksonDataFormat.doStart(AbstractJacksonDataFormat.java:628)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1462)
	at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1383)
	at org.apache.camel.support.processor.MarshalProcessor.doStart(MarshalProcessor.java:122)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1638)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:60)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.impl.engine.DefaultChannel.doStart(DefaultChannel.java:126)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:116)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
	at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:221)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)

```

**Comment by ffang** [comment]
This is because in camel-jackson component, it uses reflection way to create the Module class, we need a BuildStep to registerReflectiveClasses
