### ISSUE TITLE
Debezium: Unresolved type during parsing: org.eclipse.jetty.util.StringUtil 

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2695]
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1001:121 -v /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/debezium/target/camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-native-image-source-jar:/project:z quay.io/quarkus/ubi-quarkus-native-image:21.1-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]    classlist:  10,682.25 ms,  1.19 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]        (cap):     828.90 ms,  1.19 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]        setup:   3,374.31 ms,  1.19 GB
19:15:33,785 WARN  [io.qua.config] Unrecognized configuration key "quarkus.home" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
19:16:26,626 INFO  [org.jbo.threads] JBoss Threads version 3.4.0.Final
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]     (clinit):   1,605.98 ms,  2.64 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]   (typeflow):  54,895.35 ms,  2.64 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]    (objects):  84,074.84 ms,  2.64 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]   (features):   1,835.55 ms,  2.64 GB
[camel-quarkus-integration-test-debezium-2.0.0-SNAPSHOT-runner:25]     analysis: 145,414.79 ms,  2.64 GB
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.eclipse.jetty.util.StringUtil. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:534)
Call path from entry point to org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(String, Object): 
	at org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:529)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:499)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:114)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.connect.storage.ConverterConfig.<init>(ConverterConfig.java:48)
	at org.apache.kafka.connect.json.JsonConverterConfig.<init>(JsonConverterConfig.java:81)
	at com.oracle.svm.reflect.JsonConverterConfig_constructor_26a1d3813ebd65e89a2c3f30076706e6af911644_595.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:667)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.eclipse.jetty.util.StringUtil. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:534)
Call path from entry point to org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(String, Object): 
	at org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:529)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:499)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:114)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.connect.storage.ConverterConfig.<init>(ConverterConfig.java:48)
	at org.apache.kafka.connect.json.JsonConverterConfig.<init>(JsonConverterConfig.java:81)
	at com.oracle.svm.reflect.JsonConverterConfig_constructor_26a1d3813ebd65e89a2c3f30076706e6af911644_595.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:667)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:798)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.eclipse.jetty.util.StringUtil. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:534)
Call path from entry point to org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(String, Object): 
	at org.apache.kafka.connect.runtime.WorkerConfig$ResponseHttpHeadersValidator.ensureValid(WorkerConfig.java:529)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:499)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:114)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at org.apache.kafka.connect.storage.ConverterConfig.<init>(ConverterConfig.java:48)
	at org.apache.kafka.connect.json.JsonConverterConfig.<init>(JsonConverterConfig.java:81)
	at com.oracle.svm.reflect.JsonConverterConfig_constructor_26a1d3813ebd65e89a2c3f30076706e6af911644_595.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:667)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:795)
	... 8 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.eclipse.jetty.util.StringUtil. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:286)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:242)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:268)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:231)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1676)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1651)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5448)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:113)
	at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:647)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	... 5 more
Error: Image build request failed with exit status 1
```

**Comment by ppalaga** [comment]
Soved via 2ec4138ccdfafae3c5761cec234596753259c7ea
