### ISSUE TITLE
camel-quarkus-minio: "quarkus.minio.url" is mandatory and must be a valid url

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#2721]
Create from https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Minio.20Source.20Kamlet.20to.20Knative.20Sequence

Running the following kamelet binding using camel-k:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: minio-to-tester-binding
  namespace: hello-eventing
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: minio-source
    properties:
      accessKey: "dev-access-key"
      bucketName: "trigger"
      endpoint: "http://minio.minio.svc.cluster.local:9000"
      secretKey: "dev-secret-key"
  sink:
    uri:  http://tester-sequence-kn-sequence-0-kn-channel.hello-eventing.svc.cluster.local
```

Leads to:

```
io.quarkiverse.minio.client.MinioProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.arc$delegate(MinioProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.zig:67)
    at io.quarkiverse.minio.client.MinioProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.bucketExists(MinioProducer_ProducerMethod_produceMinioClient_a74f1d65447af9f0051b3615caa3aca9cac0ca25_ClientProxy.zig:3843)
    at org.apache.camel.component.minio.MinioEndpoint.bucketExists(MinioEndpoint.java:175)
    at org.apache.camel.component.minio.MinioEndpoint.doStart(MinioEndpoint.java:95)
    at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
    at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
    at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:186)
    at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:121)
    ... 28 more
"quarkus.minio.url" is mandatory and must be a valid url
```

**Comment by jamesnetherton** [comment]
Wondering whether this maybe be the same issue we have with Infinispan?

When autowiring is enabled, Camel will try to resolve a bean from the registry of type `MinoClient`. The registry lookup delegates to Arc and it triggers the CDI producer to run. Hence the validation check on the URL config is performed.

If you disable autowiring in the kamelet config, it may work properly.

Perhaps the `produceMinioClient` method should return null if all of the config options are empty.
