### ISSUE TITLE
camel-quarkus-example : dev mode issue

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#2723]
I have an issue on my local machine running examples with dev mode.
Branch : camel-quarkus-main, with camel-quarkus 2.x

**Reproducing the error:**

1. Get the  [file-bindy-ftp example](https://github.com/apache/camel-quarkus-examples/tree/camel-quarkus-main/file-bindy-ftp)
2. Run the docker line to setup prerequisites : 
`docker run -ti --rm -p 2222:2222 \
    -e PASSWORD_ACCESS=true \
    -e USER_NAME=ftpuser \
    -e USER_PASSWORD=ftppassword \
    -e DOCKER_MODS=linuxserver/mods:openssh-server-openssh-client \
    linuxserver/openssh-server`
3. Start the dev mode `mvn clean compile quarkus:dev`

**The error is :** 
`
[INFO] --- quarkus-maven-plugin:2.0.0.Alpha3:dev (default-cli) @ camel-quarkus-examples-file-bindy-ftp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/zbendhib/dev/camel-quarkus-examples/file-bindy-ftp/src/test/resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/zbendhib/dev/camel-quarkus-examples/file-bindy-ftp/target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 8
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.InvalidClassException: io.quarkus.deployment.dev.DevModeContext$ModuleInfo; local class incompatible: stream classdesc serialVersionUID = 7401504187889312018, local class serialVersionUID = -6977380306703936042
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:151)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.InvalidClassException: io.quarkus.deployment.dev.DevModeContext$ModuleInfo; local class incompatible: stream classdesc serialVersionUID = 7401504187889312018, local class serialVersionUID = -6977380306703936042
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:135)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:89)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        ... 1 more
Caused by: java.lang.RuntimeException: java.io.InvalidClassException: io.quarkus.deployment.dev.DevModeContext$ModuleInfo; local class incompatible: stream classdesc serialVersionUID = 7401504187889312018, local class serialVersionUID = -6977380306703936042
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:436)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:58)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        ... 3 more
Caused by: java.io.InvalidClassException: io.quarkus.deployment.dev.DevModeContext$ModuleInfo; local class incompatible: stream classdesc serialVersionUID = 7401504187889312018, local class serialVersionUID = -6977380306703936042
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2012)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:362)
        ... 5 more
`

**Comment by jamesnetherton** [comment]
This works ok for me on `camel-quarkus-main` with Quarkus 2 CR2 / CR3.

**Comment by zbendhiba** [comment]
@jamesnetherton  thanks !!
works fine too for me.
