### ISSUE TITLE
kubernetes integration-test failure in native mode

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2730]
I consistently got exception like
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /Users/ffang/kit/graalvm-ce-java11-21.0.0.2/Contents/Home/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=CA -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]    classlist:   3,235.52 ms,  1.20 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]        (cap):   2,966.28 ms,  1.20 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]        setup:   4,378.83 ms,  1.20 GB
11:55:51,060 INFO  [org.jbo.threads] JBoss Threads version 3.4.0.Final
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]     (clinit):   1,987.92 ms,  6.62 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]   (typeflow):  44,178.20 ms,  6.62 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]    (objects):  70,313.83 ms,  6.62 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]   (features):   2,864.71 ms,  6.62 GB
[camel-quarkus-integration-test-kubernetes-2.0.0-SNAPSHOT-runner:70225]     analysis: 130,243.23 ms,  6.62 GB
Error: Unsupported features in 5 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.watch(java.lang.String, io.fabric8.kubernetes.client.Watcher). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:96)
Call path from entry point to org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(): 
	at org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:89)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.Job. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:123)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:112)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:71)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:63)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:105)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:95)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:67)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobSpec. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:133)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:130)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:75)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 5 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.watch(java.lang.String, io.fabric8.kubernetes.client.Watcher). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:96)
Call path from entry point to org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(): 
	at org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:89)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.Job. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:123)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:112)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:71)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:63)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:105)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:95)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:67)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobSpec. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:133)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:130)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:75)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:773)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 5 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.watch(java.lang.String, io.fabric8.kubernetes.client.Watcher). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:96)
Call path from entry point to org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(): 
	at org.apache.camel.component.kubernetes.customresources.KubernetesCustomResourcesConsumer$CustomResourcesConsumerTask.run(KubernetesCustomResourcesConsumer.java:89)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.Job. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:123)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doGetJob(KubernetesJobProducer.java:112)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:71)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doList(KubernetesJobProducer.java:88)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:63)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobList. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:105)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doListJobByLabel(KubernetesJobProducer.java:95)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:67)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.fabric8.kubernetes.api.model.batch.JobSpec. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:133)
Call path from entry point to org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(Exchange, String): 
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.doCreateJob(KubernetesJobProducer.java:130)
	at org.apache.camel.component.kubernetes.job.KubernetesJobProducer.process(KubernetesJobProducer.java:75)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.WireTapProcessor$WireTapTask.run(WireTapProcessor.java:126)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:770)
```

**Comment by ffang** [comment]
From the stacktrace here, I'm not sure if this is caused by my specific env(OS and JDK version)

**Comment by aldettinger** [comment]
@ffang I reproduce on Linux too. This issue must have been unnoticed as native tests are disabled on CI according to #1101.
But despite memory consumption, I think a fix is welcome here.

**Comment by ffang** [comment]
Thanks for the info @aldettinger !

**Comment by ffang** [comment]
This is caused by kubernetes-client version mismatch.
camel 3.10.0 requires kubernetes-client 5.3.1, while quarkus 2.0.0.CR2 provides kubernetes-client 5.4.0

**Comment by ffang** [comment]
camel-kubernetes already upgraded to kubernetes-client/model 5.4.1 for the coming CAMEL 3.11 release. So once  CAMEL 3.11 is out we can align it

**Comment by ffang** [comment]
Verified this issue is gone with CAMEL 3.11 upgrade, so we can close this one now
