### ISSUE TITLE
Unable to determine the status of the running process in LogIT without resteasy

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2737]
Not sure if this is my env specific, but this test fails consistently on my machine
```
2021-06-07 10:51:42,148 DEBUG [org.apa.cam.qua.cor.dep.CamelProcessor] (build-7) Camel XML capability not detected, disable XML reifiers
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /Users/ffang/projects/camel-quarkus-new/integration-test-groups/foundation/log/target/camel-quarkus-integration-test-log-2.0.0-SNAPSHOT-runner
======================================================================================
Executing [/Users/ffang/projects/camel-quarkus-new/integration-test-groups/foundation/log/target/camel-quarkus-integration-test-log-2.0.0-SNAPSHOT-runner, -Dquarkus.http.port=55497, -Dquarkus.http.ssl-port=55498, -Dtest.url=http://localhost:55497, -Dquarkus.log.file.path=/Users/ffang/projects/camel-quarkus-new/integration-test-groups/foundation/log/target/quarkus.log, -Dquarkus.log.file.enable=true]
2021-06-07 10:51:43,883 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.ssl-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-06-07 10:51:43,886 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-06-07 10:51:43,889 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-06-07 10:51:43,892 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:0 started:0)
2021-06-07 10:51:43,892 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.10.0 (camel-1) started in 0ms (build:0ms init:0ms start:0ms)
2021-06-07 10:51:43,893 INFO  [foo-topic] (main) Exchange[ExchangePattern: InOnly, BodyType: String, Body: Hello foo!]
2021-06-07 10:51:43,894 INFO  [io.quarkus] (main) camel-quarkus-integration-test-log 2.0.0-SNAPSHOT native (powered by Quarkus 2.0.0.CR2) started in 0.021s. 
2021-06-07 10:51:43,894 INFO  [io.quarkus] (main) Profile prod activated. 
2021-06-07 10:51:43,894 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-log, camel-support-common, cdi]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.096 s <<< FAILURE! - in org.apache.camel.quarkus.component.log.it.LogIT
[ERROR] info  Time elapsed: 0.022 s  <<< ERROR!
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:74)
	at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:116)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:130)
	at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:150)
	at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)
	at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

**Comment by ppalaga** [comment]
I can reproduce too. Quarkus tries to match the log against `Listening on:\\s+(https?)://\\S*:(\\d+)` pattern. This would work if we added resteasy or similar. But I actually wanted to have a test without those (for better isolation). So maybe we could just fake the message ourselves? After all we are testing our log component :)

**Comment by danielspeixoto** [comment]
I am having the same problem. This issue is marked as closed but I still couldn't manage to overcome this.

resteasy is already configured in my project
