### ISSUE TITLE
Unable to determine the status of the running process in TimerIT without resteasy

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#2772]
Get the error like
======================================================================================
Executing [/Users/ffang/projects/ffang-forks/camel-quarkus/integration-test-groups/foundation/timer/target/camel-quarkus-integration-test-timer-2.0.0-SNAPSHOT-runner, -Dquarkus.http.port=50645, -Dquarkus.http.ssl-port=50646, -Dtest.url=http://localhost:50645, -Dquarkus.log.file.path=/Users/ffang/projects/ffang-forks/camel-quarkus/integration-test-groups/foundation/timer/target/quarkus.log, -Dquarkus.log.file.enable=true]
2021-06-11 09:52:20,292 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.ssl-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-06-11 09:52:20,293 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.http.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2021-06-11 09:52:20,295 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-06-11 09:52:20,298 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:2 started:2)
2021-06-11 09:52:20,298 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started timer (timer://keep-alive)
2021-06-11 09:52:20,298 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started bar (timer://bar)
2021-06-11 09:52:20,298 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.10.0 (camel-1) started in 1ms (build:0ms init:1ms start:0ms)
2021-06-11 09:52:20,298 INFO  [io.quarkus] (main) camel-quarkus-integration-test-timer 2.0.0-SNAPSHOT native (powered by Quarkus 2.0.0.CR3) started in 0.013s. 
2021-06-11 09:52:20,298 INFO  [io.quarkus] (main) Profile prod activated. 
2021-06-11 09:52:20,298 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-support-common, camel-timer, cdi]
2021-06-11 09:52:21,302 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:21,302 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:22,304 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:22,304 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:23,307 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:23,307 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:24,310 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:24,310 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:25,315 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:25,315 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:26,319 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:26,319 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:27,320 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:27,320 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:28,320 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:28,320 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
2021-06-11 09:52:29,323 INFO  [org.apa.cam.qua.com.tim.it.TimerProducers] (Camel (camel-1) thread #1 - timer://bar) Hello from timer:bar
2021-06-11 09:52:29,323 INFO  [org.apa.cam.qua.com.tim.it.TimerRoutes] (Camel (camel-1) thread #0 - timer://keep-alive) keep-alive: I'm alive !
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.851 s <<< FAILURE! - in org.apache.camel.quarkus.component.timer.it.TimerIT
[ERROR] timer  Time elapsed: 0.022 s  <<< ERROR!
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:74)
	at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:118)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:132)
	at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:150)
	at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)
	at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by ffang** [comment]
We have the similar issue here
https://github.com/apache/camel-quarkus/issues/2737
I will do the same fix
