### ISSUE TITLE
camel-quarkus-http doesn't build native image - Random/SplittableRandom

### ISSUE THREAD

**Issue by juangon** [apache/camel-quarkus#2793]
When using Quarkus (v 1.13.7, didn't check others) and using http routes (camel-quarkus-http) trying to build native, it throws this error:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.security.SecureRandom. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
	at parsing org.apache.http.impl.auth.NTLMEngineImpl.access$000(NTLMEngineImpl.java:51)
Call path from entry point to org.apache.http.impl.auth.NTLMEngineImpl.access$000(): 
	at org.apache.http.impl.auth.NTLMEngineImpl.access$000(NTLMEngineImpl.java:51)
	at org.apache.http.impl.auth.NTLMEngineImpl$Type3Message.<init>(NTLMEngineImpl.java:1505)
	at org.apache.http.impl.auth.NTLMEngineImpl$Type3Message.<init>(NTLMEngineImpl.java:1474)
	at org.apache.http.impl.auth.NTLMEngineImpl.getType3Message(NTLMEngineImpl.java:181)
	at org.apache.http.impl.auth.NTLMEngineImpl.generateType3Msg(NTLMEngineImpl.java:2097)
	at org.apache.http.impl.auth.NTLMScheme.authenticate(NTLMScheme.java:142)
	at org.apache.http.impl.auth.AuthSchemeBase.authenticate(AuthSchemeBase.java:136)
	at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:233)
	at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:213)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:262)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.camel.component.http.HttpProducer.executeMethod(HttpProducer.java:442)
	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:270)
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:108)
	at org.apache.camel.processor.DelayProcessorSupport$ProcessCall.run(DelayProcessorSupport.java:71)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

```

**Comment by jamesnetherton** [comment]
Please can you provide some more information about how your `http` endpoint is configured.

**Comment by juangon** [comment]
Sure @jamesnetherton , there are multiple "to" like this:

```java
.toF("https://%s%s?throwExceptionOnFailure=false&cookieHandler=#instanceCookieHandler&..", a,b)
```
I have 3 "direct" routes, with some minor exception handling retries like this:

```java
onException(RejectedExecutionException.class)
        .maximumRedeliveries(3).redeliveryDelay(500);
```
I use choice() , unmarshal, etc too.

**Comment by juangon** [comment]
BTw I use a toD too as I need to get some dynamic values from header:

```java
.toD("https://" + url + "ACK?throwExceptionOnFailure=false&cookieHandler=#instanceCookieHandler&ClientKey=${exchangeProperty[key]}'")            
```

**Comment by jamesnetherton** [comment]
It was the `AuthSchemeBase` & `NTLMScheme` parts of the stacktrace that interested me. Do you have any authentication options configured?

**Comment by juangon** [comment]
The only auth thing I did was manually set Authorization header like this:

```java
.setHeader("Authorization", constant("Basic " + basicAuth))
```
