### ISSUE TITLE
Box native integration test failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2830]
Not sure why, but the native application is taking 10 seconds or more to fully start:

```
Apache Camel 3.10.0 (camel-1) started in 10s509ms (build:0ms init:1ms start:10s508ms)
```

Hence we get: 

```
ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.161 s <<< FAILURE! - in org.apache.camel.quarkus.component.box.it.BoxIT
[ERROR] testUploadDownloadDeleteFile  Time elapsed: 0.011 s  <<< ERROR!
java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:74)
	at io.quarkus.test.common.NativeImageLauncher.start(NativeImageLauncher.java:118)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:132)
	at io.quarkus.test.junit.NativeTestExtension.doNativeStart(NativeTestExtension.java:150)
	at io.quarkus.test.junit.NativeTestExtension.ensureStarted(NativeTestExtension.java:92)
	at io.quarkus.test.junit.NativeTestExtension.beforeAll(NativeTestExtension.java:65)
```

**Comment by jamesnetherton** [comment]
The reason for the slowness is that there seems to be 4 box authentication events that occur before the `CamelContext` is considered started. In the logs I see:

```
2021-06-23 13:52:33,180 DEBUG [org.apa.cam.imp.eng.InternalRouteStartupManager] (main) Warming up route id: route1 having autoStartup=true
2021-06-23 13:52:33,655 FINE  [com.box.sdk.BoxAPIRequest] (main) Request
POST https://api.box.com/oauth2/token
Accept-Charset: utf-8
X-Box-UA: agent=box-java-sdk/2.54.0; env=Java/11.0.11
User-Agent: Box Java SDK v2.54.0 (Java 11.0.11)
Accept-Encoding: gzip
```

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-16764.
