### ISSUE TITLE
Intermittent failures in OpenstackGlanceTest

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2862]
Seen in https://github.com/apache/camel-quarkus/pull/2859/checks?check_run_id=2952026388
```
2021-06-30T12:49:13.0983693Z [INFO] Running org.apache.camel.quarkus.component.openstack.it.OpenstackGlanceTest
2021-06-30T12:49:22.5423816Z 2021-06-30 12:49:20,776 INFO  [org.apa.cam.qua.tes.wir.WireMockTestResourceLifecycleManager] (pool-4-thread-1) Starting WireMockServer
2021-06-30T12:49:22.5440799Z 2021-06-30 12:49:20,844 INFO  [org.apa.cam.qua.tes.moc.bac.MockBackendUtils] (pool-4-thread-1) Mock backend will be used
2021-06-30T12:49:22.5443263Z 2021-06-30 12:49:21,690 INFO  [org.ecl.jet.uti.log] (pool-4-thread-1) Logging initialized @9594ms to org.eclipse.jetty.util.log.Slf4jLog
2021-06-30T12:49:22.5481027Z 2021-06-30 12:49:21,764 WARN  [org.ecl.jet.ser.AbstractConnector] (pool-4-thread-1) Acceptors should be <= availableProcessors: NetworkTrafficServerConnector@63b3fc9c{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
2021-06-30T12:49:22.5483609Z 2021-06-30 12:49:21,837 INFO  [org.ecl.jet.ser.Server] (pool-4-thread-1) jetty-9.4.42.v20210604; built: 2021-06-04T17:33:38.939Z; git: 5cd5e6d2375eeab146813b0de9f19eda6ab6e6cb; jvm 11.0.11+9
2021-06-30T12:49:22.5490383Z 2021-06-30 12:49:21,851 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-4-thread-1) Started o.e.j.s.ServletContextHandler@4adbf71d{/__admin,null,AVAILABLE}
2021-06-30T12:49:22.5492681Z 2021-06-30 12:49:21,853 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-4-thread-1) Started o.e.j.s.ServletContextHandler@3917e635{/,null,AVAILABLE}
2021-06-30T12:49:22.5498888Z 2021-06-30 12:49:21,872 INFO  [org.ecl.jet.ser.AbstractConnector] (pool-4-thread-1) Started NetworkTrafficServerConnector@63b3fc9c{HTTP/1.1, (http/1.1)}{0.0.0.0:34241}
2021-06-30T12:49:22.5502170Z 2021-06-30 12:49:21,872 INFO  [org.ecl.jet.ser.Server] (pool-4-thread-1) Started @9777ms
2021-06-30T12:49:22.5504130Z 2021-06-30 12:49:21,872 INFO  [org.apa.cam.qua.tes.wir.WireMockTestResourceLifecycleManager] (pool-4-thread-1) WireMock started on http://localhost:34241
2021-06-30T12:49:22.7054938Z 2021-06-30 12:49:22,704 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-06-30T12:49:22.7649161Z 2021-06-30 12:49:22,764 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:0 started:0)
2021-06-30T12:49:22.7656792Z 2021-06-30 12:49:22,765 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.11.0 (camel-1) started in 21ms (build:0ms init:17ms start:4ms)
2021-06-30T12:49:22.8750499Z 2021-06-30 12:49:22,871 INFO  [io.quarkus] (main) Quarkus 2.0.0.Final on JVM started in 4.888s. Listening on: http://localhost:44795
2021-06-30T12:49:22.8752221Z 2021-06-30 12:49:22,872 INFO  [io.quarkus] (main) Profile test activated. 
2021-06-30T12:49:22.8753897Z 2021-06-30 12:49:22,873 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-openstack, camel-support-common, cdi, resteasy, smallrye-context-propagation]
2021-06-30T12:49:24.1825953Z 2021-06-30 12:49:24,181 INFO  [org.ecl.jet.ser.han.Con.ROOT] (qtp1009344578-88) RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2021-06-30T12:49:24.7096709Z [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.606 s - in org.apache.camel.quarkus.component.openstack.it.OpenstackGlanceTest
2021-06-30T12:49:24.7108204Z [INFO] Running org.apache.camel.quarkus.component.openstack.it.OpenstackCinderSnapshotTest
2021-06-30T12:49:24.7619280Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 s - in org.apache.camel.quarkus.component.openstack.it.OpenstackCinderSnapshotTest
2021-06-30T12:49:24.7629096Z [INFO] Running org.apache.camel.quarkus.component.openstack.it.OpenstackKeystoneRegionTest
2021-06-30T12:49:24.9202914Z 2021-06-30 12:49:24,913 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /openstack/keystone/regions/getShouldSucceed failed, error id: de61a019-9a50-4bba-b1ba-900a1c950b33-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2021-06-30T12:49:24.9207000Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
2021-06-30T12:49:24.9209589Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
2021-06-30T12:49:24.9212051Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
2021-06-30T12:49:24.9214488Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
2021-06-30T12:49:24.9216957Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2021-06-30T12:49:24.9219257Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2021-06-30T12:49:24.9222491Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2021-06-30T12:49:24.9226550Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2021-06-30T12:49:24.9243596Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2021-06-30T12:49:24.9256675Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
2021-06-30T12:49:24.9259407Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
2021-06-30T12:49:24.9261920Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
2021-06-30T12:49:24.9263960Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:481)
2021-06-30T12:49:24.9265641Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
2021-06-30T12:49:24.9267244Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1450)
2021-06-30T12:49:24.9268799Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2021-06-30T12:49:24.9270790Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2021-06-30T12:49:24.9272903Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2021-06-30T12:49:24.9274280Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-30T12:49:24.9275546Z Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2021-06-30T12:49:24.9277854Z 	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
2021-06-30T12:49:24.9280572Z 	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:677)
2021-06-30T12:49:24.9283157Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
2021-06-30T12:49:24.9286196Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587)
2021-06-30T12:49:24.9289357Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBodyAndHeader(DefaultProducerTemplate.java:431)
2021-06-30T12:49:24.9293565Z 	at org.apache.camel.quarkus.component.openstack.it.OpenstackKeystoneRegionResource.getShouldSucceed(OpenstackKeystoneRegionResource.java:75)
2021-06-30T12:49:24.9298258Z 	at org.apache.camel.quarkus.component.openstack.it.OpenstackKeystoneRegionResource_ClientProxy.getShouldSucceed(OpenstackKeystoneRegionResource_ClientProxy.zig:261)
2021-06-30T12:49:24.9301348Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-30T12:49:24.9303404Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-30T12:49:24.9305774Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-30T12:49:24.9307538Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-30T12:49:24.9308921Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2021-06-30T12:49:24.9310737Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2021-06-30T12:49:24.9313100Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
2021-06-30T12:49:24.9316118Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
2021-06-30T12:49:24.9318774Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
2021-06-30T12:49:24.9337175Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2021-06-30T12:49:24.9340433Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
2021-06-30T12:49:24.9342681Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
2021-06-30T12:49:24.9344723Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
2021-06-30T12:49:24.9346765Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
2021-06-30T12:49:24.9348764Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2021-06-30T12:49:24.9349932Z 	... 15 more
2021-06-30T12:49:24.9351049Z Caused by: org.openstack4j.api.exceptions.OS4JException: Unable to retrieve current session. Please verify thread has a current session available.
2021-06-30T12:49:24.9353300Z 	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:108)
2021-06-30T12:49:24.9355878Z 	at org.openstack4j.openstack.internal.BaseOpenStackService.builder(BaseOpenStackService.java:102)
2021-06-30T12:49:24.9358382Z 	at org.openstack4j.openstack.internal.BaseOpenStackService.get(BaseOpenStackService.java:56)
2021-06-30T12:49:24.9361072Z 	at org.openstack4j.openstack.identity.v3.internal.RegionServiceImpl.get(RegionServiceImpl.java:37)
2021-06-30T12:49:24.9364080Z 	at org.apache.camel.component.openstack.keystone.producer.RegionProducer.doGet(RegionProducer.java:73)
2021-06-30T12:49:24.9367320Z 	at org.apache.camel.component.openstack.keystone.producer.RegionProducer.process(RegionProducer.java:48)
2021-06-30T12:49:24.9370541Z 	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
2021-06-30T12:49:24.9373636Z 	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:217)
2021-06-30T12:49:24.9452169Z 	at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
2021-06-30T12:49:24.9455200Z 	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
2021-06-30T12:49:24.9458353Z 	at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
2021-06-30T12:49:24.9461181Z 	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:190)
2021-06-30T12:49:24.9463463Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
2021-06-30T12:49:24.9465806Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
2021-06-30T12:49:24.9468589Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBodyAndHeader(DefaultProducerTemplate.java:429)
2021-06-30T12:49:24.9470374Z 	... 32 more
```

**Comment by zbendhiba** [comment]
seems to be out-to-date
