### ISSUE TITLE
master failing 

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#288]
Master is now failing, probably because of recents additions additon to the camel-main: 

```
error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.apache.camel.model.ModelHelper.loadRestsDefinition(org.apache.camel.CamelContext, java.io.InputStream). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace: 
	at parsing org.apache.camel.main.DefaultRoutesCollector.collectXmlRestsFromDirectory(DefaultRoutesCollector.java:127)
Call path from entry point to org.apache.camel.main.DefaultRoutesCollector.collectXmlRestsFromDirectory(CamelContext, String): 
	at org.apache.camel.main.DefaultRoutesCollector.collectXmlRestsFromDirectory(DefaultRoutesCollector.java:119)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:98)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:549)
	at org.apache.camel.quarkus.core.CamelMain.doInit(CamelMain.java:42)
	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:62)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2317)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:71)
	at org.apache.camel.support.LazyStartProducer.process(LazyStartProducer.java:50)
	at org.apache.camel.processor.Resequencer.processExchange(Resequencer.java:302)
	at org.apache.camel.processor.Resequencer$BatchSender.sendExchanges(Resequencer.java:530)
	at org.apache.camel.processor.Resequencer$BatchSender.run(Resequencer.java:455)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0
```

@gnodet do you mind having a look ? if not I can have a look on monday

**Comment by lburgazzoli** [comment]
@gnodet found some time, working on a fix
