### ISSUE TITLE
Dev mode does not work on Java 12

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#289]
Just got a report over a private channel that this demo https://github.com/ppalaga/camel-quarkus-cnorris-demo does not work on some unspecified Java version that is greater than 8. Asked for details, but do not have a reply yet. 

Regardless of this specific issue, we should test regularly on Java 11.

```
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:139)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.<init>(JaxbAnnotationIntrospector.java:126)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule.setupModule(JaxbAnnotationModule.java:90)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:751)
	at org.apache.camel.component.jackson.converter.JacksonTypeConverters.<init>(JacksonTypeConverters.java:57)
	at org.apache.camel.component.jackson.converter.JacksonTypeConvertersLoader.getJacksonTypeConverters(JacksonTypeConvertersLoader.java:38)
	at org.apache.camel.component.jackson.converter.JacksonTypeConvertersLoader.lambda$registerFallbackConverters$0(JacksonTypeConvertersLoader.java:28)
	at org.apache.camel.support.SimpleTypeConverter.convertTo(SimpleTypeConverter.java:99)
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:301)
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.doConvertTo(BaseTypeConverterRegistry.java:158)
	at org.apache.camel.impl.converter.BaseTypeConverterRegistry.convertTo(BaseTypeConverterRegistry.java:125)
	at org.apache.camel.support.DefaultMessage.getHeader(DefaultMessage.java:94)
	at org.apache.camel.component.netty.http.NettyHttpHelper.createMethod(NettyHttpHelper.java:106)
	at org.apache.camel.component.netty.http.DefaultNettyHttpBinding.toNettyRequest(DefaultNettyHttpBinding.java:643)
	at org.apache.camel.component.netty.http.NettyHttpProducer.getRequestBody(NettyHttpProducer.java:68)
	at org.apache.camel.component.netty.NettyProducer.process(NettyProducer.java:201)
	at org.apache.camel.component.netty.http.NettyHttpProducer.process(NettyHttpProducer.java:57)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:134)
	... 28 more
```

**Comment by lburgazzoli** [comment]
note that graalvm does not support java 11 yet

**Comment by ppalaga** [comment]
Yes, I know. The reported failures were in the JVM mode and perhaps even in the dev mode.

**Comment by ppalaga** [comment]
The above stack trace happened with OpenJDK 12. I'll try to reproduce with 11.

**Comment by ppalaga** [comment]
> note that graalvm does not support java 11 yet

To put it more clearly: as long as GraalVM is on Java 8, we should run at least the JVM mode tests on Java 11 on the CI.

**Comment by lburgazzoli** [comment]
We have not a GitHub Action that builds the project in JVM mode against Java 11

**Comment by ppalaga** [comment]
Because the CI is apparently passing on Java 11, let's narrow the scope of this issue to the originally reported problem.

**Comment by ppalaga** [comment]
There is a related issue for dev mode with Java 13 on Windows https://github.com/quarkusio/quarkus/issues/5359

**Comment by lburgazzoli** [comment]
We now build on Java 12 too and we have a test for dev mode so I think we can close this issue
