### ISSUE TITLE
[Quarkus 2.2.0] JavaScriptDslTest fails with CNFE `org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractValueImpl` 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2968]
Possibly because Camel 3.11.x is aligned with `org.graalvm.js:js` 21.0.0.2 where as latest Quarkus main is aligned with 21.2.0.

I'm disabling the tests for now.

```
Caused by: java.util.ServiceConfigurationError: org.graalvm.polyglot.impl.AbstractPolyglotImpl: com.oracle.truffle.polyglot.PolyglotImpl Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:673)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:808)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:794)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:768)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:768)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:109)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:133)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:320)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:559)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1725)
	at org.apache.camel.dsl.js.JavaScriptRoutesBuilderLoader.doLoadEndpointRouteBuilder(JavaScriptRoutesBuilderLoader.java:44)
	at org.apache.camel.builder.endpoint.EndpointRouteBuilder$2.configure(EndpointRouteBuilder.java:78)
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:541)
	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:487)
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:462)
	at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1150)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:211)
	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:550)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:744)
	... 48 more
Caused by: java.lang.NoClassDefFoundError: org/graalvm/polyglot/impl/AbstractPolyglotImpl$AbstractValueImpl
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:660)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:657)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:668)
	... 80 more
Caused by: java.lang.ClassNotFoundException: org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractValueImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 88 more
```

**Comment by jamesnetherton** [comment]
All it needed to fix was `mvn cq:sync-versions`.

**Comment by ppalaga** [comment]
> All it needed to fix was `mvn cq:sync-versions`.

We should perhaps add `mvn cq:sync-versions` before checking for changes around here https://github.com/apache/camel-quarkus/blob/main/.github/workflows/ci-build.yaml#L92 `mvn cq:sync-versions` is cheap
