### ISSUE TITLE
Cannot register java.lang. classes via quarkus.camel.native.reflection.include-patterns

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#2969]
https://github.com/apache/camel-k/pull/2536#issuecomment-889857056

The problem is that JRE classes are not available in Jandex.

**Comment by ppalaga** [comment]
This hint from @mkouba might be useful:

> if you need to index JDK classes you can try to use CombinedIndexBuildItem.getComputingIndex() or BeanArchiveIndexBuildItem.getIndex() which is computing by default
> computing means that if not found the class is additionaly indexed and cached,
> so that the next time you request the class a cache entry can be used
> oh and I forgot to mention that not all operations perform the additional computation ofc
> e.g. getClassByName() does but getKnownClasses() does not... for obvious reasons ;-)

**Comment by llowinge** [comment]
@ppalaga I have a feeling this issue was already resolved by your commit https://github.com/apache/camel-quarkus/commit/10c8517be05ae2d006633f7c78620debfb2708bf.

Reading the original issue in camel-k project, i've tried following:

```
        from("timer:foo?period=1000")
                .bean(new Double(10), "intValue");
```

which fails in native with:
```
Caused by: org.apache.camel.component.bean.MethodNotFoundException: Method with name: intValue not found on bean: 10.0 of type: java.lang.Double
        at org.apache.camel.component.bean.DefaultBeanProcessorFactory.createBeanProcessor(DefaultBeanProcessorFactory.java:191)
        at org.apache.camel.reifier.BeanReifier.createProcessor(BeanReifier.java:50)
        at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:843)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:616)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:238)
```
And by adding `quarkus.camel.native.reflection.include-patterns=java.lang.Double`, it started working.
I've also checked that the `java.lang.Double` was added to `selectedClassNames` of https://github.com/apache/camel-quarkus/blob/210bdde876acc91136fe7156190ce2fbffe095a5/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelNativeImageProcessor.java#L263.

**Comment by ppalaga** [comment]
Great, thanks for having a look @llowinge! Should we close this issue?

**Comment by llowinge** [comment]
@ppalaga Based on the title and description it works. But i have a feeling this issue was more about finding better way of handling registration of JRE classes and validating their presence in Jandex (based on your comment https://github.com/apache/camel-quarkus/blob/3.30.0/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/util/PathFilter.java#L104). IMO closing this issue and creating new one based on your input would be the best way to go. But i'll leave decision up to you, as i'm bit confused from this issue. Maybe at the time of creation this issue it was not fixed even with the workaround, i'm not sure.

**Comment by ppalaga** [comment]
It was too long ago, to recollect the details. @llowinge if you think improving the UX of registering the JRE classes is worth the effort, feel free to file a new issue.
