### ISSUE TITLE
[Quarkus 2.2.0] `quarkus-google-cloud-services` dependent extensions native image build fails 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#2979]
Seems `google-cloud-graalvm-support` 0.4.0 is not compatible with GraalVM 21.2.0. The following is observed for Google extensions: 

* `bigquery` 
* `pubsub`
* `storage`

```
Fatal error:java.lang.NoSuchMethodError: 'void org.graalvm.nativeimage.impl.RuntimeReflectionSupport.register(boolean, boolean, java.lang.reflect.Field[])'
	at com.google.cloud.graalvm.features.NativeImageUtils.registerForUnsafeFieldAccess(NativeImageUtils.java:119)
	at com.google.cloud.graalvm.features.core.GrpcNettyFeature.loadMiscClasses(GrpcNettyFeature.java:125)
	at com.google.cloud.graalvm.features.core.GrpcNettyFeature.beforeAnalysis(GrpcNettyFeature.java:43)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:691)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
```

**Comment by jamesnetherton** [comment]
I opened https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/180.

**Comment by jamesnetherton** [comment]
I'll do a workaround to override `google-cloud-graalvm-support` until we get a new `quarkus-google-cloud-services` release.
