### ISSUE TITLE
XchangeTest failure due to deprecated binance WAPI endpoints

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3016]
Observed in https://github.com/apache/camel-quarkus/pull/3015. As the error message states, binance WAPI endpoints are deprecated and were apparently [delisted](https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269) from the binance API at the beginning of August.

What's weird is that sometimes the tests pass fine and the WAPI endpoints are resolvable and sometimes a 503 response is returned.

The only option I can see to fix in 2.2.0 is to override the xchange libs to a version >= 5.0.9 where the deprecated APIs have been dealt with.

```
2021-08-18T14:02:10.5976013Z 2021-08-18 14:02:10,596 INFO  [org.kno.xch.bin.BinanceExchange] (executor-thread-0) Calling Remote Init...
2021-08-18T14:02:12.5425064Z 2021-08-18 14:02:12,534 WARN  [si.maz.res.ResponseReader] (executor-thread-0) Noncritical error parsing error output: This endpoint has been deprecated, please integrate with “GET@/sapi/v1/asset/assetDetail”. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946be...: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'This': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
2021-08-18T14:02:12.5461742Z  at [Source: (String)"This endpoint has been deprecated, please integrate with “GET@/sapi/v1/asset/assetDetail���. See details in the announcement: https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269"; line: 1, column: 5]
2021-08-18T14:02:12.5464042Z 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
2021-08-18T14:02:12.5472789Z 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:720)
2021-08-18T14:02:12.5478716Z 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2903)
2021-08-18T14:02:12.5486541Z 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1949)
2021-08-18T14:02:12.5497256Z 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:781)
2021-08-18T14:02:12.5500956Z 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
2021-08-18T14:02:12.5526631Z 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
2021-08-18T14:02:12.5539803Z 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
2021-08-18T14:02:12.5547145Z 	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.read(JacksonResponseReader.java:53)
2021-08-18T14:02:12.5553473Z 	at si.mazi.rescu.serialization.jackson.JacksonResponseReader.readException(JacksonResponseReader.java:58)
2021-08-18T14:02:12.5562431Z 	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:82)
2021-08-18T14:02:12.5593713Z 	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
2021-08-18T14:02:12.5601416Z 	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
2021-08-18T14:02:12.5607825Z 	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:113)
2021-08-18T14:02:12.5609806Z 	at com.sun.proxy.$Proxy297.assetDetail(Unknown Source)
```

**Comment by jamesnetherton** [comment]
I think the xchange Coinbase 'ticker' test is also broken, but it's been masked by a flaw in the test implementation:

```
2021-08-18 16:56:26,583 DEBUG [org.apa.cam.sup.cac.DefaultProducerCache] (executor-thread-0) >>>> xchange-coinbase://coinbase?currencyPair=BTC%2FUSDT&method=ticker&service=marketdata Exchange[]
2021-08-18 16:56:26,584 DEBUG [si.maz.res.HttpTemplate] (executor-thread-0) Executing GET request at https://coinbase.com/api/v1/prices/buy?qty=1&currency=USDT
2021-08-18 16:56:27,134 DEBUG [si.maz.res.HttpTemplate] (executor-thread-0) Request http status = 404
2021-08-18 16:56:27,135 DEBUG [si.maz.res.HttpTemplate] (executor-thread-0) Http call returned 404; response body:
{"errors":[{"id":"not_found","message":"Not found"}]}
```
