### ISSUE TITLE
Exception when configuring camel-kafka with environment variables in native mode

### ISSUE THREAD

**Issue by knupfera** [apache/camel-quarkus#3017]
### Versions

Quarkus: 2.1.2.Final
Camel: 3.11.0
Camel-Quarkus: 2.1.0

### Error: 

2021-08-19 09:40:16,409 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-08-19 09:40:16,410 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: java.lang.IllegalArgumentException: Cannot find getter method: consumers on bean: class org.apache.camel.component.kafka.KafkaComponent when binding property: consumers.count
	at org.apache.camel.support.PropertyBindingSupport.doBuildPropertyOgnlPath(PropertyBindingSupport.java:282)
	at org.apache.camel.support.PropertyBindingSupport.doBindProperties(PropertyBindingSupport.java:210)
	at org.apache.camel.support.PropertyBindingSupport.access$100(PropertyBindingSupport.java:88)
	at org.apache.camel.support.PropertyBindingSupport$Builder.bind(PropertyBindingSupport.java:1792)
	at org.apache.camel.main.MainHelper.setPropertiesOnTarget(MainHelper.java:297)
	at org.apache.camel.main.BaseMainSupport.autoConfigurationFromProperties(BaseMainSupport.java:1273)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:405)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:538)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:755)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

### Steps to reproduce

1. Clone https://github.com/knupfera/camel-quarkus-kafka-issue
2. Run ./gradlew quarkusBuild
3. Run docker run --rm -e CAMEL_COMPONENT_KAFKA_CONSUMERS_COUNT=10  akn/demo:0.1.0

**Comment by jamesnetherton** [comment]
Try with `CAMEL_COMPONENT_KAFKA_CONSUMERSCOUNT=10`.

**Comment by knupfera** [comment]
Works. Thank you
