### ISSUE TITLE
Salesforce test failure

### ISSUE THREAD

**Issue by mmuzikar** [apache/camel-quarkus#3022]
*org.apache.camel.quarkus.component.salesforce.SalesforceTest.testGetAccountByQueryHelper* failed using real salesforce service with following stacktrace:
```
Caused by: org.apache.camel.component.salesforce.api.SalesforceException: {errors:[{"errorCode":"INVALID_FIELD","message":"\nLastReferencedDate, Jigsaw, JigsawCompanyId, CleanStatus, AccountSource, DunsNumber\n                                             ^\nERROR at Row:1:Column:687\nNo such column 'CleanStatus' on entity 'Account'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.","fields":null}],statusCode:400}
	at org.apache.camel.component.salesforce.internal.client.DefaultRestClient.createRestException(DefaultRestClient.java:115)
	at org.apache.camel.component.salesforce.internal.client.AbstractClientBase$1.onComplete(AbstractClientBase.java:240)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.ResponseNotifier.forwardSuccessComplete(ResponseNotifier.java:235)
```

**Comment by ppalaga** [comment]
Any volunteer with Salesforce credentials?

**Comment by jamesnetherton** [comment]
I'll try to take a look.
