### ISSUE TITLE
[Quarkus 2.3.0] `GooglePubSubTest` failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3027]
Observed on quarkus-platform main + quarkus main build and also on our `quarkus-main` branch build:

This issue may end up being solved when `quarkus-google-cloud-services` 0.10.0 is released, but it'd be nice to verify ahead of time if possible.

```
2021-08-23T03:41:29.3854947Z %1$s%1$s%1$s%1$s
2021-08-23T03:41:29.3855484Z CDI: programmatic lookup problem detected
2021-08-23T03:41:29.3856254Z -----------------------------------------
2021-08-23T03:41:29.3857101Z At least one bean matched the required type and qualifiers but was marked as unused and removed during build
2021-08-23T03:41:29.3857896Z Removed beans:
2021-08-23T03:41:29.3858404Z    - %2$s
2021-08-23T03:41:29.3859915Z Required type: %3$s
2021-08-23T03:41:29.3860416Z Required qualifiers: %4$s
2021-08-23T03:41:29.3860893Z Solutions:
2021-08-23T03:41:29.3861911Z    - Application developers can eliminate false positives via the @Unremovable annotation
2021-08-23T03:41:29.3863727Z    - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
2021-08-23T03:41:29.3865561Z    - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
2021-08-23T03:41:29.3866882Z    - Enable the DEBUG log level to see the full stack trace to identify the method that performed the lookup
2021-08-23T03:41:29.3867620Z %1$s%1$s%1$s%1$s
2021-08-23T03:41:29.3867862Z
2021-08-23T03:41:29.5944202Z [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 70.694 s &lt;&lt;&lt; FAILURE! - in org.apache.camel.quarkus.component.google.pubsub.it.GooglePubsubTest
2021-08-23T03:41:29.5946921Z [ERROR] jacksonSerializer  Time elapsed: 0.017 s  &lt;&lt;&lt; ERROR!
2021-08-23T03:41:29.5948732Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2021-08-23T03:41:29.5951466Z    at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:724)
2021-08-23T03:41:29.5955305Z    at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:797)
2021-08-23T03:41:29.5958793Z    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-08-23T03:41:29.5962329Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-08-23T03:41:29.5969251Z    at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
2021-08-23T03:41:29.5972733Z    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-08-23T03:41:29.5975805Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-08-23T03:41:29.5979319Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2021-08-23T03:41:29.5983294Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2021-08-23T03:41:29.5987298Z    at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2021-08-23T03:41:29.5990496Z    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2021-08-23T03:41:29.5993249Z    at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
2021-08-23T03:41:29.5997218Z    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
2021-08-23T03:41:29.6002161Z    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
2021-08-23T03:41:29.6006532Z    at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
2021-08-23T03:41:29.6093919Z    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
2021-08-23T03:41:29.6099080Z    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
2021-08-23T03:41:29.6101604Z    at java.base/java.util.Optional.orElseGet(Optional.java:369)
2021-08-23T03:41:29.6104134Z    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
2021-08-23T03:41:29.6108031Z    at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
2021-08-23T03:41:29.6111781Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
2021-08-23T03:41:29.6115759Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-23T03:41:29.6119749Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
2021-08-23T03:41:29.6123904Z    at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
2021-08-23T03:41:29.6127335Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
2021-08-23T03:41:29.6130899Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-23T03:41:29.6134337Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
2021-08-23T03:41:29.6137430Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
2021-08-23T03:41:29.6139545Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-08-23T03:41:29.6143931Z    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-08-23T03:41:29.6149125Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-08-23T03:41:29.6152655Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-23T03:41:29.6156176Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-23T03:41:29.6159020Z    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-23T03:41:29.6161861Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-23T03:41:29.6165374Z    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-23T03:41:29.6169319Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-23T03:41:29.6172857Z    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-23T03:41:29.6174973Z    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by jamesnetherton** [comment]
This may actually be related to the test container setup. In the logs there is:

```
WARN: Unrecognized configuration key "%s" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

The image being used is `google/cloud-sdk:latest`. It could be that the `latest` tag is the source of the problem. Maybe something has changed recently that has caused some issues.

**Comment by gsmet** [comment]
So the problem is that the `GcpConfigHolder` (https://github.com/quarkiverse/quarkus-google-cloud-services/blob/main/common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpConfigHolder.java#L6) is removed by ArC in `main` and not in older versions. If I make the `GcpConfigHolder` bean `@Unremovable`, things are working again. It's the second time someone complains about a CDI bean that is forcefully removed in `main` while it wasn't before. I think someone from the Optaplanner team also complained about something similar.

I see the `GcpConfigHolder` bean being injected via annotations in some other beans but I have no idea if these beans are removed or not.

I'm reproducing this by running the `camel-quarkus-integration-test-google-pubsub` tests (https://github.com/apache/camel-quarkus/tree/main/integration-tests/google-pubsub) with Quarkus 999-SNAPSHOT (changed in the parent pom).

The log is all garbled but the bean Quarkus is complaining about is probably this one (and yes I have to figure out why the log is all garbled).

@manovotn @mkouba does it ring a bell? Could you make sure it's not a bug? Given we have both Camel Quarkus and Optaplanner failing, it looks like it's worth digging.

/cc @loicmathieu FYI, a quick fix is to make `GcpConfigHolder` `@Unremovable`. Maybe we should do that for now?

**Comment by loicmathieu** [comment]
`GcpConfigHolder` didn't exist before so it was a bug to let it be removable but using it blindly in a build step as I did. It didn't show in my integration test because it uses the `GcpCredential`. It's also a lack of tests at my side. And the quick fix is already done ;)

**Comment by manovotn** [comment]
Is this resolved issue then, or is there some investigation to be done?

I recall there were some improvements done to the unused bean removal process here - https://github.com/quarkusio/quarkus/pull/18970
The algorithm should now be more thorough and can remove more beans than previously.

**Comment by jamesnetherton** [comment]
> Is this resolved issue

I tested with `quarkus-google-cloud-services` `0.10.0-SNAPSHOT` and it seems to have fixed things. The test is now passing.
