### ISSUE TITLE
Intermittent failure of `GrpcTest.forwardOnError`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3037]
I've seen this pop up a few times on CI:

```
Caused by: java.lang.AssertionError: mock://forwardOnError Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1790)
	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1767)
	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:448)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:426)
	at org.apache.camel.quarkus.component.grpc.it.GrpcResource.forwardOnError(GrpcResource.java:87)
```

**Comment by llowinge** [comment]
With extended timeout, it failed in native https://github.com/apache/camel-quarkus/pull/7575 (exact commit https://github.com/apache/camel-quarkus/blob/621b0aac890354dc595ae384b02b339d1c918b1e/integration-tests/grpc/src/test/java/org/apache/camel/quarkus/component/grpc/it/GrpcTest.java) in https://github.com/apache/camel-quarkus/actions/runs/16691848686/attempts/2 with error

```
Error:  org.apache.camel.quarkus.component.grpc.it.GrpcIT.forwardOnError -- Time elapsed: 0.075 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: not <null>
	at org.apache.camel.quarkus.component.grpc.it.GrpcTest.forwardOnError(GrpcTest.java:200)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:837)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
