### ISSUE TITLE
Opentracing can't be disabled via config

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#3084]
I added camel-quarkus-opentracing extension and want to disable it in development, but configuration option 
`quarkus.jaeger.enabled=false` doesn't work:
```
2021-09-09 15:13:08,969 WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (camel-quarkus-observability) thread #0 - timer://greeting) Error processing exchange. Exchange[]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
	at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:589)
	at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:27)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:346)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:210)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at io.quarkus.arc.impl.ComputingCache.getValueIfPresent(ComputingCache.java:44)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:15)
	at io.quarkus.smallrye.opentracing.runtime.TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.arc$delegate(TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.zig:68)
	at io.quarkus.smallrye.opentracing.runtime.TracerProducer_ProducerMethod_tracer_96da`
```

[observability.tar.gz](https://github.com/apache/camel-quarkus/files/7136763/observability.tar.gz)
Reproducer:
1. tar -xvpzf observability.tar.gz
2. cd observability/
3. mvn quarkus:dev
4. watch the console error trace
5. Please note plain quarkus project doesn't have this problem

expected behavior: It should be possible to disable the extension on some environments via configuration

**Comment by jamesnetherton** [comment]
Unfortunately, I don't see a workaround to avoid the problem, other than to remove the `camel-quarkus-opentracing` dependency when in dev mode.

I proposed a fix for the next Camel Quarkus release in https://github.com/apache/camel-quarkus/pull/3085.

**Comment by ennishol** [comment]
@jamesnetherton It's not only about dev mode. One could also want to disable the extension on the staging environment or some other deployment scenarios. Hopefully, your fix will be accepted. Thanks!
