### ISSUE TITLE
[Quarkus 2.4.0] AWT packages forced to be runtime initialized

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3130]
Quarkus has introduced `AwtFeature`, which forces runtime initialization of classes belonging to various AWT packages:

https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/graal/AwtFeature.java#L24-L32

We need to deal with this in our extensions. Currently the following native itest builds fail:

* FOP
* Google
* Mail
* OptaPlanner
* PDF
* Tika

**Comment by jamesnetherton** [comment]
Most of the issues should now be fixed. Except for Tika where I don't (yet) understand the root case of the native compilation error:

```
com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.nio.cs.ext.ISO2022_CN$Decoder.<init>(java.nio.charset.Charset) 
Parsing context:
   at sun.nio.cs.ext.ISO2022_CN.newDecoder(ISO2022_CN.java:74)
   at sun.nio.cs.ThreadLocalCoders$1.create(ThreadLocalCoders.java:100)
   at sun.nio.cs.ThreadLocalCoders$Cache.forName(ThreadLocalCoders.java:80)
   at sun.nio.cs.ThreadLocalCoders.decoderFor(ThreadLocalCoders.java:107)
   at sun.net.www.ParseUtil.decode(ParseUtil.java:180)
   at sun.net.www.protocol.file.Handler.openConnection(Handler.java:80)
   at sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
   at java.net.URL.openConnection(URL.java:1099)
   at java.util.ServiceLoader$LazyClassPathLookupIterator.parse(ServiceLoader.java:1163)
   at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1206)
   at com.oracle.svm.core.jdk.Target_java_util_ServiceLoader_LazyClassPathLookupIterator.hasNextService(Target_java_util_ServiceLoader.java:105)
   at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
   at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
   at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
   at javax.enterprise.inject.spi.CDI.findAllProviders(CDI.java:120)
   at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:82)
   at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
   at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:105)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
   at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
```
