### ISSUE TITLE
RestClient: NullPointerException: Cannot read field "skipPattern" because "this.tracingConfig" is null

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#3142]
When using open tracing and microprofile rest client I get the error:
```java
java.lang.NullPointerException: Cannot read field "skipPattern" because "this.tracingConfig" is null
	at io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature.configure(QuarkusSmallRyeTracingDynamicFeature.java:26)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.<init>(ClientInvoker.java:87)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.createClientInvoker(ProxyBuilderImpl.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.build(ProxyBuilderImpl.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.build(ProxyBuilderImpl.java:108)
	at io.quarkus.restclient.runtime.QuarkusRestClientBuilder.build(QuarkusRestClientBuilder.java:339)
	at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:69)
	at org.acme.observability.ChuckNorrisService_79fd6a8cbc68c8d6ace72dc55beac63165c8b1e7_Synthetic_Bean.create(ChuckNorrisService_79fd6a8cbc68c8d6ace72dc55beac63165c8b1e7_Synthetic_Bean.zig:225
```

Some logs:
```
2021-09-30 12:22:23,380 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-14) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "org.apache.camel.main" found in [org.apache.camel:camel-base-engine::jar, org.apache.camel:camel-main::jar]
2021-09-30 12:22:25,040 WARN  [io.qua.arc.impl] (Quarkus Main Thread) 
================================================================================
CDI: programmatic lookup problem detected
-----------------------------------------
At least one bean matched the required type and qualifiers but was marked as unused and removed during build
Removed beans:
        - null bean null [types=[interface javax.ws.rs.container.DynamicFeature, class io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature], qualifiers=null]
Required type: class io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature
Required qualifiers: [@javax.enterprise.inject.Default()]
Solutions:
        - Application developers can eliminate false positives via the @Unremovable annotation
        - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
        - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
================================================================================
```
Reproducer [observability.tar.gz](https://github.com/apache/camel-quarkus/files/7258879/observability.tar.gz)

1. tar -xvpzf observability.tar.gz
2. cd observability/
3. mvn quarkus:dev
4. browse http://localhost:8080/api/joke
5. or execute mvn test

Update: when fixed, update route in Route.java to make the output work
```java
        rest("/api/")
                .get("/joke")
                .produces("application/json")
                .route()
                  .process(exchange -> exchange.getIn().setBody(jokes.joke()))
                  .marshal().json(JsonLibrary.Jsonb)
                .endRest();
```
and add dependency
```xml
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-jsonb</artifactId>
        </dependency>
```

**Comment by ennishol** [comment]
When I remove `camel-quarkus-opentracing` and corresponding config and `@Traced` annotations, then the application works fine

**Comment by jamesnetherton** [comment]
The workaround is to set a configuration property:

```
quarkus.arc.unremovable-types=io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature
```

I need to dig into the problem a bit further. Seems strange that Quarkus is removing a type when the Camel extension is present.

**Comment by jamesnetherton** [comment]
@ennishol You may want to raise a Quarkus issue for this.

The same warning is present when you remove all of the Camel Quarkus dependencies and add `quarkus-smallrye-opentracing`. So it seems to be a general Quarkus OpenTracing issue, unrelated to Camel Quarkus.

**Comment by ennishol** [comment]
@jamesnetherton  I created equivalent quarkus project and it works just fine. So, it seems that it is the combination of quarkus and camel is the problem

**Comment by jamesnetherton** [comment]
Ok, I can take another look.

**Comment by jamesnetherton** [comment]
> I could make QuarkusSmallRyeTracingDynamicFeature unremovable in our OpenTracing extension if there's no RestEasy present, which would probably solve the problem.

Thinking that through some more. It'd be a hack & not a true fix. So it's Quarkus that should handle RestEasy not being present, if that is actually a valid scenario.

**Comment by ennishol** [comment]
@jamesnetherton  Thanks for looking into it. I added resteasy extension and now that fixed the problem

**Comment by gsmet** [comment]
It has finally been fixed in Quarkus here: https://github.com/quarkusio/quarkus/pull/22609 .
