### ISSUE TITLE
URL to the Kafka brokers must be configured with the brokers option in native mode

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#3157]
Happens in the Kafka example after upgrading to Camel Quarkus 2.3.0.

I am disabling the test for now.

```
mvn clean verify -Pnative

[INFO] Running org.apache.camel.example.KafkaIT
Oct 05, 2021 3:36:55 P.M. org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
2021-10-05 15:36:55,855 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-10) Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-10-05 15:36:56,226 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-10) Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
2021-10-05 15:36:56,227 INFO  [org.tes.DockerClientFactory] (build-10) Docker host IP address is localhost
2021-10-05 15:36:56,263 INFO  [org.tes.DockerClientFactory] (build-10) Connected to docker: 
  Server Version: 20.10.8
  API Version: 1.41
  Operating System: Fedora 34 (KDE Plasma)
  Total Memory: 64172 MB
2021-10-05 15:36:56,267 INFO  [org.tes.uti.ImageNameSubstitutor] (build-10) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2021-10-05 15:36:56,322 INFO  [org.tes.uti.RegistryAuthLocator] (build-10) Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.1, configFile: /home/ppalaga/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/ppalaga/.docker/config.json (No such file or directory)
2021-10-05 15:36:56,839 INFO  [org.tes.DockerClientFactory] (build-10) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2021-10-05 15:36:56,839 INFO  [org.tes.DockerClientFactory] (build-10) Checking the system...
2021-10-05 15:36:56,840 INFO  [org.tes.DockerClientFactory] (build-10) ✔︎ Docker server version should be at least 1.6.0
2021-10-05 15:36:56,913 INFO  [org.tes.DockerClientFactory] (build-10) ✔︎ Docker environment should have more than 2GB free disk space
2021-10-05 15:36:56,971 INFO  [🐳 .5.5]] (build-10) Creating container for image: vectorized/redpanda:v21.5.5
2021-10-05 15:36:57,244 INFO  [🐳 .5.5]] (build-10) Starting container with ID: 89d3240159a9e504d401020f1774ef41242f336b398bdc1d627d32b8b54fee92
2021-10-05 15:36:57,592 INFO  [🐳 .5.5]] (build-10) Container vectorized/redpanda:v21.5.5 is starting: 89d3240159a9e504d401020f1774ef41242f336b398bdc1d627d32b8b54fee92
2021-10-05 15:36:58,347 INFO  [🐳 .5.5]] (build-10) Container vectorized/redpanda:v21.5.5 started in PT1.416318S
Oct 05, 2021 3:36:58 P.M. io.quarkus.kafka.client.deployment.DevServicesKafkaProcessor startKafkaDevService
INFO: Dev Services for Kafka started. Other Quarkus applications in dev mode will find the broker automatically. For Quarkus applications in production mode, you can connect to this by starting your application with -Dkafka.bootstrap.servers=PLAINTEXT://localhost:49256
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /home/ppalaga/orgs/cq/camel-quarkus-examples/kafka/target/camel-quarkus-examples-kafka-2.3.0-SNAPSHOT-runner
======================================================================================
Executing "/home/ppalaga/orgs/cq/camel-quarkus-examples/kafka/target/camel-quarkus-examples-kafka-2.3.0-SNAPSHOT-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/ppalaga/orgs/cq/camel-quarkus-examples/kafka/target/quarkus.log -Dquarkus.log.file.enable=true -Dkafka.bootstrap.servers=PLAINTEXT://localhost:49256"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-10-05 15:36:58,523 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-10-05 15:36:58,528 ERROR [org.apa.cam.imp.eng.AbstractCamelContext] (main) Error starting CamelContext (camel-1) due to exception thrown: Failed to start route FromTimer2Kafka because of null: org.apache.camel.FailedToStartRouteException: Failed to start route FromTimer2Kafka because of null
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:123)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doWarmUpRoutes(InternalRouteStartupManager.java:306)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:189)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3167)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2847)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2798)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2494)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:245)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:139)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:843)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: URL to the Kafka brokers must be configured with the brokers option.
        at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:67)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.impl.engine.DefaultChannel.doStart(DefaultChannel.java:126)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:116)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:221)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:89)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.impl.engine.RouteService.startChildServices(RouteService.java:396)
        at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:193)
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:121)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: URL to the Kafka brokers must be configured with the brokers option.
        at org.apache.camel.component.kafka.DefaultKafkaClientFactory.getBrokers(DefaultKafkaClientFactory.java:42)
        at org.apache.camel.component.kafka.KafkaProducer.getProps(KafkaProducer.java:73)
        at org.apache.camel.component.kafka.KafkaProducer.doStart(KafkaProducer.java:105)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1462)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1383)
        at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:247)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1638)
        at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:60)
        ... 39 more

```

**Comment by jamesnetherton** [comment]
Shouldn't the CQ CI build have caught this? I thought it verified the latest CQ `main` SNAPSHOT with the examples `camel-quarkus-main`?

So I'm a bit confused why it's failing with the release build but there's never been any failure on the CQ CI.

**Comment by jamesnetherton** [comment]
Seems the CQ CI build just runs `mvn clean verify -Pnative` on each example. So basically it's just testing that the examples in their original form on `camel-quarkus-main`, build properly. Which seems somewhat pointless. 

We should tweak the CQ version so that the examples build against SNAPSHOT. I'll open a separate issue for that.

**Comment by zhfeng** [comment]
I can take a look at this issue.

**Comment by zhfeng** [comment]
It's too late to registe the ```CamelBeanBuildItem``` in native mode due to the KafkaDevSerivce is avaiable in TEST mode. It's just running before the application starts. So we only need to pass ```camel.component.kafka.brokers=PLAINTEXT://localhost:31318``` option to the native application.
