### ISSUE TITLE
OpenAPI Java integration tests fail with Camel 3.13.0-SNAPSHOT

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3171]
First run of CQ with Camel 3.13.0-SNAPSHOT was mostly successful. But openapi-java itests failed:

https://github.com/apache/camel-quarkus/runs/3837912836?check_suite_focus=true

Could be related to [CAMEL-17049](https://issues.apache.org/jira/browse/CAMEL-17049). Maybe @davsclaus knows?

```
2021-10-08T11:47:21.0728567Z Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: platform-http:///openapi?httpMethodRestrict=GET&matchOnUriPrefix=true due to: Failed to resolve endpoint: platform-http:///openapi?httpMethodRestrict=GET&matchOnUriPrefix=true due to: There are 2 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{producerComponentName=, routeId=route1}]
2021-10-08T11:47:21.0732104Z 	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:963)
2021-10-08T11:47:21.0734424Z 	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:869)
2021-10-08T11:47:21.0737509Z 	at org.apache.camel.component.platform.http.PlatformHttpComponent.doCreateConsumer(PlatformHttpComponent.java:168)
2021-10-08T11:47:21.0741033Z 	at org.apache.camel.component.platform.http.PlatformHttpComponent.createApiConsumer(PlatformHttpComponent.java:81)
2021-10-08T11:47:21.0743798Z 	at org.apache.camel.component.rest.RestApiEndpoint.createConsumer(RestApiEndpoint.java:273)
2021-10-08T11:47:21.0745941Z 	at org.apache.camel.impl.engine.DefaultRoute.gatherRootServices(DefaultRoute.java:599)
2021-10-08T11:47:21.0747917Z 	at org.apache.camel.impl.engine.DefaultRoute.gatherServices(DefaultRoute.java:583)
2021-10-08T11:47:21.0749866Z 	at org.apache.camel.impl.engine.DefaultRoute.initializeServices(DefaultRoute.java:168)
2021-10-08T11:47:21.0751696Z 	at org.apache.camel.impl.engine.RouteService.doSetup(RouteService.java:151)
2021-10-08T11:47:21.0753882Z 	at org.apache.camel.impl.engine.RouteService.setUp(RouteService.java:130)
2021-10-08T11:47:21.0754852Z 	... 66 more
```

The `platform-http:openapi` part comes from the `camel.rest.api-context-path = /openapi` config.

**Comment by jamesnetherton** [comment]
Seems this is fixed already.
