### ISSUE TITLE
Sql - native tests fail on NPE during db initialization

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#3247]
Here is a log snippet (execution with `-Dcq.sqlJdbcKind=oracle`):

```
2021-11-01 13:01:32,115 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:167)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.apache.camel.quarkus.component.sql.it.SqlDbInitializer.initDb(SqlDbInitializer.java:52)
	at org.apache.camel.quarkus.component.sql.it.SqlDbInitializer_ClientProxy.initDb(SqlDbInitializer_ClientProxy.zig:127)
```

**Comment by JiriOndrusek** [comment]
Problem is mainly caused by not consistent approach used for `oracle` db. Oracle db usage should use the same approach as other external dbs - `  -Dcq.sqlJdbcKind=oracle`.
