### ISSUE TITLE
[JDK17]integration tests failed in native mode which uses JMX

### ISSUE THREAD

**Issue by ffang** [apache/camel-quarkus#3325]
get error like
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.oracle.svm.core.genscavenge.CompleteGarbageCollectorMXBean.getObjectName(CompleteGarbageCollectorMXBean.java:81)
Call path from entry point to com.oracle.svm.core.genscavenge.CompleteGarbageCollectorMXBean.getObjectName(): 
	at com.oracle.svm.core.genscavenge.CompleteGarbageCollectorMXBean.getObjectName(CompleteGarbageCollectorMXBean.java:81)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:969)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.close(GenericKeyedObjectPool.java:695)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.oracle.svm.core.genscavenge.IncrementalGarbageCollectorMXBean.getObjectName(IncrementalGarbageCollectorMXBean.java:81)
Call path from entry point to com.oracle.svm.core.genscavenge.IncrementalGarbageCollectorMXBean.getObjectName(): 
	at com.oracle.svm.core.genscavenge.IncrementalGarbageCollectorMXBean.getObjectName(IncrementalGarbageCollectorMXBean.java:81)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:969)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.close(GenericKeyedObjectPool.java:695)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.oracle.svm.core.heap.AbstractMemoryMXBean.getObjectName(AbstractMemoryMXBean.java:66)
Call path from entry point to com.oracle.svm.core.heap.AbstractMemoryMXBean.getObjectName(): 
	at com.oracle.svm.core.heap.AbstractMemoryMXBean.getObjectName(AbstractMemoryMXBean.java:66)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:969)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.close(GenericKeyedObjectPool.java:695)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.oracle.svm.core.jdk.management.SubstrateClassLoadingMXBean.getObjectName(SubstrateClassLoadingMXBean.java:47)
Call path from entry point to com.oracle.svm.core.jdk.management.SubstrateClassLoadingMXBean.getObjectName(): 
	at com.oracle.svm.core.jdk.management.SubstrateClassLoadingMXBean.getObjectName(SubstrateClassLoadingMXBean.java:47)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:969)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.close(GenericKeyedObjectPool.java:695)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing com.oracle.svm.core.jdk.management.SubstrateCompilationMXBean.getObjectName(SubstrateCompilationMXBean.java:47)
Call path from entry point to com.oracle.svm.core.jdk.management.SubstrateCompilationMXBean.getObjectName(): 
	at com.oracle.svm.core.jdk.management.SubstrateCompilationMXBean.getObjectName(SubstrateCompilationMXBean.java:47)
	at com.oracle.svm.core.jdk.management.ManagementSupport.addMXBean(ManagementSupport.java:267)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:259)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:969)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.close(GenericKeyedObjectPool.java:695)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.close(PosixSunSecuritySubstitutions.java:86)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloserShutdownHook.run(PosixSunSecuritySubstitutions.java:70)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

This is error is on JDK17 only(but I believe this issue occurs on all OS), JDK11 it's OK.

Looks like we need to add add-opens/add-exports java.management/sun.management=ALL-UNNAMED JVM flag somewhere to make package sun.management more accessible when building the native image

**Comment by ffang** [comment]
Ah, nice, we have the similar issue reported and fixed at quarkus already
https://github.com/quarkusio/quarkus/issues/21372

And this commit https://github.com/quarkusio/quarkus/pull/21408/commits/dc9a6ec5593928ac58681d21de8bc6a8a3de483f fixed it from quarkus-core when building the native image

**Comment by ffang** [comment]
This also affects atlasmap native test

**Comment by jamesnetherton** [comment]
Out of date. This is now working without any issues.
