### ISSUE TITLE
XSLT integration-test fails on Windows 10

### ISSUE THREAD

**Issue by bvahdat** [apache/camel-quarkus#3374]
Running the tests by the following repo on Windows:

https://github.com/bvahdat/code-with-quarkus

fails with:

```
[INFO] Running org.apache.camel.quarkus.component.xml.it.XmlTest
2021-12-09 15:49:35,515 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-12-09 15:49:35,635 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route route2 at: >>> To[xslt:xslt/html-transform.xsl] <<< in route: Route(route2)[From[direct:html-transfrom] -> [Unmarshal[org.... because of Failed to resolve endpoint: xslt://xslt/html-transform.xsl due to: javax.xml.transform.TransformerConfigurationException: Cannot find class 'org.apache.camel.quarkus.component.xslt.generated.HtmlTransform'.
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:240)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:74)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:851)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:741)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2773)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:165)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2491)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2510)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:246)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:139)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:237)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:242)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:561)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:599)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: xslt://xslt/html-transform.xsl due to: javax.xml.transform.TransformerConfigurationException: Cannot find class 'org.apache.camel.quarkus.component.xslt.generated.HtmlTransform'.
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:964)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:846)
        at org.apache.camel.support.CamelContextHelper.resolveEndpoint(CamelContextHelper.java:123)
        at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:43)
        at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:36)
        at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:838)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:579)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:236)
        ... 70 more
Caused by: org.apache.camel.RuntimeCamelException: javax.xml.transform.TransformerConfigurationException: Cannot find class 'org.apache.camel.quarkus.component.xslt.generated.HtmlTransform'.
        at org.apache.camel.RuntimeCamelException.wrapRuntimeException(RuntimeCamelException.java:66)
        at org.apache.camel.support.service.BaseService.doFail(BaseService.java:413)
        at org.apache.camel.support.service.BaseService.fail(BaseService.java:342)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:88)
        at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84)
        at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1454)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1399)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1394)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1389)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:948)
        ... 77 more
Caused by: javax.xml.transform.TransformerConfigurationException: Cannot find class 'org.apache.camel.quarkus.component.xslt.generated.HtmlTransform'.
        at org.apache.xalan.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:699)
        at org.apache.camel.quarkus.support.xalan.XalanTransformerFactory.newTemplates(XalanTransformerFactory.java:70)
        at org.apache.camel.component.xslt.XsltBuilder.setTransformerSource(XsltBuilder.java:345)
        at org.apache.camel.component.xslt.XsltEndpoint.loadResource(XsltEndpoint.java:326)
        at org.apache.camel.component.xslt.XsltEndpoint.doInit(XsltEndpoint.java:342)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        ... 83 more
```

But not on macOS!

Or you could also run the following tests which is exaclty the same codebase as above:

https://github.com/apache/camel-quarkus/tree/main/integration-tests/xml

**Comment by zhfeng** [comment]
It's weird. These classes could be pre-compiled and write into the tempory directory. see https://github.com/apache/camel-quarkus/blob/main/extensions/xslt/deployment/src/main/java/org/apache/camel/quarkus/component/xslt/deployment/XsltProcessor.java#L88

Can you check in the windows tempory directory to see if .class files exists ? unfortunately I have no windows environment to test it locally.

**Comment by bvahdat** [comment]
Thanks for your support @zhfeng. I checked on 2 different Windows machines and the behaviour is the same:

The temp directory points to `C:\Users\MY_NAME\AppData\Local\Temp` folder and unfortunately there is no classes being generated there. As the tests get executed I only see the following folder being quickly generated while tests are running and removed afterwards:

- `hsperfdata_MY_NAME` which belongs to Java performance counter I think
- `surefire93443224453552`  <-- with some arbitraray number at each run which belongs to surefire plugin I think

When the test executions fails / ends I see an empty folder with the following name being generated:

- `vertx-cache`

**Comment by zhfeng** [comment]
OK, I think I found an issue in ```XsltProcessor``` which should use ```File.pathSeparatorChar``` but no ```'/'```.

**Comment by zhfeng** [comment]
@bvahdat can you test this fix to see if it works on windows ? Thanks !

**Comment by bvahdat** [comment]
> @bvahdat can you test this fix to see if it works on windows ? Thanks !

Thanks, I'm looking into it right now, unfortunately on Windows building camel-quarkus locally with:

`mvn  clean install -Dquickly`

is failing for me by the `camel-quarkus-docs` artifact:

```
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (update-antora-config) on project camel-quarkus-docs: Execution update-antora-config of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Impossible to read the text content from file://C:/dev/workspace/camel-quarkus/tooling/scripts/update-antora-config.groovy: Unknown host C -> [Help 1]
```

https://github.com/apache/camel-quarkus/issues/3307 seems to be relevant in this regard.

**Comment by bvahdat** [comment]
Ah just removing the following lines helped me to bypass the error above:

https://github.com/apache/camel-quarkus/blob/main/docs/pom.xml#L36-L54

**Comment by bvahdat** [comment]
Awesome job @zhfeng, that was indeed the root cause of the issue we were facing on WIndows. Now running tests behave differently with just the following assertion failure:

```
[ERROR] Failures:
[ERROR]   XmlTest.htmlToText:93 expected: <= Title

Paragraph Contents> but was: <= Title

Paragraph Contents>
```

Which corresponds to the following lines:

https://github.com/apache/camel-quarkus/blob/main/integration-tests/xml/src/test/java/org/apache/camel/quarkus/component/xml/it/XmlTest.java#L93-L97

Which I could quickly fix locally with:

```
Assertions.assertEquals(
        "= Title" + System.lineSeparator()
                +  System.lineSeparator()
                + "Paragraph Contents",
        actual);
```

Would you please provide your fix + this tiny test failure fix of mine above as a PR?

**Comment by zhfeng** [comment]
Thanks @bvahdat for checking - yeah, I can add this fix for ```XmlTest``` in https://github.com/apache/camel-quarkus/pull/3380.
