### ISSUE TITLE
file: FileTest is flaky

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#3627]
The build has failed once on [camel-quarkus CI](https://github.com/apache/camel-quarkus/runs/5509250742?check_suite_focus=true) and once in [quarkus-platform CI](https://github.com/quarkusio/quarkus-platform/runs/5569244554?check_suite_focus=true#step:6:24599) with error message as below:

```
Error:  Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 23.503 s <<< FAILURE! - in org.apache.camel.quarkus.component.file.it.FileTest
Error:  charset  Time elapsed: 10.127 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: org.apache.camel.quarkus.component.file.it.FileTest expected "Hello World 你好" but was "" within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
	at org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:645)
	at org.apache.camel.quarkus.component.file.it.FileTest.charset(FileTest.java:93)
```

The frequency of this build issue seems quite low, still problematic.

There could be a link with #3584 .

**Comment by aldettinger** [comment]
One occurence more: https://github.com/apache/camel-quarkus/runs/5579549052?check_suite_focus=true#step:9:10012
