### ISSUE TITLE
Improve support for `InfinispanRemoteAggregationRepository` with Quarkus Infinispan

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3657]
There is some commentary about moving away from the (deprecated) `JbossUserMarshaller` and Java serialization here:

https://github.com/apache/camel/blob/main/components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepository.java

When testing the scenario where the Infinispan client is configured & managed by the Camel component, it works ok. When the client is managed by the Quarkus Infinispan extension, things get a little complicated. You have to create `hotrod-client.properties` and manually set the marshaller. This isn't ideal because it prohibits some nice functionality provided by the default `ProtoStreamMarshaller`.

**Comment by jamesnetherton** [comment]
Also it does not seem to work properly in native mode. There is something wrong with deserialization. For some reason it's trying to instantiate `AbstractMap`:

```
Caused by: java.lang.IllegalStateException: Instantiation failed unexpectedly
        at org.jboss.marshalling.reflect.SerializableClass.invokeConstructorNoException(SerializableClass.java:32)
        at org.jboss.marshalling.reflect.SerializableClass.callNonInitConstructor(SerializableClass.java:340)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1417)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:246)
        at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1879)
        at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1793)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1421)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:298)
        at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:231)
        at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromObjectStream(AbstractJBossMarshaller.java:137)
        at org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectFromByteBuffer(AbstractJBossMarshaller.java:115)
        at org.infinispan.commons.marshall.AbstractMarshaller.objectFromByteBuffer(AbstractMarshaller.java:82)
        at org.infinispan.client.hotrod.marshall.MarshallerUtil.bytes2obj(MarshallerUtil.java:57)
        ... 28 more
Caused by: java.lang.InstantiationException: Only non-abstract instance classes can be instantiated using reflection
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.jboss.marshalling.reflect.SerializableClass.invokeConstructorNoException(SerializableClass.java:21)
        ... 42 more
Caused by: an exception which occurred:
        in object of type java.util.LinkedHashMap
        in field org.apache.camel.support.DefaultExchangeHolder.inHeaders
        in object org.apache.camel.support.DefaultExchangeHolder@bac388f
        in object of type org.apache.camel.support.DefaultExchangeHolder
```

**Comment by jamesnetherton** [comment]
Opened some issues that could eventually help here:

https://issues.apache.org/jira/browse/CAMEL-18044
https://issues.apache.org/jira/browse/CAMEL-18045

**Comment by jamesnetherton** [comment]
> So actually, you've fixed this with quarkus.camel.native.reflection.serialization-enabled

No, it is solved by [CAMEL-18044](https://issues.apache.org/jira/browse/CAMEL-18044).

**Comment by aldettinger** [comment]
Ok, thanks for sharing. So I could try to evaluate whether stopping to use the jboss marshaller is feasible in my context.
