### ISSUE TITLE
Upgrade to Quarkus 0.28.1

### ISSUE THREAD

**Issue by gastaldi** [apache/camel-quarkus#372]
Right now simply bumping the version in the platform BOM in https://github.com/quarkusio/quarkus-platform fails on the `MicroProfileMetricsTest`: 

```bash
[ERROR] Failures: 
[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsCamelContextEventNotifier:130->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsConcurrentGauge:50->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsCounter:40->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsExchangeEventNotifier:125->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsGauge:65->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsHistogram:73->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsMessageHistoryFactory:106->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsMeter:81->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsRouteEventNotifier:116->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsRoutePolicyFactory:97->getMetricIntValue:135->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[ERROR]   MicroProfileMetricsTest.testMicroProfileMetricsTimer:89->getMetricFloatValue:139->getApplicationMetrics:162 1 expectation failed.
Expected status code <200> but was <500>.

[INFO] 
[ERROR] Tests run: 11, Failures: 11, Errors: 0, Skipped: 0

```

**Comment by gnodet** [comment]
@gastaldi are you sure this isn't a transient issue ? the tests do run fine for me with #373

**Comment by gastaldi** [comment]
@gnodet it looks like it. The tests run fine for me too when bumping the quarkus version in this repository, but fails in the https://github.com/quarkusio/quarkus-platform/tree/0.28 (which in theory should be the same)?

**Comment by gastaldi** [comment]
This is the stacktrace seen in quarkus-platform: 

```java
Nov 04, 2019 12:57:57 PM io.quarkus.vertx.http.runtime.QuarkusErrorHandler handle
ERROR: HTTP Request to /metrics/application failed, error id: d4150f81-9045-45c7-b952-f06078d17392-1
java.lang.AbstractMethodError
	at io.smallrye.metrics.exporters.JsonExporter.getValueFromMetric(JsonExporter.java:286)
	at io.smallrye.metrics.exporters.JsonExporter.exportSimpleMetric(JsonExporter.java:201)
	at io.smallrye.metrics.exporters.JsonExporter.lambda$exportMetricsByName$1(JsonExporter.java:132)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.smallrye.metrics.exporters.JsonExporter.exportMetricsByName(JsonExporter.java:130)
	at io.smallrye.metrics.exporters.JsonExporter.lambda$exportMetricsForMap$8(JsonExporter.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at io.smallrye.metrics.exporters.JsonExporter.exportMetricsForMap(JsonExporter.java:194)
	at io.smallrye.metrics.exporters.JsonExporter.exportOneRegistry(JsonExporter.java:178)
	at io.smallrye.metrics.exporters.JsonExporter.exportOneScope(JsonExporter.java:59)
	at io.smallrye.metrics.MetricsRequestHandler.handleRequest(MetricsRequestHandler.java:153)
	at io.smallrye.metrics.MetricsRequestHandler_ClientProxy.handleRequest(MetricsRequestHandler_ClientProxy.zig:246)
	at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler.handle(SmallRyeMetricsHandler.java:35)
	at io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler.handle(SmallRyeMetricsHandler.java:17)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:19)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:6)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
