### ISSUE TITLE
Use WireMock for xchange tests

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3724]
```
[INFO] Running org.apache.camel.quarkus.component.xchange.it.XchangeTest
2022-04-22 18:44:55,154 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final-redhat-00001
2022-04-22 18:44:56,930 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.https.test-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2022-04-22 18:44:57,670 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2022-04-22 18:44:57,744 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (total:0 started:0)
2022-04-22 18:44:57,744 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.14.2.redhat-00006 (camel-1) started in 38ms (build:0ms init:18ms start:20ms)
2022-04-22 18:44:57,887 INFO  [io.quarkus] (main) Quarkus 2.7.5.Final-redhat-00007 on JVM started in 3.314s. Listening on: http://localhost:35088
2022-04-22 18:44:57,887 INFO  [io.quarkus] (main) Profile test activated. 
2022-04-22 18:44:57,888 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-xchange, cdi, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]
2022-04-22 18:44:59,856 INFO  [org.kno.xch.bin.BinanceExchange] (executor-thread-0) Calling Remote Init...
2022-04-22 18:44:59,903 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xchange/currency/metadata/BTC failed, error id: a201012d-5ffa-4bbe-a81a-30074b245f5b-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: xchange://binance?method=currencyMetaData&service=metadata due to: Failed to initialize: Connection refused (Connection refused)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: xchange://binance?method=currencyMetaData&service=metadata due to: Failed to initialize: Connection refused (Connection refused)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:968)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:850)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:573)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:411)
	at org.apache.camel.quarkus.component.xchange.it.XchangeResource.currencyMetadata(XchangeResource.java:87)
	at org.apache.camel.quarkus.component.xchange.it.XchangeResource_ClientProxy.currencyMetadata(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 15 more
Caused by: org.knowm.xchange.exceptions.ExchangeException: Failed to initialize: Connection refused (Connection refused)
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:114)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
	at org.knowm.xchange.binance.BinanceExchange.applySpecification(BinanceExchange.java:86)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:110)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:53)
	at org.apache.camel.component.xchange.XChangeComponent.getOrCreateXChange(XChangeComponent.java:64)
	at org.apache.camel.component.xchange.XChangeComponent.createEndpoint(XChangeComponent.java:43)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:934)
	... 35 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:145)
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:156)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:113)
	at com.sun.proxy.$Proxy81.exchangeInfo(Unknown Source)
	at org.knowm.xchange.client.ResilienceUtils$DecorateCallableApi.call(ResilienceUtils.java:86)
	at org.knowm.xchange.binance.service.BinanceBaseService.getExchangeInfo(BinanceBaseService.java:69)
	at org.knowm.xchange.binance.BinanceExchange.remoteInit(BinanceExchange.java:103)
	... 43 more
```

**Comment by jamesnetherton** [comment]
Turns out this a bit tricky to implement as it's not simple to get XChange to talk to WireMock instead of the real APIs. I've made a minor tweak to the `XChangeComponent` for Camel 3.17 which should help fix this.
