### ISSUE TITLE
[Camel 3.17.0] Property placeholder resolution is broken

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3739]
Lots of tests failing due to routes with URIs having property placeholders:

```
Caused by: java.util.NoSuchElementException: SRCFG00040: The config property sun.cpu.isalist is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:282)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:237)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:165)
	at org.apache.camel.component.microprofile.config.CamelMicroProfilePropertiesSource.loadProperties(CamelMicroProfilePropertiesSource.java:50)
	at org.apache.camel.component.properties.DefaultPropertiesLookup.doLookup(DefaultPropertiesLookup.java:89)
	at org.apache.camel.component.properties.DefaultPropertiesLookup.lookup(DefaultPropertiesLookup.java:43)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.doGetPropertyValue(DefaultPropertiesParser.java:348)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.getPropertyValue(DefaultPropertiesParser.java:275)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.readProperty(DefaultPropertiesParser.java:177)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.doParse(DefaultPropertiesParser.java:119)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.parse(DefaultPropertiesParser.java:103)
	at org.apache.camel.component.properties.DefaultPropertiesParser.parseUri(DefaultPropertiesParser.java:68)
	at org.apache.camel.component.properties.PropertiesComponent.parseUri(PropertiesComponent.java:312)
	at org.apache.camel.component.properties.PropertiesComponent.parseUri(PropertiesComponent.java:168)
	at org.apache.camel.impl.engine.AbstractCamelContext.resolvePropertyPlaceholders(AbstractCamelContext.java:1879)
	at org.apache.camel.support.EndpointHelper.resolveEndpointUriPropertyPlaceholders(EndpointHelper.java:74)
	... 74 more
```

**Comment by jamesnetherton** [comment]
https://issues.apache.org/jira/browse/CAMEL-17996
