### ISSUE TITLE
Intermittent failure of FHIR integration tests `SocketTimeoutException`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3746]
I saw this once on the platform CI build and also on the `quarkus-main` branch. Not sure what the root cause is. Maybe the FHIR server cannot handle the volume of requests being sent to it?

```
log=false, resource=org.hl7.fhir.r4.model.Patient@56f28ef8, methodName=resource, extraParameters={PRETTY_PRINT=false}, deferModelScanning=false, forceConformanceCheck=false, fhirVersion=R4, serverUrl=http://localhost:49172/fhir, fhirContext=FhirContext[R4], client=ca.uhn.fhir.rest.client.impl.GenericClient@4e29bb54}: Failed to parse response from server when performing POST to URL http://localhost:49172/fhir/Patient - java.net.SocketTimeoutException: Read timed out
2022-04-25T04:04:35.7543247Z 	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:531)
2022-04-25T04:04:35.7543962Z 	at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:122)
2022-04-25T04:04:35.7544669Z 	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:89)
2022-04-25T04:04:35.7545238Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-04-25T04:04:35.7545723Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-04-25T04:04:35.7546318Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2022-04-25T04:04:35.7546996Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-25T04:04:35.7547578Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-25T04:04:35.7548017Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-25T04:04:35.7549239Z Caused by: ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing POST to URL http://localhost:49172/fhir/Patient - java.net.SocketTimeoutException: Read timed out
2022-04-25T04:04:35.7550056Z 	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:398)
2022-04-25T04:04:35.7550630Z 	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
2022-04-25T04:04:35.7551212Z 	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:581)
2022-04-25T04:04:35.7551763Z 	at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:536)
2022-04-25T04:04:35.7552331Z 	at org.apache.camel.component.fhir.api.FhirCreate.resource(FhirCreate.java:57)
2022-04-25T04:04:35.7552899Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-25T04:04:35.7553504Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-25T04:04:35.7554194Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-25T04:04:35.7554760Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-25T04:04:35.7555310Z 	at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:523)
2022-04-25T04:04:35.7555731Z 	... 8 more
2022-04-25T04:04:35.7556042Z Caused by: java.net.SocketTimeoutException: Read timed out
2022-04-25T04:04:35.7556600Z 	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
2022-04-25T04:04:35.7557358Z 	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
2022-04-25T04:04:35.7558079Z 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
2022-04-25T04:04:35.7558552Z 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
2022-04-25T04:04:35.7559124Z 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
2022-04-25T04:04:35.7559761Z 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
2022-04-25T04:04:35.7560404Z 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
2022-04-25T04:04:35.7561306Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
2022-04-25T04:04:35.7562012Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
2022-04-25T04:04:35.7562638Z 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
2022-04-25T04:04:35.7563334Z 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
2022-04-25T04:04:35.7564141Z 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
2022-04-25T04:04:35.7564774Z 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
2022-04-25T04:04:35.7565416Z 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
2022-04-25T04:04:35.7566006Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
2022-04-25T04:04:35.7566575Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
2022-04-25T04:04:35.7567209Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2022-04-25T04:04:35.7567853Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
2022-04-25T04:04:35.7568442Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2022-04-25T04:04:35.7569046Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2022-04-25T04:04:35.7569657Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
2022-04-25T04:04:35.7570265Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
2022-04-25T04:04:35.7571005Z 	at ca.uhn.fhir.rest.client.apache.ApacheHttpRequest.execute(ApacheHttpRequest.java:64)
2022-04-25T04:04:35.7571546Z 	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:302)
2022-04-25T04:04:35.7572025Z 	... 17 more
```

**Comment by jamesnetherton** [comment]
Seems this is fixed. I have not seen the error happen on any CI builds since #3789 was merged.
