### ISSUE TITLE
Debezium Postgresql integration test fails with Quarkus 2.8.1.Final

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#3748]
While upgrading to Quarkus 2.8.1.Final, the integrations tests fail.
Reason behind this : Debezium uses a version of Postgresql driver that is behind Quarkus's one, and uses in its code a method that doesn't exist anymore.

Stack trace:
```
2022-04-22T07:39:54.9404688Z Detailed message:
2022-04-22T07:39:54.9406597Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.postgresql.jdbc.TimestampUtils.toOffsetDateTime(java.lang.String). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
2022-04-22T07:39:54.9407406Z Trace: 
2022-04-22T07:39:54.9407987Z 	at parsing io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.lambda$createDefaultValueMappers$20(PostgresDefaultValueConverter.java:147)
2022-04-22T07:39:54.9409492Z Call path from entry point to io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.lambda$createDefaultValueMappers$20(TimestampUtils, String): 
2022-04-22T07:39:54.9410622Z 	at io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.lambda$createDefaultValueMappers$20(PostgresDefaultValueConverter.java:147)
2022-04-22T07:39:54.9411482Z 	at io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter$$Lambda$2248/0x00000007c25d0840.parse(Unknown Source)
2022-04-22T07:39:54.9412334Z 	at io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.parseDefaultValue(PostgresDefaultValueConverter.java:77)
2022-04-22T07:39:54.9413245Z 	at io.debezium.connector.postgresql.connection.PostgresConnection.getDefaultValue(PostgresConnection.java:574)
2022-04-22T07:39:54.9414025Z 	at io.debezium.connector.postgresql.connection.PostgresConnection.doReadTableColumn(PostgresConnection.java:563)
2022-04-22T07:39:54.9442261Z 	at io.debezium.connector.postgresql.connection.PostgresConnection.readTableColumn(PostgresConnection.java:511)
2022-04-22T07:39:54.9442910Z 	at io.debezium.jdbc.JdbcConnection.getColumnsDetails(JdbcConnection.java:1231)
2022-04-22T07:39:54.9443391Z 	at io.debezium.jdbc.JdbcConnection.readSchema(JdbcConnection.java:1187)
2022-04-22T07:39:54.9444089Z 	at io.debezium.connector.postgresql.PostgresSnapshotChangeEventSource.readTableStructure(PostgresSnapshotChangeEventSource.java:184)
2022-04-22T07:39:54.9444998Z 	at io.debezium.connector.postgresql.PostgresSnapshotChangeEventSource.readTableStructure(PostgresSnapshotChangeEventSource.java:32)
2022-04-22T07:39:54.9445817Z 	at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:120)
2022-04-22T07:39:54.9446575Z 	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:69)
2022-04-22T07:39:54.9447272Z 	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:113)
2022-04-22T07:39:54.9448104Z 	at io.debezium.pipeline.ChangeEventSourceCoordinator$$Lambda$2135/0x00000007c25adc40.run(Unknown Source)
2022-04-22T07:39:54.9448493Z 	at java.lang.Thread.run(Thread.java:829)
2022-04-22T07:39:54.9448918Z 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
2022-04-22T07:39:54.9449531Z 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
2022-04-22T07:39:54.9450203Z 	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
2022-04-22T07:39:54.9451820Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.postgresql.jdbc.TimestampUtils.toOffsetDateTime(java.lang.String). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
```

**Comment by zbendhiba** [comment]
I wonder how this works in Quarkus platform BTW

**Comment by jamesnetherton** [comment]
We should align our debezium version with the platform and upgrade to `1.8.1.Final` if possible.

**Comment by zbendhiba** [comment]
The quarkus tracker: https://github.com/quarkusio/quarkus/issues/25190

The Debezium tracker: [DBZ-5060](https://issues.redhat.com/browse/DBZ-5060)
