### ISSUE TITLE
Unable to compile native image for Azure Storage Blob extension

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3820]
The [introduction](https://issues.apache.org/jira/browse/CAMEL-18099) of `azure-identity` into the Azure Storage Blob component poses some problems for native mode because of JNA usage.

Because I'm building on Linux, there are a lot of failures reported for libraries that do not exist because they relate to other platforms like Mac & Windows.

```
Error: Class initialization of com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary failed. Use the option --initialize-at-run-time=com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.UnsatisfiedLinkError: Unable to load library 'Security':
        Suppressed: java.lang.UnsatisfiedLinkError: libSecurity.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 58 more
```

```
Error: Class initialization of com.sun.jna.platform.win32.Crypt32 failed. Use the option --initialize-at-run-time=com.sun.jna.platform.win32.Crypt32 to explicitly request delayed initialization of this class.
Original exception that caused the problem: java.lang.UnsatisfiedLinkError: Unable to load library 'Crypt32':
        Suppressed: java.lang.UnsatisfiedLinkError: libCrypt32.so: cannot open shared object file: No such file or directory
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 55 more
```

**Comment by jamesnetherton** [comment]
Verified native compilation works on Windows too.
