### ISSUE TITLE
Unable to find a JDBC driver corresponding to the database kind 'postgresql', when camel-quarkus-quartz dependency added

### ISSUE THREAD

**Issue by ennishol** [apache/camel-quarkus#3823]
Originially created [Issue 25817](https://github.com/quarkusio/quarkus/issues/25817) in quarkus.

I have a simple quarkus project using mutiny and postgres, which works with Quarkus 2.7.5.Final. Starting from Quarkus 2.8.0.Final, build fails, when I add some camel route that needs quartz endpoint:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.9.1.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgresql' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.resolveDriver(AgroalProcessor.java:330)
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.getAggregatedConfigBuildItems(AgroalProcessor.java:276)
[ERROR] 	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:82)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
....

```

It looks like quartz extension requires the postgresql JDBC driver

How to Reproduce?
Unpack attached project [code-with-quarkus.tar.gz](https://github.com/apache/camel-quarkus/files/8804030/code-with-quarkus.tar.gz)

and run ./mvnw clean package
Remove <artifactId>camel-quarkus-quartz</artifactId> dependency to make build work

**Comment by jamesnetherton** [comment]
We probably need to make `quarkus-agroal` an optional dependency in `camel-quarkus-quartz` as it's only needed for clustering support.
