### ISSUE TITLE
[Quarkus 2.10.0] `ElasticsearchRestTest.testElasticsearchDeleteIndex` test failue

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3831]
Fails only in native mode. For some reason the index deletion is failing.

```
Suppressed: org.elasticsearch.client.ResponseException: method [DELETE], host [http://localhost:49242], URI [/f3f7bf94-96eb-4f8a-9de8-51df7368ffee?master_timeout=30s&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=true&ignore_throttled=false&timeout=30s], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [f3f7bf94-96eb-4f8a-9de8-51df7368ffee]","resource.type":"index_or_alias","resource.id":"f3f7bf94-96eb-4f8a-9de8-51df7368ffee","index_uuid":"_na_","index":"f3f7bf94-96eb-4f8a-9de8-51df7368ffee"}],"type":"index_not_found_exception","reason":"no such index [f3f7bf94-96eb-4f8a-9de8-51df7368ffee]","resource.type":"index_or_alias","resource.id":"f3f7bf94-96eb-4f8a-9de8-51df7368ffee","index_uuid":"_na_","index":"f3f7bf94-96eb-4f8a-9de8-51df7368ffee"},"status":404}
                at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:346)
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:312)
                at org.elasticsearch.client.RestClient.performRequest(RestClient.java:287)
                at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
                ... 51 more
```

**Comment by jamesnetherton** [comment]
I should have also mentioned that this only fails when the Quarkus ES client is used. When the client is created / managed by Camel it seems to work fine.
