### ISSUE TITLE
Cannot compile native image for Google PubSub integration tests

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3832]
Multiple failures like:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials). This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line
Trace: 
        at parsing com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:326)
Call path from entry point to com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(): 
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:305)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$$Lambda$1409/0x00000007c2aea440.createSingleChannel(Unknown Source)
        at com.google.api.gax.grpc.ChannelPool.refresh(ChannelPool.java:361)
        at com.google.api.gax.grpc.ChannelPool.refreshSafely(ChannelPool.java:335)
        at com.google.api.gax.grpc.ChannelPool$$Lambda$1411/0x00000007c2aeac40.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)
```

**Comment by aldettinger** [comment]
In the stack trace we see:
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: com.google.rpc.ErrorInfo. This error is reported at image build time because class com.google.cloud.pubsub.v1.StreamingSubscriberConnection is registered for linking at image build time by command line
Trace: 
	at parsing com.google.cloud.pubsub.v1.StreamingSubscriberConnection.getMetadataMapFromThrowable(StreamingSubscriberConnection.java:478)
Call path from entry point to com.google.cloud.pubsub.v1.StreamingSubscriberConnection.getMetadataMapFromThrowable(Throwable): 
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection.getMetadataMapFromThrowable(StreamingSubscriberConnection.java:474)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection.access$3200(StreamingSubscriberConnection.java:53)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$2.onFailure(StreamingSubscriberConnection.java:522)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1135)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)
```

This part of the issue might find its root cause in camel-quarkus-bom version management.

The class `com.google.rpc.ErrorInfo` should apparently come from `com.google.api.grpc::proto-google-common-protos`.
Camel-quarkus-bom manages this artifact to version 1.17.0 where the class is not present.
The original dependency management from camel would manage this artifact to version 2.18.3 where the class is present.

**Comment by jamesnetherton** [comment]
Nice investigation, thanks.

I wonder if this is fixed in the next Quarkus release by https://github.com/quarkusio/quarkus/commit/7edb055cccc0cd880364cbd90b947da93fb2fcf3.

**Comment by aldettinger** [comment]
I had a try on `quarkus-main`, the unresolved type issue is gone but others are still here:
```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials). This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line
Detailed message:
Trace: 
	at parsing com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:326)
Call path from entry point to com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(): 
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:305)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$$Lambda$1427/0x00000007c2b2e840.createSingleChannel(Unknown Source)
	at com.google.api.gax.grpc.ChannelPool.refresh(ChannelPool.java:361)
	at com.google.api.gax.grpc.ChannelPool.refreshSafely(ChannelPool.java:335)
	at com.google.api.gax.grpc.ChannelPool$$Lambda$1430/0x00000007c2b2e440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials). This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line
Detailed message:
Trace: 
	at parsing com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:326)
Call path from entry point to com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(): 
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:305)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$$Lambda$1427/0x00000007c2b2e840.createSingleChannel(Unknown Source)
	at com.google.api.gax.grpc.ChannelPool.refresh(ChannelPool.java:361)
	at com.google.api.gax.grpc.ChannelPool.refreshSafely(ChannelPool.java:335)
	at com.google.api.gax.grpc.ChannelPool$$Lambda$1430/0x00000007c2b2e440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:84)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:249)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:754)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials). This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line
Detailed message:
Trace: 
	at parsing com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:326)
Call path from entry point to com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(): 
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:305)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$$Lambda$1427/0x00000007c2b2e840.createSingleChannel(Unknown Source)
	at com.google.api.gax.grpc.ChannelPool.refresh(ChannelPool.java:361)
	at com.google.api.gax.grpc.ChannelPool.refreshSafely(ChannelPool.java:335)
	at com.google.api.gax.grpc.ChannelPool$$Lambda$1430/0x00000007c2b2e440.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_38d96cbc1a188a6051c29be1299afe681d67942e(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:751)
	... 6 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials). This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:288)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:244)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5216)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3358)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3318)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3163)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:236)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:586)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:166)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:301)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:290)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:111)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:393)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:552)
	at com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:631)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
---------------------------------------------------------------------------------------------------------
                8.8s (12.2% of total time) in 26 GCs | Peak RSS: 6.61GB | CPU load: 5.62
=========================================================================================================
Failed generating 'camel-quarkus-integration-test-google-pubsub-2.11.0-SNAPSHOT-runner' after 1m 10s.
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:03 min
[INFO] Finished at: 2022-06-28T14:07:08+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (quarkus-build) on project camel-quarkus-integration-test-google-pubsub: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:423)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:959)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

```

**Comment by jamesnetherton** [comment]
I finally see what's going on here...

`InstantiatingGrpcChannelProvider.createSingleChannel` makes reference to `GoogleDefaultChannelCredentials` which lives in `grpc-alts`. That dependency has `runtime` scope and is thus not on the classpath by default.

**Comment by aldettinger** [comment]
Ok, so not present for compilation. That make a more successful week, good job @jamesnetherton :+1:
