### ISSUE TITLE
[Quarkus 2.11.0] OptaPlanner native image build fails

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3899]
Compiler complains about various unresolved methods in `com.github.javaparser`. The problem is that the version of `com.github.javaparser:javaparser-*` used by Quarkus & OptaPlanner is out of sync. It was recently fixed in [DROOLS-7016](https://issues.redhat.com/browse/DROOLS-7016) but there is no new release with that change yet.

```
Error: Unsupported features in 2 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.github.javaparser.ast.Node.findAncestor(java.lang.Class). This error is reported at image build time because class org.drools.ancompiler.PropagatorCompilerHandler is registered for linking at image build time by command line
Trace: 
        at parsing org.drools.ancompiler.PropagatorCompilerHandler.getLastSwitchEntry(PropagatorCompilerHandler.java:282)
Call path from entry point to org.drools.ancompiler.PropagatorCompilerHandler.getLastSwitchEntry(): 
        at org.drools.ancompiler.PropagatorCompilerHandler.getLastSwitchEntry(PropagatorCompilerHandler.java:280)
        at org.drools.ancompiler.PropagatorCompilerHandler.endRangeIndexedAlphaNode(PropagatorCompilerHandler.java:275)
        at org.drools.ancompiler.ObjectTypeNodeParser.traverseRangeIndexedAlphaNodes(ObjectTypeNodeParser.java:187)
        at org.drools.ancompiler.ObjectTypeNodeParser.traversePropagator(ObjectTypeNodeParser.java:112)
        at org.drools.ancompiler.ObjectTypeNodeParser.accept(ObjectTypeNodeParser.java:95)
        at org.drools.ancompiler.ObjectTypeNodeCompiler.generateSource(ObjectTypeNodeCompiler.java:138)
        at org.drools.ancompiler.ObjectTypeNodeCompiler$$Lambda$1859/0x00000007c2420000.apply(Unknown Source)
        at sun.security.ec.ParametersMap$1.get(ParametersMap.java:78)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:169)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:299)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_System_getProperty_deeeaa72a006d330408a3b7d002c7533e108bc28(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.github.javaparser.ast.stmt.SwitchEntry.findAncestor(java.lang.Class). This error is reported at image build time because class org.drools.ancompiler.PropagatorCompilerHandler is registered for linking at image build time by command line
Trace: 
        at parsing org.drools.ancompiler.PropagatorCompilerHandler.extractMethod(PropagatorCompilerHandler.java:352)
Call path from entry point to org.drools.ancompiler.PropagatorCompilerHandler.extractMethod(SwitchEntry): 
        at org.drools.ancompiler.PropagatorCompilerHandler.extractMethod(PropagatorCompilerHandler.java:350)
        at org.drools.ancompiler.PropagatorCompilerHandler$$Lambda$2286/0x00000007c24a39c0.accept(Unknown Source)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
        at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:344)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
```

**Comment by ge0ffrey** [comment]
I believe OptaPlanner 8.24.1.Final fixes this because it is compatible with Drools 8.24.0.Beta.
