### ISSUE TITLE
Intermittent failure of Hazelcast integration test native image build

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3936]
Not sure what's going on here. It occurs sporadically. Sometimes everything is fine, other times it fails. 

```
========================================================================================================================
2022-07-21T11:26:21.4198845Z GraalVM Native Image: Generating 'camel-quarkus-integration-test-hazelcast-2.11.0-SNAPSHOT-runner' (executable)...
2022-07-21T11:26:21.4199324Z ========================================================================================================================
2022-07-21T11:26:24.8988156Z [1/7] Initializing...                                                                                   (14.0s @ 0.36GB)
2022-07-21T11:26:24.9001275Z  Version info: 'GraalVM 22.1.0 Java 17 CE'
2022-07-21T11:26:24.9009489Z  C compiler: gcc (redhat, x86_64, 8.5.0)
2022-07-21T11:26:24.9016525Z  Garbage collector: Serial GC
2022-07-21T11:26:24.9054739Z  3 user-provided feature(s)
2022-07-21T11:26:24.9061989Z   - io.quarkus.runner.Feature
2022-07-21T11:26:24.9066587Z   - io.quarkus.runtime.graal.DisableLoggingFeature
2022-07-21T11:26:24.9070109Z   - io.quarkus.runtime.graal.ResourcesFeature
2022-07-21T11:26:25.3571358Z com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.hazelcast.internal.util.ICMPHelper: trying to change RUN_TIME from feature io.quarkus.runner.Feature.beforeAnalysis with 'ICMPHelper.class' to RERUN Quarkus
2022-07-21T11:26:25.3574364Z 	at com.oracle.svm.core.util.UserError.abort(UserError.java:72)
2022-07-21T11:26:25.3578421Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:102)
2022-07-21T11:26:25.3580621Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:116)
2022-07-21T11:26:25.3583604Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:116)
2022-07-21T11:26:25.3586720Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:116)
2022-07-21T11:26:25.3589194Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:116)
2022-07-21T11:26:25.3592106Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:116)
2022-07-21T11:26:25.3594969Z 	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
2022-07-21T11:26:25.3598412Z 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:400)
2022-07-21T11:26:25.3600937Z 	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
2022-07-21T11:26:25.3603757Z 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:716)
2022-07-21T11:26:25.3606946Z 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:74)
2022-07-21T11:26:25.3609534Z 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:716)
2022-07-21T11:26:25.3612488Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
2022-07-21T11:26:25.3615223Z 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
2022-07-21T11:26:25.3618122Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
2022-07-21T11:26:25.3620775Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
2022-07-21T11:26:25.3623542Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
2022-07-21T11:26:25.3677710Z 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
2022-07-21T11:26:36.7593570Z 11:26:36,757 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
2022-07-21T11:26:36.7595351Z  --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2022-07-21T11:28:36.7041112Z [2/7] Performing analysis...  [**********]                                                             (130.9s @ 2.10GB)
2022-07-21T11:28:36.7164420Z   23,378 (92.96%) of 25,149 classes reachable
2022-07-21T11:28:36.7322943Z   33,736 (67.57%) of 49,929 fields reachable
2022-07-21T11:28:36.8201489Z  131,368 (61.55%) of 213,442 methods reachable
2022-07-21T11:28:36.8202092Z    2,590 classes, 5,666 fields, and 22,789 methods registered for reflection
2022-07-21T11:28:36.8202482Z       65 classes,    77 fields, and    55 methods registered for JNI access
2022-07-21T11:28:46.2608133Z [3/7] Building universe...                                                                               (9.4s @ 2.31GB)
2022-07-21T11:29:26.3818286Z [4/7] Parsing methods...      [******]                                                                  (40.1s @ 2.32GB)
2022-07-21T11:29:53.0863759Z [5/7] Inlining methods...     [*****]                                                                   (25.6s @ 2.94GB)
2022-07-21T11:32:16.3288220Z [6/7] Compiling methods...    [************]                                                           (143.2s @ 3.52GB)
2022-07-21T11:32:43.1076492Z /home/runner/work/_temp/5138418c-73f8-44cd-8734-c654b346db65.sh: line 29:  2413 Killed                  ./mvnw -V -ntp -Dhttp.keepAlive=false -e clean verify -Dformatter.skip -Dimpsort.skip -Denforcer.skip -Pnative,docker,ci --fail-at-end -pl integration-tests/avro-rpc,integration-tests/caffeine,integration-tests/git,integration-tests/google-storage,integration-tests/hazelcast,integration-tests/http,integration-tests/infinispan,integration-tests/jms-artemis-client,integration-tests/jsch,integration-tests/kafka,integration-tests/kafka-sasl,integration-tests/mllp
2022-07-21T11:32:48.3228997Z ##[error]Process completed with exit code 137.
```

**Comment by jamesnetherton** [comment]
Similar issues is happening occasionally for the PDF itests. Looks like the OOM killer is killing the native image build.
