### ISSUE TITLE
camel-quarkus-servicenow - 2.11.0 release - java.lang.ClassNotFoundException: javax.ws.rs.client.ClientRequestFilter

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#3946]
2022-07-28 15:43:43,874 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (Quarkus Main Thread) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime

2022-07-28 15:43:43,876 INFO  [org.apa.cam.mai.MainSupport] (Quarkus Main Thread) Apache Camel (Main) 3.18.0 is starting
2022-07-28 15:43:43,923 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread) Auto-configuration summary
2022-07-28 15:43:43,924 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.main.tracing=false
2022-07-28 15:43:43,924 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.main.name=CamelJBang
2022-07-28 15:43:43,925 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.main.sourceLocationEnabled=true
2022-07-28 15:43:43,925 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.health.exposureLevel=full
2022-07-28 15:43:43,926 INFO  [org.apa.cam.mai.BaseMainSupport] (Quarkus Main Thread)     [MicroProfilePropertiesSource] camel.health.enabled=true
2022-07-28 15:43:44,120 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread) Apache Camel 3.18.0 (CamelJBang) is starting
2022-07-28 15:43:44,134 INFO  [org.ecl.jet.uti.log] (Quarkus Main Thread) Logging initialized @4965ms to org.eclipse.jetty.util.log.Slf4jLog
2022-07-28 15:43:44,174 INFO  [org.apa.cam.sup.jss.SSLContextParameters] (Quarkus Main Thread) Available providers: SUN version 11.
2022-07-28 15:43:44,388 INFO  [org.apa.cam.com.sal.int.SalesforceSession] (Quarkus Main Thread) Login at Salesforce loginUrl: https://login.salesforce.com/services/oauth2/token
2022-07-28 15:43:45,074 INFO  [org.apa.cam.com.sal.int.SalesforceSession] (Quarkus Main Thread) Login successful
2022-07-28 15:43:45,074 WARN  [org.apa.cam.com.sal.SalesforceComponent] (Quarkus Main Thread) Missing property packages, getSObject* operations will NOT work without property rawPayload=true
2022-07-28 15:43:45,074 INFO  [org.apa.cam.sup.jss.SSLContextParameters] (Quarkus Main Thread) Available providers: SUN version 11.
2022-07-28 15:43:45,081 INFO  [org.apa.cam.com.sal.int.SalesforceSession] (Quarkus Main Thread) Login at Salesforce loginUrl: https://login.salesforce.com/services/oauth2/token
2022-07-28 15:43:45,429 INFO  [org.apa.cam.com.sal.int.SalesforceSession] (Quarkus Main Thread) Login successful
2022-07-28 15:43:45,429 WARN  [org.apa.cam.com.sal.SalesforceComponent] (Quarkus Main Thread) Missing property packages, getSObject* operations will NOT work without property rawPayload=true
2022-07-28 15:43:45,438 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread) Apache Camel 3.18.0 (CamelJBang) is shutting down
2022-07-28 15:43:45,443 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread) Routes stopped (stopped:6)
2022-07-28 15:43:45,443 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped MainRoute (kamelet://salesforce-source)
2022-07-28 15:43:45,443 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped Save Opportunity (direct://saveOpportunity)
2022-07-28 15:43:45,444 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped Prepare For ServiceNow (direct://prepareForServiceNow)
2022-07-28 15:43:45,444 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped Get SF Account Data (direct://getAccount)
2022-07-28 15:43:45,444 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped Update Salesforce (direct://updateSalesforce)
2022-07-28 15:43:45,445 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread)     Stopped salesforce-source-1 (local-salesforce-1://OpportunityTopic)
2022-07-28 15:43:45,884 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (Quarkus Main Thread) Apache Camel 3.18.0 (CamelJBang) shutdown in 446ms (uptime:1s)
2022-07-28 15:43:45,898 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.ClassNotFoundException: javax.ws.rs.client.ClientRequestFilter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:490)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:480)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:440)
        at org.apache.camel.component.servicenow.ServiceNowClient.<init>(ServiceNowClient.java:54)
        at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.<init>(AbstractServiceNowProcessor.java:53)
        at org.apache.camel.component.servicenow.releases.helsinki.HelsinkiServiceNowTableProcessor.<init>(HelsinkiServiceNowTableProcessor.java:38)
        at org.apache.camel.component.servicenow.releases.helsinki.HelsinkiServiceNowProducer.<init>(HelsinkiServiceNowProducer.java:44)
        at org.apache.camel.component.servicenow.ServiceNowRelease$3.get(ServiceNowRelease.java:38)
        at org.apache.camel.component.servicenow.ServiceNowEndpoint.createProducer(ServiceNowEndpoint.java:57)
        at org.apache.camel.support.DefaultEndpoint.createAsyncProducer(DefaultEndpoint.java:200)
        at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:242)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1664)
        at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:60)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.impl.engine.DefaultChannel.doStart(DefaultChannel.java:126)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:116)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:130)
        at org.apache.camel.processor.Pipeline.doStart(Pipeline.java:221)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.support.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:89)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
        at org.apache.camel.impl.engine.RouteService.startChildServices(RouteService.java:396)
        at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:193)
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:121)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doWarmUpRoutes(InternalRouteStartupManager.java:306)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:189)
        at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:3364)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:3033)
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2988)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2649)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by davsclaus** [comment]
It may be to the CXF splitup or something, because this component uses Apache CXF as dependency in camel-servicenow:

```
        <!-- CXF -->
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-rs-security-oauth2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-rs-extension-providers</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-rs-client</artifactId>
        </dependency>
```

In the camel core project, so maybe the extension is missing some dependency or something

**Comment by jamesnetherton** [comment]
Tests did not catch this because RestEasy is on the classpath.

**Comment by ppalaga** [comment]
A nice example to the collection of examples of "an ancillary extension unintentionally fixes the extension under test"!
