### ISSUE TITLE
[Quarkus 2.12.0] Azure Storage Blob native integration test failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#3964]
Native image fails to build with:

```
2022-08-08T06:30:35.2659793Z Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.microsoft.aad.msal4j.AbstractClientApplicationBase.getAuthenticationResultSupplier(com.microsoft.aad.msal4j.MsalRequest) 
2022-08-08T06:30:35.2663238Z Parsing context:
2022-08-08T06:30:35.2664157Z    at com.microsoft.aad.msal4j.AbstractClientApplicationBase.getAuthenticationResultSupplier(AbstractClientApplicationBase.java:140)
2022-08-08T06:30:35.2665540Z    at com.microsoft.aad.msal4j.AbstractClientApplicationBase.executeRequest(AbstractClientApplicationBase.java:117)
2022-08-08T06:30:35.2666449Z    at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenSilently(AbstractClientApplicationBase.java:78)
2022-08-08T06:30:35.2667490Z    at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithConfidentialClientCache$29(IdentityClient.java:803)
2022-08-08T06:30:35.2668416Z    at com.azure.identity.implementation.IdentityClient$$Lambda$3249/0x00000007c24ba248.get(Unknown Source)
2022-08-08T06:30:35.2669323Z    at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:217)
2022-08-08T06:30:35.2670116Z    at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:170)
2022-08-08T06:30:35.2670993Z    at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:303)
2022-08-08T06:30:35.2671834Z    at sun.security.action.GetPropertyAction.privilegedGetProperty(GetPropertyAction.java:106)
2022-08-08T06:30:35.2672602Z    at java.lang.reflect.AccessibleObject.printStackTraceWhenAccessFails(AccessibleObject.java:741)
2022-08-08T06:30:35.2673456Z    at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:676)
2022-08-08T06:30:35.2674192Z    at java.lang.reflect.Method.invoke(Method.java:560)
2022-08-08T06:30:35.2674922Z    at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:63)
2022-08-08T06:30:35.2675541Z    at com.oracle.svm.core.containers.Container.metrics(Container.java:44)
2022-08-08T06:30:35.2676278Z    at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
2022-08-08T06:30:35.2677017Z    at com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:166)
2022-08-08T06:30:35.2677660Z    at com.oracle.svm.core.heap.PhysicalMemory.doInitialize(PhysicalMemory.java:146)
2022-08-08T06:30:35.2678470Z    at com.oracle.svm.core.heap.PhysicalMemory.tryInitialize(PhysicalMemory.java:115)
2022-08-08T06:30:35.2679408Z    at com.oracle.svm.core.genscavenge.BasicCollectionPolicies$BasicPolicy.updateSizeParameters(BasicCollectionPolicies.java:93)
2022-08-08T06:30:35.2680428Z    at com.oracle.svm.core.genscavenge.BasicCollectionPolicies$BySpaceAndTime.updateSizeParameters(BasicCollectionPolicies.java:232)
2022-08-08T06:30:35.2681351Z    at com.oracle.svm.core.genscavenge.ThreadLocalAllocation.runSlowPathHooks(ThreadLocalAllocation.java:219)
2022-08-08T06:30:35.2682349Z    at com.oracle.svm.core.genscavenge.ThreadLocalAllocation.slowPathNewInstance(ThreadLocalAllocation.java:183)
2022-08-08T06:30:35.2682897Z 
2022-08-08T06:30:35.2683381Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
2022-08-08T06:30:35.2684561Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
2022-08-08T06:30:35.2685454Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
2022-08-08T06:30:35.2686534Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
2022-08-08T06:30:35.2687612Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultSpecialInvokeTypeFlow.java:61)
2022-08-08T06:30:35.2689523Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:558)
2022-08-08T06:30:35.2690221Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:635)
2022-08-08T06:30:35.2717005Z ------------------------------------------------------------------------------------------------------------------------
2022-08-08T06:30:35.2717963Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
2022-08-08T06:30:35.2718938Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
2022-08-08T06:30:35.2719749Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2022-08-08T06:30:35.2720325Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2022-08-08T06:30:35.2721004Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2022-08-08T06:30:35.2721684Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2022-08-08T06:30:35.2722238Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2022-08-08T06:30:35.2722934Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-08-08T06:30:35.2724562Z Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.<init>(com.microsoft.aad.msal4j.PublicClientApplication, com.microsoft.aad.msal4j.InteractiveRequest). This error is reported at image build time because class com.microsoft.aad.msal4j.AbstractClientApplicationBase is registered for linking at image build time by command line
2022-08-08T06:30:35.2726257Z 	at parsing com.microsoft.aad.msal4j.AbstractClientApplicationBase.getAuthenticationResultSupplier(AbstractClientApplicationBase.java:145)
2022-08-08T06:30:35.2727232Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2506)
2022-08-08T06:30:35.2728170Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
2022-08-08T06:30:35.2729316Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3367)
2022-08-08T06:30:35.2730107Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3319)
2022-08-08T06:30:35.2730899Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3164)
2022-08-08T06:30:35.2731673Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
2022-08-08T06:30:35.2732349Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
2022-08-08T06:30:35.2733136Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2022-08-08T06:30:35.2733980Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
2022-08-08T06:30:35.2734887Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2022-08-08T06:30:35.2735480Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
2022-08-08T06:30:35.2736178Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2022-08-08T06:30:35.2736859Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2022-08-08T06:30:35.2737683Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
2022-08-08T06:30:35.2738508Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
2022-08-08T06:30:35.2739481Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:168)
2022-08-08T06:30:35.2740490Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
2022-08-08T06:30:35.2741405Z 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
2022-08-08T06:30:35.2741941Z 	... 13 more
2022-08-08T06:30:35.2743186Z Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.<init>(com.microsoft.aad.msal4j.PublicClientApplication, com.microsoft.aad.msal4j.InteractiveRequest). This error is reported at image build time because class com.microsoft.aad.msal4j.AbstractClientApplicationBase is registered for linking at image build time by command line
2022-08-08T06:30:35.2744757Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:298)
2022-08-08T06:30:35.2745832Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:288)
2022-08-08T06:30:35.2746884Z 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:244)
2022-08-08T06:30:35.2747722Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1766)
2022-08-08T06:30:35.2748551Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeSpecial(BytecodeParser.java:1756)
2022-08-08T06:30:35.2749383Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5223)
2022-08-08T06:30:35.2750243Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3359)
2022-08-08T06:30:35.2750778Z 	... 28 more
```

**Comment by jamesnetherton** [comment]
This was fixed 592f260.
