### ISSUE TITLE
perf-regression: java.lang.NumberFormatException: For input string: "782,36"

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#4014]
On some machine, the hyperfoil-maven-plugin could report the throughput using the french locale. Thus generating the below stack trace:

```
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-18 16:08:09,549 INFO  [io.quarkus] (main) perf-regression 2.12.0-SNAPSHOT on JVM (powered by Quarkus 2.12.0.CR1) started in 0.828s. 
2022-08-18 16:08:09,607 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-18 16:08:09,607 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
java.lang.NumberFormatException: For input string: "782,36"
    at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
    at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.base/java.lang.Double.parseDouble(Double.java:543)
    at org.apache.camel.quarkus.performance.regression.PerfRegressionCommand.runPerfRegression(PerfRegressionCommand.java:117)
    at org.apache.camel.quarkus.performance.regression.PerfRegressionCommand.runPerfRegressionForCqVersion(PerfRegressionCommand.java:88)
    at org.apache.camel.quarkus.performance.regression.PerfRegressionCommand.run(PerfRegressionCommand.java:64)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
    at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:131)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
2022-08-18 16:08:56,070 INFO  [io.quarkus] (main) perf-regression stopped in 0.026s
    at org.zeroturnaround.exec.InvalidExitUtil.checkExit(InvalidExitUtil.java:27)
    at org.zeroturnaround.exec.WaitForProcess.call(WaitForProcess.java:114)
    at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1076)
    at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
    at org.apache.camel.quarkus.performance.regression.it.PerfRegressionIT.nominalShouldPrintReport(PerfRegressionIT.java:65)
    ... 70 more
```

It breaks the itests.

**Comment by aldettinger** [comment]
It can't be reproduced locally:

```
[main_upstream @ perf-regression]$ java -jar target/quarkus-app/quarkus-run.jar -d 1s 2.9.0
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-22 10:06:56,116 INFO  [io.quarkus] (main) perf-regression 2.12.0-SNAPSHOT on JVM (powered by Quarkus 2.12.0.CR1) started in 0.311s. 
2022-08-22 10:06:56,140 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-22 10:06:56,140 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
 Camel Quarkus Throughput Performance Increase Compared to Previous Version 
 Camel Quarkus version  |  Duration  |  JVM req/s [%increase]   |  Status  |
----------------------------------------------------------------------------
                 2.9.0  |        1s  |  1078.39 req/s [+0.00%]  |      OK  |
2022-08-22 10:07:14,078 INFO  [io.quarkus] (main) perf-regression stopped in 0.020s
[main_upstream @ perf-regression]$ java -Duser.country=FR -Duser.language=fr -jar target/quarkus-app/quarkus-run.jar -d 1s 2.9.0
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-08-22 10:07:31,137 INFO  [io.quarkus] (main) perf-regression 2.12.0-SNAPSHOT on JVM (powered by Quarkus 2.12.0.CR1) started in 0.316s. 
2022-08-22 10:07:31,153 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-22 10:07:31,153 INFO  [io.quarkus] (main) Installed features: [cdi, picocli]
Camel Quarkus Throughput Performance Increase Compared to Previous Version 
 Camel Quarkus version  |  Duration  |  JVM req/s [%increase]  |  Status  |
---------------------------------------------------------------------------
                 2.9.0  |        1s  |  866,29 req/s [+0,00%]  |      OK  |
2022-08-22 10:07:50,429 INFO  [io.quarkus] (main) perf-regression stopped in 0.028s
```

The best candidate explanation would be that on some environments, the `java` and `mvnw` default locale might not be the same.
