### ISSUE TITLE
master: fix itests harness in native mode

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#4050]
The integration-test reports:

```
[INFO] Running org.apache.camel.quarkus.component.master.it.MasterIT
Aug 25, 2022 5:11:24 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
======================================================================================
  native.image.path was not set, making a guess for the correct path of native image
  guessed path: /home/agallice/dev/projects/camel-quarkus-upstream/integration-tests/master/target/camel-quarkus-integration-test-master-2.12.0-SNAPSHOT-runner
======================================================================================
Executing "/home/agallice/dev/projects/camel-quarkus-upstream/integration-tests/master/target/camel-quarkus-integration-test-master-2.12.0-SNAPSHOT-runner -Dquarkus.http.port=43433 -Dquarkus.http.ssl-port=45709 -Dtest.url=http://localhost:43433 -Dquarkus.log.file.path=/home/agallice/dev/projects/camel-quarkus-upstream/integration-tests/master/target/quarkus.log -Dquarkus.log.file.enable=true"
2022-08-25 17:11:24,228 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2022-08-25 17:11:24,229 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 3.18.1 is starting
2022-08-25 17:11:24,238 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.18.1 (camel-1) is starting
2022-08-25 17:11:24,238 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:1)
2022-08-25 17:11:24,238 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started leader (master:ns:timer:test)
2022-08-25 17:11:24,239 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.18.1 (camel-1) started in 3ms (build:0ms init:2ms start:1ms)
2022-08-25 17:11:24,242 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 2.12.0-SNAPSHOT native (powered by Quarkus 2.12.0.Final) started in 0.045s. Listening on: http://0.0.0.0:43433
2022-08-25 17:11:24,242 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-25 17:11:24,242 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-timer, cdi, resteasy, smallrye-context-propagation, smallrye-health, vertx]
2022-08-25 17:11:24,944 INFO  [org.apa.cam.qua.tes.AvailablePortFinder] (main) org.apache.camel.quarkus.test.support.process.QuarkusProcessExecutor reserved port 34288
2022-08-25 17:11:24,993 INFO  [org.apa.cam.qua.tes.AvailablePortFinder] (main) org.apache.camel.quarkus.test.support.process.QuarkusProcessExecutor reserved port 45594
Aug 25, 2022 5:11:24 PM org.apache.camel.quarkus.test.support.process.QuarkusProcessExecutor <init>
INFO: Executing process: /home/agallice/dev/projects/camel-quarkus-upstream/integration-tests/master/target/camel-quarkus-integration-test-master-2.12.0-SNAPSHOT-runner -Dapplication.id=follower -Dquarkus.http.port=34288 -Dquarkus.http.ssl-port=45594
2022-08-25 17:11:25,056 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2022-08-25 17:11:25,057 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 3.18.1 is starting
2022-08-25 17:11:25,066 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.18.1 (camel-1) is starting
2022-08-25 17:11:25,067 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:1)
2022-08-25 17:11:25,067 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started leader (master:ns:timer:test)
2022-08-25 17:11:25,067 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.18.1 (camel-1) started in 1ms (build:0ms init:1ms start:0ms)
2022-08-25 17:11:25,070 INFO  [io.quarkus] (main) camel-quarkus-integration-test-master 2.12.0-SNAPSHOT native (powered by Quarkus 2.12.0.Final) started in 0.059s. Listening on: http://0.0.0.0:34288
2022-08-25 17:11:25,070 INFO  [io.quarkus] (main) Profile prod activated. 
2022-08-25 17:11:25,070 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-log, camel-master, camel-microprofile-health, camel-timer, cdi, resteasy, smallrye-context-propagation, smallrye-health, vertx]
2022-08-25 17:11:25,239 INFO  [org.apa.cam.com.fil.clu.FileLockClusterView] (Camel (camel-1) thread #1 - FileLockClusterService-null) Lock on file target/cluster/ns acquired (lock=sun.nio.ch.FileLockImpl[0:1 exclusive valid])
2022-08-25 17:11:25,240 INFO  [org.apa.cam.com.mas.MasterConsumer] (Camel (camel-1) thread #1 - FileLockClusterService-null) Leadership taken. Consumer started: timer://test?period=100
2022-08-25 17:11:26,240 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,340 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,440 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,541 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,640 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,740 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,840 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
2022-08-25 17:11:26,941 INFO  [leader] (Camel (camel-1) thread #2 - timer://test) Application leader is writing into file
leaderFileContent = leader
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.568 s <<< FAILURE! - in org.apache.camel.quarkus.component.master.it.MasterIT
[ERROR] testFailover  Time elapsed: 2.644 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: an empty string
     but: was "leader"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.apache.camel.quarkus.component.master.it.MasterTest.testFailover(MasterTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:891)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MasterIT>MasterTest.testFailover:57 
Expected: an empty string
     but: was "leader"
```

~~And a manual execution shows that it works in JVM mode but not in native mode.~~
Had other manual tests and it worked fine. Worst case, this itest will soon unleash a flaky personality.

**Comment by aldettinger** [comment]
Fixed in https://github.com/apache/camel-quarkus/commit/e6c2c9f3eb6d54c0e822686910c05d46547db5c4
