### ISSUE TITLE
[Quarkus 2.13.0] JTA integration test fails due to undiscoverable `DataSource`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4063]
Not sure what's changed, but the JTA integration test fails due to:

```
2022-09-01 08:58:13,084 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route route11 at: >>> Transacted <<< in route: Route(route11)[From[direct:sqltx] -> [OnException[[java.lang... because of Failed to resolve endpoint: sql://insert%20into%20example(message,%20origin)%20values%20(:%23message,%20'sqltx') due to: DataSource must be configured
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:240)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:74)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:862)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:750)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2947)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2630)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2649)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
```

In Quarkus 2.12.x we see:

```
Autowired property: dataSource on component: sql as exactly one instance of type: javax.sql.DataSource (io.agroal.pool.DataSource) found in the registry
```

That log line is not present when the failure occurs. Seems attempting to find instances of `DataSource` returns nothing, hence autowiring does not occur.

Could be related to usage of a named `DataSource`. Things seem to work ok if the default `DataSource` is used.

**Comment by jamesnetherton** [comment]
I think this change explains why the bean lookup fails:

https://github.com/quarkusio/quarkus/commit/60f62f7283a62fe28d9282be78cec97ff2866120

To resolve a named `DataSource` bean, we'd now need to provide the appropriate `Qualifier`. 

```
Arc.container()
    .beanManager()
    .getBeans(DataSource.class, new io.quarkus.agroal.DataSource.DataSourceLiteral("camel-ds"))
```

Since we don't want `camel-quarkus-core` to depend on Agroal, we need some way for extensions to register a means of resolving the relevant `Qualifier` for the corresponding bean type.

**Comment by zhfeng** [comment]
So the workaround is to use the default datasource? Hmm, good catch for the quarkus changes and it said `this behavior is defined by the spec`. I'm not sure how we can register the bean without dependes on Agroal?

**Comment by jamesnetherton** [comment]
> So the workaround is to use the default datasource?

Yeah or to explicitly define on the component / endpoint config which DS should be used.

 > I'm not sure how we can register the bean without dependeds on Agroal?

It's more about how to resolve the bean than registering it.

I quickly hacked up something that could restore autowiring for named `DataSource`:

https://github.com/jamesnetherton/camel-quarkus/commit/d090499844e6df9dffedf1a0a6345fdf5e2a6a0e

It needs some refinement, but it could be made a common thing for the `jdbc` & `sql` extensions. And opens up a way to do similar things for resolving other bean types if needed.
