### ISSUE TITLE
kamelet-chucknorris example project tests are failing

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4111]
```
2022-09-20 10:05:01,419 WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (camel-1) thread #1 - timer://chuck) Error processing exchange. Exchange[8995EB8BDA80162-0000000000000000]. Caused by: [org.apache.camel.http.base.HttpOperationFailedException - HTTP operation failed invoking http://api.icndb.com/jokes/random with statusCode: 500]: org.apache.camel.http.base.HttpOperationFailedException: HTTP operation failed invoking http://api.icndb.com/jokes/random with statusCode: 500
	at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:422)
	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:294)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:189)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:182)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:399)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:210)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
	at java.util.TimerThread.mainLoop(Timer.java:566)
	at java.util.TimerThread.run(Timer.java:516)
```

**Comment by jamesnetherton** [comment]
I'll disable the tests for now. I looked at using a different service, but the 'jokes' being returned were somewhat NSFW, hence I chose not to use it.

**Comment by zbendhiba** [comment]
Maybe use a mock service ?
