### ISSUE TITLE
[Quarkus 2.14.0] PgeventTest application fails to start

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4114]
There's an exception being thrown from the Agroal extension:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:237)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:262)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:681)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:729)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        ... 36 more
Caused by: java.lang.IllegalArgumentException: Annotation is not a registered qualifier: interface io.quarkus.agroal.runtime.JdbcDriver
        at io.quarkus.arc.impl.Qualifiers.verifyQualifier(Qualifiers.java:151)
        at io.quarkus.arc.impl.Qualifiers.verify(Qualifiers.java:58)
        at io.quarkus.arc.impl.ArcContainerImpl.getBean(ArcContainerImpl.java:450)
        at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:413)
        at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:206)
        at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:207)
        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:125)
        at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:122)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:122)
        at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:118)
        at io.quarkus.agroal.runtime.AgroalRecorder.agroalDataSourceSupplier(AgroalRecorder.java:23)
        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans109901991.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.AgroalProcessor$generateDataSourceBeans109901991.deploy(Unknown Source)
        ... 52 more
```

**Comment by jamesnetherton** [comment]
Not sure what has changed to cause this. Maybe @mkouba knows?

The test is pretty simple:

**Postgres DataSource config:**

https://github.com/apache/camel-quarkus/blob/main/integration-tests/pgevent/src/main/resources/application.properties

**Camel routes that look up the DataSource by name:**

https://github.com/apache/camel-quarkus/blob/main/integration-tests/pgevent/src/main/java/org/apache/camel/quarkus/component/pgevent/it/PgeventRoutes.java

**Comment by mkouba** [comment]
Yes, we added a few more checks to comply with the spec and it seems that the [JdbcDriver](https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/JdbcDriver.java) is not registered as a CDI qualifier but used in the programmatic look here: https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/runtime/src/main/java/io/quarkus/agroal/runtime/DataSources.java#L207.

It's possible that there is no test for this qualifier at all.

CC @gsmet

**Comment by mkouba** [comment]
It should be enough to produce an `AdditionalBeanBuildItem` for the `JdbcDriver` qualifier [somewhere here](https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L193-L222). Also these lines are completely useless: https://github.com/quarkusio/quarkus/blob/main/extensions/agroal/deployment/src/main/java/io/quarkus/agroal/deployment/AgroalProcessor.java#L212-L213 because the `AgroalPoolInterceptor` is just an interface.

**Comment by jamesnetherton** [comment]
I verified that https://github.com/quarkusio/quarkus/pull/28121 fixes the problem, so I'll close this one.
