### ISSUE TITLE
Native mode tests for serialization are failing

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4148]
Seems any tests for serialization in native mode are failing with an exception being thrown similar to this one:

```
SerializationConstructorAccessor class not found for declaringClass: java.util.Collections$EmptyList (targetConstructorClass: 
java.util.AbstractList). Usually adding java.util.Collections$EmptyList to serialization-config.json fixes the problem.]: ```
```

`Collections.EMPTY_LIST` is listed in the core set of classes bound for native serialization support.

https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/deployment/src/main/java/org/apache/camel/quarkus/core/deployment/CamelSerializationProcessor.java#L47

```
2022-09-29 13:27:27,535 WARN  [org.apa.cam.com.jms.EndpointMessageListener] (Camel (camel-1) thread #3 - JmsConsumer[transferException]) Execution of JMS message listener failed. Caused by: [com.oracle.svm.core.jdk.UnsupportedFeatureError - SerializationConstructorAccessor class not found for declaringClass: java.util.Collections$EmptyList (targetConstructorClass: java.util.AbstractList). Usually adding java.util.Collections$EmptyList to serialization-config.json fixes the problem.]: com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: java.util.Collections$EmptyList (targetConstructorClass: java.util.AbstractList). Usually adding java.util.Collections$EmptyList to serialization-config.json fixes the problem.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at com.oracle.svm.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:143)
        at jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
        at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:455)
        at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1443)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:412)
        at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:384)
        at java.security.AccessController.executePrivileged(AccessController.java:169)
        at java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:384)
        at java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:110)
        at java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:107)
        at java.io.ClassCache$1.computeValue(ClassCache.java:73)
        at java.io.ClassCache$1.computeValue(ClassCache.java:70)
        at java.lang.ClassValue.get(JavaLangSubstitutions.java:588)
        at java.io.ClassCache.get(ClassCache.java:84)
        at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:363)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1137)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:443)
        at java.lang.Throwable.writeObject(Throwable.java:1014)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1070)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1516)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
        at org.apache.activemq.artemis.jms.client.ActiveMQObjectMessage.setObject(ActiveMQObjectMessage.java:118)
        at org.apache.activemq.artemis.jms.client.ActiveMQSession.createObjectMessage(ActiveMQSession.java:216)
        at org.apache.camel.component.jms.JmsBinding.createJmsMessage(JmsBinding.java:516)
        at org.apache.camel.component.jms.JmsBinding.makeJmsMessage(JmsBinding.java:344)
        at org.apache.camel.component.jms.EndpointMessageListener.lambda$sendReply$0(EndpointMessageListener.java:401)
        at org.apache.camel.component.jms.JmsConfiguration$CamelJmsTemplate.doSendToDestination(JmsConfiguration.java:616)
        at org.apache.camel.component.jms.JmsConfiguration$CamelJmsTemplate.lambda$send$3(JmsConfiguration.java:602)
        at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:504)
        at org.apache.camel.component.jms.JmsConfiguration$CamelJmsTemplate.send(JmsConfiguration.java:602)
        at org.apache.camel.component.jms.EndpointMessageListener.sendReply(EndpointMessageListener.java:400)
        at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:233)
        at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:136)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:331)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:270)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120)
```

**Comment by jamesnetherton** [comment]
@zakkak any ideas on recent changes that may have had an impact on Serialization in native mode? I see some commits related to native that got backported to 2.13.1.

**Comment by zakkak** [comment]
> @zakkak any ideas on recent changes that may have had an impact on Serialization in native mode? I see some commits related to native that got backported to 2.13.1.

Can you please be more specific? Which commits are you referring to? AFAIK most (if not all) of these commits change behavior only when using GraalVM / Mandrel 22.3 which is not yet released. So they should not affect your tests at this point.

Do I understand correctly that things are working with 2.13.0 but not with 2.13.1 using the same GraalVM / Mandrel version?

**Comment by zakkak** [comment]
OK, could you please provide the steps to reproduce this issue (ideally with the option to use local quarkus builds, as well i.e. `999-SNAPSHOT`) so that I can have a closer look?

**Comment by jamesnetherton** [comment]
@zakkak try this branch on my fork. It's set up to point at Quarkus `999-SNAPSHOT`:

```
git clone git@github.com:jamesnetherton/camel-quarkus.git -b quarkus-main
./mvnw clean install -Dquickly -T1C
cd integration-tests/http
../../mvnw clean verify -Dnative -Ddocker
```

You can omit the `-Ddocker` part if you have GraalVM 22.2.0 installed locally.

**Comment by zakkak** [comment]
I confirm that https://github.com/quarkusio/quarkus/commit/e3639143fbe8eaa86ce15ef7c438fc3d2b64d0be#diff-7d1388bbdd07a9362ef261153d5cc4cbccd0f5f5f95446ad3f647f9cd38768bcL471-R469 is the one causing the regression here but the issue seems to originate from https://github.com/quarkusio/gizmo/pull/105/commits/091fe32bf498650cc0278f9f51e96bdb901ef18b.

@Sanne can you please have a look?

**Comment by Sanne** [comment]
@zakkak coul you elaborate on "not getting registered properly" ? What's happening?

**Comment by zakkak** [comment]
> @zakkak coul you elaborate on "not getting registered properly" ? What's happening?

After looking a bit more into it, the issue is the following.

When the class name starts with `java.` gizmo gets the class directly (not through reflection):

```java
    private static void registerClass35(org.graalvm.nativeimage.hosted.Feature.BeforeAnalysisAccess var0) {
        try {
            Collections.EmptyList.class.getDeclaredConstructors();
            Collections.EmptyList.class.getDeclaredMethods();
            Collections.EmptyList.class.getDeclaredFields();
            Class[] var1 = new Class[]{Collections.EmptyList.class};
            RuntimeReflection.register(var1);
            registerSerializationForClass(Collections.EmptyList.class);
        } catch (Throwable var2) {
        }

    } 
```

However, `Collections.EmptyList` is `private`, as a result this is not going to work. Note here that we don't see any error due to https://github.com/quarkusio/quarkus/issues/26162. The actual exception is:

```
java.lang.IllegalAccessError: failed to access class java.util.Collections$EmptyList from class io.quarkus.runner.Feature (java.util.Collections$EmptyList is in module java.base of loader 'bootstrap'; io.quarkus.runner.Feature is in unnamed module of loader com.oracle.svm.hosted.NativeImageClassLoaderSupport$ClassPathClassLoader @6d4b1c02)
	at io.quarkus.runner.Feature.registerClass35(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:722)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

In contrast when registering a class that is not under `java.` the register method uses `Class.forName` which works for private methods as well and looks like this:
```java
    private static void registerClass0(org.graalvm.nativeimage.hosted.Feature.BeforeAnalysisAccess var0) {
        try {
            ClassLoader var1 = Thread.currentThread().getContextClassLoader();
            Class var2 = Class.forName("org.apache.commons.pool2.impl.DefaultEvictionPolicy", (boolean)0, var1);
            Constructor[] var4 = var2.getDeclaredConstructors();
            var2.getDeclaredMethods();
            var2.getDeclaredFields();
            Class[] var3 = new Class[]{var2};
            RuntimeReflection.register(var3);
            RuntimeReflection.register((Executable[])var4);
        } catch (Throwable var5) {
        }

    }
```

So I think that we either need to drop the `java.` prefix optimization from gizmo or start checking if the class is private or not as well.

**Comment by zakkak** [comment]
> So rather than reverting I think gizmo should be fixed to handle private types correctly whatever the choice of classloader.

+1

I created https://github.com/quarkusio/quarkus/issues/28431 to track this in Quarkus as well, since it doesn't affect only camel-quarkus.

**Comment by geoand** [comment]
Could https://github.com/quarkusio/quarkus/issues/12486#issuecomment-1271114658 also be related?

**Comment by Sanne** [comment]
@geoand yes: it's a non-public class, and in package `java.` : same issue.

**Comment by geoand** [comment]
Thanks for confirming @Sanne
