### ISSUE TITLE
XStream native integration test failure

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4149]
In native mode with Quarkus 2.14.0-SNAPSHOT and 2.13.1 there's an NPE being thrown due to a failure to load a class in the XStream constructor.

```
Caused by: java.lang.NullPointerException
        at com.thoughtworks.xstream.mapper.ClassAliasingMapper.addClassAlias(ClassAliasingMapper.java:37)
        at com.thoughtworks.xstream.XStream.alias(XStream.java:1443)
        at com.thoughtworks.xstream.XStream.setupAliases(XStream.java:845)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:546)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:476)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:450)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:403)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:351)
        at org.apache.camel.dataformat.xstream.AbstractXStreamWrapper.createXStream(AbstractXStreamWrapper.java:121)
        at org.apache.camel.dataformat.xstream.JsonDataFormat.createXStream(JsonDataFormat.java:88)
        at org.apache.camel.dataformat.xstream.AbstractXStreamWrapper.doStart(AbstractXStreamWrapper.java:378)
        at org.apache.camel.dataformat.xstream.JsonDataFormat.doStart(JsonDataFormat.java:121)
```

It's a bit weird because the point where it fails links to the loading of class `java.time.Clock$FixedClock`:

https://github.com/x-stream/xstream/blob/XSTREAM_1_4_19/xstream/src/java/com/thoughtworks/xstream/XStream.java#L845

But we have this registered for constructor reflection here:

https://github.com/apache/camel-quarkus/blob/main/extensions-support/xstream/deployment/src/main/java/org/apache/camel/quarkus/support/xstream/deployment/XStreamSupportProcessor.java#L165

**Comment by jamesnetherton** [comment]
@zakkak any ideas on this one? Maybe related to something that changed in 2.13.1?

**Comment by zakkak** [comment]
@jamesnetherton is this thrown at build time or at run time?

**Comment by jamesnetherton** [comment]
@zakkak try this branch on my fork. It's set up to point at Quarkus `999-SNAPSHOT`:

```
git clone git@github.com:jamesnetherton/camel-quarkus.git -b quarkus-main
./mvnw clean install -Dquickly -T1C
cd integration-tests/xstream
../../mvnw clean verify -Dnative -Ddocker
```

You can omit the `-Ddocker` part if you have GraalVM 22.2.0 installed locally.

**Comment by zakkak** [comment]
Looks like the same issue described in https://github.com/apache/camel-quarkus/issues/4148#issuecomment-1269767157
