### ISSUE TITLE
xslt extension not building in native mode

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#419]
```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl$TransletClassLoader.defineClass(TemplatesImpl.java:185)
Call path from entry point to com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl$TransletClassLoader.defineClass(byte[]): 
	at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl$TransletClassLoader.defineClass(TemplatesImpl.java:185)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.defineTransletClasses(TemplatesImpl.java:414)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.getTransletInstance(TemplatesImpl.java:451)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl.newTransformer(TemplatesImpl.java:486)
	at org.apache.camel.component.xslt.XsltBuilder.createTransformer(XsltBuilder.java:449)
	at org.apache.camel.component.xslt.XsltBuilder.getTransformer(XsltBuilder.java:443)
	at org.apache.camel.component.xslt.XsltBuilder.process(XsltBuilder.java:103)
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:64)
	at org.apache.camel.processor.Resequencer.processExchange(Resequencer.java:302)
	at org.apache.camel.processor.Resequencer$BatchSender.sendExchanges(Resequencer.java:530)
	at org.apache.camel.processor.Resequencer$BatchSender.run(Resequencer.java:455)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

```

**Comment by lburgazzoli** [comment]
working on a sustitution

**Comment by davsclaus** [comment]
Created a ticket to make the camel-xslt simpler
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-14176
