### ISSUE TITLE
ClassNotFoundException: org.graalvm.nativeimage.ImageInfo on runnable jar when building the native application

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4218]
I believe this change in Quarkus 2.14.0.CR1 caused some issues for integration tests where we run the JVM tests in the `integration-test` phase. E.g tests like `camel-quarkus-integration-test-main-unknown-args-ignore` & `camel-quarkus-integration-test-main-command-mode`.

https://github.com/quarkusio/quarkus/commit/2ae0c0ee442d692706df1104c412276fe5573e8b

When the Quarkus runner jar is executed from `QuarkusProcessExecutor` we get:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:68)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 17 more
Caused by: java.lang.NoClassDefFoundError: org/graalvm/nativeimage/ImageInfo
        at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLoggingForImageBuild(LoggingSetupRecorder.java:494)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingStaticInit2062061316.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingStaticInit2062061316.deploy(Unknown Source)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: org.graalvm.nativeimage.ImageInfo
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        ... 21 more
```

**Comment by jamesnetherton** [comment]
Proposed a workaround for testing in https://github.com/apache/camel-quarkus/pull/4427 to just run the native runner.

Seems the assumption made by https://github.com/quarkusio/quarkus/commit/2ae0c0ee442d692706df1104c412276fe5573e8b, is that if you build a native application, you're not interested in executing the runnable JAR (which seems fair).

**Comment by Karm** [comment]
@ldrozdo @jamesnetherton It is closed Won't fix on the Quarkus side as per: https://github.com/quarkusio/quarkus/issues/30998#issuecomment-1422504405

You need a one maven build for a JVM mode and a separate Maven build for a Native mode.

**Comment by apupier** [comment]
Given that it is set as won't fix on Quarkus side, I guess we have to close as won't fix too on our side, what do you think @jamesnetherton ?

**Comment by jamesnetherton** [comment]
The issue actually seems fixed. But I don't think it's worth reverting things to the previous state before https://github.com/apache/camel-quarkus/pull/4427.

We test the JAR and native app runners in the CI build. So I think we can close this.
