### ISSUE TITLE
Kafka oauth example failing in platform

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#4238]
The kafka oauth integration tests example is failing in the quarkus platform, as it uses the artifact in maven central and doesn't find the generated file at build time `target/hosts` 

Getting the error :
```
2022-10-25T14:29:13.2788925Z Caused by: org.apache.maven.wagon.TransferFailedException: transfer failed for https://maven-central.storage-download.googleapis.com/maven2/org/apache/camel/quarkus/camel-quarkus-kafka-deployment/2.13.0/camel-quarkus-kafka-deployment-2.13.0.jar
2022-10-25T14:29:13.2790000Z 	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1250)
2022-10-25T14:29:13.2790764Z 	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1140)
2022-10-25T14:29:13.2791765Z 	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
2022-10-25T14:29:13.2792531Z 	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
2022-10-25T14:29:13.2793000Z 	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
2022-10-25T14:29:13.2793541Z 	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:546)
2022-10-25T14:29:13.2794166Z 	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:430)
2022-10-25T14:29:13.2794771Z 	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:407)
2022-10-25T14:29:13.2795446Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
2022-10-25T14:29:13.2796176Z 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
2022-10-25T14:29:13.2796633Z 	... 66 more
2022-10-25T14:29:13.2797298Z Caused by: java.net.UnknownHostException: Unable to resolve host maven-central.storage-download.googleapis.com as hosts file target/hosts not found 
```

**Comment by jamesnetherton** [comment]
Original issue cause seems to be a transitive network issue so I'll close this.
