### ISSUE TITLE
[Camel 3.20] CamelContext must be specified on: KeyStoreParameters

### ISSUE THREAD

**Issue by zhfeng** [apache/camel-quarkus#4248]
It is failing with http and netty integration tests.

```
Caused by: java.lang.IllegalArgumentException: CamelContext must be specified on: KeyStoreParameters[type=null, *** provider=null, resource=/ssl/keystore.p12]
	at org.apache.camel.util.ObjectHelper.notNull(ObjectHelper.java:176)
	at org.apache.camel.support.jsse.JsseParameters.resolveResource(JsseParameters.java:116)
	at org.apache.camel.support.jsse.KeyStoreParameters.createKeyStore(KeyStoreParameters.java:192)
	at org.apache.camel.support.jsse.KeyManagersParameters.createKeyManagers(KeyManagersParameters.java:102)
	at org.apache.camel.support.jsse.SSLContextParameters.createSSLContext(SSLContextParameters.java:263)
	at org.apache.camel.component.netty.DefaultServerInitializerFactory.createSSLContext(DefaultServerInitializerFactory.java:133)
	at org.apache.camel.component.netty.DefaultServerInitializerFactory.<init>(DefaultServerInitializerFactory.java:60)
```

https://github.com/apache/camel-quarkus/actions/runs/3390275310/jobs/5635151759

**Comment by zhfeng** [comment]
It seem be related to https://issues.apache.org/jira/browse/CAMEL-18680. I check with fix in https://github.com/apache/camel/commit/ad774bf6f0c61ffcfbe875a1917ef3e056d30237 and it works.

**Comment by zhfeng** [comment]
@JiriOndrusek I think you are taking care of this issue?

**Comment by JiriOndrusek** [comment]
Yes, it is already fixed in https://github.com/apache/camel/pull/8655

**Comment by JiriOndrusek** [comment]
It should be validated by today's night build. Camel snapshots with the fix are currently building, see https://ci-builds.apache.org/job/Camel/job/Camel%20Daily%20Snapshot%20Deploy/job/main/

**Comment by zhfeng** [comment]
Thanks @JiriOndrusek and let's wait for our night build.
