### ISSUE TITLE
CXF endpoint configured via URI options doesn't work with PAYLOAD mode

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#4282]
When i change dataFormat=PAYLOAD in https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/cxf-soap/cxf-soap-client/src/main/java/org/apache/camel/quarkus/component/cxf/soap/client/it/CxfSoapClientRoutes.java#L48 it throws

```
Caused by: org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: int[] to the required type: org.apache.camel.component.cxf.common.CxfPayload
        at org.apache.camel.impl.converter.CoreTypeConverterRegistry.mandatoryConvertTo(CoreTypeConverterRegistry.java:274)
        at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:123)
```

The problem is, that it should work the same as the https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/cxf-soap/cxf-soap-client/src/main/java/org/apache/camel/quarkus/component/cxf/soap/client/it/CxfSoapClientRoutes.java#L45 because it is configured with the same options, only via bean.

**Comment by ffang** [comment]
Hi @llowinge ,

Firstly, by defaulut there is no such type converter which can change type from int[] to the required type: org.apache.camel.component.cxf.common.CxfPayload. So the exception here is expected.

And for the cxf:bean:soapClientEndpoint, actually the POJO dataFormat is used, it's from the last part of your route
```
from("direct:operandsAdd")
                .setHeader(CxfConstants.OPERATION_NAME).constant("addOperands")
                .to("cxf:bean:soapClientEndpoint?dataFormat=POJO");
```
So here the same bean name soapClientEndpoint is reused, which means the POJO data format will be set to bean with name soapClientEndpoint, which is the same instance of CxfEndpoint from where you define soapClientEndpoint
```
@Produces
    @ApplicationScoped
    @Named
    CxfEndpoint soapClientEndpoint() {
        final CxfEndpoint result = new CxfEndpoint();
        result.setServiceClass(CalculatorService.class);
        result.setAddress(calculatorServiceAddress());
        result.setWsdlURL(calculatorServiceWsdlUrl());
        result.getFeatures().add(loggingFeature);
        return result;
    }
```
So whenever bean soapClientEndpoint is used during test, it will use POJO dataFormat, that's why https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/cxf-soap/cxf-soap-client/src/main/java/org/apache/camel/quarkus/component/cxf/soap/client/it/CxfSoapClientRoutes.java#L45 passed as it uses POJO dataFormat.

Freeman

**Comment by llowinge** [comment]
@ffang @ppalaga Isn't it bug when i declare `?dataFormat=PAYLOAD` but `POJO` dataFormat from different route declaration is being used ?

**Comment by ffang** [comment]
Hi @llowinge ,

I don't think this is a bug, and I believe this is the general behaviour how beans lifecycle(the "scope" concept) is defined in IOC container. If you don't want to use another bean name in th URI(I often use different bean names for different routes uri to make the bean self contained and less options/paramter in URI itself, and I think this is more clear), you can actually change the scope of the bean soapClientEndpoint in your testcase, currently it's @ApplicationScoped which means only one  bean soapClientEndpoint instance shared across the whole application but you can use @SessionScoped to see the different result(bean soapClientEndpoint is created differently for different route)

Freeman

**Comment by llowinge** [comment]
Hi @ffang thank you for your explanation. I've created Camel issue https://issues.apache.org/jira/browse/CAMEL-18783 for detecting such URI option misuses. Note when i've used `toD(...)` instead of `to(...)` it worked even with @ApplicationScoped endpoint.
