### ISSUE TITLE
js-dsl fails on GraalVM 22.3/Quarkus 2.14.1

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4285]
Run the js-dsl test in Camel Quarkus with GraalVM 22.3:

```
2022-11-16T13:44:56.0069333Z Caused by: java.lang.AbstractMethodError: Receiver class com.oracle.truffle.polyglot.PolyglotEngineDispatch does not define or inherit an implementation of the resolved method 'abstract org.graalvm.polyglot.Context createContext(java.lang.Object, java.io.OutputStream, java.io.OutputStream, java.io.InputStream, boolean, org.graalvm.polyglot.HostAccess, org.graalvm.polyglot.PolyglotAccess, boolean, boolean, boolean, boolean, boolean, boolean, java.util.function.Predicate, java.util.Map, java.util.Map, java.lang.String[], org.graalvm.polyglot.io.FileSystem, java.lang.Object, boolean, org.graalvm.polyglot.io.ProcessHandler, org.graalvm.polyglot.EnvironmentAccess, java.util.Map, java.time.ZoneId, java.lang.Object, java.lang.String, java.lang.ClassLoader, boolean, boolean)' of abstract class org.graalvm.polyglot.impl.AbstractPolyglotImpl$AbstractEngineDispatch.
2022-11-16T13:44:56.0071305Z    at org.graalvm.polyglot.Context$Builder.build(Context.java:1861)
2022-11-16T13:44:56.0072044Z    at org.apache.camel.dsl.js.JavaScriptRoutesBuilderLoader.doLoadEndpointRouteBuilder(JavaScriptRoutesBuilderLoader.java:53)
2022-11-16T13:44:56.0072891Z    at org.apache.camel.builder.endpoint.EndpointRouteBuilder$2.configure(EndpointRouteBuilder.java:79)
2022-11-16T13:44:56.0073551Z    at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:677)
2022-11-16T13:44:56.0074171Z    at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:619)
2022-11-16T13:44:56.0074809Z    at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:555)
2022-11-16T13:44:56.0075506Z    at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1202)
2022-11-16T13:44:56.0076207Z    at org.apache.camel.main.RoutesConfigurer.addDiscoveredRoutes(RoutesConfigurer.java:237)
2022-11-16T13:44:56.0076869Z    at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:212)
2022-11-16T13:44:56.0077491Z    at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
2022-11-16T13:44:56.0078155Z    at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:703)
2022-11-16T13:44:56.0078802Z    at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
2022-11-16T13:44:56.0079541Z    at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
2022-11-16T13:44:56.0080213Z    at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
2022-11-16T13:44:56.0080819Z    at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
2022-11-16T13:44:56.0081415Z    at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
2022-11-16T13:44:56.0082084Z    at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
2022-11-16T13:44:56.0082748Z    at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
2022-11-16T13:44:56.0083355Z    at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
```

The root cause is an incompatibility of org.graalvm.js:js:22.2 that we manage in CQ with the rest of GraalVM artifacts managed in Quarkus at version 22.3.0 (since Quarkus 2.14.1).

**Comment by jamesnetherton** [comment]
Out of date now.
