### ISSUE TITLE
[Camel 3.20.0] Remove JSONata dependency override

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4294]
Seems Quarkus has upgraded to a version of `antlr` that is no longer compatible.

```
2022-11-24T04:29:00.0489501Z Caused by: java.lang.ExceptionInInitializerError
2022-11-24T04:29:00.0489925Z 	at com.api.jsonata4java.expressions.Expressions.parse(Expressions.java:94)
2022-11-24T04:29:00.0490423Z 	at org.apache.camel.component.jsonata.JsonataEndpoint.onExchange(JsonataEndpoint.java:112)
2022-11-24T04:29:00.0490923Z 	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61)
2022-11-24T04:29:00.0491515Z 	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
2022-11-24T04:29:00.0491971Z 	... 47 more
2022-11-24T04:29:00.0492501Z Caused by: java.lang.UnsupportedOperationException: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
2022-11-24T04:29:00.0493094Z 	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:56)
2022-11-24T04:29:00.0493561Z 	at org.antlr.v4.runtime.atn.ATNDeserializer.deserialize(ATNDeserializer.java:48)
2022-11-24T04:29:00.0494093Z 	at com.api.jsonata4java.expressions.generated.MappingExpressionLexer.<clinit>(MappingExpressionLexer.java:234)
2022-11-24T04:29:00.0494532Z 	... 51 more
2022-11-24T04:29:00.0495021Z Caused by: java.io.InvalidClassException: org.antlr.v4.runtime.atn.ATN; Could not deserialize ATN with version 3 (expected 4).
```

**Comment by jamesnetherton** [comment]
For now, I've added a temporary dependency override for `JSONata4Java` to get things working again. We can remove it when we upgrade to Camel 3.20.0.

**Comment by zbendhiba** [comment]
@jamesnetherton  Maybe mark this issue also Camel 3.20.0, so that we don't miss it ?
