### ISSUE TITLE
Tika intergration tests are failing in Quarkus platform

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#4334]
```
		... 15 more
	Caused by: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
		at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214)
		at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489)
		at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
		at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
		at io.quarkus.tika.TikaParser.parseStream(TikaParser.java:85)
		at io.quarkus.tika.TikaParser.parse(TikaParser.java:44)
		at io.quarkus.tika.TikaParser.parse(TikaParser.java:36)
		at org.apache.camel.quarkus.component.tika.TikaRecorder$QuarkusTikaEndpoint$1.parse(TikaRecorder.java:97)
		at org.apache.camel.component.tika.TikaProducer.doParse(TikaProducer.java:121)
		at org.apache.camel.component.tika.TikaProducer.process(TikaProducer.java:91)
		at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
		... 40 more
```

**Comment by jamesnetherton** [comment]
It is an issue in the quarkus-platform. The dependency tree is a bit of a mess because we seem to have conflicting versions of Apache POI on the classpath 4.1.2 & 5.1.0.

We maybe need to try and move this issue along so that we can switch to Tika 2.x https://github.com/quarkiverse/quarkus-tika/issues/22.

**Comment by jamesnetherton** [comment]
No longer an issue. Tika tests are passing ok in CQ and in the Platform.
