### ISSUE TITLE
Aws2-sqs: Test with real account fails.

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#4389]
I executed JVM tests from integration-test-groups/aws2/aws2-sqs with real account.

Queues were created, but aftfer that I saw every 10 seconds an error in the log:

```
QueueDoesNotExistException: The specified queue does not exist for this wsdl version. 
```

Test with local service was successful.

**Comment by JiriOndrusek** [comment]
The problem is caused by the [CAMEL-18968](https://issues.apache.org/jira/browse/CAMEL-18968) .

**Comment by JiriOndrusek** [comment]
Another problem in native is with test `sqsDeleteMessage`

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 532.275 s <<< FAILURE! - in org.apache.camel.quarkus.component.aws2.sqs.it.Aws2SqsTest
[ERROR] sqsDeleteMessage  Time elapsed: 82.833 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <> but was: <sqs326e320629b0499f9bdd74a49e18d986>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
	at org.apache.camel.quarkus.component.aws2.sqs.it.Aws2SqsTest.sqsDeleteMessage(Aws2SqsTest.java:142)
   ...
