### ISSUE TITLE
Type interface is not a bean type of PRODUCER_METHOD

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4444]
I think this recent Quarkus change caused a few failures on the `quarkus-main` branch nightly build:

https://github.com/quarkusio/quarkus/commit/a37a5f88ce0d5e369408e1de5b1fe66ff03ee939

There's a somewhat cryptic error that I don't fully understand. Here's an example for the Caffeine test. There are some producer methods:

https://github.com/apache/camel-quarkus/blob/main/integration-tests/caffeine/src/main/java/org/apache/camel/quarkus/component/caffeine/it/CaffeineCaches.java#L34-L42

Camel is able to resolve the bean named `SHARED_CACHE_NAME`. It cannot resolve the `LOADING_CACHE_NAME` bean. It fails with:

```
Caused by: java.lang.IllegalArgumentException: Type interface com.github.benmanes.caffeine.cache.Cache is not a bean type of PRODUCER_METHOD bean [class=org.apache.camel.quarkus.component.caffeine.it.CaffeineCaches, id=3c28ddefd7b4cc0e1cabebcb36c68b1e5409524a]
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:61)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReference(RuntimeBeanRepository.java:79)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$getReferenceByName$1(RuntimeBeanRepository.java:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferenceByName(RuntimeBeanRepository.java:75)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$lookupByNameAndType$2(RuntimeBeanRepository.java:114)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lookupByNameAndType(RuntimeBeanRepository.java:114)
	at org.apache.camel.support.DefaultRegistry.lookupByNameAndType(DefaultRegistry.java:260)
	at org.apache.camel.support.CamelContextHelper.lookup(CamelContextHelper.java:202)
	at org.apache.camel.component.caffeine.cache.CaffeineCacheEndpoint.doStart(CaffeineCacheEndpoint.java:69)
```

Failure point is here:

https://github.com/apache/camel-quarkus/blob/main/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java#L79

Which for the Caffeine test is doing something like `beanManager.getReference(bean, com.github.benmanes.caffeine.cache.LoadingCache.class, beanManager.createCreationalContext(bean))`.

**Comment by jamesnetherton** [comment]
Similar issue encountered for the `core-fault-tolerance` test:

https://github.com/apache/camel-quarkus/blob/main/integration-test-groups/foundation/core-fault-tolerance/src/main/java/org/apache/camel/quarkus/core/faulttolerance/it/CoreFaultToleranceProducers.java#L36-L52

```
Caused by: java.lang.IllegalArgumentException: Type class io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker is not a bean type of PRODUCER_METHOD bean [class=org.apache.camel.quarkus.core.faulttolerance.it.CoreFaultToleranceProducers, id=c7bd74ac6dfaf58e0847777f2acd2312bd02c5ce]
    at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:61)
    at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReference(RuntimeBeanRepository.java:79)
    at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$getReferenceByName$1(RuntimeBeanRepository.java:75)
    at java.base/java.util.Optional.map(Optional.java:265)
    at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferenceByName(RuntimeBeanRepository.java:75)
    at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$lookupByNameAndType$2(RuntimeBeanRepository.java:114)
    at java.base/java.util.Optional.flatMap(Optional.java:294)
    at org.apache.camel.quarkus.core.RuntimeBeanRepository.lookupByNameAndType(RuntimeBeanRepository.java:114)
    at org.apache.camel.support.DefaultRegistry.lookupByNameAndType(DefaultRegistry.java:260)
    at org.apache.camel.reifier.AbstractReifier.lookupByNameAndType(AbstractReifier.java:175)
    at org.apache.camel.reifier.AbstractReifier.mandatoryLookup(AbstractReifier.java:147)
    at org.apache.camel.component.microprofile.faulttolerance.FaultToleranceReifier.createProcessor(FaultToleranceReifier.java:68)
    at org.apache.camel.component.microprofile.faulttolerance.FaultToleranceProcessorFactory.doCreateProcessor(FaultToleranceProcessorFactory.java:35)
    at org.apache.camel.component.microprofile.faulttolerance.FaultToleranceProcessorFactory.doCreateProcessor(FaultToleranceProcessorFactory.java:27)
    at org.apache.camel.support.TypedProcessorFactory.createProcessor(TypedProcessorFactory.java:46)
    at org.apache.camel.processor.DefaultProcessorFactory.createProcessor(DefaultProcessorFactory.java:94)
    at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:852)
    at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:598)
    at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:211)

```

**Comment by jamesnetherton** [comment]
Also pgevent tests:

```
Caused by: java.lang.IllegalArgumentException: Type class java.lang.Object is not a bean type of SYNTHETIC bean [class=io.agroal.api.AgroalDataSource, id=b64ad14e4ad657339915cc84f5838091a997c8e2]
	at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:61)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReference(RuntimeBeanRepository.java:79)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$getReferenceByName$1(RuntimeBeanRepository.java:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferenceByName(RuntimeBeanRepository.java:75)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$lookupByNameAndType$2(RuntimeBeanRepository.java:114)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lookupByNameAndType(RuntimeBeanRepository.java:114)
	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lookupByName(RuntimeBeanRepository.java:108)
	at org.apache.camel.support.DefaultRegistry.lookupByName(DefaultRegistry.java:220)
	at org.apache.camel.support.CamelContextHelper.lookup(CamelContextHelper.java:194)
	at org.apache.camel.support.CamelContextHelper.mandatoryLookupAndConvert(CamelContextHelper.java:250)
	at org.apache.camel.support.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:400)
	at org.apache.camel.support.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:347)
	at org.apache.camel.support.component.PropertyConfigurerSupport.property(PropertyConfigurerSupport.java:55)
	at org.apache.camel.component.pgevent.PgEventEndpointConfigurer.configure(PgEventEndpointConfigurer.java:26)
	at org.apache.camel.support.PropertyBindingSupport.setSimplePropertyViaConfigurer(PropertyBindingSupport.java:747)
```

**Comment by Ladicek** [comment]
The last case should be fixed by https://github.com/quarkusio/quarkus/pull/30630

**Comment by jamesnetherton** [comment]
Confirmed that https://github.com/apache/camel-quarkus/pull/4446 & https://github.com/quarkusio/quarkus/pull/30630 have fixed these issues.
