### ISSUE TITLE
JavaShell DSL native compilation fails on  GraalVM 22.2 

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4458]
If we try to launch the integration test of the JavaShell DSL against the docker image `quay.io/quarkus/ubi-quarkus-mandrel:22.2.0.0-Final-java11`, it fails with the next error:

``` 
Error: Cannot find org.apache.camel.dsl.jsh.JshRoutesBuilderLoader.loadRoutesBuilder, org.apache.camel.dsl.jsh.JshRoutesBuilderLoader can not be loaded, due to jdk/jshell/execution/LoaderDelegate not being available in the classpath. Are you missing a dependency in your classpath?
com.oracle.svm.core.util.UserError$UserException: Cannot find org.apache.camel.dsl.jsh.JshRoutesBuilderLoader.loadRoutesBuilder, org.apache.camel.dsl.jsh.JshRoutesBuilderLoader can not be loaded, due to jdk/jshell/execution/LoaderDelegate not being available in the classpath. Are you missing a dependency in your classpath?
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:808)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:423)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:395)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:368)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:324)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:941)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by ppalaga** [comment]
@essobedo is this mandrel:22.2specific? I wonder whether the same issue occurs with the newest [22.3.1](https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags&tag=latest) ?

**Comment by essobedo** [comment]
After a deeper investigation, it appears that it is not mandrel related as the bug can also be reproduced on Graalvm 22.2

**Comment by essobedo** [comment]
Since Mandrel cannot be upgraded in Camel-K for now because of the lack of Java 11 support of Mandrel 22.3, I will propose a workaround of the same type as what have been done for https://github.com/apache/camel-quarkus/issues/3617

**Comment by jamesnetherton** [comment]
JSH-DSL will be marked as deprecated in Camel 4.6.0 / CQ 3.11.0. So there's not much value in investing time here IMO.
