### ISSUE TITLE
As2Test.clientMultipartSignedTest fails on signature verification

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4492]
```
As2Test
[INFO] [stdout] 2023-02-06 09:40:28,446 INFO  [org.apa.cam.qua.tes.AvailablePortFinder] (pool-2-thread-1) org.apache.camel.quarkus.component.as2.it.As2TestResource reserved port 44607
[INFO] [stdout] 2023-02-06 09:40:28,448 INFO  [org.apa.cam.qua.tes.AvailablePortFinder] (pool-2-thread-1) org.apache.camel.quarkus.component.as2.it.As2TestResource reserved port 44647
[INFO] [stdout] 2023-02-06 09:40:28,523 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.https.test-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] [stdout] [                          main] CamelBootstrapRecorder         INFO  Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[INFO] [stdout] [                          main] MainSupport                    INFO  Apache Camel (Main) 4.0.0-M1 is starting
[INFO] [stdout] [                          main] AbstractCamelContext           INFO  Apache Camel 4.0.0-M1 (camel-1) is starting
[INFO] [stdout] [                          main] AbstractCamelContext           INFO  Routes startup (started:0)
[INFO] [stdout] [                          main] AbstractCamelContext           INFO  Apache Camel 4.0.0-M1 (camel-1) started in 17ms (build:0ms init:14ms start:3ms)
[INFO] [stdout] [                          main] quarkus                        INFO  camel-quarkus-integration-test-as2 3.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.0.Alpha3) started in 2.821s. Listening on: http://localhost:44149
[INFO] [stdout] [                          main] quarkus                        INFO  Profile test activated. 
[INFO] [stdout] [                          main] quarkus                        INFO  Installed features: [camel-as2, camel-core, camel-mock, cdi, resteasy, resteasy-jackson, security, smallrye-context-propagation, vertx]
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Initializing server from as2 component.
[INFO] [stdout] [                  AS2Svr-44647] AS2ServerConnection            INFO  Listening on port 44647
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Receiving from as2.
[INFO] [stdout] [                  AS2Svr-44647] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44647] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [                 AS2Hdlr-44647] AS2ServerConnection            INFO  Client closed connection
[INFO] [stdout] [                  AS2Svr-44647] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44647] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [                 AS2Hdlr-44647] deprecation                    WARN  configuration key 'class.resource.loader.class' has been deprecated in favor of 'resource.loader.class.class'
[INFO] [stdout] [                 AS2Hdlr-44647] deprecation                    WARN  configuration key 'resource.loader' has been deprecated in favor of 'resource.loaders'
[INFO] [stdout] [                 AS2Hdlr-44647] deprecation                    WARN  configuration key 'class.resource.loader.description' has been deprecated in favor of 'resource.loader.class.description'
[INFO] [stdout] [                  AS2Svr-44607] AS2ServerConnection            INFO  Listening on port 44607
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Sending to as2: {CamelAS2.from=mrAS@example.org, CamelAS2.ediMessageTransferEncoding=7bit, CamelAS2.as2From=878051556, CamelAS2.dispositionNotificationTo=mrAS@example.org, CamelAS2.as2To=878051556, CamelAS2.subject=Test Case, CamelAS2.as2MessageStructure=ENCRYPTED, CamelAS2.requestUri=/, CamelAS2.ediMessageContentType={mimeType=application/edifact, charset=US-ASCII}}
[INFO] [stdout] [                  AS2Svr-44607] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [                  AS2Svr-44607] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Client closed connection
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Client closed connection
[INFO] [stdout] [                  AS2Svr-44607] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [                 AS2Hdlr-44607] deprecation                    WARN  configuration key 'class.resource.loader.class' has been deprecated in favor of 'resource.loader.class.class'
[INFO] [stdout] [                 AS2Hdlr-44607] deprecation                    WARN  configuration key 'resource.loader' has been deprecated in favor of 'resource.loaders'
[INFO] [stdout] [                 AS2Hdlr-44607] deprecation                    WARN  configuration key 'class.resource.loader.description' has been deprecated in favor of 'resource.loader.class.description'
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Got response from as2: [Content-Type: multipart/report; report-type=disposition-notification; boundary="----=_Part_2_1416829735.1675672831793",Content-Length: 619,Chunked: false]
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Sending to as2: {CamelAS2.from=mrAS@example.org, CamelAS2.ediMessageTransferEncoding=7bit, CamelAS2.signedReceiptMicAlgorithms=[sha1, md5], CamelAS2.as2From=878051556, CamelAS2.dispositionNotificationTo=mrAS@example.org, CamelAS2.as2To=878051556, CamelAS2.subject=Test Case, CamelAS2.as2MessageStructure=SIGNED, CamelAS2.requestUri=/, CamelAS2.ediMessageContentType={mimeType=application/edifact, charset=US-ASCII}}
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            ERROR Unrecoverable HTTP protocol violation: Failed to validate the signature: org.apache.http.HttpException: Failed to validate the signature
[INFO] [stdout]         at org.apache.camel.component.as2.api.util.HttpMessageUtils.extractMultipartSigned(HttpMessageUtils.java:222)
[INFO] [stdout]         at org.apache.camel.component.as2.api.util.HttpMessageUtils.extractEdiPayload(HttpMessageUtils.java:149)
[INFO] [stdout]         at org.apache.camel.component.as2.api.util.MicUtils.createReceivedContentMic(MicUtils.java:101)
[INFO] [stdout]         at org.apache.camel.component.as2.api.entity.AS2MessageDispositionNotificationEntity.<init>(AS2MessageDispositionNotificationEntity.java:95)
[INFO] [stdout]         at org.apache.camel.component.as2.api.entity.DispositionNotificationMultipartReportEntity.<init>(DispositionNotificationMultipartReportEntity.java:66)
[INFO] [stdout]         at org.apache.camel.component.as2.api.protocol.ResponseMDN.process(ResponseMDN.java:158)
[INFO] [stdout]         at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:142)
[INFO] [stdout]         at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:360)
[INFO] [stdout]         at org.apache.camel.component.as2.api.AS2ServerConnection$RequestHandlerThread.run(AS2ServerConnection.java:154)
[INFO] [stdout] 
[INFO] [stdout] [             executor-thread-0] QuarkusErrorHandler            ERROR HTTP Request to /as2/client failed, error id: c2193e2e-bf6d-4a0d-b5a9-cec7eaa46e57-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] [stdout]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] [stdout]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] [stdout]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
[INFO] [stdout]         at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
[INFO] [stdout]         at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:660)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBodyAndHeaders(DefaultProducerTemplate.java:327)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBodyAndHeaders(DefaultProducerTemplate.java:383)
[INFO] [stdout]         at org.apache.camel.quarkus.component.as2.it.As2Resource.client(As2Resource.java:63)
[INFO] [stdout]         at org.apache.camel.quarkus.component.as2.it.As2Resource_ClientProxy.client(Unknown Source)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] [stdout]         ... 15 more
[INFO] [stdout] Caused by: org.apache.camel.RuntimeCamelException: Error invoking send with {server=Camel AS2 Server Endpoint, apiName=CLIENT, as2Version=1.1, as2MessageStructure=SIGNED, ediMessageTransferEncoding=7bit, subject=Test Case, httpConnectionPoolTtl=PT15M, signingPrivateKey=RSA Private CRT Key [88:a8:ba:cb:48:75:41:02:e7:e0:35:bb:71:3b:ab:bc:05:09:36:4b],[56:66:d1:a4]
[INFO] [stdout]              modulus: bd012915710c2659c73a82ac0b32b53a7f34942f01c04e5ca2dc5559196de02ec307aea9b2cc50132d85a60711dca383ed17fc467a8b6cc1bba9b56a95561acf5bd2e7333f237691ec6da8b925cecc295b3e678d7f81f04b7d24867f3844e79bf367178ed83244889792ababec43c04d2f1b7a6d43842b663e98483a1151fb13
[INFO] [stdout]      public exponent: 10001
[INFO] [stdout] , signedReceiptMicAlgorithms=[sha1, md5], ediMessage=UNB+UNOA:1+005435656:1+006415160:1+060515:1434+00000000000778'
[INFO] [stdout] UNH+00000000000117+INVOIC:D:97B:UN'
[INFO] [stdout] BGM+380+342459+9'
[INFO] [stdout] DTM+3:20060515:102'
[INFO] [stdout] RFF+ON:521052'
[INFO] [stdout] NAD+BY+792820524::16++CUMMINS MID-RANGE ENGINE PLANT'
[INFO] [stdout] NAD+SE+005435656::16++GENERAL WIDGET COMPANY'
[INFO] [stdout] CUX+1:USD'
[INFO] [stdout] LIN+1++157870:IN'
[INFO] [stdout] IMD+F++:::WIDGET'
[INFO] [stdout] QTY+47:1020:EA'
[INFO] [stdout] ALI+US'
[INFO] [stdout] MOA+203:1202.58'
[INFO] [stdout] PRI+INV:1.179'
[INFO] [stdout] LIN+2++157871:IN'
[INFO] [stdout] IMD+F++:::DIFFERENT WIDGET'
[INFO] [stdout] QTY+47:20:EA'
[INFO] [stdout] ALI+JP'
[INFO] [stdout] MOA+203:410'
[INFO] [stdout] PRI+INV:20.5'
[INFO] [stdout] UNS+S'
[INFO] [stdout] MOA+39:2137.58'
[INFO] [stdout] ALC+C+ABG'
[INFO] [stdout] MOA+8:525'
[INFO] [stdout] UNT+23+00000000000117'
[INFO] [stdout] UNZ+1+00000000000778', as2To=878051556, as2From=878051556, targetHostname=localhost, httpConnectionPoolSize=5, from=mrAS@example.org, serverFqdn=camel.apache.org, dispositionNotificationTo=mrAS@example.org, httpSocketTimeout=PT5S, ediMessageContentType=application/edifact; charset=US-ASCII, methodName=send, userAgent=Camel AS2 Client Endpoint, requestUri=/, clientFqdn=camel.apache.org, signingAlgorithm=SHA512WITHRSA, httpConnectionTimeout=PT5S, signingCertificateChain=[Ljava.security.cert.Certificate;@45a582f8, targetPortNumber=44607}: Failed to send http request message
[INFO] [stdout]         at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:531)
[INFO] [stdout]         at org.apache.camel.support.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:122)
[INFO] [stdout]         at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:89)
[INFO] [stdout]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[INFO] [stdout]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[INFO] [stdout]         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[INFO] [stdout]         ... 1 more
[INFO] [stdout] Caused by: org.apache.http.HttpException: Failed to send http request message
[INFO] [stdout]         at org.apache.camel.component.as2.api.AS2ClientManager.send(AS2ClientManager.java:394)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.apache.camel.support.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:523)
[INFO] [stdout]         ... 8 more
[INFO] [stdout] Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
[INFO] [stdout]         at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:131)
[INFO] [stdout]         at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:53)
[INFO] [stdout]         at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
[INFO] [stdout]         at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
[INFO] [stdout]         at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
[INFO] [stdout]         at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
[INFO] [stdout]         at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
[INFO] [stdout]         at org.apache.camel.component.as2.api.AS2ClientConnection.send(AS2ClientConnection.java:162)
[INFO] [stdout]         at org.apache.camel.component.as2.api.AS2ClientManager.send(AS2ClientManager.java:391)
[INFO] [stdout]         ... 11 more
[INFO] [stdout] 
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Sending to as2: {CamelAS2.from=mrAS@example.org, CamelAS2.ediMessageTransferEncoding=7bit, CamelAS2.as2From=878051556, CamelAS2.dispositionNotificationTo=mrAS@example.org, CamelAS2.as2To=878051556, CamelAS2.subject=Test Case, CamelAS2.as2MessageStructure=PLAIN, CamelAS2.requestUri=/, CamelAS2.ediMessageContentType={mimeType=application/edifact, charset=US-ASCII}}
[INFO] [stdout] [                  AS2Svr-44607] AS2ServerConnection            INFO  Incoming connection from /127.0.0.1
[INFO] [stdout] [                 AS2Hdlr-44607] AS2ServerConnection            INFO  Processing new AS2 request
[INFO] [stdout] [             executor-thread-0] As2Resource                    INFO  Got response from as2: [Content-Type: multipart/report; report-type=disposition-notification; boundary="----=_Part_5_792181098.1675672832156",Content-Length: 616,Chunked: false]
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.966 s <<< FAILURE! - in org.apache.camel.quarkus.component.as2.it.As2Test
[ERROR] clientMultipartSignedTest  Time elapsed: 0.21 s  <<< FAILURE!
```

**Comment by jamesnetherton** [comment]
The actual problem point is here:

https://github.com/apache/camel/blob/c7ae16fde3891c84a9fd18ea11002190c41dc9a4/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/SigningUtils.java#L134

Signature verification fails for reasons that I could not determine.

**Comment by ppalaga** [comment]
Works as of Platform 3.15.0
