### ISSUE TITLE
MailTest.receiveSecured fails on Camel 4/Quarkus 3: Can't verify identity of server: localhost

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4493]
```
 WARN  [org.apa.cam.com.mai.MailConsumer] (Camel (camel-1) thread #4 - pop3s://localhost:32830) Failed polling endpoint: pop3s://localhost:32830?additionalJavaMailProperties=%23additionalProperties&delay=500&delete=true&initialDelay=100&password=xxxxxx&sslContextParameters=%23sslContextParameters&username=xxxxxx. Will try again at next poll. Caused by: [jakarta.mail.MessagingException - Connect failed]: jakarta.mail.MessagingException: Connect failed;
[INFO] [stdout]   nested exception is:
[INFO] [stdout]         java.io.IOException: Can't verify identity of server: localhost
[INFO] [stdout]         at com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:198)
[INFO] [stdout]         at jakarta.mail.Service.connect(Service.java:342)
[INFO] [stdout]         at org.apache.camel.component.mail.MailConsumer.ensureIsConnected(MailConsumer.java:601)
[INFO] [stdout]         at org.apache.camel.component.mail.MailConsumer.poll(MailConsumer.java:128)
[INFO] [stdout]         at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:202)
[INFO] [stdout]         at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:116)
[INFO] [stdout]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[INFO] [stdout]         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
[INFO] [stdout]         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: java.io.IOException: Can't verify identity of server: localhost
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.checkServerIdentity(SocketFetcher.java:699)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:636)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:402)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:215)
[INFO] [stdout]         at com.sun.mail.pop3.Protocol.<init>(Protocol.java:123)
[INFO] [stdout]         at com.sun.mail.pop3.POP3Store.getPort(POP3Store.java:250)
[INFO] [stdout]         at com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:192)
[INFO] [stdout]         ... 11 more
[INFO] [stdout] 
[INFO] [stdout] 2023-02-06 11:38:00,092 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (executor-thread-0) Failed delivery for (MessageId: 3212D4F4377541D-0000000000000000 on ExchangeId: 3212D4F4377541D-0000000000000000). Exhausted after delivery attempt: 1 caught: jakarta.mail.MessagingException: Could not connect to SMTP host: localhost, port: 32832;
[INFO] [stdout]   nested exception is:
[INFO] [stdout]         java.io.IOException: Can't verify identity of server: localhost
[INFO] [stdout] 
[INFO] [stdout] Message History (source location and message history is disabled)
[INFO] [stdout] ---------------------------------------------------------------------------------------------------------------------------------------
[INFO] [stdout] Source                                   ID                             Processor                                          Elapsed (ms)
[INFO] [stdout]                                          route2/route2                  from[direct://sendMailSecured]                         11903578
[INFO] [stdout]         ...
[INFO] [stdout]                                          route2/to2                     smtps://localhost:32832?username=xxxxxx&password=x            0
[INFO] [stdout] 
[INFO] [stdout] Stacktrace
[INFO] [stdout] ---------------------------------------------------------------------------------------------------------------------------------------: jakarta.mail.MessagingException: Could not connect to SMTP host: localhost, port: 32832;
[INFO] [stdout]   nested exception is:
[INFO] [stdout]         java.io.IOException: Can't verify identity of server: localhost
[INFO] [stdout]         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2261)
[INFO] [stdout]         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:754)
[INFO] [stdout]         at jakarta.mail.Service.connect(Service.java:342)
[INFO] [stdout]         at org.apache.camel.component.mail.DefaultJavaMailSender.send(DefaultJavaMailSender.java:153)
[INFO] [stdout]         at org.apache.camel.component.mail.MailProducer.process(MailProducer.java:71)
[INFO] [stdout]         at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
[INFO] [stdout]         at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
[INFO] [stdout]         at org.apache.camel.processor.Pipeline.process(Pipeline.java:165)
[INFO] [stdout]         at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392)
[INFO] [stdout]         at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:96)
[INFO] [stdout]         at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:214)
[INFO] [stdout]         at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:111)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83)
[INFO] [stdout]         at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:108)
[INFO] [stdout]         at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:199)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:137)
[INFO] [stdout]         at org.apache.camel.quarkus.component.mail.CamelResource.sendMail(CamelResource.java:81)
[INFO] [stdout]         at org.apache.camel.quarkus.component.mail.CamelResource_ClientProxy.sendMail(Unknown Source)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] [stdout]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] [stdout]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] [stdout]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: java.io.IOException: Can't verify identity of server: localhost
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.checkServerIdentity(SocketFetcher.java:699)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:636)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:402)
[INFO] [stdout]         at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:215)
[INFO] [stdout]         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
[INFO] [stdout]         ... 49 more
[INFO] [stdout] 
```

**Comment by ppalaga** [comment]
There is one more issue in native mode:

```
[INFO] Running org.apache.camel.quarkus.component.mail.MailIT
[INFO] [stdout] 2023-02-07 13:54:50,991 INFO  [org.tes.uti.ImageNameSubstitutor] (pool-2-thread-1) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[INFO] [stdout] 2023-02-07 13:54:51,032 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-2-thread-1) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[INFO] [stdout] 2023-02-07 13:54:51,435 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-2-thread-1) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
[INFO] [stdout] 2023-02-07 13:54:51,437 INFO  [org.tes.DockerClientFactory] (pool-2-thread-1) Docker host IP address is localhost
[INFO] [stdout] 2023-02-07 13:54:51,451 INFO  [org.tes.DockerClientFactory] (pool-2-thread-1) Connected to docker: 
[INFO] [stdout]   Server Version: 20.10.22
[INFO] [stdout]   API Version: 1.41
[INFO] [stdout]   Operating System: Fedora Linux 35 (KDE Plasma)
[INFO] [stdout]   Total Memory: 64064 MB
[INFO] [stdout] 2023-02-07 13:54:51,514 INFO  [🐳 .3.4]] (pool-2-thread-1) Creating container for image: testcontainers/ryuk:0.3.4
[INFO] [stdout] 2023-02-07 13:54:51,640 INFO  [🐳 .3.4]] (pool-2-thread-1) Container testcontainers/ryuk:0.3.4 is starting: ba01edfe5a2bf4d7e2ef31850e8ad479f7091fb82241db7b7e715b5eeeb9552d
[INFO] [stdout] 2023-02-07 13:54:52,017 INFO  [🐳 .3.4]] (pool-2-thread-1) Container testcontainers/ryuk:0.3.4 started in PT0.560671212S
[INFO] [stdout] 2023-02-07 13:54:52,023 INFO  [org.tes.uti.RyukResourceReaper] (pool-2-thread-1) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[INFO] [stdout] 2023-02-07 13:54:52,024 INFO  [org.tes.DockerClientFactory] (pool-2-thread-1) Checking the system...
[INFO] [stdout] 2023-02-07 13:54:52,024 INFO  [org.tes.DockerClientFactory] (pool-2-thread-1) ✔︎ Docker server version should be at least 1.6.0
[INFO] [stdout] 2023-02-07 13:54:52,025 INFO  [🐳 .6.7]] (pool-2-thread-1) Creating container for image: greenmail/standalone:1.6.7
[INFO] [stdout] 2023-02-07 13:54:52,070 INFO  [🐳 .6.7]] (pool-2-thread-1) Container greenmail/standalone:1.6.7 is starting: 5f4780ec995f06f81cdf8f8d19fb3c46420a3aa465de5a3b5663848bf5628e4d
[INFO] [stdout] 2023-02-07 13:54:52,504 INFO  [org.tes.con.wai.str.HttpWaitStrategy] (pool-2-thread-1) /xenodochial_diffie: Waiting for 60 seconds for URL: http://localhost:32798/api/service/readiness (where port 32798 maps to container port 8080)
[INFO] [stdout] 2023-02-07 13:54:54,591 INFO  [🐳 .6.7]] (pool-2-thread-1) Container greenmail/standalone:1.6.7 started in PT2.566679275S
[WARN] [stderr] ======================================================================================
[WARN] [stderr]   native.image.path was not set, making a guess for the correct path of native image
[WARN] [stderr]   guessed path: /home/ppalaga/orgs/cq/camel-quarkus/integration-tests/mail/target/camel-quarkus-integration-test-mail-3.0.0-SNAPSHOT-runner
[WARN] [stderr] ======================================================================================
[INFO] [stdout] Executing "/home/ppalaga/orgs/cq/camel-quarkus/integration-tests/mail/target/camel-quarkus-integration-test-mail-3.0.0-SNAPSHOT-runner -Dquarkus.http.port=40241 -Dquarkus.http.ssl-port=42491 -Dtest.url=http://localhost:40241 -Dquarkus.log.file.path=/home/ppalaga/orgs/cq/camel-quarkus/integration-tests/mail/target/quarkus.log -Dquarkus.log.file.enable=true -Dmail.imaps.port=32800 -Dmail.smtps.port=32801 -Dmail.pop3s.port=32799 -Dmail.api.port=32798 -Dmail.smtp.port=32804 -Dmail.pop3.port=32803 -Dmail.imap.port=32802"
[INFO] [stdout] 2023-02-07 13:54:54,654 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[INFO] [stdout] 2023-02-07 13:54:54,655 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.0.0-M1 is starting
[INFO] [stdout] 2023-02-07 13:54:54,668 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToStartRouteException: Failed to start route pop3ReceiveRoute because of null
[INFO] [stdout]         at org.apache.camel.impl.engine.RouteService.setUp(RouteService.java:132)
[INFO] [stdout]         at org.apache.camel.impl.engine.InternalRouteStartupManager.doInitRoutes(InternalRouteStartupManager.java:92)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:3010)
[INFO] [stdout]         at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2679)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2698)
[INFO] [stdout]         at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
[INFO] [stdout]         at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
[INFO] [stdout]         at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
[INFO] [stdout]         at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
[INFO] [stdout]         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[INFO] [stdout]         at io.quarkus.runtime.Application.start(Application.java:101)
[INFO] [stdout]         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
[INFO] [stdout]         at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[INFO] [stdout] Caused by: java.lang.IllegalStateException: Not provider of jakarta.mail.util.StreamProvider was found
[INFO] [stdout]         at jakarta.mail.util.FactoryFinder.find(FactoryFinder.java:64)
[INFO] [stdout]         at jakarta.mail.util.StreamProvider.provider(StreamProvider.java:186)
[INFO] [stdout]         at jakarta.mail.Session.<init>(Session.java:254)
[INFO] [stdout]         at jakarta.mail.Session.getInstance(Session.java:308)
[INFO] [stdout]         at org.apache.camel.component.mail.MailConfiguration.createJavaMailSender(MailConfiguration.java:256)
[INFO] [stdout]         at org.apache.camel.component.mail.MailEndpoint.createConsumer(MailEndpoint.java:116)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.gatherRootServices(DefaultRoute.java:636)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.gatherServices(DefaultRoute.java:620)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.initializeServices(DefaultRoute.java:205)
[INFO] [stdout]         at org.apache.camel.impl.engine.RouteService.doSetup(RouteService.java:151)
[INFO] [stdout]         at org.apache.camel.impl.engine.RouteService.setUp(RouteService.java:130)
[INFO] [stdout]         ... 22 more
[INFO] [stdout] 
[INFO] [stdout] 2023-02-07 13:54:54,671 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.IllegalStateException: Not provider of jakarta.mail.util.StreamProvider was found
[INFO] [stdout]         at jakarta.mail.util.FactoryFinder.find(FactoryFinder.java:64)
[INFO] [stdout]         at jakarta.mail.util.StreamProvider.provider(StreamProvider.java:186)
[INFO] [stdout]         at jakarta.mail.Session.<init>(Session.java:254)
[INFO] [stdout]         at jakarta.mail.Session.getInstance(Session.java:308)
[INFO] [stdout]         at org.apache.camel.component.mail.MailConfiguration.createJavaMailSender(MailConfiguration.java:256)
[INFO] [stdout]         at org.apache.camel.component.mail.MailEndpoint.createConsumer(MailEndpoint.java:116)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.gatherRootServices(DefaultRoute.java:636)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.gatherServices(DefaultRoute.java:620)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultRoute.initializeServices(DefaultRoute.java:205)
[INFO] [stdout]         at org.apache.camel.impl.engine.RouteService.doSetup(RouteService.java:151)
[INFO] [stdout]         at org.apache.camel.impl.engine.RouteService.setUp(RouteService.java:130)
[INFO] [stdout]         at org.apache.camel.impl.engine.InternalRouteStartupManager.doInitRoutes(InternalRouteStartupManager.java:92)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:3010)
[INFO] [stdout]         at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:174)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2679)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2698)
[INFO] [stdout]         at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:262)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
[INFO] [stdout]         at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
[INFO] [stdout]         at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
[INFO] [stdout]         at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
[INFO] [stdout]         at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
[INFO] [stdout]         at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
[INFO] [stdout]         at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
[INFO] [stdout]         at io.quarkus.runtime.Application.start(Application.java:101)
[INFO] [stdout]         at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
[INFO] [stdout]         at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
[INFO] [stdout]         at io.quarkus.runner.GeneratedMain.main(Unknown Source)
[INFO] [stdout] 
```

**Comment by JiriOndrusek** [comment]
@ppalaga  Is there anything special to configure/build? My native execution fails on `Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.camel.quarkus.core.CamelRecorder. This error is reported at image build time because class io.quarkus.deployment.steps.CamelRegistryProcessor$registry1441653894 is registered for linking at image build time by command line`
Similarly  other random test extensions fail for me on `camel-4` branch. I expect some local issues or I just miss some configuration/
