### ISSUE TITLE
GRPC test fails on Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4503]
I have replaced the `protobuf-maven-plugin` by Quarkus code generation phase. Something is still missing

```
[INFO] Running org.apache.camel.quarkus.component.grpc.it.GrpcTest
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 9, Time elapsed: 3.572 s <<< FAILURE! - in org.apache.camel.quarkus.component.grpc.it.GrpcTest
[ERROR] producer  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] A gRPC service bean must be annotated with @io.quarkus.grpc.GrpcService: CLASS bean [types=[org.apache.camel.quarkus.grpc.runtime.CamelQuarkusBindableService, io.grpc.BindableService, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler, java.lang.Object, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBase], qualifiers=[@Default, @Any], target=org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler]
[2] A gRPC service bean must have the jakarta.inject.Singleton scope: CLASS bean [types=[org.apache.camel.quarkus.grpc.runtime.CamelQuarkusBindableService, io.grpc.BindableService, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler, java.lang.Object, org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBase], qualifiers=[@Default, @Any], target=org.apache.camel.quarkus.component.grpc.it.model.PingPongGrpc$PingPongImplBaseQuarkusMethodHandler]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1235)
        at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:161)
        at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:560)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by jamesnetherton** [comment]
I can take a look. Probably something to fix in our build time generation of the `BindableService`.

**Comment by ppalaga** [comment]
Thanks @jamesnetherton 

I am going to push my camel-4 branch to apache/camel-quarkus so that it is easier to send PRs
