### ISSUE TITLE
xchange and com.github.mmazi:rescu not ready for Jakarta 10

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4516]
Blocked by

* https://github.com/mmazi/rescu/issues/142
* https://github.com/knowm/XChange/issues/4676

`com.github.mmazi:rescu` is a transitive dependency of xchange and it still pulls jakarta.ws.rs-api 2.1.5 which makes it incompatible with Quarkus 3.

```
[INFO] Running org.apache.camel.quarkus.component.xchange.it.XchangeTest
...
[INFO] [stdout] 2023-02-07 13:33:30,936 INFO  [io.quarkus] (main) camel-quarkus-integration-test-xchange 3.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.0.Alpha3) started in 2.719s. Listening on: http://localhost:39981
[INFO] [stdout] 2023-02-07 13:33:30,936 INFO  [io.quarkus] (main) Profile test activated. 
[INFO] [stdout] 2023-02-07 13:33:30,936 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-xchange, cdi, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]
[INFO] [stdout] 2023-02-07 13:33:31,863 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xchange/currency/metadata/BTC failed, error id: fdb0ac95-e8d5-46c9-b490-97ed8dffc228-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] [stdout]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] [stdout]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] [stdout]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at si.mazi.rescu.RestInvocationHandler.<init>(RestInvocationHandler.java:59)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactory.createProxy(RestProxyFactory.java:47)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactoryImpl.createProxy(RestProxyFactoryImpl.java:9)
[INFO] [stdout]         at org.knowm.xchange.client.ExchangeRestProxyBuilder.build(ExchangeRestProxyBuilder.java:80)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.initServices(BinanceExchange.java:37)
[INFO] [stdout]         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:108)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.applySpecification(BinanceExchange.java:84)
[INFO] [stdout]         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource$WireMockedXChangeComponent.createExchange(XchangeResource.java:156)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.getOrCreateXChange(XChangeComponent.java:72)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.createEndpoint(XChangeComponent.java:43)
[INFO] [stdout]         at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:974)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:890)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:573)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:411)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource.currencyMetadata(XchangeResource.java:95)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource_ClientProxy.currencyMetadata(Unknown Source)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] [stdout]         ... 15 more
[INFO] [stdout] Caused by: java.lang.ClassNotFoundException: javax.ws.rs.Path
[INFO] [stdout]         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[INFO] [stdout]         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[INFO] [stdout]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[INFO] [stdout]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
[INFO] [stdout]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
[INFO] [stdout]         ... 46 more
[INFO] [stdout] 
[INFO] [stdout] 2023-02-07 13:33:31,999 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xchange/currency/pairs/metadata?base=BTC&counter=USDT failed, error id: fdb0ac95-e8d5-46c9-b490-97ed8dffc228-2: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] [stdout]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] [stdout]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] [stdout]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at si.mazi.rescu.RestInvocationHandler.<init>(RestInvocationHandler.java:59)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactory.createProxy(RestProxyFactory.java:47)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactoryImpl.createProxy(RestProxyFactoryImpl.java:9)
[INFO] [stdout]         at org.knowm.xchange.client.ExchangeRestProxyBuilder.build(ExchangeRestProxyBuilder.java:80)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.initServices(BinanceExchange.java:37)
[INFO] [stdout]         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:108)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.applySpecification(BinanceExchange.java:84)
[INFO] [stdout]         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource$WireMockedXChangeComponent.createExchange(XchangeResource.java:156)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.getOrCreateXChange(XChangeComponent.java:72)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.createEndpoint(XChangeComponent.java:43)
[INFO] [stdout]         at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:974)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:890)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:573)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:411)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource.currencyPairsMetadata(XchangeResource.java:118)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource_ClientProxy.currencyPairsMetadata(Unknown Source)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] [stdout]         ... 15 more
[INFO] [stdout] Caused by: java.lang.ClassNotFoundException: javax.ws.rs.Path
[INFO] [stdout]         ... 46 more
[INFO] [stdout] 
[INFO] [stdout] 2023-02-07 13:33:32,034 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /xchange/currency failed, error id: fdb0ac95-e8d5-46c9-b490-97ed8dffc228-3: org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
[INFO] [stdout]         at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
[INFO] [stdout]         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
[INFO] [stdout]         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[INFO] [stdout]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[INFO] [stdout]         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[INFO] [stdout]         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[INFO] [stdout]         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:1589)
[INFO] [stdout] Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/Path
[INFO] [stdout]         at si.mazi.rescu.RestInvocationHandler.<init>(RestInvocationHandler.java:59)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactory.createProxy(RestProxyFactory.java:47)
[INFO] [stdout]         at si.mazi.rescu.RestProxyFactoryImpl.createProxy(RestProxyFactoryImpl.java:9)
[INFO] [stdout]         at org.knowm.xchange.client.ExchangeRestProxyBuilder.build(ExchangeRestProxyBuilder.java:80)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.initServices(BinanceExchange.java:37)
[INFO] [stdout]         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:108)
[INFO] [stdout]         at org.knowm.xchange.binance.BinanceExchange.applySpecification(BinanceExchange.java:84)
[INFO] [stdout]         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:130)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource$WireMockedXChangeComponent.createExchange(XchangeResource.java:156)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.getOrCreateXChange(XChangeComponent.java:72)
[INFO] [stdout]         at org.apache.camel.component.xchange.XChangeComponent.createEndpoint(XChangeComponent.java:43)
[INFO] [stdout]         at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:974)
[INFO] [stdout]         at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:890)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:573)
[INFO] [stdout]         at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:411)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource.currencies(XchangeResource.java:83)
[INFO] [stdout]         at org.apache.camel.quarkus.component.xchange.it.XchangeResource_ClientProxy.currencies(Unknown Source)
[INFO] [stdout]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO] [stdout]         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[INFO] [stdout]         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[INFO] [stdout]         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
[INFO] [stdout]         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
[INFO] [stdout]         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[INFO] [stdout]         ... 15 more
[INFO] [stdout] Caused by: java.lang.ClassNotFoundException: javax.ws.rs.Path
[INFO] [stdout]         ... 46 more
```

**Comment by ppalaga** [comment]
There is a PR https://github.com/knowm/XChange/pull/4710

**Comment by jamesnetherton** [comment]
xchange has switched to Jakarta on their `develop` branch. So hopefully in their next release we can pick up all of the changes.

**Comment by ppalaga** [comment]
Would anybody like to test their development branch? https://github.com/knowm/XChange/tree/develop/

**Comment by jamesnetherton** [comment]
We should be able to enable this again with Camel 4.5.0.
