### ISSUE TITLE
Twilio test fails with Camel 4 and Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#4527]
```
[INFO] Running org.apache.camel.quarkus.component.twilio.it.TwilioTest
2023-02-07T15:41:19.4065176Z 2023-02-07 15:41:19,404 INFO  [org.apa.cam.qua.tes.wir.WireMockTestResourceLifecycleManager] (pool-2-thread-1) Starting WireMockServer
2023-02-07T15:41:19.4443265Z 2023-02-07 15:41:19,442 INFO  [org.apa.cam.qua.tes.moc.bac.MockBackendUtils] (pool-2-thread-1) Mock backend will be used
2023-02-07T15:41:19.4705104Z 2023-02-07 15:41:19,468 INFO  [org.apa.cam.qua.tes.AvailablePortFinder] (pool-2-thread-1) org.apache.camel.quarkus.test.wiremock.WireMockTestResourceLifecycleManager reserved port 35895
2023-02-07T15:41:19.9142786Z 2023-02-07 15:41:19,913 WARN  [org.ecl.jet.ser.AbstractConnector] (pool-2-thread-1) Acceptors should be <= availableProcessors: NetworkTrafficServerConnector@14d48377{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0} 
2023-02-07T15:41:19.9689245Z 2023-02-07 15:41:19,968 INFO  [org.ecl.jet.ser.Server] (pool-2-thread-1) jetty-11.0.12; built: 2022-09-14T02:38:00.723Z; git: d5b8c29485f5f56a14be5f20c2ccce81b93c5555; jvm 17.0.6+10
2023-02-07T15:41:19.9953613Z 2023-02-07 15:41:19,994 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-2-thread-1) Started o.e.j.s.ServletContextHandler@7691a1fc{/__admin,null,AVAILABLE}
2023-02-07T15:41:20.0051660Z 2023-02-07 15:41:20,002 INFO  [org.ecl.jet.ser.han.Con.ROOT] (pool-2-thread-1) RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
2023-02-07T15:41:20.0053163Z 2023-02-07 15:41:20,003 INFO  [org.ecl.jet.ser.han.ContextHandler] (pool-2-thread-1) Started o.e.j.s.ServletContextHandler@68338d9d{/,null,AVAILABLE}
2023-02-07T15:41:20.0125215Z 2023-02-07 15:41:20,011 INFO  [org.ecl.jet.ser.AbstractConnector] (pool-2-thread-1) Started NetworkTrafficServerConnector@14d48377{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:35895}
2023-02-07T15:41:20.0139303Z 2023-02-07 15:41:20,013 INFO  [org.ecl.jet.ser.Server] (pool-2-thread-1) Started Server@3cad162d{STARTING}[11.0.12,sto=1000] @8286ms
2023-02-07T15:41:20.0145888Z 2023-02-07 15:41:20,014 INFO  [org.apa.cam.qua.tes.wir.WireMockTestResourceLifecycleManager] (pool-2-thread-1) WireMock started on http://localhost:35895
2023-02-07T15:41:20.0961467Z 2023-02-07 15:41:20,094 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.https.test-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-02-07T15:41:20.8396600Z 2023-02-07 15:41:20,838 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2023-02-07T15:41:20.8404885Z 2023-02-07 15:41:20,839 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.0.0-M1 is starting
2023-02-07T15:41:20.9024488Z 2023-02-07 15:41:20,901 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2023-02-07T15:41:20.9028494Z 2023-02-07 15:41:20,902 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.component.twilio.accountSid=xxxxxx
2023-02-07T15:41:20.9034510Z 2023-02-07 15:41:20,902 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.component.twilio.username=xxxxxx
2023-02-07T15:41:20.9087686Z 2023-02-07 15:41:20,903 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.component.twilio.***
2023-02-07T15:41:20.9786368Z 2023-02-07 15:41:20,978 INFO  [org.apa.cam.mai.MainAutowiredLifecycleStrategy] (main) Autowired property: restClient on component: twilio as exactly one instance of type: com.twilio.http.TwilioRestClient (com.twilio.http.TwilioRestClient) found in the registry
2023-02-07T15:41:20.9859848Z 2023-02-07 15:41:20,984 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-M1 (camel-1) is starting
2023-02-07T15:41:20.9881728Z 2023-02-07 15:41:20,987 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:0)
2023-02-07T15:41:20.9885954Z 2023-02-07 15:41:20,987 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-M1 (camel-1) started in 78ms (build:0ms init:76ms start:2ms)
2023-02-07T15:41:21.0827385Z 2023-02-07 15:41:21,080 INFO  [io.quarkus] (main) camel-quarkus-integration-test-twilio 3.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.0.Alpha3) started in 4.818s. Listening on: http://localhost:40573
2023-02-07T15:41:21.0828171Z 2023-02-07 15:41:21,080 INFO  [io.quarkus] (main) Profile test activated. 
2023-02-07T15:41:21.0836435Z 2023-02-07 15:41:21,080 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-twilio, cdi, resteasy, smallrye-context-propagation, vertx]
2023-02-07T15:41:22.3215251Z 2023-02-07 15:41:22,319 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /twilio/call failed, error id: 89dfe74f-689e-447c-b129-af493340c453-1: org.jboss.resteasy.spi.UnhandledException: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2023-02-07T15:41:22.3216548Z 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:110)
2023-02-07T15:41:22.3217299Z 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:370)
2023-02-07T15:41:22.3224941Z 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
2023-02-07T15:41:22.3234336Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
2023-02-07T15:41:22.3245618Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
2023-02-07T15:41:22.3249367Z 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
2023-02-07T15:41:22.3256445Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-02-07T15:41:22.3257264Z 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
2023-02-07T15:41:22.3258113Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
2023-02-07T15:41:22.3260556Z 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
2023-02-07T15:41:22.3264511Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
2023-02-07T15:41:22.3268745Z 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
2023-02-07T15:41:22.3269361Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
2023-02-07T15:41:22.3272013Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
2023-02-07T15:41:22.3279124Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
2023-02-07T15:41:22.3284463Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2023-02-07T15:41:22.3286897Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2023-02-07T15:41:22.3292305Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-02-07T15:41:22.3295893Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-07T15:41:22.3296393Z Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
2023-02-07T15:41:22.3298439Z 	at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
2023-02-07T15:41:22.3300436Z 	at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:660)
2023-02-07T15:41:22.3302449Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
2023-02-07T15:41:22.3303120Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587)
2023-02-07T15:41:22.3307233Z 	at org.apache.camel.impl.engine.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:414)
2023-02-07T15:41:22.3310746Z 	at org.apache.camel.quarkus.component.twilio.it.TwilioResource.phoneCall(TwilioResource.java:70)
2023-02-07T15:41:22.3316668Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-02-07T15:41:22.3319612Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-02-07T15:41:22.3332796Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-07T15:41:22.3336149Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-02-07T15:41:22.3336649Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
2023-02-07T15:41:22.3339860Z 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
2023-02-07T15:41:22.3348698Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
2023-02-07T15:41:22.3349488Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
2023-02-07T15:41:22.3356719Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
2023-02-07T15:41:22.3362944Z 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
2023-02-07T15:41:22.3370393Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
2023-02-07T15:41:22.3371085Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
2023-02-07T15:41:22.3374528Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
2023-02-07T15:41:22.3377203Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
2023-02-07T15:41:22.3377790Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
2023-02-07T15:41:22.3378443Z 	... 15 more
2023-02-07T15:41:22.3378904Z Caused by: org.apache.camel.RuntimeCamelException: java.lang.reflect.InvocationTargetException
2023-02-07T15:41:22.3386914Z 	at org.apache.camel.component.twilio.TwilioEndpoint.execute(TwilioEndpoint.java:116)
2023-02-07T15:41:22.3407977Z 	at org.apache.camel.component.twilio.TwilioProducer.doInvokeMethod(TwilioProducer.java:42)
2023-02-07T15:41:22.3415695Z 	at org.apache.camel.support.component.AbstractApiProducer$1.run(AbstractApiProducer.java:89)
2023-02-07T15:41:22.3416324Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2023-02-07T15:41:22.3425669Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-07T15:41:22.3430210Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2023-02-07T15:41:22.3434437Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-02-07T15:41:22.3437334Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-02-07T15:41:22.3440568Z 	... 1 more
2023-02-07T15:41:22.3440933Z Caused by: java.lang.reflect.InvocationTargetException
2023-02-07T15:41:22.3443050Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-02-07T15:41:22.3450573Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-02-07T15:41:22.3453312Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-07T15:41:22.3453877Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-02-07T15:41:22.3459562Z 	at org.apache.camel.component.twilio.TwilioEndpoint.doExecute(TwilioEndpoint.java:122)
2023-02-07T15:41:22.3467623Z 	at org.apache.camel.component.twilio.TwilioEndpoint.execute(TwilioEndpoint.java:114)
2023-02-07T15:41:22.3474927Z 	... 8 more
2023-02-07T15:41:22.3489876Z Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
2023-02-07T15:41:22.3492463Z 	at com.twilio.http.Request.getAuthString(Request.java:114)
2023-02-07T15:41:22.3495207Z 	at com.twilio.http.NetworkHttpClient.makeRequest(NetworkHttpClient.java:110)
2023-02-07T15:41:22.3495795Z 	at org.apache.camel.quarkus.component.twilio.it.TwilioResource$1.makeRequest(TwilioResource.java:112)
2023-02-07T15:41:22.3499578Z 	at com.twilio.http.HttpClient.reliableRequest(HttpClient.java:48)
2023-02-07T15:41:22.3516369Z 	at com.twilio.http.HttpClient.reliableRequest(HttpClient.java:31)
2023-02-07T15:41:22.3535764Z 	at com.twilio.http.TwilioRestClient.request(TwilioRestClient.java:50)
2023-02-07T15:41:22.3541123Z 	at com.twilio.rest.api.v2010.account.CallCreator.create(CallCreator.java:707)
2023-02-07T15:41:22.3551228Z 	... 14 more
2023-02-07T15:41:22.3553473Z Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
2023-02-07T15:41:22.3560610Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2023-02-07T15:41:22.6792914Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2023-02-07T15:41:22.6796915Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2023-02-07T15:41:22.6799237Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
2023-02-07T15:41:22.6799874Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
2023-02-07T15:41:22.6802407Z 	... 21 more
```

**Comment by aldettinger** [comment]
According to https://github.com/twilio/twilio-java/issues/713, twilio should have removed dependency to javax.*.

Wonder if migration to twilio 8 or 9 would help.

**Comment by oscerd** [comment]
> According to [twilio/twilio-java#713](https://github.com/twilio/twilio-java/issues/713), twilio should have removed dependency to javax.*.
> 
> Wonder if migration to twilio 8 or 9 would help.

It should for sure.

**Comment by aldettinger** [comment]
So, the right version to use is twilio >= 9.1.

**Comment by essobedo** [comment]
Depends on https://issues.apache.org/jira/browse/CAMEL-19029

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/commit/aa895ccea043fa9366e2857b9b5a4ec439d34ed6.
