### ISSUE TITLE
camel-quarkus-hazelcast and camel-quarkus-cxf-soap in same project cannot build native image

### ISSUE THREAD

**Issue by JesperBerggren** [apache/camel-quarkus#4616]
Hello,

We have a project that uses both camel-quarkus-hazelcast and camel-quarkus-cxf-soap.

To best illustrate the error (and remove everything unrelated to the error) I've created a sample project on https://code.quarkus.io/ with the following dependencies:
```
  <dependencies>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-hazelcast</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-cxf-soap</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
  <dependencies>
```

Having **both camel-quarkus-hazelcast and camel-quarkus-cxf-soap** as dependencies we get these exceptions (and the native build fails):
```
========================================================================================================================
GraalVM Native Image: Generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (15.1s @ 0.27GB)
 Version info: 'GraalVM 22.3.1 Java 17 CE'
 Java version info: '17.0.6+10-jvmci-22.3-b13'
 C compiler: gcc (linux, x86_64, 11.3.0)
 Garbage collector: Serial GC
 3 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.hazelcast.internal.util.ICMPHelper: trying to change RUN_TIME from feature io.quarkus.runner.Feature.beforeAnalysis with 'ICMPHelper.class' to RERUN Quarkus
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:103)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.rerunInitialization(ProvenSafeClassInitializationSupport.java:158)
	at io.quarkus.runner.Feature.runtimeReinitializedClasses(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[2/7] Performing analysis...  [12:25:09,283 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
*****]                                                                  (182.2s @ 3.27GB)
  26,720 (91.41%) of 29,232 classes reachable
  39,633 (67.49%) of 58,728 fields reachable
 140,591 (58.40%) of 240,723 methods reachable
   4,221 classes, 9,903 fields, and 39,475 methods registered for reflection
       2 native libraries: m, stdc++

Error: Analysis step failed. Reason: should not reach here: When a feature makes more types, methods, or fields reachable, it must require another analysis iteration via DuringAnalysisAccess.requireAnalysisIteration().
com.oracle.svm.core.util.UserError$UserException: Analysis step failed. Reason: should not reach here: When a feature makes more types, methods, or fields reachable, it must require another analysis iteration via DuringAnalysisAccess.requireAnalysisIteration().
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:753)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.graal.pointsto.util.AnalysisError: should not reach here: When a feature makes more types, methods, or fields reachable, it must require another analysis iteration via DuringAnalysisAccess.requireAnalysisIteration()
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:169)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:164)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
	... 5 more
```

Having **only camel-quarkus-hazelcast** as a dependency we get this exception (but the build is still "successful"):
```
========================================================================================================================
GraalVM Native Image: Generating 'code-with-quarkus-1.0.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (11.7s @ 0.32GB)
 Version info: 'GraalVM 22.3.1 Java 17 CE'
 Java version info: '17.0.6+10-jvmci-22.3-b13'
 C compiler: gcc (linux, x86_64, 11.3.0)
 Garbage collector: Serial GC
 3 user-specific feature(s)
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.hazelcast.internal.util.ICMPHelper: trying to change RUN_TIME from feature io.quarkus.runner.Feature.beforeAnalysis with 'ICMPHelper.class' to RERUN Quarkus
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:103)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:117)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.rerunInitialization(ProvenSafeClassInitializationSupport.java:158)
	at io.quarkus.runner.Feature.runtimeReinitializedClasses(Unknown Source)
	at io.quarkus.runner.Feature.beforeAnalysis(Unknown Source)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$9(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:736)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
[2/7] Performing analysis...  [12:19:06,896 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
********]                                                               (121.7s @ 3.89GB)
  18,906 (90.53%) of 20,883 classes reachable
  25,872 (66.54%) of 38,883 fields reachable
  88,179 (52.98%) of 166,449 methods reachable
   2,593 classes, 6,058 fields, and 24,037 methods registered for reflection
      64 classes,    70 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                              (10.6s @ 3.66GB)
[4/7] Parsing methods...      [***]                                                                      (8.0s @ 4.77GB)
[5/7] Inlining methods...     [***]                                                                      (4.0s @ 3.16GB)
[6/7] Compiling methods...    [********]                                                                (63.1s @ 4.44GB)
[7/7] Creating image...                                                                                  (8.5s @ 3.68GB)
  35.34MB (42.13%) for code area:    63,362 compilation units
  48.22MB (57.49%) for image heap:  447,193 objects and 879 resources
 324.16KB ( 0.38%) for other data
  83.88MB in total
```
This error seems related to #3936 (although not really intermittent but rather persistent)
Furthermore it looks a lot like this #2719 (although not on Mac but rather Ubuntu 22.04)

We need to run with both camel-quarkus-hazelcast and camel-quarkus-cxf-soap so currently we're not able to build a native image.
Please advice.

Best regards
Jesper Berggren

**Comment by zbendhiba** [comment]
Hello @JesperBerggren. Thanks for raising this issue. 

- Could you please tell version of quarkus do you use?

- Does it happen systematically by the presence of the 2 dependencies or on a specific use case ?

**Comment by ppalaga** [comment]
There is indeed a conflict between ours https://github.com/apache/camel-quarkus/blob/e5ec7310ec8a1f700359745ef85f8df4f5f28ed0/extensions/hazelcast/deployment/src/main/java/org/apache/camel/quarkus/component/hazelcast/deployment/HazelcastProcessor.java#L55-L67
and quarkus-hazelcast-client's https://github.com/hazelcast/quarkus-hazelcast-client/blob/dcf253cbed800de8e4174e4a1e21a92d0a1dcde0/deployment/src/main/java/io/quarkus/hazelcast/client/deployment/HazelcastClientProcessor.java#L241 init setting for ICMPHelper.
We should try to remove the RuntimeInitializedClassBuildItem on our side and see whether it helps. 

The camel-quarkus-cxf-soap interference is strange. I only see an optional provided hazelcast dependency in cxf-services-sts-core that camel-quarkus-cxf-soap does not seem to depend on in any way. Do you happen to have io.quarkiverse.cxf:quarkus-cxf-services-sts in your app?

**Comment by JesperBerggren** [comment]
@zbendhiba 
- I use version2.16.3.Final
- I happens systematically when adding both dependencies. Not with either, only when having both included.

@ppalaga 
I don't have any additional dependencies.

This is the full pom.xml in the "dummy" project (empty project generated by code.quarkus.io so there are no other stuff that could interfere):
```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>code-with-quarkus</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.10.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.16.3.Final</quarkus.platform.version>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-camel-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-hazelcast</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-cxf-soap</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <skipITs>false</skipITs>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```

**Comment by zbendhiba** [comment]
Thanks @JesperBerggren. I am able to reproduce the bug very quickly.

@ppalaga I can fix the ICMHelper bug. However, this isn't the reason of the build error. 

The error is not being able to register hierarchies. This is a common issue in Hazelcast, we do have some configuration to ignore those warnings in [camel-quarkus extension](https://github.com/apache/camel-quarkus/blob/1b6fbb4642efa9e3ed7bfa3b4c4662976a73823e/extensions/hazelcast/deployment/src/main/java/org/apache/camel/quarkus/component/hazelcast/deployment/HazelcastProcessor.java#L89) and in [hazelcast extension](https://github.com/hazelcast/quarkus-hazelcast-client/blob/dcf253cbed800de8e4174e4a1e21a92d0a1dcde0/deployment/src/main/java/io/quarkus/hazelcast/client/deployment/HazelcastClientProcessor.java#L228).

Combining those 2 camel-quarkus extensions in pom.xml, generates a very larger number of files unable to register, Even stuff related to Osgi and Spring. (cf log trace below).  This needs some investigation to check what's the problem. 

FYI: the build is okay if we use Hazelcast client + camel quarkus cxf soap.

```
INFO] [io.quarkiverse.cxf.deployment.CxfEndpointImplementationProcessor] Mapping a Vert.x handler for CXF to /* as requested by [camel-cxf-soap]
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- com.sun.istack.FinalArrayList (source: <unknown>)
	- com.sun.istack.Pool (source: <unknown>)
	- com.sun.xml.fastinfoset.stax.StAXDocumentSerializer (source: <unknown>)
	- io.netty.buffer.ByteBuf (source: <unknown>)
	- io.quarkus.vertx.http.runtime.VertxInputStream (source: <unknown>)
	- io.vertx.core.http.HttpServerRequest (source: <unknown>)
	- io.vertx.core.http.HttpServerResponse (source: <unknown>)
	- io.vertx.ext.web.RoutingContext (source: <unknown>)
	- javax.crypto.Cipher (source: <unknown>)
	- javax.crypto.SecretKey (source: <unknown>)
	- javax.jws.WebService (source: <unknown>)
	- javax.management.ObjectName (source: <unknown>)
	- javax.net.ssl.HostnameVerifier (source: <unknown>)
	- javax.net.ssl.SSLContext (source: <unknown>)
	- javax.net.ssl.SSLSocket (source: <unknown>)
	- javax.net.ssl.SSLSocketFactory (source: <unknown>)
	- javax.security.auth.Subject (source: <unknown>)
	- javax.security.auth.login.Configuration (source: <unknown>)
	- javax.servlet.AsyncContext (source: <unknown>)
	- javax.servlet.DispatcherType (source: <unknown>)
	- javax.servlet.ServletContext (source: <unknown>)
	- javax.servlet.ServletInputStream (source: <unknown>)
	- javax.servlet.ServletOutputStream (source: <unknown>)
	- javax.servlet.http.Cookie (source: <unknown>)
	- javax.servlet.http.HttpServletRequest (source: <unknown>)
	- javax.servlet.http.HttpServletResponse (source: <unknown>)
	- javax.servlet.http.HttpSession (source: <unknown>)
	- javax.servlet.http.Part (source: <unknown>)
	- javax.validation.Validator (source: <unknown>)
	- javax.wsdl.Definition (source: <unknown>)
	- javax.xml.bind.Binder (source: <unknown>)
	- javax.xml.bind.JAXBContext (source: <unknown>)
	- javax.xml.bind.JAXBElement (source: <unknown>)
	- javax.xml.bind.JAXBException (source: <unknown>)
	- javax.xml.bind.JAXBIntrospector (source: <unknown>)
	- javax.xml.bind.Marshaller (source: <unknown>)
	- javax.xml.bind.Marshaller$Listener (source: <unknown>)
	- javax.xml.bind.Unmarshaller (source: <unknown>)
	- javax.xml.bind.Unmarshaller$Listener (source: <unknown>)
	- javax.xml.bind.UnmarshallerHandler (source: <unknown>)
	- javax.xml.bind.ValidationEventHandler (source: <unknown>)
	- javax.xml.bind.ValidationEventLocator (source: <unknown>)
	- javax.xml.bind.Validator (source: <unknown>)
	- javax.xml.bind.annotation.DomHandler (source: <unknown>)
	- javax.xml.bind.annotation.XmlAccessOrder (source: <unknown>)
	- javax.xml.bind.annotation.XmlAccessType (source: <unknown>)
	- javax.xml.bind.annotation.XmlAttribute (source: <unknown>)
	- javax.xml.bind.annotation.XmlElement (source: <unknown>)
	- javax.xml.bind.annotation.XmlElementDecl (source: <unknown>)
	- javax.xml.bind.annotation.XmlElementRef (source: <unknown>)
	- javax.xml.bind.annotation.XmlElementRefs (source: <unknown>)
	- javax.xml.bind.annotation.XmlEnum (source: <unknown>)
	- javax.xml.bind.annotation.XmlNs (source: <unknown>)
	- javax.xml.bind.annotation.XmlNsForm (source: <unknown>)
	- javax.xml.bind.annotation.XmlRootElement (source: <unknown>)
	- javax.xml.bind.annotation.XmlSchema (source: <unknown>)
	- javax.xml.bind.annotation.XmlSchemaType (source: <unknown>)
	- javax.xml.bind.annotation.XmlTransient (source: <unknown>)
	- javax.xml.bind.annotation.XmlType (source: <unknown>)
	- javax.xml.bind.annotation.XmlValue (source: <unknown>)
	- javax.xml.bind.annotation.adapters.XmlAdapter (source: <unknown>)
	- javax.xml.bind.attachment.AttachmentMarshaller (source: <unknown>)
	- javax.xml.bind.attachment.AttachmentUnmarshaller (source: <unknown>)
	- javax.xml.bind.helpers.AbstractMarshallerImpl (source: <unknown>)
	- javax.xml.bind.helpers.AbstractUnmarshallerImpl (source: <unknown>)
	- javax.xml.bind.helpers.ValidationEventLocatorImpl (source: <unknown>)
	- javax.xml.namespace.NamespaceContext (source: <unknown>)
	- javax.xml.namespace.QName (source: <unknown>)
	- javax.xml.parsers.DocumentBuilder (source: <unknown>)
	- javax.xml.parsers.DocumentBuilderFactory (source: <unknown>)
	- javax.xml.parsers.SAXParserFactory (source: <unknown>)
	- javax.xml.stream.Location (source: <unknown>)
	- javax.xml.stream.XMLEventFactory (source: <unknown>)
	- javax.xml.stream.XMLEventWriter (source: <unknown>)
	- javax.xml.stream.XMLInputFactory (source: <unknown>)
	- javax.xml.stream.XMLOutputFactory (source: <unknown>)
	- javax.xml.stream.XMLStreamReader (source: <unknown>)
	- javax.xml.stream.XMLStreamWriter (source: <unknown>)
	- javax.xml.stream.events.Characters (source: <unknown>)
	- javax.xml.stream.events.XMLEvent (source: <unknown>)
	- javax.xml.transform.ErrorListener (source: <unknown>)
	- javax.xml.transform.Source (source: <unknown>)
	- javax.xml.transform.Templates (source: <unknown>)
	- javax.xml.transform.Transformer (source: <unknown>)
	- javax.xml.transform.TransformerFactory (source: <unknown>)
	- javax.xml.transform.URIResolver (source: <unknown>)
	- javax.xml.transform.dom.DOMResult (source: <unknown>)
	- javax.xml.transform.dom.DOMSource (source: <unknown>)
	- javax.xml.transform.sax.SAXSource (source: <unknown>)
	- javax.xml.validation.Schema (source: <unknown>)
	- javax.xml.validation.SchemaFactory (source: <unknown>)
	- javax.xml.validation.ValidatorHandler (source: <unknown>)
	- org.apache.ws.commons.schema.XmlSchema (source: <unknown>)
	- org.apache.ws.commons.schema.XmlSchemaAnnotated (source: <unknown>)
	- org.apache.ws.commons.schema.XmlSchemaCollection (source: <unknown>)
	- org.apache.ws.commons.schema.XmlSchemaType (source: <unknown>)
	- org.apache.ws.commons.schema.extensions.ExtensionRegistry (source: <unknown>)
	- org.apache.ws.commons.schema.utils.NamespacePrefixList (source: <unknown>)
	- org.ietf.jgss.Oid (source: <unknown>)
	- org.jvnet.mimepull.MIMEMessage (source: <unknown>)
	- org.jvnet.mimepull.MIMEPart (source: <unknown>)
	- org.jvnet.staxex.BinaryText (source: <unknown>)
	- org.jvnet.staxex.NamespaceContextEx (source: <unknown>)
	- org.jvnet.staxex.NamespaceContextEx$Binding (source: <unknown>)
	- org.jvnet.staxex.XMLStreamWriterEx (source: <unknown>)
	- org.jvnet.staxex.util.XMLStreamReaderToXMLStreamWriter (source: <unknown>)
	- org.jvnet.staxex.util.XMLStreamReaderToXMLStreamWriter$Breakpoint (source: <unknown>)
	- org.osgi.framework.Bundle (source: <unknown>)
	- org.osgi.framework.BundleContext (source: <unknown>)
	- org.osgi.framework.ServiceRegistration (source: <unknown>)
	- org.osgi.service.blueprint.container.BlueprintContainer (source: <unknown>)
	- org.springframework.context.ApplicationContext (source: <unknown>)
	- org.springframework.context.ConfigurableApplicationContext (source: <unknown>)
	- org.springframework.context.support.AbstractApplicationContext (source: <unknown>)
	- org.springframework.core.io.Resource (source: <unknown>)
	- org.w3c.dom.Attr (source: <unknown>)
	- org.w3c.dom.DOMConfiguration (source: <unknown>)
	- org.w3c.dom.DOMImplementation (source: <unknown>)
	- org.w3c.dom.Document (source: <unknown>)
	- org.w3c.dom.DocumentFragment (source: <unknown>)
	- org.w3c.dom.DocumentType (source: <unknown>)
	- org.w3c.dom.Element (source: <unknown>)
	- org.w3c.dom.NamedNodeMap (source: <unknown>)
	- org.w3c.dom.Node (source: <unknown>)
	- org.w3c.dom.NodeList (source: <unknown>)
	- org.w3c.dom.TypeInfo (source: <unknown>)
	- org.w3c.dom.ls.LSResourceResolver (source: <unknown>)
	- org.xml.sax.Attributes (source: <unknown>)
	- org.xml.sax.ContentHandler (source: <unknown>)
	- org.xml.sax.DTDHandler (source: <unknown>)
	- org.xml.sax.EntityResolver (source: <unknown>)
	- org.xml.sax.ErrorHandler (source: <unknown>)
	- org.xml.sax.Locator (source: <unknown>)
	- org.xml.sax.SAXParseException (source: <unknown>)
	- org.xml.sax.XMLReader (source: <unknown>)
	- org.xml.sax.ext.LexicalHandler (source: <unknown>)
	- org.xml.sax.helpers.AttributesImpl (source: <unknown>)
	- org.xml.sax.helpers.DefaultHandler (source: <unknown>)
	- org.xml.sax.helpers.XMLFilterImpl (source: <unknown>)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
```
