### ISSUE TITLE
camel-quarkus-snakeyaml not compatible with Quarkus 3.0.0.Alpha6

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4662]
SnakeYAML has been upgraded to 2.x:

```
2023-03-15T16:52:20.6319162Z Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
2023-03-15T16:52:20.6319978Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.defaultRepresenter(SnakeYAMLDataFormat.java:419)
2023-03-15T16:52:20.6320884Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.getYaml(SnakeYAMLDataFormat.java:150)
2023-03-15T16:52:20.6321994Z 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.marshal(SnakeYAMLDataFormat.java:114)
2023-03-15T16:52:20.6322867Z 	at org.apache.camel.support.processor.MarshalProcessor.process(MarshalProcessor.java:64)
2023-03-15T16:52:20.6323574Z 	... 48 more
```

We need:

https://issues.apache.org/jira/browse/CAMEL-19130

I will disable the affected tests for now.

**Comment by zhfeng** [comment]
- https://github.com/apache/camel/pull/9572
It has been merged and should be good to test with `camel-main` branch.
