### ISSUE TITLE
Problem: Classes that should be initialized at run time got initialized during image building

### ISSUE THREAD

**Issue by bframke** [apache/camel-quarkus#467]
What we are trying to do is sending Messages between IBM MQ and ActiveMQ Artemis. Therefore we use an selfmade Quarkus IBM MQ Extension and a selfmade Camel-JMS Extension. When we started the project there was no JMS support for Camel-Quarkus.

We currently face a problem with our Camel Extension. We tried to update it to a newer version to Camel 0.4.0, Graal 19.3.0 and Quarkus 1.0.0.CR2. But we receive this error message upon building a native image:
```Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at build time (from the command line and Quarkus).  To see why io.netty.buffer.PooledByteBufAllocator got initialized use -H:+TraceClassInitialization
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at build time (from the command line and Quarkus).  To see why io.netty.buffer.PooledByteBufAllocator got initialized use -H:+TraceClassInitialization
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:494)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:188)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

I already tried to use the `--initialize-at-run-time` and `--initialize-at-build-time` parameters. The first throws the same message and the second this:
```Error: Incompatible change of initialization policy for io.netty.buffer.PooledByteBufAllocator: trying to change BUILD_TIME from the command line to RUN_TIME from the command line
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for io.netty.buffer.PooledByteBufAllocator: trying to change BUILD_TIME from the command line to RUN_TIME from the command line
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:96)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:107)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:107)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:107)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:107)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:63)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.initializeAtRunTime(ConfigurableClassInitialization.java:205)
        at com.oracle.svm.hosted.classinitialization.InitKind.lambda$stringConsumer$0(InitKind.java:69)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.processClassInitializationOptions(ClassInitializationFeature.java:146)
        at com.oracle.svm.hosted.HostedConfiguration.setDefaultIfEmpty(HostedConfiguration.java:71)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:819)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

I also tried to add this class via rerun and the Extension-Loader from Quarkus which also runs into an error in this case. Is there anyway for Camel to help or is the netty hub better suited for that?

**Comment by lburgazzoli** [comment]
Graal 19.3.0 is not yet officially supported by quarkus so as first step I'd recommend to stick with 19.2.x.

**Comment by bframke** [comment]
Okay, the extension camel-quarkus-sjms is not released anywhere I look. Tried it via maven search and some googleing only to end up in the readme which tells me, it does exist.

**Comment by lburgazzoli** [comment]
It is not yet available in a release but you can use it from [Apache Snapshots Repo](https://repository.apache.org/content/repositories/snapshots/org/apache/camel/quarkus/camel-quarkus-sjms) or build it from source. 

It will be available in the next Camel Quarkus release

**Comment by bframke** [comment]
Ah okay, currently building it for our snapshot repo. I will test it out and let you know if the problem above still appears or not.

**Comment by lburgazzoli** [comment]
There's a small integration test [here](https://github.com/apache/camel-quarkus/tree/master/integration-tests/sjms) which is far to be completed but can at least give you some hints about the dependencies and set-up

**Comment by bframke** [comment]
No changes here. Used SJMS and Graal 19.2.1

```Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at build time (from the command line and Quarkus).  To see why io.netty.buffer.PooledByteBufAllocator got initialized use -H:+TraceClassInitialization
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at build time (from the command line and Quarkus).  To see why io.netty.buffer.PooledByteBufAllocator got initialized use -H:+TraceClassInitialization
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:494)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:188)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:711)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```

**Comment by lburgazzoli** [comment]
can you share the example or part of it ? netty substitutions should be provided by one of the extensions

**Comment by bframke** [comment]
Not sure, what you exactly mean. But our project setup is just a "normal" java project with quarkus at its core and camel-quarkus plus camel-quarkus-sjms and quarkus-ibmmq.
`
ibmmqVersion=0.1
quarkusVersion=1.0.0.CR2
camelVersion=0.4.1-SNAPSHOT
`
```
dependencies {
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.6.1'
    compile group: 'log4j', name: 'log4j', version: '1.2.17'
    compile group: 'xxx', name: 'quarkus-ibmmq', version: "${ibmmqVersion}"
    compile group: 'io.quarkus', name: 'quarkus-core-deployment', version: "${quarkusVersion}"
    compile group: 'io.quarkus', name: 'quarkus-jackson', version: "${quarkusVersion}"
    compile group: 'io.quarkus', name: 'quarkus-smallrye-metrics', version: "${quarkusVersion}"

    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.8'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.8'
    compile group: 'org.apache.activemq', name: 'artemis-jms-client', version: '2.9.0'
    compile group: 'org.apache.camel', name: 'camel-core-engine', version: '3.0.0-RC3'
    compile group: 'org.apache.camel', name: 'camel-sjms', version: '3.0.0-RC3'

    implementation group: 'org.apache.camel.quarkus', name: 'camel-quarkus-core', version: "0.4.0"
    implementation group: 'org.apache.camel.quarkus', name: 'camel-quarkus-core-xml', version: "0.4.0"
    implementation group: 'org.apache.camel.quarkus', name: 'camel-quarkus-sjms', version: "${camelVersion}"
    implementation group: 'org.apache.camel.quarkus', name: 'camel-quarkus-sjms-deployment', version: "${camelVersion}"
    implementation group: 'org.apache.camel.quarkus', name: 'camel-quarkus-sjms-parent', version: "${camelVersion}"
    implementation group: 'org.conscrypt', name: 'conscrypt-openjdk', version: '2.2.1'

    implementation enforcedPlatform('io.quarkus:quarkus-bom:'+"${quarkusVersion}")
    implementation("io.quarkus:quarkus-resteasy")

    testCompile group: 'org.junit.jupiter', name:'junit-jupiter-api', version:'5.3.1'
    testCompile 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
    testCompile group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
    testCompile group: 'org.mockito', name: 'mockito-core', version: '3.1.0'
    testCompile group: 'org.mockito', name: 'mockito-junit-jupiter', version: '3.1.0'
    testCompile "org.jboss.resteasy:resteasy-client:3.0.14.Final"
    testCompile "org.jboss.resteasy:resteasy-client-api:3.0.14.Final"
}
```
I could try to give you a variation of the project, but the quarkus-ibmmq extension is not shared for other in the internet.

**Comment by lburgazzoli** [comment]
Thre's a quarkus-artemis-jms extension available, can you add it to your project ? it should alsoe bring netty substitutions

**Comment by bframke** [comment]
Added the Extension and now it builds correctly. Also removed removed the artemis-jms-client.

thanks for the help

**Comment by bframke** [comment]
Now when I try to start it I get this error:  Cannot auto create component: jms

Which I normally only got, when there was no jms known to camel. Same happens to sjms.

**Comment by lburgazzoli** [comment]
Looks like the connection factory is misconfigured, but hard to guess why without a reproducer.
how did you configure the connection factory ?

**Comment by bframke** [comment]
They are configured via application.properties.

```
camel.activemq.connection.factories={ \
  "amqConnectionFactoryPlain" : { \
    "hostName" : "localhost", \
    "port" : 61616, \
    "ssl" : false \
  } \
}
camel.ibmmq.connection.factories={ \
  "ibmmqConnectionFactoryPlain" : { \
    "hostName" : "localhost", \
    "port" : 1414, \
    "ssl" : false, \
    "queueManager" : "QM1", \
    "channel" : "CAL" \
  }\
}
```

**Comment by lburgazzoli** [comment]
This is how the it is set-up in our tests: https://github.com/apache/camel-quarkus/blob/master/integration-tests/sjms/src/main/resources/application.properties#L29

It is pretty simple but that is what the extension provides at the moment

**Comment by bframke** [comment]
Also before the update to 0.4.0 we used CamelRuntime and now CamelMain to work with the ContextListener.

**Comment by lburgazzoli** [comment]
I guess you are parsing the property and then you create the connection factory from that  one right ?

**Comment by bframke** [comment]
Yes and we configure it via the key:value map.

```
void registerActiveMqFactories() {
        Map<String, JmsConfig> activemqConnectionFactoriesConfig = getJmsConfigs(_activemqConfigsAsString);
        _logger.info("activemqConnectionFactoriesConfig : {}", activemqConnectionFactoriesConfig);
        if (activemqConnectionFactoriesConfig != null) {
            Registry registry = _camelMain.getCamelContext().getRegistry();
            activemqConnectionFactoriesConfig.forEach((name, config) -> {
                registry.bind(name, _activeMqConnectionFactoryProducer.getConnectionFactory(config));
            });
        }
    }

    void registerIbmMqFactories() {
        Map<String, JmsConfig> ibmmqConnectionFactoriesConfig = getJmsConfigs(_ibmmqConfigsAsString);
        _logger.info("ibmmqConnectionFactoriesConfig : {}", ibmmqConnectionFactoriesConfig);
        if (ibmmqConnectionFactoriesConfig != null) {
            Registry registry = _camelMain.getCamelContext().getRegistry();
            ibmmqConnectionFactoriesConfig.forEach((name, config) -> {
                registry.bind(name, _ibmMqConnectionFactoryProducer.getConnectionFactory(config));
            });
        }
    }

    private Map<String,JmsConfig> getJmsConfigs(String jsonValue) {
        try {
            return _jsonMapper.readValue(jsonValue,
                    TypeFactory.defaultInstance().constructMapLikeType(HashMap.class, String.class, JmsConfig.class));
        } catch (IOException e) {
            _logger.error("cannot convert config value '" + jsonValue +"'", e);
        }
        return null;
    }
```

**Comment by lburgazzoli** [comment]
I think the problem is in the aartemis-jms extension as it creates a connection factory even if the configurations are empty.

Can you try to add something like https://github.com/apache/camel-quarkus/blob/master/integration-tests/sjms/src/main/resources/application.properties#L29 ?

**Comment by bframke** [comment]
Both changes have no effect. The part I showed a post back was just for the configuration. We initialize the Factories via Injection, could this be a problem?

**Comment by lburgazzoli** [comment]
I need to digg into it more, can you share a reproducer ? without the ibm bits of course

**Comment by bframke** [comment]
Just edited the two producers we use in the last comment, if it helps.

**Comment by lburgazzoli** [comment]
can you create a sample reproducer and share it on github ? that would help a lot

**Comment by bframke** [comment]
Created an example without IBM MQ usage. quarkusBuild is the fastest way to directly to a first test, after importing the project.

https://github.com/bframke/quarkus-examples

dir: camel-producer

**Comment by lburgazzoli** [comment]
I've cleaned it up and shrink-ed it to a bare minimum to reduce complexity: https://github.com/lburgazzoli/bframke-quarkus-examples/tree/cleanup/camel-producer

To create connection factories, the best is to use CDI instead of putting things directly to the camel registry which is possible but should be done before routes are started otherwise registry elements can't be found.

**Comment by bframke** [comment]
Okay, your example is just for one ConnectionFactory, we create several with this key:value map. Question here is, after reading through the CDI stuff, how to correctly implement it, that CDI does work for one? We use the registry in the configure phase and add the routes in before start. 

Just injecting the example from you is already enough in that case or is there more to be done?

**Comment by lburgazzoli** [comment]
I made it simpler because the example was not working out of the box so I did try to check that things are working as expected.

In your code, the main problem is that `CamelMainEvents.Configure` happens after `CamelMainEvents.BeforeStart` so when routes are created they may not find the beans they are looking for (in this case the connection factories).

**Comment by bframke** [comment]
Ah, so the AfterStart would be the better case?

**Comment by lburgazzoli** [comment]
You should do it in `CamelMainEvents.BeforeStart`

**Comment by bframke** [comment]
Ah...darn events, thanks. Now it works. Was a bit confusing after we had to change the used events in the newer version. Factories are now registered correctly and the same is for the routes.

Thanks for the help in this problem.

**Comment by lburgazzoli** [comment]
can we close this ?

**Comment by bframke** [comment]
Yes.
