### ISSUE TITLE
Fix camel-quarkus-pdf native tests

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#472]
Following this [pr](https://github.com/apache/camel-quarkus/pull/471/files#diff-7cc83a1071a5196fb78d4f99b1bb014cR67-R93), the camel-quarkus-pdf tests are no more running in native mode.

**Comment by aldettinger** [comment]
Hey @lburgazzoli, thanks for checking this. I'am not able to reproduce it locally with graal-vm/native-mage 19.2.1. Could you please check the graal-vm version involved when the issue is reproduced ?

**Comment by lburgazzoli** [comment]
```
$ /opt/data/sfw/lang/java/graalvm/bin/native-image --version
GraalVM Version 19.2.1 CE

$ mvn clean install -Dnative-pdf
[INFO] Scanning for projects...
[INFO] 
[INFO] ----< org.apache.camel.quarkus:camel-quarkus-integration-test-pdf >-----
[INFO] Building Camel Quarkus :: Integration Tests :: PDF 0.4.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ camel-quarkus-integration-test-pdf ---
[INFO] Deleting /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target
[INFO] 
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (directories) @ camel-quarkus-integration-test-pdf ---
[INFO] Highest basedir set to: /home/lburgazz/work/apache/dev/camel-quarkus
[INFO] 
[INFO] --- groovy-maven-plugin:2.1.1:execute (sanity-checks) @ camel-quarkus-integration-test-pdf ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-integration-test-pdf ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ camel-quarkus-integration-test-pdf ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.10.0:format (default) @ camel-quarkus-integration-test-pdf ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 3
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         3 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ camel-quarkus-integration-test-pdf ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-integration-test-pdf ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (copy-generated-resources) @ camel-quarkus-integration-test-pdf ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ camel-quarkus-integration-test-pdf ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-quarkus-integration-test-pdf ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ camel-quarkus-integration-test-pdf ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.quarkus.component.pdf.it.PdfTest
2019-11-27 16:55:02,477 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Using properties from classpath:application.properties
2019-11-27 16:55:02,496 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: camel-1) is starting
2019-11-27 16:55:02,497 INFO  [org.apa.cam.imp.eng.DefaultManagementStrategy] (main) JMX is disabled
2019-11-27 16:55:02,509 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2019-11-27 16:55:02,516 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Total 0 routes, of which 0 are started
2019-11-27 16:55:02,517 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: camel-1) started in 0.020 seconds
2019-11-27 16:55:02,519 INFO  [io.quarkus] (main) Quarkus 1.0.0.Final started in 0.692s. Listening on: http://0.0.0.0:8081
2019-11-27 16:55:02,520 INFO  [io.quarkus] (main) Profile test activated. 
2019-11-27 16:55:02,520 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-pdf, camel-support-common, cdi, resteasy]
2019-11-27 16:55:03,894 WARN  [org.apa.pdf.pdm.fon.PDType1Font] (vert.x-worker-thread-0) Using fallback font LiberationSans for base font Symbol
2019-11-27 16:55:03,895 WARN  [org.apa.pdf.pdm.fon.PDType1Font] (vert.x-worker-thread-0) Using fallback font LiberationSans for base font ZapfDingbats
2019-11-27 16:55:04,000 INFO  [org.apa.cam.qua.com.pdf.it.PdfResource] (vert.x-worker-thread-0) The PDDocument has been created and contains 876 bytes
2019-11-27 16:55:04,209 INFO  [org.apa.cam.qua.com.pdf.it.PdfResource] (vert.x-worker-thread-1) The PDDocument has been updated and now contains 1426 bytes
2019-11-27 16:55:04,237 INFO  [org.apa.cam.qua.com.pdf.it.PdfResource] (vert.x-worker-thread-2) Extracting text from the PDDocument
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.854 s - in org.apache.camel.quarkus.component.pdf.it.PdfTest
2019-11-27 16:55:04,252 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: camel-1) is shutting down
2019-11-27 16:55:04,258 INFO  [org.apa.cam.mai.MainLifecycleStrategy] (main) CamelContext: camel-1 has been shutdown, triggering shutdown of the JVM.
2019-11-27 16:55:04,266 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: camel-1) uptime 1.770 seconds
2019-11-27 16:55:04,267 INFO  [org.apa.cam.qua.cor.FastCamelContext] (main) Apache Camel 3.0.0 (CamelContext: camel-1) is shutdown in 0.015 seconds
2019-11-27 16:55:04,297 INFO  [io.quarkus] (main) Quarkus stopped in 0.045s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ camel-quarkus-integration-test-pdf ---
[INFO] Building jar: /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-site-plugin:3.7.1:attach-descriptor (attach-descriptor) @ camel-quarkus-integration-test-pdf ---
[INFO] Skipping because packaging 'jar' is not pom.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.0:test-jar (default) @ camel-quarkus-integration-test-pdf ---
[INFO] Building jar: /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-tests.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:1.0.0.Final:build (default) @ camel-quarkus-integration-test-pdf ---
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1454ms
[INFO] 
[INFO] --- quarkus-maven-plugin:1.0.0.Final:native-image (native-image) @ camel-quarkus-integration-test-pdf ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-native-image-source-jar/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/lburgazz/work/apache/dev/camel-quarkus/integration-tests/pdf/target/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-native-image-source-jar/camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on OpenJDK 64-Bit Server VM
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /opt/data/sfw/lang/java/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner
[camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner:93972]    classlist:   7,280.98 ms
[camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner:93972]        (cap):     966.98 ms
[camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner:93972]        setup:   2,401.10 ms
16:55:20,342 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
16:55:28,290 WARNING [org.apa.pdf.pdm.fon.PDType1Font] Using fallback font LiberationSans for base font Symbol
16:55:28,291 WARNING [org.apa.pdf.pdm.fon.PDType1Font] Using fallback font LiberationSans for base font ZapfDingbats
[camel-quarkus-integration-test-pdf-0.4.1-SNAPSHOT-runner:93972]     analysis:  24,381.11 ms
Error: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 	object org.apache.fontbox.ttf.BufferedRandomAccessFile
	object org.apache.fontbox.ttf.RAFDataStream
	object org.apache.fontbox.ttf.TrueTypeFont
	object org.apache.pdfbox.pdmodel.font.PDType1Font
	method org.apache.camel.component.pdf.PdfConfiguration.<init>()
Call path from entry point to org.apache.camel.component.pdf.PdfConfiguration.<init>(): 
	at org.apache.camel.component.pdf.PdfConfiguration.<init>(PdfConfiguration.java:43)
	at org.apache.camel.component.pdf.PdfComponent.createEndpoint(PdfComponent.java:34)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:240)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:786)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:550)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:130)
	at org.apache.camel.processor.aggregate.AggregateProcessor$RecoverTask.run(AggregateProcessor.java:1339)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 	object org.apache.fontbox.ttf.BufferedRandomAccessFile
	object org.apache.fontbox.ttf.RAFDataStream
	object org.apache.fontbox.ttf.TrueTypeFont
	object org.apache.pdfbox.pdmodel.font.PDType1Font
	method org.apache.camel.component.pdf.PdfConfiguration.<init>()
Call path from entry point to org.apache.camel.component.pdf.PdfConfiguration.<init>(): 
	at org.apache.camel.component.pdf.PdfConfiguration.<init>(PdfConfiguration.java:43)
	at org.apache.camel.component.pdf.PdfComponent.createEndpoint(PdfComponent.java:34)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:240)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:786)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:550)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:130)
	at org.apache.camel.processor.aggregate.AggregateProcessor$RecoverTask.run(AggregateProcessor.java:1339)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a FileDescriptor in the image heap. File descriptors opened during image generation are no longer open at image run time, and the files might not even be present anymore at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 	object org.apache.fontbox.ttf.BufferedRandomAccessFile
	object org.apache.fontbox.ttf.RAFDataStream
	object org.apache.fontbox.ttf.TrueTypeFont
	object org.apache.pdfbox.pdmodel.font.PDType1Font
	method org.apache.camel.component.pdf.PdfConfiguration.<init>()
Call path from entry point to org.apache.camel.component.pdf.PdfConfiguration.<init>(): 
	at org.apache.camel.component.pdf.PdfConfiguration.<init>(PdfConfiguration.java:43)
	at org.apache.camel.component.pdf.PdfComponent.createEndpoint(PdfComponent.java:34)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:240)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:786)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.resolveMandatoryEndpoint(DefaultProducerTemplate.java:550)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:130)
	at org.apache.camel.processor.aggregate.AggregateProcessor$RecoverTask.run(AggregateProcessor.java:1339)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
	... 7 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.342 s
[INFO] Finished at: 2019-11-27T16:55:43+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.0.0.Final:native-image (native-image) on project camel-quarkus-integration-test-pdf: Failed to generate a native image: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:289)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:941)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:278)
[ERROR] 	... 12 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by aldettinger** [comment]
Discarded the change, and tests were passing on CI.

**Comment by ffang** [comment]
the native test failure comes back again with GraalVM Version 19.3.1 CE
```
native-image --version
GraalVM Version 19.3.1 CE
```

**Comment by jamesnetherton** [comment]
Yes, it's covered here https://github.com/apache/camel-quarkus/issues/670. 

It's not related to the GraalVM version.

**Comment by ffang** [comment]
@jamesnetherton ,thanks for the update!
