### ISSUE TITLE
Fhir test are not working in native mode

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#473]
See: https://builds.apache.org/job/camel-quarkus-pr/430/consoleFull

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: ca.uhn.fhir.rest.server.RestfulServerUtils. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.hl7.fhir.dstu3.hapi.rest.server.Dstu3BundleFactory.addResourcesToBundle(Dstu3BundleFactory.java:147)
Call path from entry point to org.hl7.fhir.dstu3.hapi.rest.server.Dstu3BundleFactory.addResourcesToBundle(List, BundleTypeEnum, String, BundleInclusionRule, Set): 
	at org.hl7.fhir.dstu3.hapi.rest.server.Dstu3BundleFactory.addResourcesToBundle(Dstu3BundleFactory.java:57)
	at ca.uhn.fhir.rest.client.method.BaseHttpClientInvocationWithContents.encodeContents(BaseHttpClientInvocationWithContents.java:177)
	at ca.uhn.fhir.rest.client.method.BaseHttpClientInvocationWithContents.asHttpRequest(BaseHttpClientInvocationWithContents.java:136)
	at ca.uhn.fhir.rest.client.method.HttpPutClientInvocation.asHttpRequest(HttpPutClientInvocation.java:28)
	at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:431)
	at ca.uhn.fhir.rest.client.impl.GenericClient$MetaInternal.execute(GenericClient.java:953)
	at org.apache.camel.component.fhir.api.FhirMeta.getFromServer(FhirMeta.java:49)
	at com.oracle.svm.reflect.FhirMeta_getFromServer_1817c6b7280f11bd10af4b5a0adf91bd06f782c8_51.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:118)
	at com.sun.proxy.$Proxy299.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:557)
	at com.oracle.svm.jni.access.JNIReflectionDictionary.getClassObjectByName(JNIReflectionDictionary.java:123)
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:326)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_FindClass_3ec1032c6cb9443725d1e68194130533bfb04076(generated:0)
```

**Comment by lburgazzoli** [comment]
I'm gogin to disable native image tests to make https://github.com/apache/camel-quarkus/pull/471 suceed

**Comment by johnpoth** [comment]
@lburgazzoli Camel 3 brings in a Major upgrade for FHIR (3-->4) so it's expected. I'll take a look
