### ISSUE TITLE
Native compile fails in some aggregation strategy which I am not using

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#477]
```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.reflect.Proxy.defineClass0(ClassLoader, String, byte[], int, int) is reachable: Native method. If you intend to use the Java Native Interface (JNI), specify -H:+JNI and see also -H:JNIConfigurationFiles=<path> (use -H:+PrintFlags for details)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Call path from entry point to java.lang.reflect.Proxy.defineClass0(ClassLoader, String, byte[], int, int):
	at java.lang.reflect.Proxy.defineClass0(Proxy.java)
	at java.lang.reflect.Proxy.access$300(Proxy.java:228)
	at com.oracle.svm.reflect.Proxy_access$300_c7f2160d72324f8fd5d02e2aa54a3c3562bea247_48.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.processor.aggregate.AggregationStrategyMethodInfo.invoke(AggregationStrategyMethodInfo.java:66)
	at org.apache.camel.processor.aggregate.AggregationStrategyBeanAdapter.aggregate(AggregationStrategyBeanAdapter.java:143)
	at org.apache.camel.processor.PollEnricher.process(PollEnricher.java:275)
	at org.apache.camel.processor.Resequencer.processExchange(Resequencer.java:302)
	at org.apache.camel.processor.Resequencer$BatchSender.sendExchanges(Resequencer.java:530)
	at org.apache.camel.processor.Resequencer$BatchSender.run(Resequencer.java:455)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:579)
	... 6 more
Error: Image build request failed with exit status 1
```

**Comment by davsclaus** [comment]
A simple Camel route calling a java bean
```
@ApplicationScoped
public class MyRoute extends RouteBuilder {

    @Inject
    MyBean myBean;

    @Override
    public void configure() throws Exception {
        from("direct:camel")
            .log("Hello Camel")
            .setBody(e -> myBean.doSomething());
    }

    
}
```

**Comment by davsclaus** [comment]
It smells like its when I have camel-quarkus-bean as dependency. If I remove that then it can build.

**Comment by lburgazzoli** [comment]
I think that if you add `--report-unsupported-elements-at-runtime` then the build will succeed and the application will run without problem, can you confirm if you have some time ?

**Comment by lburgazzoli** [comment]
looks like adding `<enableJni>true</enableJni>` to the quarkus plugin solved the issue, don't know the reason :(

**Comment by lburgazzoli** [comment]
`<enableJni>true</enableJni>` fixes the issue
