### ISSUE TITLE
[Quarkus 3.2.0] No recovery system in which to register XAResourceRecovery instance

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#4945]
The mybatis tests are failing on `quarkus-main`. There's a similar error coming from the JPA-JTA example project too.

```
2023-05-31T04:27:50.1755516Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2023-05-31T04:27:50.1755883Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-05-31T04:27:50.1756262Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-05-31T04:27:50.1756678Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-05-31T04:27:50.1757189Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-05-31T04:27:50.1757760Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-05-31T04:27:50.1758232Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-05-31T04:27:50.1758642Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:273)
2023-05-31T04:27:50.1759267Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:251)
2023-05-31T04:27:50.1759782Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:607)
2023-05-31T04:27:50.1760287Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
2023-05-31T04:27:50.1760880Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
2023-05-31T04:27:50.1761548Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2023-05-31T04:27:50.1762251Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
2023-05-31T04:27:50.1762933Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
2023-05-31T04:27:50.1763702Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
2023-05-31T04:27:50.1764410Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
2023-05-31T04:27:50.1764804Z 	... 36 more
2023-05-31T04:27:50.1765163Z Caused by: java.lang.IllegalStateException: ARJUNA032012: No recovery system in which to register XAResourceRecovery instance
2023-05-31T04:27:50.1765741Z 	at com.arjuna.ats.jbossatx.jta.RecoveryManagerService.addXAResourceRecovery(RecoveryManagerService.java:93)
2023-05-31T04:27:50.1766415Z 	at io.agroal.narayana.NarayanaTransactionIntegration.addResourceRecoveryFactory(NarayanaTransactionIntegration.java:132)
2023-05-31T04:27:50.1767063Z 	at io.agroal.pool.ConnectionPool.init(ConnectionPool.java:133)
2023-05-31T04:27:50.1767419Z 	at io.agroal.pool.DataSource.<init>(DataSource.java:42)
2023-05-31T04:27:50.1767839Z 	at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:246)
2023-05-31T04:27:50.1768373Z 	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:129)
2023-05-31T04:27:50.1768759Z 	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:126)
2023-05-31T04:27:50.1769228Z 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
2023-05-31T04:27:50.1769724Z 	at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:126)
2023-05-31T04:27:50.1770163Z 	at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:122)
2023-05-31T04:27:50.1770650Z 	at io.quarkus.agroal.runtime.AgroalRecorder.agroalDataSourceSupplier(AgroalRecorder.java:23)
```

**Comment by jamesnetherton** [comment]
@zhfeng maybe related to https://github.com/quarkusio/quarkus/commit/c2546e70fd5e75a981f292a79a0d378243b0f9a0? Maybe we have some missing config etc.

**Comment by zhfeng** [comment]
Yeah, I think so and will take a look. Which test is failling?

**Comment by jamesnetherton** [comment]
> Which test is failing?

Here's a link to the build:

https://github.com/apache/camel-quarkus/actions/runs/5128205009

**Comment by zhfeng** [comment]
Thanks @jamesnetherton and I confirm that it should be an issue when we introduce the feature of JDBC Object Store. It need to defer to register the XAResourceRecovery after the recovery manager service is started. I was missing such test case in the quarkus. I will open an issue on quarkus soon.

**Comment by zhfeng** [comment]
Hi @jamesnetherton , the [fix](https://github.com/quarkusio/quarkus/pull/33729) in upstream quarkus has been merged into `main` branch.

**Comment by jamesnetherton** [comment]
Thanks @zhfeng. Confirmed that the issues in CQ are resolved.
