### ISSUE TITLE
[Mandrel 23.0.0] cxf-soap grouped integration tests native compilation fails

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5008]
### Bug description

FYI @ppalaga not sure if you've seen this before or have been testing `quarkus-cxf` with Quarkus 3.2.0.

```
2023-06-22T14:52:08.2232052Z Error: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
2023-06-22T14:52:08.2236304Z Trace: Object was reached by
2023-06-22T14:52:08.2236679Z   trying to constant fold static field org.opensaml.xmlsec.signature.impl.X509CRLImpl.CLEANER
2023-06-22T14:52:08.2237160Z     at org.opensaml.xmlsec.signature.impl.X509CRLImpl.setValue(X509CRLImpl.java:81)
2023-06-22T14:52:08.2237909Z   parsing method org.opensaml.xmlsec.signature.impl.X509CRLImpl.setValue(X509CRLImpl.java:70) reachable via the parsing context
2023-06-22T14:52:08.2238563Z     at org.opensaml.core.xml.schema.impl.XSBase64BinaryUnmarshaller.processElementContent(XSBase64BinaryUnmarshaller.java:38)
2023-06-22T14:52:08.2239278Z     at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallTextContent(AbstractXMLObjectUnmarshaller.java:354)
2023-06-22T14:52:08.2239938Z     at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:130)
2023-06-22T14:52:08.2240491Z     at org.apache.wss4j.common.saml.OpenSAMLUtil.fromDom(OpenSAMLUtil.java:158)
2023-06-22T14:52:08.2240998Z     at org.apache.wss4j.common.saml.SamlAssertionWrapper.parseElement(SamlAssertionWrapper.java:983)
2023-06-22T14:52:08.2241519Z     at org.apache.wss4j.common.saml.SamlAssertionWrapper.<init>(SamlAssertionWrapper.java:184)
2023-06-22T14:52:08.2242018Z     at org.apache.wss4j.dom.action.SAMLTokenSignedAction.execute(SAMLTokenSignedAction.java:71)
2023-06-22T14:52:08.2242497Z     at org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:240)
2023-06-22T14:52:08.2247818Z     at root method.(Unknown Source)
2023-06-22T14:52:08.2247980Z 
2023-06-22T14:52:08.2249300Z Error: Detected a java.lang.ref.Cleaner object in the image heap which uses a daemon thread that invokes cleaning actions, but threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.lang.ref.Cleaner. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
2023-06-22T14:52:08.2250463Z Trace: Object was reached by
2023-06-22T14:52:08.2250873Z   trying to constant fold static field org.opensaml.xmlsec.signature.impl.X509CertificateImpl.CLEANER
2023-06-22T14:52:08.2251427Z     at org.opensaml.xmlsec.signature.impl.X509CertificateImpl.setValue(X509CertificateImpl.java:84)
2023-06-22T14:52:08.2252048Z   parsing method org.opensaml.xmlsec.signature.impl.X509CertificateImpl.setValue(X509CertificateImpl.java:73) reachable via the parsing context
2023-06-22T14:52:08.2252737Z     at org.opensaml.core.xml.schema.impl.XSBase64BinaryUnmarshaller.processElementContent(XSBase64BinaryUnmarshaller.java:38)
2023-06-22T14:52:08.2253740Z     at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallTextContent(AbstractXMLObjectUnmarshaller.java:354)
2023-06-22T14:52:08.2254398Z     at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:130)
2023-06-22T14:52:08.2254922Z     at org.apache.wss4j.common.saml.OpenSAMLUtil.fromDom(OpenSAMLUtil.java:158)
2023-06-22T14:52:08.2255431Z     at org.apache.wss4j.common.saml.SamlAssertionWrapper.parseElement(SamlAssertionWrapper.java:983)
2023-06-22T14:52:08.2255950Z     at org.apache.wss4j.common.saml.SamlAssertionWrapper.<init>(SamlAssertionWrapper.java:184)
2023-06-22T14:52:08.2256454Z     at org.apache.wss4j.dom.action.SAMLTokenSignedAction.execute(SAMLTokenSignedAction.java:71)
2023-06-22T14:52:08.2256942Z     at org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:240)
2023-06-22T14:52:08.2257285Z     at root method.(Unknown Source)
```

**Comment by ppalaga** [comment]
Thanks for the heads up, @jamesnetherton. I have not seen that one yet, trying to upgrade in QCXF right now. Let's see if it pops up there too.

**Comment by ppalaga** [comment]
Yes, it needs to get fixed [in QCXF](https://github.com/quarkiverse/quarkus-cxf/pull/924/files#diff-e6a9c646bed1481441595503423f31c49a0e6ccf55321b26ab6a1f42502a0d05R98-R105).
