### ISSUE TITLE
HazelcastMapTest fails when run after HazelcastIdempotentTest and HazelcastInstanceTest

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#5081]
### Bug description

steps to reproduce: 

```
mvnd clean test -Dtest=HazelcastIdempotentTest,HazelcastInstanceTest,HazelcastMapTest
...
[INFO] Running org.apache.camel.quarkus.component.hazelcast.it.HazelcastIdempotentTest
2023-07-07 18:46:18,477 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] (pool-3-thread-1) Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2023-07-07 18:46:18,485 INFO  [com.haz.int.con.AbstractConfigLocator] (pool-3-thread-1) Loading 'hazelcast.xml' from the classpath.
2023-07-07 18:46:18,517 WARNING [com.haz.con.AbstractXmlConfigHelper] (pool-3-thread-1) Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd] is incorrect, using default
2023-07-07 18:46:18,653 INFO  [com.haz.ins.AddressPicker] (pool-3-thread-1) [LOCAL] [dev] [5.2.3] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [127.0.0.1]
2023-07-07 18:46:18,668 INFO  [com.haz.sys.logo] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2023-07-07 18:46:18,668 INFO  [com.haz.system] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2023-07-07 18:46:18,668 INFO  [com.haz.system] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Hazelcast Platform 5.2.3 (20230323 - 30f246a) starting at [127.0.0.1]:5701
2023-07-07 18:46:18,668 INFO  [com.haz.system] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Cluster name: dev
2023-07-07 18:46:18,668 INFO  [com.haz.system] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
2023-07-07 18:46:18,670 INFO  [com.haz.system] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-07-07 18:46:18,838 INFO  [com.haz.sys.security] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2023-07-07 18:46:18,864 INFO  [com.haz.ins.imp.Node] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Using TCP/IP discovery
2023-07-07 18:46:18,864 WARNING [com.haz.cp.CPSubsystem] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2023-07-07 18:46:18,976 INFO  [com.haz.int.dia.Diagnostics] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-07-07 18:46:18,980 INFO  [com.haz.cor.LifecycleService] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] [127.0.0.1]:5701 is STARTING
2023-07-07 18:46:18,994 INFO  [com.haz.int.clu.ClusterService] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 22e714e8-5148-403c-abff-eed8f8969c6b this
]

2023-07-07 18:46:19,000 INFO  [com.haz.cor.LifecycleService] (pool-3-thread-1) [127.0.0.1]:5701 [dev] [5.2.3] [127.0.0.1]:5701 is STARTED
2023-07-07 18:46:19,490 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2023-07-07 18:46:19,491 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.0.0-RC1 is starting
2023-07-07 18:46:19,527 INFO  [com.haz.int.con.AbstractConfigLocator] (main) Loading 'hazelcast-client-default.xml' from the classpath.
2023-07-07 18:46:19,566 INFO  [com.haz.cli.imp.spi.ClientInvocationService] (main) hz.client_1 [dev] [5.2.3] Running with 2 response threads, dynamic=true
2023-07-07 18:46:19,572 INFO  [com.haz.cor.LifecycleService] (main) hz.client_1 [dev] [5.2.3] HazelcastClient 5.2.3 (20230323 - 30f246a) is STARTING
2023-07-07 18:46:19,572 INFO  [com.haz.cor.LifecycleService] (main) hz.client_1 [dev] [5.2.3] HazelcastClient 5.2.3 (20230323 - 30f246a) is STARTED
2023-07-07 18:46:19,575 INFO  [com.haz.cli.imp.con.ClientConnectionManager] (main) hz.client_1 [dev] [5.2.3] Trying to connect to cluster: dev
2023-07-07 18:46:19,576 INFO  [com.haz.cli.imp.con.ClientConnectionManager] (main) hz.client_1 [dev] [5.2.3] Trying to connect to [localhost]:5701
2023-07-07 18:46:19,585 INFO  [com.haz.cli.imp.pro.tas.AuthenticationMessageTask] (hz.admiring_almeida.priority-generic-operation.thread-0) [127.0.0.1]:5701 [dev] [5.2.3] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:51501, qualifier=null, endpoint=[127.0.0.1]:51501, remoteUuid=e60f4695-638f-47db-9f70-21771fbd6d3d, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: e60f4695-638f-47db-9f70-21771fbd6d3d, client name: hz.client_1, client version: 5.2.3
2023-07-07 18:46:19,586 INFO  [com.haz.cor.LifecycleService] (main) hz.client_1 [dev] [5.2.3] HazelcastClient 5.2.3 (20230323 - 30f246a) is CLIENT_CONNECTED
2023-07-07 18:46:19,586 INFO  [com.haz.cli.imp.con.ClientConnectionManager] (main) hz.client_1 [dev] [5.2.3] Authenticated with server [127.0.0.1]:5701:22e714e8-5148-403c-abff-eed8f8969c6b, server version: 5.2.3, local address: /127.0.0.1:51501
2023-07-07 18:46:19,587 INFO  [com.haz.int.dia.Diagnostics] (main) hz.client_1 [dev] [5.2.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-07-07 18:46:19,590 INFO  [com.haz.cli.imp.spi.ClientClusterService] (hz.client_1.event-7) hz.client_1 [dev] [5.2.3] 

Members [1] {
	Member [127.0.0.1]:5701 - 22e714e8-5148-403c-abff-eed8f8969c6b
}

2023-07-07 18:46:19,602 INFO  [com.haz.cli.imp.sta.ClientStatisticsService] (main) Client statistics is enabled with period 5 seconds.
2023-07-07 18:46:19,721 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-RC1 (camel-1) is starting
2023-07-07 18:46:19,727 INFO  [com.haz.int.par.imp.PartitionStateManager] (hz.admiring_almeida.partition-operation.thread-20) [127.0.0.1]:5701 [dev] [5.2.3] Initializing cluster partition table arrangement...
2023-07-07 18:46:19,746 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:14)
2023-07-07 18:46:19,746 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (hazelcast-list://foo-list)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route2 (hazelcast-map://foo-map)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route3 (hazelcast-multimap://foo-multimap)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route4 (hazelcast-replicatedmap://foo-replicate)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route5 (hazelcast-set://foo-set)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route6 (hazelcast-topic://foo-topic)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route7 (hazelcast-queue://foo-queue)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route8 (hazelcast-queue://foo-queue-poll)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route9 (hazelcast-seda://foo-fifo)
2023-07-07 18:46:19,747 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route10 (hazelcast-seda://foo-in-only)
2023-07-07 18:46:19,748 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route11 (hazelcast-seda://foo-in-out)
2023-07-07 18:46:19,748 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route12 (hazelcast-instance://foo-instance)
2023-07-07 18:46:19,748 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route13 (direct://in-idempotent)
2023-07-07 18:46:19,748 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started id-value (direct://in-policy)
2023-07-07 18:46:19,748 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-RC1 (camel-1) started in 26ms (build:0ms init:0ms start:26ms)
2023-07-07 18:46:19,763 INFO  [org.apa.cam.com.haz.pol.HazelcastRoutePolicy] (Camel (camel-1) thread #1 - HazelcastRoutePolicy) Leadership taken (map=camel:lock:map, key=route-policy, val=id-value)
2023-07-07 18:46:19,806 INFO  [io.quarkus] (main) camel-quarkus-integration-test-hazelcast 3.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.0.Final) started in 2.350s. Listening on: http://localhost:8081
2023-07-07 18:46:19,807 INFO  [io.quarkus] (main) Profile test activated. 
2023-07-07 18:46:19,807 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-direct, camel-hazelcast, cdi, hazelcast-client, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.936 s -- in org.apache.camel.quarkus.component.hazelcast.it.HazelcastIdempotentTest
[INFO] Running org.apache.camel.quarkus.component.hazelcast.it.HazelcastInstanceTest
2023-07-07 18:46:20,773 INFO  [com.haz.int.con.AbstractConfigLocator] (main) Loading 'hazelcast.xml' from the classpath.
2023-07-07 18:46:20,779 WARNING [com.haz.con.AbstractXmlConfigHelper] (main) Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd] is incorrect, using default
2023-07-07 18:46:20,803 INFO  [com.haz.ins.AddressPicker] (main) [LOCAL] [dev] [5.2.3] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [127.0.0.1]
2023-07-07 18:46:20,804 INFO  [com.haz.sys.logo] (main) [127.0.0.1]:5702 [dev] [5.2.3] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2023-07-07 18:46:20,804 INFO  [com.haz.system] (main) [127.0.0.1]:5702 [dev] [5.2.3] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2023-07-07 18:46:20,804 INFO  [com.haz.system] (main) [127.0.0.1]:5702 [dev] [5.2.3] Hazelcast Platform 5.2.3 (20230323 - 30f246a) starting at [127.0.0.1]:5702
2023-07-07 18:46:20,804 INFO  [com.haz.system] (main) [127.0.0.1]:5702 [dev] [5.2.3] Cluster name: dev
2023-07-07 18:46:20,804 INFO  [com.haz.system] (main) [127.0.0.1]:5702 [dev] [5.2.3] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
2023-07-07 18:46:20,804 INFO  [com.haz.system] (main) [127.0.0.1]:5702 [dev] [5.2.3] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-07-07 18:46:20,814 INFO  [com.haz.sys.security] (main) [127.0.0.1]:5702 [dev] [5.2.3] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2023-07-07 18:46:20,815 INFO  [com.haz.ins.imp.Node] (main) [127.0.0.1]:5702 [dev] [5.2.3] Using TCP/IP discovery
2023-07-07 18:46:20,816 WARNING [com.haz.cp.CPSubsystem] (main) [127.0.0.1]:5702 [dev] [5.2.3] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2023-07-07 18:46:20,824 INFO  [com.haz.int.dia.Diagnostics] (main) [127.0.0.1]:5702 [dev] [5.2.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-07-07 18:46:20,824 INFO  [com.haz.cor.LifecycleService] (main) [127.0.0.1]:5702 [dev] [5.2.3] [127.0.0.1]:5702 is STARTING
2023-07-07 18:46:20,829 INFO  [com.haz.int.ser.tcp.TcpServerConnector] (hz.compassionate_almeida.cached.thread-3) [127.0.0.1]:5702 [dev] [5.2.3] Connecting to /127.0.0.1:5701, timeout: 10000, bind-any: true
2023-07-07 18:46:20,830 INFO  [com.haz.int.ser.tcp.TcpServerConnection] (hz.admiring_almeida.IO.thread-in-1) [127.0.0.1]:5701 [dev] [5.2.3] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:41921
2023-07-07 18:46:20,830 INFO  [com.haz.int.ser.tcp.TcpServerConnection] (hz.compassionate_almeida.IO.thread-in-0) [127.0.0.1]:5702 [dev] [5.2.3] Initialized new cluster connection between /127.0.0.1:41921 and /127.0.0.1:5701
2023-07-07 18:46:25,839 INFO  [com.haz.cli.imp.spi.ClientClusterService] (hz.client_1.event-7) hz.client_1 [dev] [5.2.3] 

Members [2] {
	Member [127.0.0.1]:5701 - 22e714e8-5148-403c-abff-eed8f8969c6b
	Member [127.0.0.1]:5702 - bee0d553-87c2-434b-894e-dfb31963318f
}

2023-07-07 18:46:25,839 INFO  [com.haz.int.clu.ClusterService] (hz.admiring_almeida.priority-generic-operation.thread-0) [127.0.0.1]:5701 [dev] [5.2.3] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 22e714e8-5148-403c-abff-eed8f8969c6b this
	Member [127.0.0.1]:5702 - bee0d553-87c2-434b-894e-dfb31963318f
]

2023-07-07 18:46:25,840 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-7) instance...
2023-07-07 18:46:25,840 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-7) ...added
2023-07-07 18:46:25,844 INFO  [com.haz.int.clu.ClusterService] (hz.compassionate_almeida.priority-generic-operation.thread-0) [127.0.0.1]:5702 [dev] [5.2.3] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 22e714e8-5148-403c-abff-eed8f8969c6b
	Member [127.0.0.1]:5702 - bee0d553-87c2-434b-894e-dfb31963318f this
]

2023-07-07 18:46:25,845 INFO  [com.haz.cor.LifecycleService] (main) [127.0.0.1]:5702 [dev] [5.2.3] [127.0.0.1]:5702 is STARTED
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.186 s -- in org.apache.camel.quarkus.component.hazelcast.it.HazelcastInstanceTest
[INFO] Running org.apache.camel.quarkus.component.hazelcast.it.HazelcastMapTest
2023-07-07 18:46:25,975 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-7) object...
2023-07-07 18:46:25,975 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-7) ...added
2023-07-07 18:46:26,000 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) object...
2023-07-07 18:46:26,001 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) ...added
2023-07-07 18:46:26,102 INFO  [com.haz.int.par.imp.MigrationManager] (hz.admiring_almeida.migration) [127.0.0.1]:5701 [dev] [5.2.3] Repartitioning cluster data. Migration tasks count: 271
2023-07-07 18:46:26,198 INFO  [com.haz.int.par.imp.MigrationManager] (hz.admiring_almeida.migration) [127.0.0.1]:5701 [dev] [5.2.3] All migration tasks have been completed. (repartitionTime=Fri Jul 07 18:46:26 CEST 2023, plannedMigrations=271, completedMigrations=271, remainingMigrations=0, totalCompletedMigrations=271)
2023-07-07 18:46:26,594 INFO  [com.haz.cli.imp.pro.tas.AuthenticationMessageTask] (hz.compassionate_almeida.priority-generic-operation.thread-0) [127.0.0.1]:5702 [dev] [5.2.3] Received auth from Connection[id=2, /127.0.0.1:5702->/127.0.0.1:56365, qualifier=null, endpoint=[127.0.0.1]:56365, remoteUuid=e60f4695-638f-47db-9f70-21771fbd6d3d, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: e60f4695-638f-47db-9f70-21771fbd6d3d, client name: hz.client_1, client version: 5.2.3
2023-07-07 18:46:26,595 INFO  [com.haz.cli.imp.con.ClientConnectionManager] (hz.client_1.internal-5) hz.client_1 [dev] [5.2.3] Authenticated with server [127.0.0.1]:5702:bee0d553-87c2-434b-894e-dfb31963318f, server version: 5.2.3, local address: /127.0.0.1:56365
2023-07-07 18:46:31,476 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) object...
2023-07-07 18:46:31,476 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) ...updated
2023-07-07 18:46:31,493 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) object...
2023-07-07 18:46:31,494 INFO  [org.apa.cam.qua.com.haz.it.HazelcastRoutes] (hz.client_1.event-8) ...evicted
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.74 s <<< FAILURE! -- in org.apache.camel.quarkus.component.hazelcast.it.HazelcastMapTest
[ERROR] org.apache.camel.quarkus.component.hazelcast.it.HazelcastMapTest.testMap -- Time elapsed: 15.74 s <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with org.apache.camel.quarkus.component.hazelcast.it.HazelcastMapTest was not fulfilled within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at org.apache.camel.quarkus.component.hazelcast.it.HazelcastMapTest.testMap(HazelcastMapTest.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1015)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:829)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

**Comment by ppalaga** [comment]
It looks like the HazelcastInstanceTest calling HazelcastTestResource.addMemberToCluster() makes the HazelcastMapTest fail, but only if some other test (e.g. HazelcastIdempotentTest) was run before HazelcastInstanceTest.

I am not sure the fix in https://github.com/apache/camel-quarkus/pull/5082/files is actually not sweeping the real issue under the carpet. I guess the subsequent tests should work regardless of how many nodes the cluster has? And I guess all these tests were passing in the past?

**Comment by zhfeng** [comment]
@ppalaga is there any update?

**Comment by ppalaga** [comment]
> @ppalaga is there any update?

Not really. I do not feel to be a Hazelcast and camel-hazelcast expert to tell whether cluster topology changes happening after a Camel app was started are expected to impact the events received by the app. Here apparently, if a node is added, the app does not receive some events after that. Is that expected @davsclaus?

**Comment by jamesnetherton** [comment]
Not sure if the problem is with test order as this issue title implies.

When the failure occurs, the `hazelcast-map:foo-map` route `when` clause for the `removed` action never runs. I see the `ProducerTemplate` send the delete request, but it never seems to arrive at the Camel route.

I notice on failure this log message after the delete request is sent:

```
2023-11-23 08:52:47,883 INFO  [com.haz.cli.imp.pro.tas.AuthenticationMessageTask] (hz.cranky_booth.priority-generic-operation.thread-0) [127.0.0.1]:5702 [dev] [5.2.3] Received auth from Connection[id=2, /127.0.0.1:5702->/127.0.0.1:59105, qualifier=null, endpoint=[127.0.0.1]:59105, remoteUuid=92c14817-b631-4d7e-83da-8e2d6805bf5b, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 92c14817-b631-4d7e-83da-8e2d6805bf5b, client name: hz.client_1, client version: 5.2.3
```

When the test is successful, this message comes far earlier before the tests run. Maybe there is some kind of race with Hazelcast sometimes not being fully initialized before tests run?

**Comment by jamesnetherton** [comment]
Turns out this is partially related to test ordering.

The problem is that `HazelcastInstanceTest` adds a new member instance to the cluster, but it does not wait or verify that it was shut down after the test completes. In fact, it currently does not shut down the [correct member](https://github.com/apache/camel-quarkus/blob/main/integration-tests/hazelcast/src/test/java/org/apache/camel/quarkus/component/hazelcast/it/HazelcastTestResource.java#L42).

Thus when the other tests run afterwards, the cluster can be temporarily in a state where operations can fail.
