### ISSUE TITLE
MicrometerTest.testJMXQuarkusDomain() fail with Quarkus Platform BOMs

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#5086]
### Bug description

The two `MicrometerTest.testJMXQuarkusDomain()` fail on Quarkus Platfrom.

Steps to reproduce

```
cd quarkus-platform
git remote add ppalaga git@github.com:ppalaga/quarkus-platform.git
git fetch ppalaga 230707-cq-3.0.0-CR1
git checkout 230707-cq-3.0.0-CR1
./mvnw clean install -DskipTests

cd generated-platform-project/quarkus-camel/integration-tests/camel-quarkus-integration-test-micrometer
mvn clean test -Dtest=MicrometerTest#testJMXQuarkusDomain

...
[INFO] Running org.apache.camel.quarkus.component.micrometer.it.MicrometerTest
[INFO] [stdout] 2023-07-10 14:59:53,100 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.https.test-port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] [stdout] 2023-07-10 14:59:53,694 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[INFO] [stdout] 2023-07-10 14:59:53,696 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.0.0-RC1 is starting
[INFO] [stdout] 2023-07-10 14:59:53,743 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
[INFO] [stdout] 2023-07-10 14:59:53,743 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.context.name=quarkus-camel-micrometer
[INFO] [stdout] 2023-07-10 14:59:53,953 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-RC1 (quarkus-camel-micrometer) is starting
[INFO] [stdout] 2023-07-10 14:59:53,956 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Using ThreadPoolFactory: org.apache.camel.component.micrometer.spi.InstrumentedThreadPoolFactory@10ec54c3
[INFO] [stdout] 2023-07-10 14:59:53,964 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Using 2 instances of same component class: org.apache.camel.component.micrometer.MicrometerComponent with names: micrometer, micrometerCustom
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:7)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (direct://counter)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route2 (direct://counterComposite)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route3 (direct://counterCustom)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route4 (direct://summary)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started micrometer-metrics-timer (direct://timer)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started log (direct://log)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route5 (direct://annotatedBean)
[INFO] [stdout] 2023-07-10 14:59:53,965 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0-RC1 (quarkus-camel-micrometer) started in 12ms (build:0ms init:0ms start:12ms)
[INFO] [stdout] 2023-07-10 14:59:54,074 INFO  [io.quarkus] (main) camel-quarkus-integration-test-micrometer 999-SNAPSHOT on JVM (powered by Quarkus 3.2.0.Final) started in 2.763s. Listening on: http://localhost:42667
[INFO] [stdout] 2023-07-10 14:59:54,074 INFO  [io.quarkus] (main) Profile test activated. 
[INFO] [stdout] 2023-07-10 14:59:54,075 INFO  [io.quarkus] (main) Installed features: [camel-bean, camel-core, camel-direct, camel-log, camel-micrometer, cdi, micrometer, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 5.629 s <<< FAILURE! - in org.apache.camel.quarkus.component.micrometer.it.MicrometerTest
[ERROR] org.apache.camel.quarkus.component.micrometer.it.MicrometerTest.testJMXQuarkusDomain(String)[1]  Time elapsed: 0.243 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at org.apache.camel.quarkus.component.micrometer.it.MicrometerTest.testJMXQuarkusDomain(MicrometerTest.java:210)
[ERROR] org.apache.camel.quarkus.component.micrometer.it.MicrometerTest.testJMXQuarkusDomain(String)[2]  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:528)
        at org.apache.camel.quarkus.component.micrometer.it.MicrometerTest.testJMXQuarkusDomain(MicrometerTest.java:210)
```

Note that the test also fails when executed against the Platform BOMs (after installing them as sketched above) from within Camel Quarkus source tree:

```
cd camel-quarkus
git checkout 3.0.0-RC1
mvnd clean install -Dquickly
cd integration-tests/micrometer

mvn clean test -DnoVirtualDependencies   -Dquarkus.platform.group-id=io.quarkus.platform   -Dquarkus.platform.artifact-id=quarkus-bom   -Dquarkus.platform.version=999-SNAPSHOT   -Dcamel-quarkus.platform.group-id=io.quarkus.platform   -Dcamel-quarkus.platform.artifact-id=quarkus-camel-bom   -Dcamel-quarkus.platform.version=999-SNAPSHOT   -Dcamel-quarkus.version=3.0.0-SNAPSHOT -Dtest=MicrometerTest#testJMXQuarkusDomain
```

The second test run proves that the issue has nothing to do reading local files. 

I thought there might be some difference in dependency versions, but running `mvn org.apache.maven.plugins:maven-dependency-plugin:3.6.0:tree` with and without `-Dquarkus.platform.group-id=io.quarkus.platform   -Dquarkus.platform.artifact-id=quarkus-bom   -Dquarkus.platform.version=999-SNAPSHOT   -Dcamel-quarkus.platform.group-id=io.quarkus.platform   -Dcamel-quarkus.platform.artifact-id=quarkus-camel-bom   -Dcamel-quarkus.platform.version=999-SNAPSHOT   -Dcamel-quarkus.version=3.0.0-RC1` does not show any important difference.

**Comment by jamesnetherton** [comment]
For some reason, when the tests run in the platform, the JMX metric `ObjectName` is slightly different. It is suffixed with `,type=gauges`. This seems to not be the case when the test runs with the CQ project.

**Comment by jamesnetherton** [comment]
There are some conflicting versions due to `debezium-bom` managing `metrics-core`:

```
[INFO] |        \- io.dropwizard.metrics:metrics-jmx:jar:4.2.19:compile
[INFO] |           \- io.dropwizard.metrics:metrics-core:jar:4.0.1:compile
```

It's probably better to manage these ourselves and not rely on a third party to do it.
