### ISSUE TITLE
cxf-soap `CxfSoapConverterTest` fails with `NoSuchMethodError`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5108]
### Bug description

`CxfSoapConverterTest` is failing with the latest Quarkus SNAPSHOT with:

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /soapservice/PayLoadConvert/RouterPort failed, error id: c2287777-e2c3-4707-97f2-fc9b785d32e3-1: java.lang.NoSuchMethodError: 'void io.quarkus.arc.ManagedContext.activate()'
 	at io.quarkiverse.cxf.transport.CxfHandler.process(CxfHandler.java:230)
 	at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:182)
 	at io.quarkiverse.cxf.transport.CxfHandler.handle(CxfHandler.java:46)
 	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
 	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
 	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Probably related to some reworking of `ManagedContext`:

https://github.com/quarkusio/quarkus/commit/ccabce0630eaf1fc2d0bb53964a6668c789e0b5a

**Comment by jamesnetherton** [comment]
Fixed in #5236.
