### ISSUE TITLE
Debezium tests fail with NoSuchMethodException

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5110]
### Bug description

Quarkus has upgraded to Kafka 3.5.0, but the version of Debezium we use aligns with 3.4.0.

Kafka 3.5.0 Seems to be supported in Debezium 2.4.x, but there is only an alpha release at present. 

```
 Unable to instantiate OffsetBackingStore class 'org.apache.kafka.connect.storage.FileOffsetBackingStore': java.lang.NoSuchMethodException: org.apache.kafka.connect.storage.FileOffsetBackingStore.<init>()
 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
 	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
 	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:732)
 	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:229)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5674.
