### ISSUE TITLE
[camel-main] BOX (native & JVM )fails because of okhttp 3.x vs 4.x problem

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5160]
### Bug description

Recent upgrade of Box-sdk-java in https://github.com/apache/camel/commit/29b6d20b6a9e8ebd87141cc0eaf179b385400e95
brought dependency on "com.squareup.okhttp3:okhttp:4.10.0. 
Quarkus forces in its BOM version 3.14.9 (see https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L177)
(There is a bunch of issues about old okhttp3 dependencies in Quarkus, but nothing shows any kind of solution for the future e.g. https://github.com/quarkusio/quarkus/issues/12680, https://github.com/instagram4j/instagram4j/issues/533)

Having okhttp 3.14.9 with the updated box-sdk, native build fails with:

```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: okhttp3.OkHttpClient$Builder.<init>(okhttp3.OkHttpClient). This error is reported at image build time because class com.box.sdk.BoxAPIConnection is registered for linking at image build time by command line

```

JVM error:

```
Caused by: java.lang.IllegalAccessError: class com.box.sdk.BoxAPIConnection tried to access method 'void okhttp3.OkHttpClient$Builder.<init>(okhttp3.OkHttpClient)' (com.box.sdk.BoxAPIConnection and okhttp3.OkHttpClient$Builder are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @73d62b5)
        at com.box.sdk.BoxAPIConnection.buildHttpClients(BoxAPIConnection.java:240)
        at com.box.sdk.BoxAPIConnection.<init>(BoxAPIConnection.java:166)
        at com.box.sdk.BoxAPIConnection.<init>(BoxAPIConnection.java:177)
```

Native profile of the test  module is disabled, to make CI pass this issue.

**Comment by ppalaga** [comment]
For this particular error, we could try to suggest a fix to Box: `OkHttpClient.Builder(httpClient)` is not public in 3.x but `httpClient.newBuilder()` would do the same. `httpClient.newBuilder()` is available in 3.x and I hope it is there also in 4.x.

We should try to propose reverting the upgrade in Camel for now.

**Comment by JiriOndrusek** [comment]
@jamesnetherton already asked on Camel Zulip: https://camel.zulipchat.com/#narrow/stream/364655-camel-v4-work-in-progress/topic/Camel.20v4.20.28help.20wanted.29/near/383197687 

@ppalaga ^^^
