### ISSUE TITLE
Infinispan failing with Quarkus 3.3.1

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#5237]
### Bug description

Error is
```
Caused by: java.lang.NoSuchMethodError: 'org.infinispan.client.hotrod.configuration.ConfigurationBuilder org.infinispan.client.hotrod.configuration.ConfigurationBuilder.read(org.infinispan.client.hotrod.configuration.Configuration)'
	at org.apache.camel.component.infinispan.remote.InfinispanRemoteAggregationRepository.doStart(InfinispanRemoteAggregationRepository.java:65)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:113)
```

**Comment by zbendhiba** [comment]
Hello @karesti, can you help with this?

**Comment by zbendhiba** [comment]
Disabling tests not working either because GraalVm is detecting the missing method on build time
`Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.infinispan.client.hotrod.configuration.ConfigurationBuilder.read(org.infinispan.client.hotrod.configuration.Configuration). This error is reported at image build time because class org.apache.camel.component.infinispan.remote.InfinispanRemoteAggregationRepository is registered for linking at image build time by command line`

**Comment by karesti** [comment]
@zbendhiba unless this can wait for monday, ask the team @tristantarrant @wburns

**Comment by tristantarrant** [comment]
We're making the change in 14.0.15.Final, so that's not an issue.

**Comment by jamesnetherton** [comment]
I think we're good since 3.4.x. Tests were enabled again and are passing.
