### ISSUE TITLE
Opentelemetry failing with Quarkus 3.3.1

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#5240]
### Bug description

Test in native is failing.
This needs investigation, as Quarkus 3.3 come with improvements in Opentelemetry.

Log message is not clear 
```
Z ERROR: Failed to start application (with profile [prod])
2023-08-30T14:22:38.6975070Z java.lang.RuntimeException: Failed to start quarkus
2023-08-30T14:22:38.6975906Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-08-30T14:22:38.6976354Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-08-30T14:22:38.6976822Z 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
2023-08-30T14:22:38.6977258Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2023-08-30T14:22:38.6977581Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
2023-08-30T14:22:38.6977927Z 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
2023-08-30T14:22:38.6978293Z 	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2023-08-30T14:22:38.6978643Z Caused by: java.lang.NullPointerException
2023-08-30T14:22:38.6979117Z 	at io.quarkus.runtime.configuration.ConfigRecorder.handleConfigChange(ConfigRecorder.java:44)
2023-08-30T14:22:38.6979820Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy_6(Unknown Source)
2023-08-30T14:22:38.6980530Z 	at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy(Unknown Source)
2023-08-30T14:22:38.6980959Z 	... 7 more
```

**Comment by jamesnetherton** [comment]
It's related to 9ec9f2b05b05976f151abb5591462460cf9895a3 and resolution of:

```
quarkus.datasource."postgres".devservices.image-name=${postgres.container.image}
```

The test container properties are defined in `microprofile-config.properties` in the test JAR. So referencing them in  `application.properties` for resolution at runtime in native mode is perhaps conceptually wrong.

I can follow up with the Quarkus folks about whether it should be considered a genuine regression between 3.2 & 3.3. Until then, it's simplest to use `QuarkusTestResource` and just resolve `postgres.container.image` on the test side like we do for every other test that uses containers.
