### ISSUE TITLE
Remove workaround for NoClassDefFoundError DevConsoleTemplateInfoBuildItem

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5277]
### Description

Relates to an issue encountered when upgrading to Quarkus 3.4.0.CR1. More background here:

https://github.com/quarkusio/quarkus-platform/pull/973#issuecomment-1709202024

Optaplanner and Quarkus CXF (FYI @ppalaga) are affected by it.

```
Caused by: java.lang.NoClassDefFoundError: io/quarkus/devconsole/spi/DevConsoleRuntimeTemplateInfoBuildItem
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
        at io.quarkus.deployment.ExtensionLoader.getMethods(ExtensionLoader.java:931)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFromClass(ExtensionLoader.java:441)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:171)
        ... 50 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.devconsole.spi.DevConsoleRuntimeTemplateInfoBuildItem
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        ... 56 more
```

It can be worked around by adding `quarkus-vertx-http-dev-console-spi` as a deployment dependency to the affected extensions.

**Comment by jamesnetherton** [comment]
QCXF is fixed. The workaround remains in place for optaplanner until this issue is resolved:

https://issues.redhat.com/browse/PLANNER-2936

**Comment by jamesnetherton** [comment]
Fixed by https://github.com/apache/camel-quarkus/pull/7413.
