### ISSUE TITLE
DataformatTest.snakeYaml test throws NoClassDefFoundError trustedTagInspector

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5278]
### Bug description

Quarkus 3.4.0 upgraded SnakeYAML to 2.1 and we see:

```
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/inspector/TrustedTagInspector
 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.getYaml(SnakeYAMLDataFormat.java:146)
 	at org.apache.camel.component.snakeyaml.SnakeYAMLDataFormat.marshal(SnakeYAMLDataFormat.java:115)
 	at org.apache.camel.support.processor.MarshalProcessor.process(MarshalProcessor.java:64)
 	... 47 more
```

**Comment by zhfeng** [comment]
It seems that `TrustedTagInspector` has been removed in https://github.com/snakeyaml/snakeyaml/commit/39a4b874c70ddf8beb0b73c4092ea1c700cc66df

I'll try to upgrade `SnakeYAML` to `2.1` in camel to see if it could be fixed.

**Comment by zhfeng** [comment]
Upstream camel PR:
- https://github.com/apache/camel/pull/11962
