### ISSUE TITLE
CamelOracleJdbcTest is failing due to failure to initialize timezone information

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5353]
### Bug description

Seems the container image `gvenzl/oracle-free:23.3-slim` got updated in a way that breaks our tests. I am not sure what is wrong. Seems related to timezones:

```
2023-09-25T10:15:21.7206276Z Caused by: jakarta.enterprise.inject.CreationException: java.sql.SQLException: ORA-00604: Error occurred at recursive SQL level 1. Check subsequent errors.
2023-09-25T10:15:21.7208765Z ORA-01804: failure to initialize timezone information
2023-09-25T10:15:21.7209108Z 
2023-09-25T10:15:21.7209514Z 	at org.apache.camel.quarkus.component.jdbc.oracle.OracleJdbcResource_Bean.create(Unknown Source)
2023-09-25T10:15:21.7210320Z 	at org.apache.camel.quarkus.component.jdbc.oracle.OracleJdbcResource_Bean.create(Unknown Source)
2023-09-25T10:15:21.7211443Z 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
2023-09-25T10:15:21.7213035Z 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
2023-09-25T10:15:21.7215527Z 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
2023-09-25T10:15:21.7217898Z 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
2023-09-25T10:15:21.7218371Z 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2023-09-25T10:15:21.7219132Z 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
2023-09-25T10:15:21.7219742Z 	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
2023-09-25T10:15:21.7220422Z 	at org.apache.camel.quarkus.component.jdbc.oracle.OracleJdbcResource_ClientProxy.arc$delegate(Unknown Source)
2023-09-25T10:15:21.7221174Z 	at org.apache.camel.quarkus.component.jdbc.oracle.OracleJdbcResource_ClientProxy.arc_contextualInstance(Unknown Source)
2023-09-25T10:15:21.7221751Z 	at io.quarkus.arc.ClientProxy.unwrap(ClientProxy.java:52)
2023-09-25T10:15:21.7222378Z 	at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:72)
2023-09-25T10:15:21.7223231Z 	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:74)
2023-09-25T10:15:21.7224120Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:349)
2023-09-25T10:15:21.7224727Z 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
2023-09-25T10:15:21.7225323Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
2023-09-25T10:15:21.7225711Z 	... 15 more
```

Similar issue reported here:

https://github.com/gvenzl/oci-oracle-free/issues/22

I am going to force the image to `gvenzl/oracle-free:23.2-slim` until there's a resolution.

**Comment by yrodiere** [comment]
Looks like https://github.com/gvenzl/oci-oracle-xe/issues/227

**Comment by jamesnetherton** [comment]
Issue appears to be resolved now.
