### ISSUE TITLE
camel-quarkus-jaxb fails to run in JVM mode with Quarkus 3 with `ClassNotFoundException: org.graalvm.nativeimage.ImageInfo`

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-quarkus#5407]
### Bug description

When I create a Quarkus 3.x app and try to add any of the Camel Quarkus dependencies to the project, it starts to fail to launch the `target/quarkus-app/quarkus-run.jar` in JVM mode.
```
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-management</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-jaxb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-debug</artifactId>
    </dependency>
```

This is the error after I run `mvn clean package -DskipTests && java -jar target/quarkus-app/quarkus-run.jar`:
```
The DelayedHandler was closed before any children handlers were configured. Messages will be written to stderr.
2023-10-06 16:07:05,774 DEBUG [org.jboss.logging] (main) Logging Provider: org.jboss.logging.JBossLogManagerProvider

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/graalvm/nativeimage/ImageInfo
        at org.apache.camel.quarkus.component.xml.jaxb.XmlJaxbRecorder.newContextFactory(XmlJaxbRecorder.java:34)
        at io.quarkus.deployment.steps.XmlJaxbProcessor$contextFactory121769731.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.XmlJaxbProcessor$contextFactory121769731.deploy(Unknown Source)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: org.graalvm.nativeimage.ImageInfo
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
        ... 19 more
```

All of those three components share `camel-quarkus-jaxb` and the error stacktrace also suggests `camel-quarkus-jaxb` is the root cause.

Here is a reproducer project:
- https://github.com/tadayosi/samples-quarkus3/tree/camel-quarkus-5407

To reproduce the issue, run the following under the project root:
```
mvn clean package -DskipTests
java -jar target/quarkus-app/quarkus-run.jar
```

**Comment by ppalaga** [comment]
It should be possible to workaround the issue by adding the 

```
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
        </dependency>
```

dependency without `<scope>provided</scope>`.
