### ISSUE TITLE
Azure, MongoDB  native compilation fails if both extensions are present.

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#5623]
### Bug description

Native failure:

```
Caused by: java.lang.ClassNotFoundException: jnr.unixsocket.UnixSocket
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
```

Issue is caused by the azure native configuration, see https://github.com/Azure/azure-sdk-for-java/issues/38186

**Reproducer**: https://github.com/JiriOndrusek/azure-mongodb-native-failure-reproducer
Execute ./mvnw package -Dnative to simulate the error.

(Project is created automatically by https://code.quarkus.io/?e=mongodb-client&e=org.apache.camel.quarkus%3Acamel-quarkus-azure-storage-queue without any change)

 **Workaround** is to add dependency `com.github:jnr-unixsocket`.

**Comment by jamesnetherton** [comment]
No longer an issue.
