### ISSUE TITLE
Intermittent failure of EipTest.throttle

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5679]
See failure stack trace below.

**Comment by spatnity** [comment]
I'd want to work on this.

**Comment by jamesnetherton** [comment]
Seems I totally misread the CI build logs. The actual failure was in `EipTest.throttle`:

```
2024-01-25T10:09:30.7914371Z [ERROR] Tests run: 22, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.71 s <<< FAILURE! -- in org.apache.camel.quarkus.eip.it.EipTest
2024-01-25T10:09:30.7917689Z [ERROR] org.apache.camel.quarkus.eip.it.EipTest.throttle -- Time elapsed: 10.12 s <<< ERROR!
2024-01-25T10:09:30.7919831Z org.awaitility.core.ConditionTimeoutException: Condition with org.apache.camel.quarkus.eip.it.EipTest was not fulfilled within 10 seconds.
2024-01-25T10:09:30.7921922Z 	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
2024-01-25T10:09:30.7923262Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
2024-01-25T10:09:30.7924468Z 	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
2024-01-25T10:09:30.7925667Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
2024-01-25T10:09:30.7929861Z 	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
2024-01-25T10:09:30.7931228Z 	at org.apache.camel.quarkus.eip.it.EipTest.throttle(EipTest.java:488)
2024-01-25T10:09:30.7932375Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-01-25T10:09:30.7933750Z 	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
2024-01-25T10:09:30.7935757Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
2024-01-25T10:09:30.7937637Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2024-01-25T10:09:30.7938647Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Seems the mock endpoint expectation is not fulfilled in time.

**Comment by jamesnetherton** [comment]
This failure just happened on the Quarkus Platform CI build too.
