### ISSUE TITLE
Minio tests fail in the Quarkus Platform

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5690]
### Bug description

There is an incompatibility with okhttp.

```
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.internal.Util
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
	at okhttp3.HttpUrl.parse(HttpUrl.kt)
	at io.minio.MinioClient$Builder.getBaseUrl(MinioClient.java:2791)
	at io.minio.MinioClient$Builder.endpoint(MinioClient.java:2803)
	at org.apache.camel.quarkus.component.minio.it.MinioProducer.produceMinioClient(MinioProducer.java:35)
	at org.apache.camel.quarkus.component.minio.it.MinioTest.initClient(MinioTest.java:387)
	at org.apache.camel.quarkus.component.minio.it.MinioTest.testGetObjectRange(MinioTest.java:295)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Companion [in thread "main"]
	at okhttp3.internal.Util.<clinit>(Util.kt:72)
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
	at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
	at okhttp3.HttpUrl.parse(HttpUrl.kt)
	at io.minio.MinioClient$Builder.getBaseUrl(MinioClient.java:2791)
	at io.minio.MinioClient$Builder.endpoint(MinioClient.java:2803)
	at org.apache.camel.quarkus.component.minio.it.MinioProducer.produceMinioClient(MinioProducer.java:35)
	at org.apache.camel.quarkus.component.minio.it.MinioTest.initClient(MinioTest.java:387)
	at org.apache.camel.quarkus.component.minio.it.MinioTest.testMoveDataBetweenBuckets(MinioTest.java:251)
	... 5 more
```

**Comment by ppalaga** [comment]
Did we start managing okhttp after Quarkus stopped?

**Comment by jamesnetherton** [comment]
> Did we start managing okhttp after Quarkus stopped?

Nothing has been done nor any investigation conducted as to what is required AFAIK...

**Comment by zhfeng** [comment]
What's version of `okhttp` used in the platform?

**Comment by jamesnetherton** [comment]
> What's version of `okhttp` used in the platform?

There isn't one now that `quarkus-bom` stopped managing it.  So the tests will probably just use whatever version is in their dependency tree. Seems odd that it works fine here and not in the platform though...

**Comment by jamesnetherton** [comment]
> I'm a little bit confuse that which version is working?

It should be `4.8.1`. 

https://github.com/minio/minio-java/blob/8.2.2/build.gradle#L56

I suppose that's what is used when the tests run, else they should fail.

> the version is `3.14.9`

The SBOM also thinks it should be `3.14.9`:

```
    {
      "ref" : "pkg:maven/io.minio/minio@8.2.2?type=jar",
      "dependsOn" : [
        "pkg:maven/com.carrotsearch.thirdparty/simple-xml-safe@2.7.1?type=jar",
        "pkg:maven/com.google.guava/guava@33.0.0-jre?type=jar",
        "pkg:maven/com.squareup.okhttp3/okhttp@3.14.9?type=jar",
        "pkg:maven/com.fasterxml.jackson.core/jackson-annotations@2.16.1?type=jar",
        "pkg:maven/com.fasterxml.jackson.core/jackson-core@2.16.1?type=jar",
        "pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.16.1?type=jar"
      ]
    },
```

I guess the bottom line is we (or Camel) need to manage the okhttp version somewhere.

**Comment by zhfeng** [comment]
Well, I wonder where is `3.14.9` coming from  the transitive dependency?

**Comment by zhfeng** [comment]
@jamesnetherton It seems be related to 

https://github.com/apache/camel-quarkus/blob/e3a2e6c07aadc7ecf4c088750cf8be56a0ef97fe/poms/bom/src/main/generated/flattened-full-pom.xml#L10360-L10363
```xml
      <dependency>
        <groupId>com.squareup.okhttp3</groupId><!-- io.quarkus:quarkus-bom:3.6.0 -->
        <artifactId>okhttp</artifactId><!-- io.quarkus:quarkus-bom:3.6.0 -->
        <version>3.14.9</version><!-- io.quarkus:quarkus-bom:3.6.0 -->
      </dependency>
```

and they are imported from `quarkus-qpid-jms-bom` which has the outdated `quarkus-bom`
https://github.com/apache/camel-quarkus/blob/e3a2e6c07aadc7ecf4c088750cf8be56a0ef97fe/poms/bom/pom.xml#L60-L66

I try to upgrade quarku-qpid-jms to `2.6.0-SNAPSHOT` with `quarkus:3.7.0` and now the `okhttp` version is `4.8.1` and there is the same issue with the plaform minio tests when running `integration-tests/minio`.

Then @ppalaga the following option in `poms/bom/pom.xml` is really working? or is there anyting we missed?

```xml 
              <originExcludes>
                    <!-- Remove BOM entries from the flattened BOM which come from quarkus-bom -->
                    <!-- This is mainly to get rid of potentially outdated quarkus-bom imports brought -->
                    <!-- via other participant's BOMs that we are importing -->
                    <originExclude>io.quarkus:quarkus-bom</originExclude>
               </originExcludes>
```

**Comment by b-thiswatch** [comment]
Hi,

I guess this is related then? Running Quarkus 3.7.1 with 

```xml
<dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-minio</artifactId>
    </dependency>
```

```shell
Caused by: java.lang.NoSuchFieldError: Class okio.Options does not have member field 'okio.Options$Companion Companion'
        at okhttp3.internal.Util.<clinit>(Util.kt:72)
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
        at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
        at okhttp3.HttpUrl.parse(HttpUrl.kt)
        at io.minio.MinioClient$Builder.getBaseUrl(MinioClient.java:2791)
        at io.minio.MinioClient$Builder.endpoint(MinioClient.java:2803)
        at io.quarkiverse.minio.client.MinioClients.createMinioClient(MinioClients.java:71)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at io.quarkiverse.minio.client.MinioClients.getMinioClient(MinioClients.java:53)
        at io.quarkiverse.minio.client.MinioClients.fromName(MinioClients.java:49)
        at io.quarkiverse.minio.client.MinioRecorder.lambda$minioClientSupplier$0(MinioRecorder.java:13)
        at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:129)
        at io.quarkus.arc.runtime.ArcRecorder$4.apply(ArcRecorder.java:126)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.createSynthetic(Unknown Source)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.doCreate(Unknown Source)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.create(Unknown Source)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.get(Unknown Source)
        at io.minio.MinioClient_QkxR8LBKo9FajXHrFaNmu3FHxiE_Synthetic_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.Instances$3.get(Instances.java:132)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
        at io.quarkus.arc.impl.LazyInstanceHandle.instanceInternal(LazyInstanceHandle.java:32)
        at io.quarkus.arc.impl.AbstractInstanceHandle.get(AbstractInstanceHandle.java:42)
        at org.apache.camel.quarkus.core.RuntimeBeanRepository.findSingleByType(RuntimeBeanRepository.java:167)
        at org.apache.camel.support.DefaultRegistry.findSingleByType(DefaultRegistry.java:367)
        at org.apache.camel.support.LifecycleStrategySupport.doAutoWire(LifecycleStrategySupport.java:260)
        at org.apache.camel.main.MainAutowiredLifecycleStrategy.autowire(MainAutowiredLifecycleStrategy.java:132)
        at org.apache.camel.main.MainAutowiredLifecycleStrategy.autowireComponent(MainAutowiredLifecycleStrategy.java:115)
        at org.apache.camel.main.MainAutowiredLifecycleStrategy.onComponentAdd(MainAutowiredLifecycleStrategy.java:75)
        at org.apache.camel.impl.engine.AbstractCamelContext.postInitComponent(AbstractCamelContext.java:472)
        at org.apache.camel.impl.engine.AbstractCamelContext.initComponent(AbstractCamelContext.java:587)
        at org.apache.camel.impl.engine.AbstractCamelContext.lambda$getComponent$1(AbstractCamelContext.java:505)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:503)
        at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:478)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:803)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:745)
        at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:61)
        at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:195)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:96)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:76)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:724)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:590)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2364)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:176)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2000)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:105)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2019)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:208)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:113)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
        ... 11 more
```

**Comment by jamesnetherton** [comment]
> I guess this is related then?

Yes. You can probably work around it by adding a dependency for `com.squareup.okhttp3:okhttp:4.8.1`.

**Comment by b-thiswatch** [comment]
@jamesnetherton

thanks. It doesn't help though and I checked that `mvn dependency:tree` gives me

```shell
[INFO] +- org.apache.camel.quarkus:camel-quarkus-minio:jar:3.7.0:compile
[INFO] |  +- org.apache.camel:camel-minio:jar:4.3.0:compile
[INFO] |  |  +- io.minio:minio:jar:8.2.2:compile
[INFO] |  |  |  +- com.carrotsearch.thirdparty:simple-xml-safe:jar:2.7.1:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:33.0.0-jre:compile
[INFO] |  |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
[INFO] |  |  |  \- com.squareup.okhttp3:okhttp:jar:4.8.1:compile
```
And with Quarkus `3.6.9` it's

```shell
[INFO] +- org.apache.camel.quarkus:camel-quarkus-minio:jar:3.6.0:compile
[INFO] |  +- org.apache.camel:camel-minio:jar:4.2.0:compile
[INFO] |  |  +- io.minio:minio:jar:8.2.2:compile
[INFO] |  |  |  +- com.carrotsearch.thirdparty:simple-xml-safe:jar:2.7.1:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:32.1.3-jre:compile
[INFO] |  |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
[INFO] |  |  |  \- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
```

which works...

**Comment by zhfeng** [comment]
> Yes. You can probably work around it by adding a dependency for `com.squareup.okhttp3:okhttp:4.8.1`.

@jamesnetherton No, it does not work because we manage `com.squareup.okio:okio` with `1.17.5` which looks like inherried from `camel`.

**Comment by jamesnetherton** [comment]
> because we manage `com.squareup.okio:okio` with `1.17.5` which looks like inherried from `camel`.

Ok, so it can be overridden.

```xml
<dependency>
  <groupId>com.squareup.okio</groupId>
  <artifactId>okio</artifactId>
  <version>2.7.0</version>
</dependency>
```

**Comment by b-thiswatch** [comment]
true.

```xml
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.14.9</version>
</dependency>
```

is working for me on Quarkus 3.7.1

**Comment by janwesterkamp** [comment]
> ```
> 3.14.9
> ```



> true.
> 
> ```
> <dependency>
>     <groupId>com.squareup.okhttp3</groupId>
>     <artifactId>okhttp</artifactId>
>     <version>3.14.9</version>
> </dependency>
> ```
> 
> is working for me on Quarkus 3.7.1

This is working for me on Quarkus 3.7.2 too.

Another potential workaround is downgrading to Quarkus 3.6.9 simply, which does not require overwrites.

BTW, I checked also overwrinting/updating the MinIO version to 8.5.7, but this version requires an okhttp version of 4.11+. When testing this with 4.11.0 and 4.12.0 the error (`Caused by: java.lang.NoSuchFieldError: Class okio.Options does not have member field 'okio.Options$Companion Companion'`) shows up again.

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/5770.
