### ISSUE TITLE
SMB tests fail in the Quarkus Platform

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5692]
### Bug description

Seems the `Dockerfile` used to create the SMB container cannot be resolved.

```
[ERROR] org.apache.camel.quarkus.component.smb.it.SmbTest.testSmbResultsValidation  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.apache.camel.quarkus.component.smb.it.SmbTestResource
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.apache.camel.quarkus.component.smb.it.SmbTestResource
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@19f23acf)
	at org.apache.camel.quarkus.component.smb.it.SmbTestResource.start(SmbTestResource.java:51)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:500)
	... 4 more
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@19f23acf)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1367)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
	at org.apache.camel.quarkus.component.smb.it.SmbTestResource.start(SmbTestResource.java:39)
	... 5 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Cannot locate specified Dockerfile: Dockerfile"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	... 1 more
```

**Comment by spatnity** [comment]
I'd want to workaround this one.
