### ISSUE TITLE
org/hl7/fhir/r5/model/fhirversion.properties wrong path

### ISSUE THREAD

**Issue by Koitix-KTX** [apache/camel-quarkus#5725]
### Bug description

I'm using Fhir R5, but every time i run quarkus, I get following error:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.7.1:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step org.apache.camel.quarkus.component.fhir.deployment.r5.FhirR5Processor#fhirProperties threw an exception: java.lang.RuntimeException: Please ensure FHIR is on the classpath
[ERROR]         at org.apache.camel.quarkus.component.fhir.deployment.AbstractPropertiesBuildItem.loadProperties(AbstractPropertiesBuildItem.java:43)
[ERROR]         at org.apache.camel.quarkus.component.fhir.deployment.AbstractPropertiesBuildItem.<init>(AbstractPropertiesBuildItem.java:33)
[ERROR]         at org.apache.camel.quarkus.component.fhir.deployment.r5.R5PropertiesBuildItem.<init>(R5PropertiesBuildItem.java:24)
[ERROR]         at org.apache.camel.quarkus.component.fhir.deployment.r5.FhirR5Processor.fhirProperties(FhirR5Processor.java:50)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.NullPointerException: inStream parameter is null
[ERROR]         at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[ERROR]         at java.base/java.util.Properties.load(Properties.java:407)
[ERROR]         at org.apache.camel.quarkus.component.fhir.deployment.AbstractPropertiesBuildItem.loadProperties(AbstractPropertiesBuildItem.java:40)
[ERROR]         ... 14 more

```
After some research I found, that the current path in FhirR5Processor.java is "org/hl7/fhir/r5/model/fhirversion.properties", but the actual file is found under "org/hl7/fhir/r5/hapi/model/fhirversion.properties" like in R4 (FhirR4Processor.java).

**Comment by jamesnetherton** [comment]
Thanks for reporting this. Unfortunately, I don't think there's a way to work around it. 

@spatnity would you like to work on a fix?

**Comment by spatnity** [comment]
Yeah sure!
