### ISSUE TITLE
google-pubsub: testAck is failing on the platform

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#5799]
### Bug description

While releasing Camel Quarkus 3.8.0, the google-pubsub testAck test was failing in the [pr](https://github.com/quarkusio/quarkus-platform/pull/1129):
 * org.apache.camel.quarkus.component.google.pubsub.it.GooglePubsubTest.testAck

```
java.lang.RuntimeException: java.lang.IncompatibleClassChangeError: class com.google.cloud.pubsub.v1.stub.SubscriberStubSettings overrides final method com.google.api.gax.rpc.StubSettings.getEndpoint()Ljava/lang/String;
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IncompatibleClassChangeError: class com.google.cloud.pubsub.v1.stub.SubscriberStubSettings overrides final method com.google.api.gax.rpc.StubSettings.getEndpoint()Ljava/lang/String;
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by zhfeng** [comment]
@jamesnetherton @aldettinger I just wonder to check the line in `quarkus-platform` https://github.com/quarkusio/quarkus-platform/blob/3.8/pom.xml#L387-L388

could be removed?

**Comment by jamesnetherton** [comment]
> could be removed?

I think it would require quarkus-google-cloud-services to be upgraded to 2.8.0.
