### ISSUE TITLE
jsch: scpFileToServer failing on quarkus-platform test

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#5800]
### Bug description

While releasing Camel Quarkus 3.8.0, the test below was failing on the quarkus-platform:
 * org.apache.camel.quarkus.component.jsch.it.JschTest.scpFileToServer(Path)

```
java.lang.RuntimeException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.apache.camel.quarkus.component.jsch.it.JschTestResource
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:722)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.apache.camel.quarkus.component.jsch.it.JschTestResource
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:506)
```

**Comment by jamesnetherton** [comment]
This passes fine for me. Also passed on the latest successful build on the platform 3.8.0 upgrade PR:

```
2024-02-27T11:33:58.8828559Z [INFO] -------------------------------------------------------
2024-02-27T11:33:58.8829246Z [INFO]  T E S T S
2024-02-27T11:33:58.8829856Z [INFO] -------------------------------------------------------
2024-02-27T11:33:59.5277277Z [INFO] Running org.apache.camel.quarkus.component.jsch.it.JschTest
2024-02-27T11:34:02.1623222Z Downloading from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/apache/camel/quarkus/camel-quarkus-jsch-deployment/3.8.0/camel-quarkus-jsch-deployment-3.8.0.jar
2024-02-27T11:34:02.5627466Z Downloaded from google-maven-central: https://maven-central.storage-download.googleapis.com/maven2/org/apache/camel/quarkus/camel-quarkus-jsch-deployment/3.8.0/camel-quarkus-jsch-deployment-3.8.0.jar (4.6 kB at 14 kB/s)
2024-02-27T11:34:04.8725745Z 2024-02-27 11:34:04,843 INFO  [org.tes.ima.PullPolicy] (pool-3-thread-1) Image pull policy will be performed by: DefaultPullPolicy()
2024-02-27T11:34:04.8729212Z 2024-02-27 11:34:04,845 INFO  [org.tes.uti.ImageNameSubstitutor] (pool-3-thread-1) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2024-02-27T11:34:05.0780556Z 2024-02-27 11:34:05,025 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2024-02-27T11:34:05.2782926Z 2024-02-27 11:34:05,179 INFO  [org.tes.doc.DockerClientProviderStrategy] (pool-3-thread-1) Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2024-02-27T11:34:05.2785780Z 2024-02-27 11:34:05,180 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Docker host IP address is localhost
2024-02-27T11:34:05.2787976Z 2024-02-27 11:34:05,195 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Connected to docker: 
2024-02-27T11:34:05.2789319Z   Server Version: 24.0.8
2024-02-27T11:34:05.2790161Z   API Version: 1.43
2024-02-27T11:34:05.2790995Z   Operating System: Ubuntu 22.04.4 LTS
2024-02-27T11:34:05.2791588Z   Total Memory: 15981 MB
2024-02-27T11:34:05.2792826Z 2024-02-27 11:34:05,229 INFO  [tc.tes.6.0] (pool-3-thread-1) Creating container for image: testcontainers/ryuk:0.6.0
2024-02-27T11:34:05.3790367Z 2024-02-27 11:34:05,313 INFO  [tc.tes.6.0] (pool-3-thread-1) Container testcontainers/ryuk:0.6.0 is starting: 3573aedf7cad35c9701442b7edb5c60f9395ee4375ce7a56ad9ee3d613097175
2024-02-27T11:34:05.6817784Z 2024-02-27 11:34:05,644 INFO  [tc.tes.6.0] (pool-3-thread-1) Container testcontainers/ryuk:0.6.0 started in PT0.41465202S
2024-02-27T11:34:05.6820455Z 2024-02-27 11:34:05,647 INFO  [org.tes.uti.RyukResourceReaper] (pool-3-thread-1) Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2024-02-27T11:34:05.6822762Z 2024-02-27 11:34:05,648 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) Checking the system...
2024-02-27T11:34:05.6824882Z 2024-02-27 11:34:05,648 INFO  [org.tes.DockerClientFactory] (pool-3-thread-1) ✔︎ Docker server version should be at least 1.6.0
2024-02-27T11:34:05.6828297Z 2024-02-27 11:34:05,655 INFO  [tc.doc.io/.3_p2-r0] (pool-3-thread-1) Pulling docker image: docker.io/linuxserver/openssh-server:version-9.3_p2-r0. Please be patient; this may take some time but only needs to be done once.
2024-02-27T11:34:05.8819303Z 2024-02-27 11:34:05,845 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Starting to pull image
2024-02-27T11:34:05.8820876Z 2024-02-27 11:34:05,860 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2024-02-27T11:34:06.0822619Z 2024-02-27 11:34:05,987 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  6 pending,  1 downloaded,  0 extracted, (966 bytes/? MB)
2024-02-27T11:34:06.0824648Z 2024-02-27 11:34:06,010 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  5 pending,  2 downloaded,  0 extracted, (5 KB/? MB)
2024-02-27T11:34:06.0826026Z 2024-02-27 11:34:06,053 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  4 pending,  3 downloaded,  0 extracted, (60 KB/? MB)
2024-02-27T11:34:06.0827384Z 2024-02-27 11:34:06,077 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  3 pending,  4 downloaded,  0 extracted, (60 KB/? MB)
2024-02-27T11:34:06.1823901Z 2024-02-27 11:34:06,135 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  2 pending,  5 downloaded,  0 extracted, (149 KB/? MB)
2024-02-27T11:34:06.1825713Z 2024-02-27 11:34:06,139 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  1 pending,  6 downloaded,  0 extracted, (152 KB/? MB)
2024-02-27T11:34:06.1827365Z 2024-02-27 11:34:06,157 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  0 extracted, (152 KB/13 MB)
2024-02-27T11:34:06.4826912Z 2024-02-27 11:34:06,391 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  1 extracted, (5 MB/13 MB)
2024-02-27T11:34:06.4829402Z 2024-02-27 11:34:06,429 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  2 extracted, (5 MB/13 MB)
2024-02-27T11:34:06.4832037Z 2024-02-27 11:34:06,440 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  3 extracted, (5 MB/13 MB)
2024-02-27T11:34:06.9833354Z 2024-02-27 11:34:06,912 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  4 extracted, (10 MB/13 MB)
2024-02-27T11:34:06.9835963Z 2024-02-27 11:34:06,940 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  5 extracted, (10 MB/13 MB)
2024-02-27T11:34:07.0834981Z 2024-02-27 11:34:07,019 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  6 extracted, (13 MB/13 MB)
2024-02-27T11:34:07.0837550Z 2024-02-27 11:34:07,034 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pulling image layers:  0 pending,  7 downloaded,  7 extracted, (13 MB/13 MB)
2024-02-27T11:34:07.0839940Z 2024-02-27 11:34:07,041 INFO  [tc.doc.io/.3_p2-r0] (docker-java-stream-841559818) Pull complete. 7 layers, pulled in 1s (downloaded 13 MB at 13 MB/s)
2024-02-27T11:34:07.0842293Z 2024-02-27 11:34:07,041 INFO  [tc.doc.io/.3_p2-r0] (pool-3-thread-1) Image docker.io/linuxserver/openssh-server:version-9.3_p2-r0 pull took PT1.386028602S
2024-02-27T11:34:07.0844643Z 2024-02-27 11:34:07,044 INFO  [tc.doc.io/.3_p2-r0] (pool-3-thread-1) Creating container for image: docker.io/linuxserver/openssh-server:version-9.3_p2-r0
2024-02-27T11:34:07.0847483Z 2024-02-27 11:34:07,056 INFO  [tc.doc.io/.3_p2-r0] (pool-3-thread-1) Container docker.io/linuxserver/openssh-server:version-9.3_p2-r0 is starting: 2c77c2685146a7581444f03e2fe2360c43717205c9da4b383da0ddd6732f97ee
2024-02-27T11:34:09.8869222Z 2024-02-27 11:34:09,854 INFO  [tc.doc.io/.3_p2-r0] (pool-3-thread-1) Container docker.io/linuxserver/openssh-server:version-9.3_p2-r0 started in PT2.810370729S
2024-02-27T11:34:10.4876235Z 2024-02-27 11:34:10,406 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2024-02-27T11:34:10.4878590Z 2024-02-27 11:34:10,408 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.4.0 is starting
2024-02-27T11:34:10.4880643Z 2024-02-27 11:34:10,461 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) is starting
2024-02-27T11:34:10.4882869Z 2024-02-27 11:34:10,468 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:0)
2024-02-27T11:34:10.4885739Z 2024-02-27 11:34:10,468 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) started in 4ms (build:0ms init:0ms start:4ms)
2024-02-27T11:34:10.5806993Z 2024-02-27 11:34:10,560 INFO  [io.quarkus] (main) camel-quarkus-integration-test-jsch 999-SNAPSHOT on JVM (powered by Quarkus 3.8.0) started in 7.661s. Listening on: http://localhost:8081
2024-02-27T11:34:10.5809559Z 2024-02-27 11:34:10,561 INFO  [io.quarkus] (main) Profile test activated. 
2024-02-27T11:34:10.5811945Z 2024-02-27 11:34:10,561 INFO  [io.quarkus] (main) Installed features: [camel-core, camel-file, camel-ftp, camel-jsch, cdi, jsch, resteasy, smallrye-context-propagation, vertx]
2024-02-27T11:34:11.8893451Z 2024-02-27 11:34:11,878 WARN  [org.apa.cam.com.scp.ScpOperations] (executor-thread-1) Private Key authentication not supported
2024-02-27T11:34:11.8902156Z 2024-02-27 11:34:11,878 WARN  [org.apa.cam.com.scp.ScpOperations] (executor-thread-1) Private Key authentication not supported
2024-02-27T11:34:11.8904706Z 2024-02-27 11:34:11,878 WARN  [org.apa.cam.com.scp.ScpOperations] (executor-thread-1) Private Key authentication not supported
2024-02-27T11:34:11.8906823Z 2024-02-27 11:34:11,878 WARN  [org.apa.cam.com.scp.ScpOperations] (executor-thread-1) Private Key authentication not supported
2024-02-27T11:34:11.8908988Z 2024-02-27 11:34:11,878 WARN  [org.apa.cam.com.scp.ScpOperations] (executor-thread-1) Private Key authentication not supported
2024-02-27T11:34:11.9894808Z 2024-02-27 11:34:11,950 WARN  [org.apa.cam.com.scp.ScpComponent] (executor-thread-1) [JSCH] getInputStream() should be called before connect()
2024-02-27T11:34:12.2547613Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.717 s - in org.apache.camel.quarkus.component.jsch.it.JschTest
2024-02-27T11:34:12.3933558Z 2024-02-27 11:34:12,258 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) is shutting down (timeout:45s)
2024-02-27T11:34:12.3936261Z 2024-02-27 11:34:12,260 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (stopped:0)
2024-02-27T11:34:12.3938334Z 2024-02-27 11:34:12,262 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.0 (camel-1) shutdown in 3ms (uptime:1s)
2024-02-27T11:34:12.3940286Z 2024-02-27 11:34:12,276 INFO  [io.quarkus] (main) camel-quarkus-integration-test-jsch stopped in 0.029s```
