### ISSUE TITLE
Error binding property (camel.main.routeControllerBackOffMaxAttempts=true

### ISSUE THREAD

**Issue by hakuseki** [apache/camel-quarkus#5832]
### Bug description

When using Camel in Quarkus 3.8.1 there's an error generated, failing the application to start:

```
2024-03-01 15:23:06,205 ERROR [io.qua.run.Application] (Quarkus Main Thread)  -  Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.camel.PropertyBindingException: Error binding property (camel.main.routeControllerBackOffMaxAttempts=true) with name: routeControllerBackOffMaxAttempts on bean: org.apache.camel.main.MainConfigurationProperties@5c8196f with value: true
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	... 11 more
Caused by: java.lang.RuntimeException: org.apache.camel.PropertyBindingException: Error binding property (camel.main.routeControllerBackOffMaxAttempts=true) with name: routeControllerBackOffMaxAttempts on bean: org.apache.camel.main.MainConfigurationProperties@5c8196f with value: true
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:65)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	... 13 more
Caused by: org.apache.camel.PropertyBindingException: Error binding property (camel.main.routeControllerBackOffMaxAttempts=true) with name: routeControllerBackOffMaxAttempts on bean: org.apache.camel.main.MainConfigurationProperties@5c8196f with value: true
	at org.apache.camel.main.MainHelper.setPropertiesOnTarget(MainHelper.java:354)
	at org.apache.camel.main.BaseMainSupport.autoConfigurationMainConfiguration(BaseMainSupport.java:1915)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:451)
	at org.apache.camel.main.MainSupport.autoconfigure(MainSupport.java:73)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:687)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	... 14 more
```

Running Quarkus 3.7.4 works fine

Running on MacOS
Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)

**Comment by jamesnetherton** [comment]
See this section of the Camel 4.4.0 upgrade guide:

https://camel.apache.org/manual/camel-4x-upgrade-guide-4_4.html#_camel_main

`camel.main.routesController` is now `camel.routecontroller`.

**Comment by hakuseki** [comment]
Ahh, missed that part. Thx
