### ISSUE TITLE
Kamelet tests fail at build time due to StackOverflowError

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5849]
### Bug description

Also seen on the Kamelet Chuck Norris example project.

```
[INFO] Running org.apache.camel.quarkus.component.kamelet.it.KameletTest
2024-03-07 14:08:00,823 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (build-4) Apache Camel 4.5.0-SNAPSHOT (camel-2) is shutting down (timeout:45s)
2024-03-07 14:08:00,828 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (build-4) Routes stopped (total:0)
2024-03-07 14:08:00,832 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (build-4) Apache Camel 4.5.0-SNAPSHOT (camel-2) shutdown in 11ms (uptime:)
[ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 1.885 s <<< FAILURE! -- in org.apache.camel.quarkus.component.kamelet.it.KameletTest
[ERROR] org.apache.camel.quarkus.component.kamelet.it.KameletTest.testKameletWithProperties -- Time elapsed: 0.003 s <<< ERROR!
java.lang.RuntimeException:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: java.lang.StackOverflowError
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3362)
        at java.base/java.lang.Class.getConstructors(Class.java:2060)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1173)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstanceImpl(BytecodeRecorderImpl.java:914)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadObjectInstance(BytecodeRecorderImpl.java:586)
        at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1357)
```

**Comment by JiriOndrusek** [comment]
Fixed in camel-main branch, issue can be closed as camel-main (for Camel 4.5 is merged into main)
