### ISSUE TITLE
SSH tests fail due to NoSuchMethodError: boolean org.apache.sshd.client.future.ConnectFuture.await(long)

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5850]
### Bug description

Camel upgraded to SSHD 2.12.1 but Quarkus 3.8.x is currently aligned with 2.12.0.

There were changes in 2.12.1 in `VerifiableFuture` & `WaitableFuture`.

https://github.com/apache/mina-sshd/compare/sshd-2.12.0...sshd-2.12.1

```
Caused by: java.lang.NoSuchMethodError: 'boolean org.apache.sshd.client.future.ConnectFuture.await(long)'
        at org.apache.camel.component.ssh.SshHelper.sendExecCommand(SshHelper.java:69)
        at org.apache.camel.component.ssh.SshProducer.process(SshProducer.java:82)
        at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:65)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor.processNonTransacted(SharedCamelInternalProcessor.java:199)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:173)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor$1.process(SharedCamelInternalProcessor.java:109)
        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:82)
        at org.apache.camel.impl.engine.SharedCamelInternalProcessor.process(SharedCamelInternalProcessor.java:106)
        at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:178)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:153)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:187)
        at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:195)
        at org.apache.camel.quarkus.component.ssh.it.SshResource.writeToFile(SshResource.java:57)
        at org.apache.camel.quarkus.component.ssh.it.SshResource_ClientProxy.writeToFile(Unknown Source)
```

**Comment by jamesnetherton** [comment]
I upgraded SSHD in Quarkus so I fixed this on `quarkus-main`:

https://github.com/quarkusio/quarkus/pull/39860
