### ISSUE TITLE
QuarkusCxfProcessor throws NoSuchFieldError: type

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5926]
### Bug description

Observed on anything CXF releated with Quarkus 999-SNAPSHOT. Due to some recent refactoring:

https://github.com/quarkusio/quarkus/commit/095feab7314beef55520d4e5087daf053755260e

I'll disable the CXF bits on `quarkus-main` until there's an updated QCXF.

```
2024-03-25T08:37:31.9144876Z Caused by: java.lang.NoSuchFieldError: type
2024-03-25T08:37:31.9146108Z 	at io.quarkiverse.cxf.deployment.QuarkusCxfProcessor.buildXmlResources(QuarkusCxfProcessor.java:317)
2024-03-25T08:37:31.9147487Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-03-25T08:37:31.9148599Z 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
2024-03-25T08:37:31.9149716Z 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
2024-03-25T08:37:31.9150754Z 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
2024-03-25T08:37:31.9233364Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
2024-03-25T08:37:31.9234902Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
2024-03-25T08:37:31.9236336Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
2024-03-25T08:37:31.9237480Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-03-25T08:37:31.9238313Z 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

**Comment by jamesnetherton** [comment]
FYI @ppalaga.

**Comment by ppalaga** [comment]
Thanks for the headsup, @jamesnetherton. 

I wonder why my brand new quarkus main job for QCXF did not complain in recent days 😱 
https://github.com/quarkiverse/quarkus-cxf/actions/workflows/quarkus-main-rebase.yml

**Comment by ppalaga** [comment]
The fix is underway in the Quarkus CXF quarkus-main branch https://github.com/quarkiverse/quarkus-cxf/commits/quarkus-main/
