### ISSUE TITLE
camel-quarkus-spring-redis doesn't autowire RedisTemplate so it cannot be used for e.g. RedisIdempotentRepository

### ISSUE THREAD

**Issue by JesperBerggren** [apache/camel-quarkus#5962]
### Bug description

The extension _camel-quarkus-spring-redis_ doesn't seem to autowire _RedisTemplate_ which is needed for _RedisIdempotentRepository_.

I've got this dependency:
```
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-spring-redis</artifactId>
</dependency>
```

And in my code I have something like this:
```
@ApplicationScoped
public class CommonRoutes extends RouteBuilder {

    public static final int SUCCESS = 100;
    public static final int ERROR = 200;
    public static final int EXHAUSTED = 300;

    @ConfigProperty(name = "url")
    private String url;
    @ConfigProperty(name = "max.retry.count")
    private String maxRetryCnt;
    @ConfigProperty(name = "ordning")
    private String ordning;

    @Inject
    private CamelContext context;
    @Inject
    private RedisTemplate redisTemplate;

    @Override
    public void configure() throws Exception {

        // Redis idempotent repository
        RedisIdempotentRepository redisIdempotentRepository = new RedisIdempotentRepository(redisTemplate, "NGDP.KvitteringOpsamler");
        context.getRegistry().bind("redisIdempotentRepo", redisIdempotentRepository);
...
```

But when I run my code I get these exceptions:
```
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 4 deployment problems: 
[1] Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.FileRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, dk.atp.integration.dp.kvitteringopsamler.FileRouter, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.FileRouter]
[2] Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.MailRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, dk.atp.integration.dp.kvitteringopsamler.MailRouter, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.MailRouter]
[3] Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.CommonRoutes#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, dk.atp.integration.dp.kvitteringopsamler.CommonRoutes, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.CommonRoutes]
[4] Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1516)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:320)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:160)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:488)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.FileRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, dk.atp.integration.dp.kvitteringopsamler.FileRouter, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.FileRouter]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
		... 14 more
	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.MailRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, dk.atp.integration.dp.kvitteringopsamler.MailRouter, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.MailRouter]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
		... 14 more
	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.CommonRoutes#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, dk.atp.integration.dp.kvitteringopsamler.CommonRoutes, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.CommonRoutes]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
		... 14 more
	Suppressed: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.springframework.data.redis.core.RedisTemplate and qualifiers [@Default]
	- injection target: dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter#redisTemplate
	- declared on CLASS bean [types=[org.apache.camel.builder.BuilderSupport, org.apache.camel.Ordered, org.apache.camel.CamelContextAware, dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter, org.apache.camel.spi.ResourceAware, org.apache.camel.spi.HasCamelContext, org.apache.camel.RoutesBuilder, java.lang.Object, org.apache.camel.builder.ModelRoutesBuilder, org.apache.camel.builder.RouteBuilder], qualifiers=[@Default, @Any], target=dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
		... 14 more
```

**Comment by jamesnetherton** [comment]
In order to `@Inject` `RedisTemplate` you need to [produce](https://quarkus.io/guides/cdi-reference#simplified-producer-method-declaration) a bean of that type somewhere in your application.

If you don't need any special customisation of the `RedisTemplate`, then you can use the simplified constructor:

https://github.com/apache/camel/blob/camel-4.4.1/components/camel-spring-redis/src/main/java/org/apache/camel/component/redis/processor/idempotent/RedisIdempotentRepository.java#L41-L47

**Comment by JesperBerggren** [comment]
Thanks for a quick reply!

Ok, then it works quite differently in Quarkus than Spring Boot. 
In Spring Boot it enough to set something like this in application.properties
```
spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=mypass
spring.data.redis.timeout=60000
```
after which the a RedisTemplate bean can automatically be injected (without producing it manually).
It seems smarter and more in line with e.g. the CamelContext which doesn't need to be produced manually in Quarkus.

When I have something functional I'll post it for later reference if anybody else should be interested.

**Comment by davsclaus** [comment]
Yeah would be nice if quarkus could allow configuration form application properties - its very common and handy for setting this kind of stuff - instead of writing code all the time.

And it would be needed for low-code effort like karavan/kaoto as well.

**Comment by davsclaus** [comment]
I created a ticket to see if we can make something generic
https://issues.apache.org/jira/browse/CAMEL-20654

It will be useful for other components where you need to setup something that is common to configure via a set of key=value pairs.

**Comment by JesperBerggren** [comment]
I wonder what I'm missing.
When I produce a bean of type RedisTemplate with this simple code:
```
public class Producers {

    @Produces
    @ApplicationScoped
    RedisTemplate produceRedisTemplate() {

        RedisConfiguration redisConfiguration = new RedisConfiguration();
        redisConfiguration.setHost("localhost");
        redisConfiguration.setPort(6379);

        RedisTemplate redisTemplate = (RedisTemplate<String, String>) redisConfiguration.getRedisTemplate();
        redisTemplate.opsForSet();
        LettuceConnectionFactory lettuceConnectionFactory = (LettuceConnectionFactory) redisTemplate.getConnectionFactory();
        assert lettuceConnectionFactory != null;
        Objects.requireNonNull(lettuceConnectionFactory.getSentinelConfiguration()).setPassword("password");

        redisTemplate.getConnectionFactory().getConnection().serverCommands().flushDb();
        return redisTemplate;
    }
}
```
I get this exception that causes quarkus not to be able to start up.
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:643)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:727)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:610)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:725)
	... 2 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/util/CloseableIterator
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:508)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	at org.apache.camel.component.redis.RedisConfiguration.createDefaultTemplate(RedisConfiguration.java:160)
	at org.apache.camel.component.redis.RedisConfiguration.getRedisTemplate(RedisConfiguration.java:90)
	at dk.atp.integration.dp.kvitteringopsamler.Producers.produceRedisTemplate(Producers.java:22)
	at dk.atp.integration.dp.kvitteringopsamler.Producers_ProducerMethod_produceRedisTemplate_oXh1o33dh07G6QKT2LUDr_oOLFE_Bean.doCreate(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.Producers_ProducerMethod_produceRedisTemplate_oXh1o33dh07G6QKT2LUDr_oOLFE_Bean.create(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.Producers_ProducerMethod_produceRedisTemplate_oXh1o33dh07G6QKT2LUDr_oOLFE_Bean.get(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.Producers_ProducerMethod_produceRedisTemplate_oXh1o33dh07G6QKT2LUDr_oOLFE_Bean.get(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter_Bean.doCreate(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter_Bean.create(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c19(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter_ClientProxy.arc$delegate(Unknown Source)
	at dk.atp.integration.dp.kvitteringopsamler.DatabaseRouter_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.quarkus.arc.ClientProxy.unwrap(ClientProxy.java:52)
	at org.apache.camel.quarkus.CamelQuarkusBeanPostProcessor.postProcessBeforeInitialization(CamelQuarkusBeanPostProcessor.java:31)
	at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:230)
	at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:67)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:695)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:113)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:83)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:134)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.springframework.data.util.CloseableIterator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	... 45 more
```
Am I missing something?

It appears to be something with the RedisTemplate because even with this code I get the same exception.
```
public class Producers {

    @Produces
    @ApplicationScoped
    RedisTemplate produceRedisTemplate() {

        return null;
    }
}
```

**Comment by JesperBerggren** [comment]
Ok, I have it running but had to make two unexpected dependencies in the pom.

First it complained about:
`java.lang.ClassNotFoundException: org.springframework.data.util.CloseableIterator`
I got past that by adding this dependency:
```
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-commons</artifactId>
  <version>3.2.4</version>
</dependency>
```

Then I complained about:
`java.lang.ClassNotFoundException: org.springframework.expression.EvaluationContext`
And I got past that by adding this dependency:
```
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-expression</artifactId>
  <version>6.1.5</version>
</dependency>
```

I'm thinking that these dependencies really shouldn't be necessary and perhaps should be included in the `camel-quarkus-spring-redis artifact`??

**Comment by jamesnetherton** [comment]
> I'm thinking that these dependencies really shouldn't be necessary and perhaps should be included in the `camel-quarkus-spring-redis artifact`??

It's likely due to usage of `io.quarkus:quarkus-spring-data-commons-api`:

https://github.com/apache/camel-quarkus/blob/main/extensions-jvm/spring-redis/runtime/pom.xml#L54-L57

Which is probably a shaded version of the original, with various packages excluded.

We should probably just use the vanilla  `org.springframework` one.

**Comment by jamesnetherton** [comment]
I made some changes that should fix the `ClassNotFoundException` issues:

https://github.com/apache/camel-quarkus/pull/5989

I'll follow up with another issue to adapt things further, after we get a resolution to [CAMEL-20654](https://issues.apache.org/jira/browse/CAMEL-20654).
