### ISSUE TITLE
[quarkus-main] CXF SOAP tests fail with NCDFE for io/quarkus/vertx/core/runtime/VertxBufferImpl

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6179]
### Bug description

Observed on the most recent `quarkus-main` nightly build:

https://github.com/apache/camel-quarkus/actions/runs/9475656179/job/26107952816

```
024-06-12T03:03:59.5872671Z 	Suppressed: java.lang.NoClassDefFoundError: io/quarkus/vertx/core/runtime/VertxBufferImpl
2024-06-12T03:03:59.5874374Z 		at io.quarkiverse.cxf.transport.generated.VertxServletOutputStream.createBuffer(VertxServletOutputStream.java:90)
2024-06-12T03:03:59.5876306Z 		at io.quarkiverse.cxf.transport.generated.VertxServletOutputStream.write(VertxServletOutputStream.java:120)
2024-06-12T03:03:59.5878286Z 		at io.quarkiverse.cxf.transport.generated.VertxServletOutputStream.writeBlocking(VertxServletOutputStream.java:204)
2024-06-12T03:03:59.5880214Z 		at io.quarkiverse.cxf.transport.generated.VertxServletOutputStream.write(VertxServletOutputStream.java:192)
2024-06-12T03:03:59.5881944Z 		at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
```

**Comment by jamesnetherton** [comment]
FYI @ppalaga

**Comment by jamesnetherton** [comment]
To work around this, I have disabled the `cxf-soap-grouped` tests and native profile.

**Comment by ppalaga** [comment]
Happens to be caused by my own PR https://github.com/quarkusio/quarkus/pull/40995 :D

**Comment by ppalaga** [comment]
This requires some change in QCXF, which I'll release today-ish right after Quarkus 3.12.0.CR1.

**Comment by jamesnetherton** [comment]
@ppalaga feel free to eventually push the QCXF upgrade to https://github.com/apache/camel-quarkus/pull/6181.

**Comment by ppalaga** [comment]
I have added the upgrade to https://github.com/apache/camel-quarkus/pull/6181
