### ISSUE TITLE
[camel-main] ical Dataformat fails in native

### ISSUE THREAD

**Issue by JiriOndrusek** [apache/camel-quarkus#6218]
### Bug description

With the update of [ical](https://github.com/apache/camel/commit/6893c54e4b75fe5766af0d5738f7c912af5e7637), there is a native failure.

Simple solutions of the failure causes other failures (with any stacktrace)

- If I add `--initialize-at-build-time=net.fortuna.ical4j.model.TimeZoneLoader`, I'm getting
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 66.76 s <<< FAILURE! -- in org.apache.camel.quarkus.component.dataformat.it.DataformatIT
[ERROR] org.apache.camel.quarkus.component.dataformat.it.DataformatIT.ical -- Time elapsed: 0.015 s <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:102)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:110)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:194)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:301)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	... 1 more
```

- If I add `--initialize-at-run-time=java.time.zone.ZoneRulesProvider`, I'm getting
```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 7.039 s <<< FAILURE! -- in org.apache.camel.quarkus.component.dataformat.it.DataformatIT
[ERROR] org.apache.camel.quarkus.component.dataformat.it.DataformatIT.ical -- Time elapsed: 0.015 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '250733'. Exit code is: '1'.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '250733'. Exit code is: '1'.
	at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:124)
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:87)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:110)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:194)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:301)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	... 1 more

[DEBUG] Closing the fork 1 after saying GoodBye.
```

The native test is disabled for now.

**Comment by jamesnetherton** [comment]
Should be fixed in https://github.com/apache/camel-quarkus/commit/83a01bb6b94970b945689107859f597634fd28a9.
