### ISSUE TITLE
microprofile-fault-tolerance tests fail with CNFE for FallbackFunction

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6285]
### Bug description

Quarkus has upgraded SmallRye Fault Tolerance to 6.4.0. We need to catch up on the Camel side.

```
2024-07-23T03:25:18.8625451Z Caused by: java.lang.ClassNotFoundException: io.smallrye.faulttolerance.core.fallback.FallbackFunction
2024-07-23T03:25:18.8627035Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2024-07-23T03:25:18.8628564Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2024-07-23T03:25:18.8629812Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2024-07-23T03:25:18.8631280Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:561)
2024-07-23T03:25:18.8632879Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:509)
2024-07-23T03:25:18.8634016Z 	... 54 more
```

**Comment by jamesnetherton** [comment]
Fixed in https://github.com/apache/camel-quarkus/pull/6439.
