### ISSUE TITLE
cxf-soap SSL tests fail with Quarkus CXF 3.13.0

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6294]
### Bug description

Likely caused by the new Vert.x HTTP client being used as the default. Which I don't fully understand, because the docs state that it's experimental.

```
Caused by: java.lang.IllegalStateException: io.quarkiverse.cxf.vertx.http.client.VertxHttpClientHTTPConduit does not support SSLSocketFactory set via TLSClientParameters
	at io.quarkiverse.cxf.vertx.http.client.VertxHttpClientHTTPConduit.setupConnection(VertxHttpClientHTTPConduit.java:119)
	at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:551)
	at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:434)
	at org.apache.camel.component.cxf.jaxws.CxfProducer.process(CxfProducer.java:120)
```

I will disable the problem tests for now.

**Comment by ppalaga** [comment]
Blocked by https://github.com/quarkiverse/quarkus-cxf/pull/1456
