### ISSUE TITLE
Discover Datasonnet libraries at build time

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6425]
### Bug description

There have been some changes to `QuarkusClassLoader` which classgraph `QuarkusClassLoaderHandler` is not ready for.

It attempts to do reflection on a field that no longer exists:

https://github.com/classgraph/classgraph/blob/688313894de1f65bb46af551babaee8cdf01294a/src/main/java/nonapi/io/github/classgraph/classloaderhandler/QuarkusClassLoaderHandler.java#L120-L121

Which results in:

```
Caused by: java.lang.RuntimeException: Exception while calling findClassLoaderOrder for nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:239)
	at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:277)
	at io.github.classgraph.Scanner.<init>(Scanner.java:170)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1562)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1590)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1615)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1654)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1667)
	at org.apache.camel.language.datasonnet.DatasonnetLanguage.<clinit>(DatasonnetLanguage.java:46)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.findClasspathOrder(ClassLoaderHandlerRegistry.java:236)
	... 22 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because the return value of "nonapi.io.github.classgraph.reflection.ReflectionUtils.getFieldVal(boolean, Object, String)" is null
	at nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler.findClasspathOrderForQuarkusClassloader(QuarkusClassLoaderHandler.java:120)
	at nonapi.io.github.classgraph.classloaderhandler.QuarkusClassLoaderHandler.findClasspathOrder(QuarkusClassLoaderHandler.java:111)
	... 24 more
```

**Comment by jamesnetherton** [comment]
We can probably replace the classgraph stuff and use Camel's own package resource scanning APIs. I'll check.

**Comment by jamesnetherton** [comment]
We can actually avoid classgraph and discover libsonnet bits at build time. Needs:

https://issues.apache.org/jira/browse/CAMEL-21177
