### ISSUE TITLE
aws-secrets-manager integration tests cannot consume AWS_* envs

### ISSUE THREAD

**Issue by llowinge** [apache/camel-quarkus#6579]
### Bug description

When i want to run integration test for aws-secrets-manager with real AWS service, i pass CAMEL_QUARKUS_START_MOCK_BACKEND=false and also AWS_ACCESS_KEY + AWS_SECRET_KEY as i'm forced to, because otherwise i get:

```
Caused by: java.lang.IllegalStateException: Set AWS_ACCESS_KEY, AWS_SECRET_KEY and AWS_REGION env vars or AWS_USE_DEFAULT-CREDENTIALS-PROVIDER to true if you set CAMEL_QUARKUS_START_MOCK_BACKEND=false
```

And if i provide the `AWS_*` it fails with 

```
Caused by: java.lang.IllegalArgumentException: Cannot find getter method: access on bean: class org.apache.camel.vault.AwsVaultConfiguration when binding property: access.key
	at org.apache.camel.support.PropertyBindingSupport.doBuildPropertyOgnlPath(PropertyBindingSupport.java:379)
	at org.apache.camel.support.PropertyBindingSupport.doBindProperties(PropertyBindingSupport.java:300)
	at org.apache.camel.support.PropertyBindingSupport$Builder.bind(PropertyBindingSupport.java:1954)
	at org.apache.camel.main.MainHelper.setPropertiesOnTarget(MainHelper.java:329)
	at org.apache.camel.main.BaseMainSupport.setVaultProperties(BaseMainSupport.java:1655)
	at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:1225)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:541)
	at org.apache.camel.main.MainSupport.autoconfigure(MainSupport.java:73)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:772)
	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:113)
	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:83)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:85)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:134)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	... 11 more
```

because of some camel autoconfiguration which kicked in.

**Comment by llowinge** [comment]
@oscerd I'm trying to run https://github.com/jboss-fuse/camel-quarkus/tree/3.15.0-product/integration-tests-jvm/aws-secrets-manager and this https://github.com/jboss-fuse/camel-quarkus/blob/3.15.0-product/integration-tests-support/aws2/src/test/java/org/apache/camel/quarkus/test/support/aws2/Aws2TestResource.java#L46 kicks in and forces me to use those ENVs which are probably somehow consumed by the Camel.

**Comment by oscerd** [comment]
I'll try to reproduce

**Comment by llowinge** [comment]
Sorry first error after setting the AWS_* is 

```
	Caused by: java.lang.IllegalArgumentException: useDefaultCredentialsProvider is set to false, useProfileCredentialsProvider is set to false, useSessionCredentials is set to false, Amazon Secrets Manager client or accessKey and secretKey must be specified
		at org.apache.camel.component.aws.secretsmanager.SecretsManagerComponent.createEndpoint(SecretsManagerComponent.java:55)
		at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
		at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:805)
		... 33 more
```

After that i've tried to add

```
camel.component.aws-secrets-manager.access.key=${AWS_ACCESS_KEY}
camel.component.aws-secrets-manager.secret-key=${AWS_SECRET_KEY}
camel.component.aws-secrets-manager.region=${AWS_REGION:us-east-1}
```

to application.properties and the error with `Cannot find getter method: access on bean: class org.apache.camel.vault.AwsVaultConfiguration when binding property: access.key` is triggered.

**Comment by llowinge** [comment]
If i've changed the application.properties to (note i had `access.key` by accident):

```
camel.component.aws-secrets-manager.access-key=${AWS_ACCESS_KEY}
camel.component.aws-secrets-manager.secret-key=${AWS_SECRET_KEY}
camel.component.aws-secrets-manager.region=${AWS_REGION:us-east-1}
```

It finally passed the issue with credentials and failed with 

```
2024-10-03 07:41:56,602 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /aws-secrets-manager/operation/createSecret?body=changeit failed, error id: 494ee0a2-2dfb-4785-93ca-e989127e562c-1: org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.services.secretsmanager.model.CreateSecretResponse.arn()" because the return value of "org.apache.camel.Message.getBody(java.lang.Class)" is null
```

**Comment by llowinge** [comment]
Please @oscerd don't spend time on this. It looks like i have misconfigured AWS account. I'll update this issue accordingly when i have more info.

**Comment by llowinge** [comment]
The test doesn't work, but atleast i'm able to run it now. Thus closing this issue.

**Comment by oscerd** [comment]
> Please @oscerd don't spend time on this. It looks like i have misconfigured AWS account. I'll update this issue accordingly when i have more info.

Thanks for letting me know.
