### ISSUE TITLE
SmallRye Fault Tolerance 6.4.1 not compatible with camel-microprofile-fault-tolerance

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6584]
### Bug description

Seems some public API got removed, so we'll have to deal with it in the Camel component.

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/microprofile-fault-tolerance/src/main/java/org/apache/camel/quarkus/component/microprofile/it/faulttolerance/MicroprofileFaultToleranceProducers.java:[57,27] cannot find symbol
  symbol:   method create(java.util.concurrent.ExecutorService)
  location: class io.smallrye.faulttolerance.core.timer.ThreadTimer
```

**Comment by jamesnetherton** [comment]
Actually it's only the native build that is impacted:

```
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered unresolved method during parsing: io.smallrye.faulttolerance.core.timer.ThreadTimer.create(java.util.concurrent.Executor). This error is reported at image build time because class org.apache.camel.component.microprofile.faulttolerance.FaultToleranceTimerService is registered for linking at image build time by command line and command line.
Error encountered while parsing org.apache.camel.component.microprofile.faulttolerance.FaultToleranceTimerService.doInit(FaultToleranceTimerService.java:38)
Parsing context:
   at org.apache.camel.support.service.BaseService.init(BaseService.java:85)
   at org.apache.camel.support.service.BaseService.start(BaseService.java:115)
   at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:126)
   at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
   at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:153)
   at org.apache.camel.support.DefaultConsumer.doStart(DefaultConsumer.java:230)
   at root method.(Unknown Source)

```
