### ISSUE TITLE
jq extension does not load built in functions in native mode

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6651]
### Bug description

For instance, if you try to use a function like `length`, then you get:

```
Caused by: net.thisptr.jackson.jq.exception.JsonQueryException: Function length/0 does not exist
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.lookupFunction(FunctionCall.java:49)
	at net.thisptr.jackson.jq.internal.tree.FunctionCall.apply(FunctionCall.java:55)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.internal.tree.binaryop.SimpleBinaryOperatorExpression.lambda$apply$1(SimpleBinaryOperatorExpression.java:23)
	at net.thisptr.jackson.jq.Output.emit(Output.java:14)
	at net.thisptr.jackson.jq.internal.tree.literal.ValueLiteral.apply(ValueLiteral.java:20)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.internal.tree.binaryop.SimpleBinaryOperatorExpression.apply(SimpleBinaryOperatorExpression.java:22)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.lambda$pathRecursive$2(PipedQuery.java:53)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.resolve(ObjectFieldPath.java:83)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.FieldAccess.emitObjectFieldPath(FieldAccess.java:56)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.lambda$apply$0(IdentifierFieldAccess.java:35)
	at net.thisptr.jackson.jq.internal.tree.ThisObject.apply(ThisObject.java:20)
	at net.thisptr.jackson.jq.internal.tree.fieldaccess.IdentifierFieldAccess.apply(IdentifierFieldAccess.java:34)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.pathRecursive(PipedQuery.java:52)
	at net.thisptr.jackson.jq.internal.tree.PipedQuery.apply(PipedQuery.java:25)
	at net.thisptr.jackson.jq.internal.IsolatedScopeQuery.apply(IsolatedScopeQuery.java:21)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.JsonQuery.apply(JsonQuery.java:17)
	at org.apache.camel.language.jq.JqExpression.evaluate(JqExpression.java:156)
```

It's due to Camel using it's own jackson-jq root scope in `JqLanguage`. We need it to resolve the existing scope created by quarkus-jackson-jq at build time.

**Comment by jamesnetherton** [comment]
Needs: https://issues.apache.org/jira/browse/CAMEL-21357.
