### ISSUE TITLE
[camel-main] amazon-kinesis-client 3.x not compatible with protobuf 3.25.x 

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#6813]
### Bug description

Things seem to work ok in JVM mode (likely because we have no tests for KCL). But the native build fails with:

```
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
	at software.amazon.kinesis.retrieval.kpl.Messages$AggregatedRecord.<clinit>(Messages.java:1909)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:177)
	... 43 more
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageClassLoader.loadClass(NativeImageClassLoader.java:652)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
```

We need Quarkus to upgrade protobuf-java to >= 3.26.x. Even then, it may not work since the kinesis-client is aligning with 4.27.x.

**Comment by jamesnetherton** [comment]
Some more context to the actual problem. This change:

https://github.com/protocolbuffers/protobuf/commit/318d310e645306a895be53a985f34feb49acf579#diff-f34332f53194a822438f42063a2c54982362f4ca665561dea0005af83781641b

Generates a static initialiser in protobuf generated code like:

```java
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 5,
      /* suffix= */ "",
      Messages.class.getName());
  }
```

**Comment by jamesnetherton** [comment]
I downgraded the amazon-kinesis-client in Camel, so there's nothing to fix (for now).

https://github.com/apache/camel/pull/16353

**Comment by JiriOndrusek** [comment]
Also amazon-kinesis-client 2.6.1 is not not compatible with protobuf 3.25.x. (amazon-kinesis-client has to stay on 2.6.0)
