### ISSUE TITLE
Quarkus fails to start with uri: platform-http://hello

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-quarkus#879]
If a route is defined like:

    from("platform-http://hello")
        .log("${body}")

Then quarkus fails to start with:

```
Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:248)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.Application.run(Application.java:226)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Path must start with /
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:99)
	at io.quarkus.deployment.steps.Main$start43.deploy_0(Main$start43.zig:78)
	at io.quarkus.deployment.steps.Main$start43.deploy(Main$start43.zig:97)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:218)
	... 3 more
Caused by: java.lang.IllegalArgumentException: Path must start with /
	at io.vertx.ext.web.impl.RouteImpl.checkPath(RouteImpl.java:310)
	at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:49)
	at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:72)
	at org.apache.camel.quarkus.component.platform.http.runtime.QuarkusPlatformHttpConsumer.doStart(QuarkusPlatformHttpConsumer.java:102)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:121)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:2989)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartOrResumeRouteConsumers(AbstractCamelContext.java:3327)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartRouteConsumers(AbstractCamelContext.java:3258)
	at org.apache.camel.impl.engine.AbstractCamelContext.safelyStartRouteServices(AbstractCamelContext.java:3163)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartOrResumeRoutes(AbstractCamelContext.java:2925)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2725)
	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:2527)
	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2544)
	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2525)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:121)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2421)
	at org.apache.camel.quarkus.core.CamelMain.doStart(CamelMain.java:50)
	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:121)
	at org.apache.camel.quarkus.core.CamelMainRecorder.start(CamelMainRecorder.java:97)

```

It does work with:

    platform-http:/hello

**Comment by ppalaga** [comment]
Why do you expect it to work with two slashes?

**Comment by lburgazzoli** [comment]
You typically write `http://something` when it is about http url so supporting two slashes would make it looking more "natural"

**Comment by ppalaga** [comment]
> You typically write `http://something` when it is about http url so supporting two slashes would make it looking more "natural"

Yes, as long as `something` is a host. If `something` is a path, the allowed forms are  `http:/something` and `http:///something`, IMO.

**Comment by lburgazzoli** [comment]
ah yeah, this thing does not have any notion of host, sorry, closing
