### ISSUE TITLE
Tests fail on integration-tests/platform-http for 1.0.0-M5

### ISSUE THREAD

**Issue by esend7881** [apache/camel-quarkus#906]
I'm not sure if I am missing a prerequisite instructions for running tests on the platform-http IT, but I get the following from maven:

```
[user@ubuntu:~/workspace/camel-quarkus]$ mvn test -f integration-tests/platform-http
[INFO] Scanning for projects...
[INFO] 
[INFO] --< org.apache.camel.quarkus:camel-quarkus-integration-test-platform-http >--
[INFO] Building Camel Quarkus :: Integration Tests :: Platform HTTP 1.0.0-M5
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (directories) @ camel-quarkus-integration-test-platform-http ---
[INFO] Highest basedir set to: /home/user/workspace/camel-quarkus
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- groovy-maven-plugin:2.1.1:execute (sanity-checks) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.11.0:format (format) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 4
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         4 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          1s
[INFO] 
[INFO] --- impsort-maven-plugin:1.3.2:sort (sort-imports) @ camel-quarkus-integration-test-platform-http ---
[INFO]  Total Files Processed: 4 in 00:00.353
[INFO]         Already Sorted: 4
[INFO]         Needed Sorting: 0
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:reserve-network-port (reserve-network-port) @ camel-quarkus-integration-test-platform-http ---
[INFO] Reserved port 36615 for test.http.port.jvm
[INFO] Reserved port 42759 for test.http.port.native
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-integration-test-platform-http ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (copy-generated-resources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/user/workspace/camel-quarkus/integration-tests/platform-http/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-quarkus-integration-test-platform-http ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest
2020-03-18 12:15:25,920 INFO  [io.quarkus] (main) Quarkus 1.3.0.Final started in 1.896s. Listening on: http://0.0.0.0:36615
2020-03-18 12:15:25,926 INFO  [io.quarkus] (main) Profile test activated. 
2020-03-18 12:15:25,926 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, vertx, vertx-web]
[ERROR] Tests run: 16, Failures: 16, Errors: 0, Skipped: 0, Time elapsed: 4.288 s <<< FAILURE! - in org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest
[ERROR] code204EmptyString  Time elapsed: 1.267 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <204> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.code204EmptyString(PlatformHttpTest.java:213)

[ERROR] code204SomeString  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.code204SomeString(PlatformHttpTest.java:221)

[ERROR] multiValueParams  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.multiValueParams(PlatformHttpTest.java:174)

[ERROR] invalidMethod  Time elapsed: 0.036 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <405> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.invalidMethod(PlatformHttpTest.java:125)

[ERROR] multipart  Time elapsed: 0.103 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.multipart(PlatformHttpTest.java:140)

[ERROR] produces  Time elapsed: 0.02 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <406> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.produces(PlatformHttpTest.java:98)

[ERROR] consumes  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <415> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.consumes(PlatformHttpTest.java:70)

[ERROR] pathParam  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.pathParam(PlatformHttpTest.java:239)

[ERROR] rest  Time elapsed: 0.095 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Response body doesn't match expectation.
Expected: "GET: /rest-get"
  Actual: <html><body><h1>Resource not found</h1></body></html>

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.rest(PlatformHttpTest.java:57)

[ERROR] responseCodeViaHeader  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <299> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.responseCodeViaHeader(PlatformHttpTest.java:197)

[ERROR] basic  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.basic(PlatformHttpTest.java:37)

[ERROR] code204Null  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <204> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.code204Null(PlatformHttpTest.java:205)

[ERROR] customHeaderFilterStrategy  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.customHeaderFilterStrategy(PlatformHttpTest.java:163)

[ERROR] formUrlEncoded  Time elapsed: 0.03 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.formUrlEncoded(PlatformHttpTest.java:152)

[ERROR] encoding  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.encoding(PlatformHttpTest.java:187)

[ERROR] code200EmptyString  Time elapsed: 0.039 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <404>.

        at org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest.code200EmptyString(PlatformHttpTest.java:230)

2020-03-18 12:15:27,780 INFO  [io.quarkus] (main) Quarkus stopped in 0.083s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PlatformHttpTest.basic:37 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.code200EmptyString:230 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.code204EmptyString:213 1 expectation failed.
Expected status code <204> but was <404>.

[ERROR]   PlatformHttpTest.code204Null:205 1 expectation failed.
Expected status code <204> but was <404>.

[ERROR]   PlatformHttpTest.code204SomeString:221 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.consumes:70 1 expectation failed.
Expected status code <415> but was <404>.

[ERROR]   PlatformHttpTest.customHeaderFilterStrategy:163 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.encoding:187 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.formUrlEncoded:152 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.invalidMethod:125 1 expectation failed.
Expected status code <405> but was <404>.

[ERROR]   PlatformHttpTest.multiValueParams:174 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.multipart:140 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.pathParam:239 1 expectation failed.
Expected status code <200> but was <404>.

[ERROR]   PlatformHttpTest.produces:98 1 expectation failed.
Expected status code <406> but was <404>.

[ERROR]   PlatformHttpTest.responseCodeViaHeader:197 1 expectation failed.
Expected status code <299> but was <404>.

[ERROR]   PlatformHttpTest.rest:57 1 expectation failed.
Response body doesn't match expectation.
Expected: "GET: /rest-get"
  Actual: <html><body><h1>Resource not found</h1></body></html>

[INFO] 
[ERROR] Tests run: 16, Failures: 16, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.039 s
[INFO] Finished at: 2020-03-18T12:15:28-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project camel-quarkus-integration-test-platform-http: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/workspace/camel-quarkus/integration-tests/platform-http/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

I tried the integration-test/servlet tests and they pass, so I'm failing to see a common denominator.

**Comment by aldettinger** [comment]
@esend7881 Thanks for taking interest in camel-quarkus :)

On my end, I've just downloaded again the 1.0.0-M5 release and run the same command with good result:
```
[camel-quarkus-1.0.0-M5]$ mvn test -f integration-tests/platform-http
[INFO] Scanning for projects...
[INFO] 
[INFO] --< org.apache.camel.quarkus:camel-quarkus-integration-test-platform-http >--
[INFO] Building Camel Quarkus :: Integration Tests :: Platform HTTP 1.0.0-M5
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (directories) @ camel-quarkus-integration-test-platform-http ---
[INFO] Highest basedir set to: /home/agallice/Downloads/camel-quarkus-1.0.0-M5
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (camel-quarkus-enforcer-rules) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- groovy-maven-plugin:2.1.1:execute (sanity-checks) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.11.0:format (format) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 4
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         4 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
[INFO] 
[INFO] --- impsort-maven-plugin:1.3.2:sort (sort-imports) @ camel-quarkus-integration-test-platform-http ---
[INFO]  Total Files Processed: 4 in 00:00.233
[INFO]         Already Sorted: 4
[INFO]         Needed Sorting: 0
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:reserve-network-port (reserve-network-port) @ camel-quarkus-integration-test-platform-http ---
[INFO] Reserved port 42840 for test.http.port.jvm
[INFO] Reserved port 41901 for test.http.port.native
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-integration-test-platform-http ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (copy-generated-resources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ camel-quarkus-integration-test-platform-http ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/agallice/Downloads/camel-quarkus-1.0.0-M5/integration-tests/platform-http/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-quarkus-integration-test-platform-http ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ camel-quarkus-integration-test-platform-http ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest
2020-03-25 11:09:52,352 INFO  [org.apa.cam.sup.LRUCacheFactory] (main) Detected and using LURCacheFactory: camel-caffeine-lrucache
2020-03-25 11:09:52,701 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) is starting
2020-03-25 11:09:52,702 INFO  [org.apa.cam.imp.eng.DefaultManagementStrategy] (main) JMX is disabled
2020-03-25 11:09:52,770 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2020-03-25 11:09:52,779 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route1 started and consuming from: platform-http:///platform-http/hello
2020-03-25 11:09:52,779 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route2 started and consuming from: platform-http:///platform-http/get-post
2020-03-25 11:09:52,780 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route3 started and consuming from: platform-http:///platform-http/multipart
2020-03-25 11:09:52,780 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route4 started and consuming from: platform-http:///platform-http/form-urlencoded
2020-03-25 11:09:52,780 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route5 started and consuming from: platform-http:///platform-http/header-filter-strategy
2020-03-25 11:09:52,780 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route6 started and consuming from: platform-http:///platform-http/multi-value-params
2020-03-25 11:09:52,781 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route7 started and consuming from: platform-http:///platform-http/encoding
2020-03-25 11:09:52,781 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route8 started and consuming from: platform-http:///platform-http/response-code-299
2020-03-25 11:09:52,784 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route9 started and consuming from: platform-http:///platform-http/consumes
2020-03-25 11:09:52,784 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route10 started and consuming from: platform-http:///platform-http/produces
2020-03-25 11:09:52,784 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route11 started and consuming from: platform-http:///platform-http/null-body
2020-03-25 11:09:52,784 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route12 started and consuming from: platform-http:///platform-http/empty-string-body
2020-03-25 11:09:52,785 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route13 started and consuming from: platform-http:///platform-http/some-string
2020-03-25 11:09:52,785 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route14 started and consuming from: platform-http:///platform-http/empty-string-200
2020-03-25 11:09:52,785 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route15 started and consuming from: platform-http:///platform-http/rest-get
2020-03-25 11:09:52,785 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route16 started and consuming from: platform-http:///platform-http/rest-post
2020-03-25 11:09:52,786 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Route: route17 started and consuming from: platform-http:///platform-http/hello-by-name/%7Bname%7D
2020-03-25 11:09:52,789 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Total 17 routes, of which 17 are started
2020-03-25 11:09:52,790 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) started in 0.088 seconds
2020-03-25 11:09:52,792 INFO  [io.quarkus] (main) Quarkus 1.3.0.Final started in 1.587s. Listening on: http://0.0.0.0:42840
2020-03-25 11:09:52,792 INFO  [io.quarkus] (main) Profile test activated. 
2020-03-25 11:09:52,792 INFO  [io.quarkus] (main) Installed features: [camel-attachments, camel-core, camel-log, camel-platform-http, camel-policy, camel-rest, camel-support-common, cdi, mutiny, vertx, vertx-web]
2020-03-25 11:09:53,804 INFO  [multi-value-params] (vert.x-eventloop-thread-13) Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
2020-03-25 11:09:53,968 INFO  [multipart] (vert.x-eventloop-thread-4) Exchange[ExchangePattern: InOnly, BodyType: java.util.HashMap, Body: {description=cofe babe}]
2020-03-25 11:09:54,109 INFO  [response-code] (vert.x-eventloop-thread-13) Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
2020-03-25 11:09:54,163 INFO  [header-filter-strategy] (vert.x-eventloop-thread-9) Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
2020-03-25 11:09:54,182 INFO  [form-urlencoded] (vert.x-eventloop-thread-2) Exchange[ExchangePattern: InOnly, BodyType: java.util.HashMap, Body: {k1=v1, k2=v2}]
2020-03-25 11:09:54,221 INFO  [encoding] (vert.x-eventloop-thread-7) Exchange[ExchangePattern: InOnly, BodyType: byte[], Body: Ťava dvojhrbá]
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.329 s - in org.apache.camel.quarkus.component.http.server.it.PlatformHttpTest
2020-03-25 11:09:54,237 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) is shutting down
2020-03-25 11:09:54,243 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) uptime 1.541 seconds
2020-03-25 11:09:54,243 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.1.0 (CamelContext: camel-1) is shutdown in 0.006 seconds
2020-03-25 11:09:54,280 INFO  [io.quarkus] (main) Quarkus stopped in 0.044s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.928 s
[INFO] Finished at: 2020-03-25T11:09:54+01:00
[INFO] ------------------------------------------------------------------------
```
So it must be a kind of setup issue. Maybe you could try to run `mvn clean install -D skipTests` from root folder first. Another idea could be to double check the [contributor guide](https://github.com/apache/camel-quarkus/blob/master/docs/modules/ROOT/pages/contributor-guide.adoc).

**Comment by lburgazzoli** [comment]
@esend7881 is this still an issue on your side ?

**Comment by esend7881** [comment]
@lburgazzoli - for the moment, I task switched out of Camel and haven't looked into this since my post. I assume so, perhaps something is off with my set up? I am using a VM with Ubuntu 18.04

**Comment by ppalaga** [comment]
Generally, as @aldettinger  pointed out, you need to rebuild the whole source tree using `mvn clean install -DskipTests` from the source tree root directory, prior to running any individual integration tests. Using `mvn clean test` instead of `mvn test` may help in some situations.

Closing as non-reproducible. @esend7881 feel free to re-open if the above suggestions do not help.
