### ISSUE TITLE
RestBindingReifier.setupJaxb fails in native mode with JDK 11

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#999]
Continuation of #996, which means the problem is only really fixed for AWS. We need a better solution to fix all instances of this problem.

```
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/runner/work/camel-quarkus/camel-quarkus/integration-tests/core-impl/target/camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 1001:115 --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=en -J-Dfile.encoding=ANSI_X3.4-1968 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:-IncludeAllTimeZones -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]    classlist:   4,686.70 ms
09:41:14,198 INFO  [org.apa.cam.sup.LRUCacheFactory] Detected and using LURCacheFactory: camel-caffeine-lrucache
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]        (cap):   1,335.84 ms
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]        setup:   3,285.12 ms
09:41:20,921 INFO  [org.jbo.threads] JBoss Threads version 3.0.1.Final
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]   (typeflow):  30,467.45 ms
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]    (objects):  21,612.11 ms
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]   (features):     862.63 ms
[camel-quarkus-integration-test-core-impl-1.1.0-SNAPSHOT-runner:24]     analysis:  54,187.42 ms
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: javax.xml.bind.JAXBContext. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:166)
Call path from entry point to org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestConfiguration, String, String, DataFormat, DataFormat): 
	at org.apache.camel.reifier.rest.RestBindingReifier.setupJaxb(RestBindingReifier.java:160)
	at org.apache.camel.reifier.rest.RestBindingReifier.createRestBindingAdvice(RestBindingReifier.java:124)
```

**Comment by galderz** [comment]
Just came across this, thanks for spotting it @jamesnetherton.
